// Rust translation of src/audio/SDL_audio_channel_converters.h from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

// DO NOT EDIT, THIS FILE WAS GENERATED BY tools/gen_audio_channel_converters.py
// FROM SDL's src/audio/SDL_audio_channel_converters.h (itself generated by
// build-scripts/gen_audio_channel_conversion.c).

//! Channel layout converters, `[from][to]` for 1..=8 channels.
//!
//! Each converter works in place on native-endian `f32` samples stored in a
//! byte buffer: the source frames start at byte offset `src` and the
//! converted frames are written starting at `dst` (which may be the same
//! offset). Growing conversions walk backwards so they can expand in place.

#![allow(
    unused_parens,
    clippy::excessive_precision,
    clippy::identity_op,
    clippy::erasing_op
)]

/// Translation of `SDL_AudioChannelConverter`: `(buf, src_byte_offset, dst_byte_offset, num_frames)`.
pub(crate) type AudioChannelConverter = fn(&mut [u8], usize, usize, usize);

#[inline(always)]
fn rd(buf: &[u8], i: usize) -> f32 {
    f32::from_ne_bytes([buf[i * 4], buf[i * 4 + 1], buf[i * 4 + 2], buf[i * 4 + 3]])
}

#[inline(always)]
fn wr(buf: &mut [u8], i: usize, v: f32) {
    buf[i * 4..i * 4 + 4].copy_from_slice(&v.to_ne_bytes());
}

/// Translation of `SDL_ConvertMonoToStereo()` (mono to stereo).
fn convert_mono_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 2;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertMonoTo21()` (mono to 2.1).
fn convert_mono_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 3;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 2, 0.0_f32); // LFE
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertMonoToQuad()` (mono to quad).
fn convert_mono_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 4;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 3, 0.0_f32); // BR
        wr(buf, d + 2, 0.0_f32); // BL
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertMonoTo41()` (mono to 4.1).
fn convert_mono_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 5;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 4, 0.0_f32); // BR
        wr(buf, d + 3, 0.0_f32); // BL
        wr(buf, d + 2, 0.0_f32); // LFE
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertMonoTo51()` (mono to 5.1).
fn convert_mono_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 6;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 5, 0.0_f32); // BR
        wr(buf, d + 4, 0.0_f32); // BL
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertMonoTo61()` (mono to 6.1).
fn convert_mono_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 7;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 6, 0.0_f32); // SR
        wr(buf, d + 5, 0.0_f32); // SL
        wr(buf, d + 4, 0.0_f32); // BC
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertMonoTo71()` (mono to 7.1).
fn convert_mono_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 1;
        let d = dst + i * 8;
        let src_fc = rd(buf, s + 0);
        wr(buf, d + 7, 0.0_f32); // SR
        wr(buf, d + 6, 0.0_f32); // SL
        wr(buf, d + 5, 0.0_f32); // BR
        wr(buf, d + 4, 0.0_f32); // BL
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, src_fc); // FR
        wr(buf, d + 0, src_fc); // FL
    }
}

/// Translation of `SDL_ConvertStereoToMono()` (stereo to mono).
fn convert_stereo_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 2;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.500000000_f32) + (rd(buf, s + 1) * 0.500000000_f32),
        ); // FC
    }
}

/// Translation of `SDL_ConvertStereoTo21()` (stereo to 2.1).
fn convert_stereo_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 2;
        let d = dst + i * 3;
        wr(buf, d + 2, 0.0_f32); // LFE
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertStereoToQuad()` (stereo to quad).
fn convert_stereo_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 2;
        let d = dst + i * 4;
        wr(buf, d + 3, 0.0_f32); // BR
        wr(buf, d + 2, 0.0_f32); // BL
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertStereoTo41()` (stereo to 4.1).
fn convert_stereo_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 2;
        let d = dst + i * 5;
        wr(buf, d + 4, 0.0_f32); // BR
        wr(buf, d + 3, 0.0_f32); // BL
        wr(buf, d + 2, 0.0_f32); // LFE
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertStereoTo51()` (stereo to 5.1).
fn convert_stereo_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 2;
        let d = dst + i * 6;
        wr(buf, d + 5, 0.0_f32); // BR
        wr(buf, d + 4, 0.0_f32); // BL
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertStereoTo61()` (stereo to 6.1).
fn convert_stereo_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 2;
        let d = dst + i * 7;
        wr(buf, d + 6, 0.0_f32); // SR
        wr(buf, d + 5, 0.0_f32); // SL
        wr(buf, d + 4, 0.0_f32); // BC
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertStereoTo71()` (stereo to 7.1).
fn convert_stereo_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 2;
        let d = dst + i * 8;
        wr(buf, d + 7, 0.0_f32); // SR
        wr(buf, d + 6, 0.0_f32); // SL
        wr(buf, d + 5, 0.0_f32); // BR
        wr(buf, d + 4, 0.0_f32); // BL
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert21ToMono()` (2.1 to mono).
fn convert_21_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 3;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.333333343_f32)
                + (rd(buf, s + 1) * 0.333333343_f32)
                + (rd(buf, s + 2) * 0.333333343_f32),
        ); // FC
    }
}

/// Translation of `SDL_Convert21ToStereo()` (2.1 to stereo).
fn convert_21_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 3;
        let d = dst + i * 2;
        let src_lfe = rd(buf, s + 2);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.800000012_f32) + (src_lfe * 0.200000003_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.800000012_f32) + (src_lfe * 0.200000003_f32),
        ); // FR
    }
}

/// Translation of `SDL_Convert21ToQuad()` (2.1 to quad).
fn convert_21_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 3;
        let d = dst + i * 4;
        let src_lfe = rd(buf, s + 2);
        wr(buf, d + 3, (src_lfe * 0.111111112_f32)); // BR
        wr(buf, d + 2, (src_lfe * 0.111111112_f32)); // BL
        wr(
            buf,
            d + 1,
            (src_lfe * 0.111111112_f32) + (rd(buf, s + 1) * 0.888888896_f32),
        ); // FR
        wr(
            buf,
            d + 0,
            (src_lfe * 0.111111112_f32) + (rd(buf, s + 0) * 0.888888896_f32),
        ); // FL
    }
}

/// Translation of `SDL_Convert21To41()` (2.1 to 4.1).
fn convert_21_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 3;
        let d = dst + i * 5;
        wr(buf, d + 4, 0.0_f32); // BR
        wr(buf, d + 3, 0.0_f32); // BL
        wr(buf, d + 2, rd(buf, s + 2)); // LFE
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert21To51()` (2.1 to 5.1).
fn convert_21_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 3;
        let d = dst + i * 6;
        wr(buf, d + 5, 0.0_f32); // BR
        wr(buf, d + 4, 0.0_f32); // BL
        wr(buf, d + 3, rd(buf, s + 2)); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert21To61()` (2.1 to 6.1).
fn convert_21_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 3;
        let d = dst + i * 7;
        wr(buf, d + 6, 0.0_f32); // SR
        wr(buf, d + 5, 0.0_f32); // SL
        wr(buf, d + 4, 0.0_f32); // BC
        wr(buf, d + 3, rd(buf, s + 2)); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert21To71()` (2.1 to 7.1).
fn convert_21_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 3;
        let d = dst + i * 8;
        wr(buf, d + 7, 0.0_f32); // SR
        wr(buf, d + 6, 0.0_f32); // SL
        wr(buf, d + 5, 0.0_f32); // BR
        wr(buf, d + 4, 0.0_f32); // BL
        wr(buf, d + 3, rd(buf, s + 2)); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertQuadToMono()` (quad to mono).
fn convert_quad_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 4;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.250000000_f32)
                + (rd(buf, s + 1) * 0.250000000_f32)
                + (rd(buf, s + 2) * 0.250000000_f32)
                + (rd(buf, s + 3) * 0.250000000_f32),
        ); // FC
    }
}

/// Translation of `SDL_ConvertQuadToStereo()` (quad to stereo).
fn convert_quad_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 4;
        let d = dst + i * 2;
        let src_bl = rd(buf, s + 2);
        let src_br = rd(buf, s + 3);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.421000004_f32)
                + (src_bl * 0.358999997_f32)
                + (src_br * 0.219999999_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.421000004_f32)
                + (src_bl * 0.219999999_f32)
                + (src_br * 0.358999997_f32),
        ); // FR
    }
}

/// Translation of `SDL_ConvertQuadTo21()` (quad to 2.1).
fn convert_quad_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 4;
        let d = dst + i * 3;
        let src_bl = rd(buf, s + 2);
        let src_br = rd(buf, s + 3);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.421000004_f32)
                + (src_bl * 0.358999997_f32)
                + (src_br * 0.219999999_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.421000004_f32)
                + (src_bl * 0.219999999_f32)
                + (src_br * 0.358999997_f32),
        ); // FR
        wr(buf, d + 2, 0.0_f32); // LFE
    }
}

/// Translation of `SDL_ConvertQuadTo41()` (quad to 4.1).
fn convert_quad_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 4;
        let d = dst + i * 5;
        wr(buf, d + 4, rd(buf, s + 3)); // BR
        wr(buf, d + 3, rd(buf, s + 2)); // BL
        wr(buf, d + 2, 0.0_f32); // LFE
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertQuadTo51()` (quad to 5.1).
fn convert_quad_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 4;
        let d = dst + i * 6;
        wr(buf, d + 5, rd(buf, s + 3)); // BR
        wr(buf, d + 4, rd(buf, s + 2)); // BL
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_ConvertQuadTo61()` (quad to 6.1).
fn convert_quad_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 4;
        let d = dst + i * 7;
        let src_bl = rd(buf, s + 2);
        let src_br = rd(buf, s + 3);
        wr(buf, d + 6, (src_br * 0.796000004_f32)); // SR
        wr(buf, d + 5, (src_bl * 0.796000004_f32)); // SL
        wr(
            buf,
            d + 4,
            (src_br * 0.500000000_f32) + (src_bl * 0.500000000_f32),
        ); // BC
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, (rd(buf, s + 1) * 0.939999998_f32)); // FR
        wr(buf, d + 0, (rd(buf, s + 0) * 0.939999998_f32)); // FL
    }
}

/// Translation of `SDL_ConvertQuadTo71()` (quad to 7.1).
fn convert_quad_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 4;
        let d = dst + i * 8;
        wr(buf, d + 7, 0.0_f32); // SR
        wr(buf, d + 6, 0.0_f32); // SL
        wr(buf, d + 5, rd(buf, s + 3)); // BR
        wr(buf, d + 4, rd(buf, s + 2)); // BL
        wr(buf, d + 3, 0.0_f32); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert41ToMono()` (4.1 to mono).
fn convert_41_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 5;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.200000003_f32)
                + (rd(buf, s + 1) * 0.200000003_f32)
                + (rd(buf, s + 2) * 0.200000003_f32)
                + (rd(buf, s + 3) * 0.200000003_f32)
                + (rd(buf, s + 4) * 0.200000003_f32),
        ); // FC
    }
}

/// Translation of `SDL_Convert41ToStereo()` (4.1 to stereo).
fn convert_41_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 5;
        let d = dst + i * 2;
        let src_lfe = rd(buf, s + 2);
        let src_bl = rd(buf, s + 3);
        let src_br = rd(buf, s + 4);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.374222219_f32)
                + (src_lfe * 0.111111112_f32)
                + (src_bl * 0.319111109_f32)
                + (src_br * 0.195555553_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.374222219_f32)
                + (src_lfe * 0.111111112_f32)
                + (src_bl * 0.195555553_f32)
                + (src_br * 0.319111109_f32),
        ); // FR
    }
}

/// Translation of `SDL_Convert41To21()` (4.1 to 2.1).
fn convert_41_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 5;
        let d = dst + i * 3;
        let src_bl = rd(buf, s + 3);
        let src_br = rd(buf, s + 4);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.421000004_f32)
                + (src_bl * 0.358999997_f32)
                + (src_br * 0.219999999_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.421000004_f32)
                + (src_bl * 0.219999999_f32)
                + (src_br * 0.358999997_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 2)); // LFE
    }
}

/// Translation of `SDL_Convert41ToQuad()` (4.1 to quad).
fn convert_41_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 5;
        let d = dst + i * 4;
        let src_lfe = rd(buf, s + 2);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.941176474_f32) + (src_lfe * 0.058823530_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.941176474_f32) + (src_lfe * 0.058823530_f32),
        ); // FR
        wr(
            buf,
            d + 2,
            (src_lfe * 0.058823530_f32) + (rd(buf, s + 3) * 0.941176474_f32),
        ); // BL
        wr(
            buf,
            d + 3,
            (src_lfe * 0.058823530_f32) + (rd(buf, s + 4) * 0.941176474_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert41To51()` (4.1 to 5.1).
fn convert_41_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 5;
        let d = dst + i * 6;
        wr(buf, d + 5, rd(buf, s + 4)); // BR
        wr(buf, d + 4, rd(buf, s + 3)); // BL
        wr(buf, d + 3, rd(buf, s + 2)); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert41To61()` (4.1 to 6.1).
fn convert_41_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 5;
        let d = dst + i * 7;
        let src_bl = rd(buf, s + 3);
        let src_br = rd(buf, s + 4);
        wr(buf, d + 6, (src_br * 0.796000004_f32)); // SR
        wr(buf, d + 5, (src_bl * 0.796000004_f32)); // SL
        wr(
            buf,
            d + 4,
            (src_br * 0.500000000_f32) + (src_bl * 0.500000000_f32),
        ); // BC
        wr(buf, d + 3, rd(buf, s + 2)); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, (rd(buf, s + 1) * 0.939999998_f32)); // FR
        wr(buf, d + 0, (rd(buf, s + 0) * 0.939999998_f32)); // FL
    }
}

/// Translation of `SDL_Convert41To71()` (4.1 to 7.1).
fn convert_41_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 5;
        let d = dst + i * 8;
        wr(buf, d + 7, 0.0_f32); // SR
        wr(buf, d + 6, 0.0_f32); // SL
        wr(buf, d + 5, rd(buf, s + 4)); // BR
        wr(buf, d + 4, rd(buf, s + 3)); // BL
        wr(buf, d + 3, rd(buf, s + 2)); // LFE
        wr(buf, d + 2, 0.0_f32); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert51ToMono()` (5.1 to mono).
fn convert_51_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 6;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.166666672_f32)
                + (rd(buf, s + 1) * 0.166666672_f32)
                + (rd(buf, s + 2) * 0.166666672_f32)
                + (rd(buf, s + 3) * 0.166666672_f32)
                + (rd(buf, s + 4) * 0.166666672_f32)
                + (rd(buf, s + 5) * 0.166666672_f32),
        ); // FC
    }
}

/// Translation of `SDL_Convert51ToStereo()` (5.1 to stereo).
fn convert_51_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 6;
        let d = dst + i * 2;
        let src_fc = rd(buf, s + 2);
        let src_lfe = rd(buf, s + 3);
        let src_bl = rd(buf, s + 4);
        let src_br = rd(buf, s + 5);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.294545442_f32)
                + (src_fc * 0.208181813_f32)
                + (src_lfe * 0.090909094_f32)
                + (src_bl * 0.251818180_f32)
                + (src_br * 0.154545456_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.294545442_f32)
                + (src_fc * 0.208181813_f32)
                + (src_lfe * 0.090909094_f32)
                + (src_bl * 0.154545456_f32)
                + (src_br * 0.251818180_f32),
        ); // FR
    }
}

/// Translation of `SDL_Convert51To21()` (5.1 to 2.1).
fn convert_51_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 6;
        let d = dst + i * 3;
        let src_fc = rd(buf, s + 2);
        let src_bl = rd(buf, s + 4);
        let src_br = rd(buf, s + 5);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.324000001_f32)
                + (src_fc * 0.229000002_f32)
                + (src_bl * 0.277000010_f32)
                + (src_br * 0.170000002_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.324000001_f32)
                + (src_fc * 0.229000002_f32)
                + (src_bl * 0.170000002_f32)
                + (src_br * 0.277000010_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 3)); // LFE
    }
}

/// Translation of `SDL_Convert51ToQuad()` (5.1 to quad).
fn convert_51_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 6;
        let d = dst + i * 4;
        let src_fc = rd(buf, s + 2);
        let src_lfe = rd(buf, s + 3);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.558095276_f32)
                + (src_fc * 0.394285709_f32)
                + (src_lfe * 0.047619049_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.558095276_f32)
                + (src_fc * 0.394285709_f32)
                + (src_lfe * 0.047619049_f32),
        ); // FR
        wr(
            buf,
            d + 2,
            (src_lfe * 0.047619049_f32) + (rd(buf, s + 4) * 0.558095276_f32),
        ); // BL
        wr(
            buf,
            d + 3,
            (src_lfe * 0.047619049_f32) + (rd(buf, s + 5) * 0.558095276_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert51To41()` (5.1 to 4.1).
fn convert_51_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 6;
        let d = dst + i * 5;
        let src_fc = rd(buf, s + 2);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.586000025_f32) + (src_fc * 0.414000005_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.586000025_f32) + (src_fc * 0.414000005_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 3)); // LFE
        wr(buf, d + 3, (rd(buf, s + 4) * 0.586000025_f32)); // BL
        wr(buf, d + 4, (rd(buf, s + 5) * 0.586000025_f32)); // BR
    }
}

/// Translation of `SDL_Convert51To61()` (5.1 to 6.1).
fn convert_51_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 6;
        let d = dst + i * 7;
        let src_bl = rd(buf, s + 4);
        let src_br = rd(buf, s + 5);
        wr(buf, d + 6, (src_br * 0.796000004_f32)); // SR
        wr(buf, d + 5, (src_bl * 0.796000004_f32)); // SL
        wr(
            buf,
            d + 4,
            (src_br * 0.500000000_f32) + (src_bl * 0.500000000_f32),
        ); // BC
        wr(buf, d + 3, rd(buf, s + 3)); // LFE
        wr(buf, d + 2, (rd(buf, s + 2) * 0.939999998_f32)); // FC
        wr(buf, d + 1, (rd(buf, s + 1) * 0.939999998_f32)); // FR
        wr(buf, d + 0, (rd(buf, s + 0) * 0.939999998_f32)); // FL
    }
}

/// Translation of `SDL_Convert51To71()` (5.1 to 7.1).
fn convert_51_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 6;
        let d = dst + i * 8;
        wr(buf, d + 7, 0.0_f32); // SR
        wr(buf, d + 6, 0.0_f32); // SL
        wr(buf, d + 5, rd(buf, s + 5)); // BR
        wr(buf, d + 4, rd(buf, s + 4)); // BL
        wr(buf, d + 3, rd(buf, s + 3)); // LFE
        wr(buf, d + 2, rd(buf, s + 2)); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert61ToMono()` (6.1 to mono).
fn convert_61_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 7;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.143142849_f32)
                + (rd(buf, s + 1) * 0.143142849_f32)
                + (rd(buf, s + 2) * 0.143142849_f32)
                + (rd(buf, s + 3) * 0.142857149_f32)
                + (rd(buf, s + 4) * 0.143142849_f32)
                + (rd(buf, s + 5) * 0.143142849_f32)
                + (rd(buf, s + 6) * 0.143142849_f32),
        ); // FC
    }
}

/// Translation of `SDL_Convert61ToStereo()` (6.1 to stereo).
fn convert_61_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 7;
        let d = dst + i * 2;
        let src_fc = rd(buf, s + 2);
        let src_lfe = rd(buf, s + 3);
        let src_bc = rd(buf, s + 4);
        let src_sl = rd(buf, s + 5);
        let src_sr = rd(buf, s + 6);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.247384623_f32)
                + (src_fc * 0.174461529_f32)
                + (src_lfe * 0.076923080_f32)
                + (src_bc * 0.174461529_f32)
                + (src_sl * 0.226153851_f32)
                + (src_sr * 0.100615382_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.247384623_f32)
                + (src_fc * 0.174461529_f32)
                + (src_lfe * 0.076923080_f32)
                + (src_bc * 0.174461529_f32)
                + (src_sl * 0.100615382_f32)
                + (src_sr * 0.226153851_f32),
        ); // FR
    }
}

/// Translation of `SDL_Convert61To21()` (6.1 to 2.1).
fn convert_61_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 7;
        let d = dst + i * 3;
        let src_fc = rd(buf, s + 2);
        let src_bc = rd(buf, s + 4);
        let src_sl = rd(buf, s + 5);
        let src_sr = rd(buf, s + 6);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.268000007_f32)
                + (src_fc * 0.188999996_f32)
                + (src_bc * 0.188999996_f32)
                + (src_sl * 0.245000005_f32)
                + (src_sr * 0.108999997_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.268000007_f32)
                + (src_fc * 0.188999996_f32)
                + (src_bc * 0.188999996_f32)
                + (src_sl * 0.108999997_f32)
                + (src_sr * 0.245000005_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 3)); // LFE
    }
}

/// Translation of `SDL_Convert61ToQuad()` (6.1 to quad).
fn convert_61_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 7;
        let d = dst + i * 4;
        let src_fc = rd(buf, s + 2);
        let src_lfe = rd(buf, s + 3);
        let src_bc = rd(buf, s + 4);
        let src_sl = rd(buf, s + 5);
        let src_sr = rd(buf, s + 6);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.463679999_f32)
                + (src_fc * 0.327360004_f32)
                + (src_lfe * 0.040000003_f32)
                + (src_sl * 0.168960005_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.463679999_f32)
                + (src_fc * 0.327360004_f32)
                + (src_lfe * 0.040000003_f32)
                + (src_sr * 0.168960005_f32),
        ); // FR
        wr(
            buf,
            d + 2,
            (src_lfe * 0.040000003_f32) + (src_bc * 0.327360004_f32) + (src_sl * 0.431039989_f32),
        ); // BL
        wr(
            buf,
            d + 3,
            (src_lfe * 0.040000003_f32) + (src_bc * 0.327360004_f32) + (src_sr * 0.431039989_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert61To41()` (6.1 to 4.1).
fn convert_61_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 7;
        let d = dst + i * 5;
        let src_fc = rd(buf, s + 2);
        let src_bc = rd(buf, s + 4);
        let src_sl = rd(buf, s + 5);
        let src_sr = rd(buf, s + 6);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.483000010_f32)
                + (src_fc * 0.340999991_f32)
                + (src_sl * 0.175999999_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.483000010_f32)
                + (src_fc * 0.340999991_f32)
                + (src_sr * 0.175999999_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 3)); // LFE
        wr(
            buf,
            d + 3,
            (src_bc * 0.340999991_f32) + (src_sl * 0.449000001_f32),
        ); // BL
        wr(
            buf,
            d + 4,
            (src_bc * 0.340999991_f32) + (src_sr * 0.449000001_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert61To51()` (6.1 to 5.1).
fn convert_61_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 7;
        let d = dst + i * 6;
        let src_bc = rd(buf, s + 4);
        let src_sl = rd(buf, s + 5);
        let src_sr = rd(buf, s + 6);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.611000001_f32) + (src_sl * 0.223000005_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.611000001_f32) + (src_sr * 0.223000005_f32),
        ); // FR
        wr(buf, d + 2, (rd(buf, s + 2) * 0.611000001_f32)); // FC
        wr(buf, d + 3, rd(buf, s + 3)); // LFE
        wr(
            buf,
            d + 4,
            (src_bc * 0.432000011_f32) + (src_sl * 0.568000019_f32),
        ); // BL
        wr(
            buf,
            d + 5,
            (src_bc * 0.432000011_f32) + (src_sr * 0.568000019_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert61To71()` (6.1 to 7.1).
fn convert_61_to_71(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    // convert backwards, since output is growing in-place.
    for i in (0..num_frames).rev() {
        let s = src + i * 7;
        let d = dst + i * 8;
        let src_bc = rd(buf, s + 4);
        wr(buf, d + 7, rd(buf, s + 6)); // SR
        wr(buf, d + 6, rd(buf, s + 5)); // SL
        wr(buf, d + 5, (src_bc * 0.707000017_f32)); // BR
        wr(buf, d + 4, (src_bc * 0.707000017_f32)); // BL
        wr(buf, d + 3, rd(buf, s + 3)); // LFE
        wr(buf, d + 2, rd(buf, s + 2)); // FC
        wr(buf, d + 1, rd(buf, s + 1)); // FR
        wr(buf, d + 0, rd(buf, s + 0)); // FL
    }
}

/// Translation of `SDL_Convert71ToMono()` (7.1 to mono).
fn convert_71_to_mono(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 1;
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.125125006_f32)
                + (rd(buf, s + 1) * 0.125125006_f32)
                + (rd(buf, s + 2) * 0.125125006_f32)
                + (rd(buf, s + 3) * 0.125000000_f32)
                + (rd(buf, s + 4) * 0.125125006_f32)
                + (rd(buf, s + 5) * 0.125125006_f32)
                + (rd(buf, s + 6) * 0.125125006_f32)
                + (rd(buf, s + 7) * 0.125125006_f32),
        ); // FC
    }
}

/// Translation of `SDL_Convert71ToStereo()` (7.1 to stereo).
fn convert_71_to_stereo(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 2;
        let src_fc = rd(buf, s + 2);
        let src_lfe = rd(buf, s + 3);
        let src_bl = rd(buf, s + 4);
        let src_br = rd(buf, s + 5);
        let src_sl = rd(buf, s + 6);
        let src_sr = rd(buf, s + 7);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.211866662_f32)
                + (src_fc * 0.150266662_f32)
                + (src_lfe * 0.066666670_f32)
                + (src_bl * 0.181066677_f32)
                + (src_br * 0.111066669_f32)
                + (src_sl * 0.194133341_f32)
                + (src_sr * 0.085866667_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.211866662_f32)
                + (src_fc * 0.150266662_f32)
                + (src_lfe * 0.066666670_f32)
                + (src_bl * 0.111066669_f32)
                + (src_br * 0.181066677_f32)
                + (src_sl * 0.085866667_f32)
                + (src_sr * 0.194133341_f32),
        ); // FR
    }
}

/// Translation of `SDL_Convert71To21()` (7.1 to 2.1).
fn convert_71_to_21(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 3;
        let src_fc = rd(buf, s + 2);
        let src_bl = rd(buf, s + 4);
        let src_br = rd(buf, s + 5);
        let src_sl = rd(buf, s + 6);
        let src_sr = rd(buf, s + 7);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.226999998_f32)
                + (src_fc * 0.160999998_f32)
                + (src_bl * 0.194000006_f32)
                + (src_br * 0.119000003_f32)
                + (src_sl * 0.208000004_f32)
                + (src_sr * 0.092000000_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.226999998_f32)
                + (src_fc * 0.160999998_f32)
                + (src_bl * 0.119000003_f32)
                + (src_br * 0.194000006_f32)
                + (src_sl * 0.092000000_f32)
                + (src_sr * 0.208000004_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 3)); // LFE
    }
}

/// Translation of `SDL_Convert71ToQuad()` (7.1 to quad).
fn convert_71_to_quad(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 4;
        let src_fc = rd(buf, s + 2);
        let src_lfe = rd(buf, s + 3);
        let src_sl = rd(buf, s + 6);
        let src_sr = rd(buf, s + 7);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.466344833_f32)
                + (src_fc * 0.329241365_f32)
                + (src_lfe * 0.034482758_f32)
                + (src_sl * 0.169931039_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.466344833_f32)
                + (src_fc * 0.329241365_f32)
                + (src_lfe * 0.034482758_f32)
                + (src_sr * 0.169931039_f32),
        ); // FR
        wr(
            buf,
            d + 2,
            (src_lfe * 0.034482758_f32)
                + (rd(buf, s + 4) * 0.466344833_f32)
                + (src_sl * 0.433517247_f32),
        ); // BL
        wr(
            buf,
            d + 3,
            (src_lfe * 0.034482758_f32)
                + (rd(buf, s + 5) * 0.466344833_f32)
                + (src_sr * 0.433517247_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert71To41()` (7.1 to 4.1).
fn convert_71_to_41(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 5;
        let src_fc = rd(buf, s + 2);
        let src_sl = rd(buf, s + 6);
        let src_sr = rd(buf, s + 7);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.483000010_f32)
                + (src_fc * 0.340999991_f32)
                + (src_sl * 0.175999999_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.483000010_f32)
                + (src_fc * 0.340999991_f32)
                + (src_sr * 0.175999999_f32),
        ); // FR
        wr(buf, d + 2, rd(buf, s + 3)); // LFE
        wr(
            buf,
            d + 3,
            (rd(buf, s + 4) * 0.483000010_f32) + (src_sl * 0.449000001_f32),
        ); // BL
        wr(
            buf,
            d + 4,
            (rd(buf, s + 5) * 0.483000010_f32) + (src_sr * 0.449000001_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert71To51()` (7.1 to 5.1).
fn convert_71_to_51(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 6;
        let src_sl = rd(buf, s + 6);
        let src_sr = rd(buf, s + 7);
        wr(
            buf,
            d + 0,
            (rd(buf, s + 0) * 0.518000007_f32) + (src_sl * 0.188999996_f32),
        ); // FL
        wr(
            buf,
            d + 1,
            (rd(buf, s + 1) * 0.518000007_f32) + (src_sr * 0.188999996_f32),
        ); // FR
        wr(buf, d + 2, (rd(buf, s + 2) * 0.518000007_f32)); // FC
        wr(buf, d + 3, rd(buf, s + 3)); // LFE
        wr(
            buf,
            d + 4,
            (rd(buf, s + 4) * 0.518000007_f32) + (src_sl * 0.481999993_f32),
        ); // BL
        wr(
            buf,
            d + 5,
            (rd(buf, s + 5) * 0.518000007_f32) + (src_sr * 0.481999993_f32),
        ); // BR
    }
}

/// Translation of `SDL_Convert71To61()` (7.1 to 6.1).
fn convert_71_to_61(buf: &mut [u8], src: usize, dst: usize, num_frames: usize) {
    let (src, dst) = (src / 4, dst / 4);
    for i in 0..num_frames {
        let s = src + i * 8;
        let d = dst + i * 7;
        let src_bl = rd(buf, s + 4);
        let src_br = rd(buf, s + 5);
        wr(buf, d + 0, (rd(buf, s + 0) * 0.541000009_f32)); // FL
        wr(buf, d + 1, (rd(buf, s + 1) * 0.541000009_f32)); // FR
        wr(buf, d + 2, (rd(buf, s + 2) * 0.541000009_f32)); // FC
        wr(buf, d + 3, rd(buf, s + 3)); // LFE
        wr(
            buf,
            d + 4,
            (src_bl * 0.287999988_f32) + (src_br * 0.287999988_f32),
        ); // BC
        wr(
            buf,
            d + 5,
            (src_bl * 0.458999991_f32) + (rd(buf, s + 6) * 0.541000009_f32),
        ); // SL
        wr(
            buf,
            d + 6,
            (src_br * 0.458999991_f32) + (rd(buf, s + 7) * 0.541000009_f32),
        ); // SR
    }
}

/// Translation of `channel_converters`: `[from - 1][to - 1]`, `None` on the diagonal.
pub(crate) static CHANNEL_CONVERTERS: [[Option<AudioChannelConverter>; 8]; 8] = [
    [
        None,
        Some(convert_mono_to_stereo),
        Some(convert_mono_to_21),
        Some(convert_mono_to_quad),
        Some(convert_mono_to_41),
        Some(convert_mono_to_51),
        Some(convert_mono_to_61),
        Some(convert_mono_to_71),
    ],
    [
        Some(convert_stereo_to_mono),
        None,
        Some(convert_stereo_to_21),
        Some(convert_stereo_to_quad),
        Some(convert_stereo_to_41),
        Some(convert_stereo_to_51),
        Some(convert_stereo_to_61),
        Some(convert_stereo_to_71),
    ],
    [
        Some(convert_21_to_mono),
        Some(convert_21_to_stereo),
        None,
        Some(convert_21_to_quad),
        Some(convert_21_to_41),
        Some(convert_21_to_51),
        Some(convert_21_to_61),
        Some(convert_21_to_71),
    ],
    [
        Some(convert_quad_to_mono),
        Some(convert_quad_to_stereo),
        Some(convert_quad_to_21),
        None,
        Some(convert_quad_to_41),
        Some(convert_quad_to_51),
        Some(convert_quad_to_61),
        Some(convert_quad_to_71),
    ],
    [
        Some(convert_41_to_mono),
        Some(convert_41_to_stereo),
        Some(convert_41_to_21),
        Some(convert_41_to_quad),
        None,
        Some(convert_41_to_51),
        Some(convert_41_to_61),
        Some(convert_41_to_71),
    ],
    [
        Some(convert_51_to_mono),
        Some(convert_51_to_stereo),
        Some(convert_51_to_21),
        Some(convert_51_to_quad),
        Some(convert_51_to_41),
        None,
        Some(convert_51_to_61),
        Some(convert_51_to_71),
    ],
    [
        Some(convert_61_to_mono),
        Some(convert_61_to_stereo),
        Some(convert_61_to_21),
        Some(convert_61_to_quad),
        Some(convert_61_to_41),
        Some(convert_61_to_51),
        None,
        Some(convert_61_to_71),
    ],
    [
        Some(convert_71_to_mono),
        Some(convert_71_to_stereo),
        Some(convert_71_to_21),
        Some(convert_71_to_quad),
        Some(convert_71_to_41),
        Some(convert_71_to_51),
        Some(convert_71_to_61),
        None,
    ],
];
