// Rust translation of src/joystick/gdk/SDL_gameinputjoystick.cpp from Simple
// DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

//! The GameInput joystick driver (`SDL_GAMEINPUT_JoystickDriver`), ahead
//! of the other Windows drivers: the gamepads GameInput reports (when the
//! `SDL_JOYSTICK_GAMEINPUT` hint is on, the default), with their guide and
//! share buttons, rumble, trigger rumble and motion sensors, and, from raw
//! device reports (`SDL_JOYSTICK_GAMEINPUT_RAW`), the Xbox One Rock Band
//! guitars and drum kits. GameInput calls the device callback on its own
//! thread; the devices are added to the joystick list on the next detect.
//!
//! Without GameInput (no DLL, as under Wine) the driver's init fails and
//! the other drivers pick the controllers up.

use std::cell::RefCell;
use std::ffi::c_void;

use super::super::gamepad::{GamepadAxis, GamepadButton, GamepadMapping, MappingKind};
use super::super::usb_ids::{
    USB_PRODUCT_MADCATZ_XB1_DRUM_KIT, USB_PRODUCT_MADCATZ_XB1_LEGACY_ADAPTER,
    USB_PRODUCT_MADCATZ_XB1_STRATOCASTER_GUITAR, USB_PRODUCT_PDP_XB1_DRUM_KIT,
    USB_PRODUCT_PDP_XB1_JAGUAR_GUITAR, USB_PRODUCT_PDP_XB1_RIFFMASTER_GUITAR,
    USB_PRODUCT_RED_OCTANE_XB1_GUITAR_HERO_LIVE_GUITAR,
    USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_DRUMS, USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_GUITAR,
    USB_PRODUCT_XBOX360_WIRELESS_RECEIVER, USB_PRODUCT_XBOX360_WIRELESS_RECEIVER_THIRDPARTY1,
    USB_PRODUCT_XBOX360_WIRELESS_RECEIVER_THIRDPARTY2, USB_PRODUCT_XBOX_ONE_XBOXGIP_CONTROLLER,
    USB_VENDOR_CRKD, USB_VENDOR_MADCATZ, USB_VENDOR_MICROSOFT, USB_VENDOR_PDP,
    USB_VENDOR_RED_OCTANE, USB_VENDOR_RED_OCTANE_GAMES,
};
use super::super::{
    create_joystick_guid, create_joystick_name, is_joystick_xbox_series_x,
    joystick_handled_by_another_driver, lock_joysticks, private_joystick_added,
    private_joystick_removed, send_joystick_axis, send_joystick_button, send_joystick_hat,
    send_joystick_sensor, should_ignore_joystick, with_joystick, with_joysticks_unlocked,
    JoystickData, JoystickDriver, JoystickType, GAMEINPUT_DRIVER_INDEX, HARDWARE_BUS_USB,
    HAT_CENTERED, HAT_DOWN, HAT_LEFT, HAT_RIGHT, HAT_UP, PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN,
    PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN,
};
use super::{scan_int, Scan};
use crate::core::windows::error_from_hresult;
use crate::core::windows::gameinput::{
    focus_policy, gamepad_buttons, init_game_input, kind, rumble_motors, sensors, switch_position,
    system_buttons, CallbackToken, Device, DeviceInfo, GameInput, GameInputRef, GamepadState,
    Reading, RumbleParams, BLOCKING_ENUMERATION, DEVICE_CONNECTED, GAMEINPUT_API_VERSION,
    GAMEINPUT_DEFAULT,
};
use crate::error::{Error, Result};
use crate::events::JoystickID;
use crate::guid::Guid;
use crate::hints;
use crate::sensor::{SensorType, STANDARD_GRAVITY};
use crate::thread::ReentrantMutex;

/// `SDL_GAMEPAD_BUTTON_GAMEINPUT_SHARE`: the share button follows the
/// eleven buttons of the gamepad layout.
const GAMEPAD_BUTTON_GAMEINPUT_SHARE: u8 = 11;

/// The devices read from raw reports. Translation of the
/// `SDL_GAMEINPUT_RAWTYPE_*` values.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(super) enum RawType {
    None,
    RockBandGuitar,
    RockBandDrumKit,
    GuitarHeroLiveGuitar,
    LegacyAdapter,
}

/// A device of the driver. Translation of `GAMEINPUT_InternalDevice`.
struct InternalDevice {
    device: Device,
    /// `APP_LOCAL_DEVICE_ID` as a hex string
    path: String,
    name: Option<String>,
    /// generated by SDL
    guid: Guid,
    /// generated by SDL
    device_instance: JoystickID,
    vendor: u16,
    product: u16,
    raw_type: RawType,
    steam_virtual_gamepad_slot: i32,
    is_added: bool,
    is_delete_requested: bool,
}

/// The private structure used to keep track of a joystick. Translation of
/// `GAMEINPUT_InternalJoystickHwdata`.
struct HwData {
    /// The joystick this belongs to
    instance_id: JoystickID,
    /// (`devref`: a reference of its own to the device.)
    ///
    /// Note (upstream): `devref` points into the device list, whose entry
    /// is freed when the device goes away while the joystick is still
    /// open (a rumble then uses the freed entry).
    device: Device,
    raw_type: RawType,
    report_sensors: bool,
    rumble_params: RumbleParams,
    system_button_callback_token: CallbackToken,
}

/// The driver's state (`g_GameInputList`, `g_pGameInput`, ...).
#[derive(Default)]
struct State {
    /// Translation of `g_GameInputList`.
    devices: Vec<InternalDevice>,
    /// Translation of `g_pGameInput`.
    game_input: Option<GameInputRef>,
    /// Translation of `g_GameInputCallbackToken`.
    callback_token: CallbackToken,
    /// Translation of `g_GameInputTimestampOffset`.
    timestamp_offset: u64,
    /// The open joysticks' `joystick->hwdata`.
    open: Vec<HwData>,
}

/// Guarded by the joystick lock upstream; the `RefCell` borrow is never
/// held across an event push or a call back into the joystick API.
static STATE: ReentrantMutex<RefCell<Option<State>>> = ReentrantMutex::new(RefCell::new(None));

fn with_state<R>(f: impl FnOnce(&mut State) -> R) -> R {
    let guard = STATE.lock();
    let mut state = guard.borrow_mut();
    f(state.get_or_insert_with(State::default))
}

/// A new reference to the `IGameInput` interface, if the driver has it.
fn game_input() -> Option<GameInput> {
    with_state(|s| s.game_input.as_ref().map(|g| GameInput::clone(g)))
}

/// SDL's timestamp of a GameInput timestamp (microseconds), in nanoseconds.
fn sdl_timestamp(timestamp_us: u64, offset: u64) -> u64 {
    timestamp_us.wrapping_add(offset).wrapping_mul(1000)
}

/// The offset of SDL's microsecond clock from GameInput's.
pub(super) fn timestamp_offset(now_ns: u64, game_input_us: u64) -> u64 {
    (now_ns / 1000).wrapping_sub(game_input_us)
}

/// Translation of `GAMEINPUT_InternalIsGamepad()`.
pub(super) fn is_gamepad(info: &DeviceInfo) -> bool {
    (info.supported_input & kind::GAMEPAD) != 0
}

/// Translation of `GAMEINPUT_GetDeviceRawType()`.
pub(super) fn device_raw_type(info: &DeviceInfo) -> RawType {
    if GAMEINPUT_API_VERSION >= 3 && (info.supported_input & kind::RAW_DEVICE_REPORT) != 0 {
        match (info.vendor_id, info.product_id) {
            (USB_VENDOR_MADCATZ, USB_PRODUCT_MADCATZ_XB1_STRATOCASTER_GUITAR) => {
                return RawType::RockBandGuitar
            }
            (USB_VENDOR_MADCATZ, USB_PRODUCT_MADCATZ_XB1_DRUM_KIT) => {
                return RawType::RockBandDrumKit
            }
            (USB_VENDOR_MADCATZ, USB_PRODUCT_MADCATZ_XB1_LEGACY_ADAPTER) => {
                return RawType::LegacyAdapter
            }
            (
                USB_VENDOR_PDP,
                USB_PRODUCT_PDP_XB1_JAGUAR_GUITAR | USB_PRODUCT_PDP_XB1_RIFFMASTER_GUITAR,
            ) => return RawType::RockBandGuitar,
            (USB_VENDOR_PDP, USB_PRODUCT_PDP_XB1_DRUM_KIT) => return RawType::RockBandDrumKit,
            (USB_VENDOR_CRKD, USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_GUITAR) => {
                return RawType::RockBandGuitar
            }
            (USB_VENDOR_RED_OCTANE, USB_PRODUCT_RED_OCTANE_XB1_GUITAR_HERO_LIVE_GUITAR) => {
                return RawType::GuitarHeroLiveGuitar
            }
            (USB_VENDOR_RED_OCTANE_GAMES, USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_GUITAR) => {
                return RawType::RockBandGuitar
            }
            (USB_VENDOR_RED_OCTANE_GAMES, USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_DRUMS) => {
                return RawType::RockBandDrumKit
            }
            _ => {}
        }
    }
    RawType::None
}

/// Translation of `GAMEINPUT_GetDeviceSubtype()`.
pub(super) fn device_subtype(info: &DeviceInfo) -> JoystickType {
    let supported_input = info.supported_input;
    let raw_type = device_raw_type(info);
    if raw_type == RawType::RockBandGuitar || raw_type == RawType::GuitarHeroLiveGuitar {
        return JoystickType::Guitar;
    }
    if raw_type == RawType::RockBandDrumKit {
        return JoystickType::DrumKit;
    }
    if (supported_input & kind::RACING_WHEEL) != 0 {
        return JoystickType::Wheel;
    }
    if (supported_input & kind::ARCADE_STICK) != 0 {
        return JoystickType::ArcadeStick;
    }
    if (supported_input & kind::FLIGHT_STICK) != 0 {
        return JoystickType::FlightStick;
    }
    if (supported_input & (kind::GAMEPAD | kind::CONTROLLER)) != 0 {
        return JoystickType::Gamepad;
    }
    // Other device subtypes don't have their own GameInputKind enum entries.
    JoystickType::Unknown
}

/// Translation of `GetSteamVirtualGamepadSlot()`.
pub(super) fn steam_virtual_gamepad_slot(device_path: &str) -> i32 {
    // The format for the raw input device path is documented here:
    // https://partner.steamgames.com/doc/features/steam_controller/steam_input_gamepad_emulation_bestpractices
    use Scan::*;
    scan_int(
        device_path,
        &[
            Lit("\\\\.\\pipe\\HID#VID_045E&PID_028E&IG_00#"),
            SkipHex,
            Lit("&"),
            SkipHex,
            Lit("&"),
            SkipHex,
            Lit("#"),
            Int,
            Lit("#"),
            SkipUnsigned,
        ],
    )
    .unwrap_or(-1)
}

/// Translation of `IsXbox360WirelessAdapter()`.
pub(super) fn is_xbox360_wireless_adapter(vendor: u16, product: u16) -> bool {
    vendor == USB_VENDOR_MICROSOFT
        && matches!(
            product,
            USB_PRODUCT_XBOX360_WIRELESS_RECEIVER
                | USB_PRODUCT_XBOX360_WIRELESS_RECEIVER_THIRDPARTY1
                | USB_PRODUCT_XBOX360_WIRELESS_RECEIVER_THIRDPARTY2
        )
}

/// The device path: the `APP_LOCAL_DEVICE_ID` as a hex string.
pub(super) fn device_path(device_id: &[u8]) -> String {
    device_id.iter().map(|b| format!("{b:02X}")).collect()
}

/// The manufacturer and product strings of a device. Translation of
/// `QueryDeviceName()`.
fn query_device_name(
    info: &DeviceInfo,
    vendor_id: u16,
    product_id: u16,
) -> (Option<String>, Option<String>) {
    let manufacturer_string =
        super::super::hidapi::get_device_manufacturer_name(vendor_id, product_id);
    let product_string = super::super::hidapi::get_device_product_name(vendor_id, product_id);
    if product_string.is_some() {
        return (manufacturer_string, product_string);
    }

    (None, info.display_name())
}

/// Translation of `GAMEINPUT_InternalAddOrFind()`.
fn internal_add_or_find(device: Device) {
    crate::joystick::assert_joysticks_locked();

    let info = device.info();
    // (info->capabilities & GameInputDeviceCapabilityWireless isn't checked
    // upstream: the bus is always USB)
    let bus = HARDWARE_BUS_USB;
    let vendor = info.vendor_id;
    let product = info.product_id;
    let version = 0u16;
    let mut driver_signature = b'g';
    let mut subtype = device_subtype(info);
    let raw_type = device_raw_type(info);

    let (manufacturer_string, product_string) = query_device_name(info, vendor, product);

    if is_xbox360_wireless_adapter(vendor, product)
        || should_ignore_joystick(vendor, product, version, product_string.as_deref())
        || joystick_handled_by_another_driver(
            GAMEINPUT_DRIVER_INDEX,
            vendor,
            product,
            version,
            product_string.as_deref(),
        )
    {
        return;
    }

    // This joystick backend currently doesn't provide a haptic backend, so fallback to DirectInput for haptic-capable devices.
    if hints::get_bool(hints::JOYSTICK_DIRECTINPUT, true)
        && info.force_feedback_motor_count > 0
        && device.is_force_feedback_motor_powered_on(0)
    {
        return;
    }

    if is_gamepad(info) {
        if !hints::get_bool(hints::JOYSTICK_GAMEINPUT, GAMEINPUT_DEFAULT) {
            return;
        }
    } else if raw_type == RawType::None {
        // Let other backends handle non-gamepad controllers to possibly avoid bugs and/or regressions.
        if hints::get_bool(hints::JOYSTICK_DIRECTINPUT, true) {
            return;
        }
        if (info.supported_input & kind::CONTROLLER) != 0 {
            // Maintain GUID compatibility with DirectInput controller mappings.
            driver_signature = 0;
            subtype = JoystickType::Unknown;
        } else {
            // This joystick backend currently doesn't provide proper reading of other joystick types.
            return;
        }
    }

    let found = with_state(|s| {
        match s.devices.iter_mut().find(|e| e.device.same(&device)) {
            Some(elem) => {
                // we're already added
                elem.is_delete_requested = false;
                true
            }
            None => false,
        }
    });
    if found {
        return;
    }

    let elem = InternalDevice {
        // Generate a device path
        path: device_path(&info.device_id),
        name: create_joystick_name(
            vendor,
            product,
            manufacturer_string.as_deref(),
            product_string.as_deref(),
        ),
        guid: create_joystick_guid(
            bus,
            vendor,
            product,
            version,
            manufacturer_string.as_deref(),
            product_string.as_deref(),
            driver_signature,
            subtype as u8,
        ),
        device_instance: crate::utils::next_object_id(),
        vendor,
        product,
        raw_type,
        steam_virtual_gamepad_slot: info
            .pnp_path()
            .map_or(-1, |p| steam_virtual_gamepad_slot(&p)),
        is_added: false,
        is_delete_requested: false,
        device: device.clone(),
    };
    with_state(|s| s.devices.push(elem));
}

/// Translation of `GAMEINPUT_InternalJoystickDeviceCallback()`.
unsafe extern "system" fn internal_joystick_device_callback(
    _callback_token: CallbackToken,
    _context: *mut c_void,
    device: *mut c_void,
    _timestamp: u64,
    current_status: u32,
    _previous_status: u32,
) {
    if device.is_null() {
        // This should never happen, but ignore it if it does
        return;
    }

    let _lock = lock_joysticks();

    if (current_status & DEVICE_CONNECTED) != 0 {
        // SAFETY: GameInput passes a live device.
        if let Ok(device) = unsafe { Device::from_borrowed(device) } {
            internal_add_or_find(device);
        }
        // (a failure sets the error "IGameInputDevice::GetDeviceInfo"
        // upstream, which nobody reads)
    } else {
        with_state(|s| {
            if let Some(elem) = s.devices.iter_mut().find(|e| e.device.is(device)) {
                // will be deleted on the next Detect call
                elem.is_delete_requested = true;
            }
        });
    }
}

/// Translation of `GAMEINPUT_IsRawGameInputEnabled()`.
fn is_raw_game_input_enabled() -> bool {
    GAMEINPUT_API_VERSION >= 3 && hints::get_bool(hints::JOYSTICK_GAMEINPUT_RAW, true)
}

/// Translation of `GAMEINPUT_InternalSystemButtonCallback()`; the context
/// is the joystick's instance ID.
unsafe extern "system" fn internal_system_button_callback(
    _callback_token: CallbackToken,
    context: *mut c_void,
    _device: *mut c_void,
    timestamp_us: u64,
    current_buttons: u32,
    previous_buttons: u32,
) {
    let joystick = context as usize as JoystickID;

    let changed_buttons = previous_buttons ^ current_buttons;
    if changed_buttons != 0 {
        let _lock = lock_joysticks();
        let timestamp = sdl_timestamp(timestamp_us, with_state(|s| s.timestamp_offset));

        for (button, down) in system_button_inputs(changed_buttons, current_buttons) {
            send_joystick_button(timestamp, joystick, button, down);
        }
    }
}

/// The joystick buttons of the system buttons that changed.
pub(super) fn system_button_inputs(changed_buttons: u32, current_buttons: u32) -> Vec<(u8, bool)> {
    let mut inputs = Vec::new();
    if (changed_buttons & system_buttons::GUIDE) != 0 {
        let down = (current_buttons & system_buttons::GUIDE) != 0;
        inputs.push((GamepadButton::Guide as u8, down));
    }
    if (changed_buttons & system_buttons::SHARE) != 0 {
        let down = (current_buttons & system_buttons::SHARE) != 0;
        inputs.push((GAMEPAD_BUTTON_GAMEINPUT_SHARE, down));
    }
    inputs
}

/// A joystick event of a reading, in the order upstream sends them.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(super) enum Input {
    Button(u8, bool),
    Hat(u8, u8),
    Axis(u8, i16),
}

/// Send the events of a reading.
fn send_inputs(timestamp: u64, joystick: JoystickID, inputs: &[Input]) {
    for &input in inputs {
        match input {
            Input::Button(button, down) => send_joystick_button(timestamp, joystick, button, down),
            Input::Hat(hat, value) => send_joystick_hat(timestamp, joystick, hat, value),
            Input::Axis(axis, value) => send_joystick_axis(timestamp, joystick, axis, value),
        }
    }
}

/// The d-pad hat of the four direction bits of the raw instrument reports.
fn raw_dpad_hat(buttons: u16) -> u8 {
    let mut hat = HAT_CENTERED;
    if (buttons & 0x0100) != 0 {
        hat |= HAT_UP;
    }
    if (buttons & 0x0200) != 0 {
        hat |= HAT_DOWN;
    }
    if (buttons & 0x0400) != 0 {
        hat |= HAT_LEFT;
    }
    if (buttons & 0x0800) != 0 {
        hat |= HAT_RIGHT;
    }
    hat
}

/// The events of a drum kit's raw report (`len` bytes of `raw_data`).
/// Translation of `GAMEINPUT_DrumUpdate()`.
pub(super) fn drum_inputs(raw_data: &[u8; 40], len: usize) -> Vec<Input> {
    let mut inputs = Vec::new();
    let buttons = raw_data[0] as u16 | (raw_data[1] as u16) << 8;
    if len >= 6 {
        let mut hat = HAT_CENTERED;
        if (buttons & 0x0100) != 0 || (raw_data[4] & 0xf0) != 0 {
            hat |= HAT_UP;
        }
        if (buttons & 0x0200) != 0 || (raw_data[4] & 0x0f) != 0 {
            hat |= HAT_DOWN;
        }
        if (buttons & 0x0400) != 0 {
            hat |= HAT_LEFT;
        }
        if (buttons & 0x0800) != 0 {
            hat |= HAT_RIGHT;
        }
        inputs.push(Input::Hat(0, hat));
        // The rest of the instruments are mapped to PS3 style inputs
        // The PS3 used flags for dictating if a pad or a cymbal was hit, so we emulate that here
        let button = |b: GamepadButton, down: bool| Input::Button(b as u8, down);
        inputs.extend([
            button(GamepadButton::Back, (buttons & 0x0008) != 0),
            button(GamepadButton::Start, (buttons & 0x0004) != 0),
            button(GamepadButton::LeftShoulder, (buttons & 0x1000) != 0),
            button(GamepadButton::RightShoulder, (buttons & 0x2000) != 0),
            button(
                GamepadButton::South,
                (raw_data[3] & 0x0f) != 0 || (raw_data[5] & 0xf0) != 0 || (buttons & 0x0010) != 0,
            ),
            button(
                GamepadButton::East,
                (raw_data[2] & 0xf0) != 0 || (buttons & 0x0020) != 0,
            ),
            button(
                GamepadButton::West,
                (raw_data[3] & 0xf0) != 0 || (raw_data[4] & 0x0f) != 0 || (buttons & 0x0040) != 0,
            ),
            button(
                GamepadButton::North,
                (raw_data[2] & 0x0f) != 0 || (raw_data[4] & 0xf0) != 0 || (buttons & 0x0080) != 0,
            ),
            button(
                GamepadButton::LeftStick,
                raw_data[2] != 0 || raw_data[3] != 0,
            ),
            button(
                GamepadButton::RightStick,
                raw_data[4] != 0 || raw_data[5] != 0,
            ),
        ]);
    }
    inputs
}

/// Translation of `s_GuitarButtons`: the raw button of each joystick
/// button (0: not available).
const GUITAR_BUTTONS: [u16; 11] = [
    0x0010, // SDL_GAMEPAD_BUTTON_SOUTH
    0x0020, // SDL_GAMEPAD_BUTTON_EAST
    0x0040, // SDL_GAMEPAD_BUTTON_WEST
    0x0080, // SDL_GAMEPAD_BUTTON_NORTH
    0x0008, // SDL_GAMEPAD_BUTTON_BACK
    0,      // The guide button is not available
    0x0004, // SDL_GAMEPAD_BUTTON_START
    0,      // right joystick click unavailable
    0x4000, // SDL_GAMEPAD_BUTTON_RIGHT_STICK
    0x1000, // SDL_GAMEPAD_BUTTON_LEFT_SHOULDER
    0,      // right shoulder unavailable
];

/// Align pickup selector mappings with PS3 instruments
const EFFECTS_MAPPINGS: [i16; 5] = [-26880, -13568, -1792, 11008, 24576];

/// The events of a guitar's raw report (`len` bytes of `raw_data`).
/// Translation of `GAMEINPUT_GuitarUpdate()`.
pub(super) fn guitar_inputs(raw_data: &[u8; 40], len: usize) -> Vec<Input> {
    let mut inputs = Vec::new();
    let buttons = raw_data[0] as u16 | (raw_data[1] as u16) << 8;
    if len >= 10 {
        for (btnidx, &button_mask) in GUITAR_BUTTONS.iter().enumerate() {
            if button_mask == 0 {
                continue;
            }
            let down = (buttons & button_mask) != 0;
            inputs.push(Input::Button(btnidx as u8, down));
        }
        inputs.push(Input::Hat(0, raw_dpad_hat(buttons)));
        inputs.push(Input::Axis(
            GamepadAxis::RightX as u8,
            ((raw_data[3] as i32 * 257) - 32768) as i16,
        ));
        // PS3 RB guitars had tilt on right shoulder
        inputs.push(Input::Button(
            GamepadButton::RightShoulder as u8,
            raw_data[2] >= 0xD0,
        ));
        // PS3 RB guitars send L2 when using solo buttons
        inputs.push(Input::Axis(
            GamepadAxis::LeftTrigger as u8,
            if raw_data[6] != 0 { 32767 } else { -32768 },
        ));
        // Note (upstream): upstream indexes its five mappings with the top
        // nibble, reading past the table for 5 and up; here those send
        // nothing.
        if let Some(&effect) = EFFECTS_MAPPINGS.get((raw_data[4] >> 4) as usize) {
            inputs.push(Input::Axis(GamepadAxis::RightY as u8, effect));
        }
    }
    inputs
}

/// Translation of `s_XInputButtons`: the GameInput button of each joystick
/// button (0: not available).
const XINPUT_BUTTONS: [u32; 11] = [
    gamepad_buttons::A,                // SDL_GAMEPAD_BUTTON_SOUTH
    gamepad_buttons::B,                // SDL_GAMEPAD_BUTTON_EAST
    gamepad_buttons::X,                // SDL_GAMEPAD_BUTTON_WEST
    gamepad_buttons::Y,                // SDL_GAMEPAD_BUTTON_NORTH
    gamepad_buttons::VIEW,             // SDL_GAMEPAD_BUTTON_BACK
    0,                                 // The guide button is not available
    gamepad_buttons::MENU,             // SDL_GAMEPAD_BUTTON_START
    gamepad_buttons::LEFT_THUMBSTICK,  // SDL_GAMEPAD_BUTTON_LEFT_STICK
    gamepad_buttons::RIGHT_THUMBSTICK, // SDL_GAMEPAD_BUTTON_RIGHT_STICK
    gamepad_buttons::LEFT_SHOULDER,    // SDL_GAMEPAD_BUTTON_LEFT_SHOULDER
    gamepad_buttons::RIGHT_SHOULDER,   // SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER
];

/// A thumbstick axis (-1 to 1). Translation of `CONVERT_AXIS()` of
/// `GAMEINPUT_GamepadUpdate()`.
pub(super) fn convert_stick(v: f32) -> i16 {
    (if v < 0.0 { v * 32768.0 } else { v * 32767.0 }) as i16
}

/// A trigger or controller axis (0 to 1). Translation of `CONVERT_TRIGGER()`
/// (and `CONVERT_AXIS()` of `GAMEINPUT_ControllerUpdate()`).
pub(super) fn convert_trigger(v: f32) -> i16 {
    (v * 65535.0 - 32768.0) as i16
}

/// The events of a gamepad state. Translation of
/// `GAMEINPUT_GamepadUpdate()`.
pub(super) fn gamepad_inputs(state: &GamepadState) -> Vec<Input> {
    let mut inputs = Vec::new();
    for (btnidx, &button_mask) in XINPUT_BUTTONS.iter().enumerate() {
        if button_mask == 0 {
            continue;
        }
        let down = (state.buttons & button_mask) != 0;
        inputs.push(Input::Button(btnidx as u8, down));
    }

    let mut hat = HAT_CENTERED;
    if (state.buttons & gamepad_buttons::DPAD_UP) != 0 {
        hat |= HAT_UP;
    }
    if (state.buttons & gamepad_buttons::DPAD_DOWN) != 0 {
        hat |= HAT_DOWN;
    }
    if (state.buttons & gamepad_buttons::DPAD_LEFT) != 0 {
        hat |= HAT_LEFT;
    }
    if (state.buttons & gamepad_buttons::DPAD_RIGHT) != 0 {
        hat |= HAT_RIGHT;
    }
    inputs.push(Input::Hat(0, hat));

    let axis = |a: GamepadAxis, v: i16| Input::Axis(a as u8, v);
    inputs.extend([
        axis(GamepadAxis::LeftX, convert_stick(state.left_thumbstick_x)),
        axis(GamepadAxis::LeftY, convert_stick(-state.left_thumbstick_y)),
        axis(GamepadAxis::RightX, convert_stick(state.right_thumbstick_x)),
        axis(
            GamepadAxis::RightY,
            convert_stick(-state.right_thumbstick_y),
        ),
        axis(
            GamepadAxis::LeftTrigger,
            convert_trigger(state.left_trigger),
        ),
        axis(
            GamepadAxis::RightTrigger,
            convert_trigger(state.right_trigger),
        ),
    ]);
    inputs
}

/// The hat value of a switch position.
pub(super) fn switch_hat(position: i32) -> u8 {
    match position {
        switch_position::UP => HAT_UP,
        switch_position::UP_RIGHT => HAT_UP | HAT_RIGHT,
        switch_position::RIGHT => HAT_RIGHT,
        switch_position::DOWN_RIGHT => HAT_DOWN | HAT_RIGHT,
        switch_position::DOWN => HAT_DOWN,
        switch_position::DOWN_LEFT => HAT_DOWN | HAT_LEFT,
        switch_position::LEFT => HAT_LEFT,
        switch_position::UP_LEFT => HAT_UP | HAT_LEFT,
        // (switch_position::CENTER and anything else)
        _ => HAT_CENTERED,
    }
}

/// The events of a controller's buttons, axes and switches. Translation
/// of `GAMEINPUT_ControllerUpdate()`.
pub(super) fn controller_inputs(buttons: &[bool], axes: &[f32], switches: &[i32]) -> Vec<Input> {
    let buttons = buttons
        .iter()
        .enumerate()
        .map(|(i, &down)| Input::Button(i as u8, down));
    let axes = axes
        .iter()
        .enumerate()
        .map(|(i, &v)| Input::Axis(i as u8, convert_trigger(v)));
    let hats = switches
        .iter()
        .enumerate()
        .map(|(i, &position)| Input::Hat(i as u8, switch_hat(position)));
    buttons.chain(axes).chain(hats).collect()
}

/// The events of a reading of a device that isn't a gamepad or a raw
/// instrument, for a joystick of `nbuttons`, `naxes` and `nhats`.
fn read_controller(reading: &Reading, nbuttons: usize, naxes: usize, nhats: usize) -> Vec<Input> {
    controller_inputs(
        &reading.controller_button_state(nbuttons),
        &reading.controller_axis_state(naxes),
        &reading.controller_switch_state(nhats),
    )
}

/// The raw report of a reading, if it has one: up to 40 bytes and the
/// length copied.
fn read_raw_report(reading: &Reading) -> Option<([u8; 40], usize)> {
    // Note (upstream): upstream never releases the report it gets.
    let report = reading.raw_report()?;
    let mut raw_data = [0u8; 40];
    let len = report.raw_data(&mut raw_data);
    Some((raw_data, len))
}

/// The gamepad layout of a device's joystick, for the gamepads and raw
/// instruments. Translation of `GAMEINPUT_JoystickGetGamepadMapping()`.
pub(super) fn gamepad_mapping_for(
    is_gamepad: bool,
    raw_type: RawType,
    supported_system_buttons: u32,
    vendor: u16,
    product: u16,
) -> Option<GamepadMapping> {
    if !is_gamepad && raw_type == RawType::None {
        return None;
    }

    let mut out = GamepadMapping::default();
    let button = |target: GamepadButton| super::super::gamepad::InputMapping {
        kind: MappingKind::Button,
        target: target as u8,
        ..Default::default()
    };
    let hat = |target: u8| super::super::gamepad::InputMapping {
        kind: MappingKind::Hat,
        target,
        ..Default::default()
    };
    let axis = |target: GamepadAxis| super::super::gamepad::InputMapping {
        kind: MappingKind::Axis,
        target: target as u8,
        ..Default::default()
    };

    out.a = button(GamepadButton::South);
    out.b = button(GamepadButton::East);
    out.x = button(GamepadButton::West);
    out.y = button(GamepadButton::North);
    out.back = button(GamepadButton::Back);

    if (supported_system_buttons & system_buttons::GUIDE) != 0 {
        out.guide = button(GamepadButton::Guide);
    }

    if is_joystick_xbox_series_x(vendor, product)
        && (supported_system_buttons & system_buttons::SHARE) != 0
    {
        out.misc1 = super::super::gamepad::InputMapping {
            kind: MappingKind::Button,
            target: GAMEPAD_BUTTON_GAMEINPUT_SHARE,
            ..Default::default()
        };
    }

    out.start = button(GamepadButton::Start);
    out.leftstick = button(GamepadButton::LeftStick);
    out.rightstick = button(GamepadButton::RightStick);
    out.leftshoulder = button(GamepadButton::LeftShoulder);
    out.rightshoulder = button(GamepadButton::RightShoulder);

    out.dpup = hat(HAT_UP);
    out.dpdown = hat(HAT_DOWN);
    out.dpleft = hat(HAT_LEFT);
    out.dpright = hat(HAT_RIGHT);

    out.leftx = axis(GamepadAxis::LeftX);
    out.lefty = axis(GamepadAxis::LeftY);
    out.rightx = axis(GamepadAxis::RightX);
    out.righty = axis(GamepadAxis::RightY);
    out.lefttrigger = axis(GamepadAxis::LeftTrigger);
    out.righttrigger = axis(GamepadAxis::RightTrigger);

    Some(out)
}

/// Translation of `SDL_GAMEINPUT_JoystickDriver`.
pub(in crate::joystick) struct GameInputJoystickDriver;

pub(in crate::joystick) static GAMEINPUT_JOYSTICK_DRIVER: GameInputJoystickDriver =
    GameInputJoystickDriver;

impl JoystickDriver for GameInputJoystickDriver {
    /// Translation of `GAMEINPUT_JoystickInit()`.
    fn init(&self) -> Result<()> {
        if !hints::get_bool(hints::JOYSTICK_GAMEINPUT, GAMEINPUT_DEFAULT)
            && !is_raw_game_input_enabled()
        {
            return Ok(());
        }

        let game_input_ref = init_game_input()?;
        let game_input = GameInput::clone(&game_input_ref);
        with_state(|s| s.game_input = Some(game_input_ref));

        // Allow background controller input
        // SDL manages focus policy at a higher level, so we can set this unconditionally.
        game_input.set_focus_policy(
            focus_policy::ENABLE_BACKGROUND_INPUT
                | focus_policy::ENABLE_BACKGROUND_GUIDE_BUTTON
                | focus_policy::ENABLE_BACKGROUND_SHARE_BUTTON,
        );

        let mut input_kind = kind::UNKNOWN;
        if hints::get_bool(hints::JOYSTICK_GAMEINPUT, GAMEINPUT_DEFAULT) {
            input_kind |= kind::CONTROLLER;
        }
        if is_raw_game_input_enabled() {
            input_kind |= kind::RAW_DEVICE_REPORT;
        }

        // SAFETY: the callback uses no context.
        let token = unsafe {
            game_input.register_device_callback(
                input_kind,
                DEVICE_CONNECTED,
                BLOCKING_ENUMERATION,
                std::ptr::null_mut(),
                internal_joystick_device_callback,
            )
        };
        match token {
            Ok(token) => with_state(|s| s.callback_token = token),
            Err(hr) => {
                self.quit();
                return Err(error_from_hresult(
                    Some("IGameInput::RegisterDeviceCallback"),
                    hr,
                ));
            }
        }

        // Calculate the relative offset between SDL timestamps and GameInput timestamps
        let now = crate::timer::ticks_ns();
        let timestamp_us = game_input.current_timestamp();
        with_state(|s| s.timestamp_offset = timestamp_offset(now, timestamp_us));

        self.detect();

        Ok(())
    }

    /// Translation of `GAMEINPUT_JoystickGetCount()`.
    fn count(&self) -> usize {
        with_state(|s| s.devices.len())
    }

    /// Translation of `GAMEINPUT_JoystickDetect()`.
    fn detect(&self) {
        crate::joystick::assert_joysticks_locked();

        let mut idx = 0;
        while let Some((instance, is_added)) =
            with_state(|s| s.devices.get(idx).map(|e| (e.device_instance, e.is_added)))
        {
            if !is_added {
                private_joystick_added(instance);
                with_state(|s| {
                    if let Some(e) = s.devices.iter_mut().find(|e| e.device_instance == instance) {
                        e.is_added = true;
                    }
                });
            }

            let remove = with_state(|s| {
                s.devices
                    .iter()
                    .find(|e| e.device_instance == instance)
                    .is_some_and(|e| {
                        e.is_delete_requested || (e.device.status() & DEVICE_CONNECTED) == 0
                    })
            });
            if remove {
                private_joystick_removed(instance);
                // (GAMEINPUT_InternalRemoveByIndex(): the device's reference
                // is released with it)
                with_state(|s| s.devices.retain(|e| e.device_instance != instance));
            } else {
                idx += 1;
            }
        }
    }

    /// Translation of `GAMEINPUT_JoystickIsDevicePresent()`.
    fn is_device_present(
        &self,
        vendor_id: u16,
        product_id: u16,
        _version: u16,
        _name: Option<&str>,
    ) -> bool {
        crate::joystick::assert_joysticks_locked();

        with_state(|s| {
            if s.game_input.is_none() {
                return false;
            }
            if vendor_id == USB_VENDOR_MICROSOFT
                && product_id == USB_PRODUCT_XBOX_ONE_XBOXGIP_CONTROLLER
            {
                // The Xbox One controller shows up as a hardcoded raw input VID/PID, which we definitely handle
                if hints::get_bool(hints::JOYSTICK_GAMEINPUT, GAMEINPUT_DEFAULT) {
                    return true;
                }
            }

            s.devices.iter().any(|e| {
                let info = e.device.info();
                vendor_id == info.vendor_id && product_id == info.product_id
            })
        })
    }

    /// Translation of `GAMEINPUT_JoystickGetDeviceName()`.
    fn device_name(&self, device_index: usize) -> Option<String> {
        with_state(|s| s.devices.get(device_index).and_then(|e| e.name.clone()))
    }

    /// Translation of `GAMEINPUT_JoystickGetDevicePath()`.
    fn device_path(&self, device_index: usize) -> Option<String> {
        // APP_LOCAL_DEVICE_ID as a hex string, since it's required for some association callbacks
        with_state(|s| s.devices.get(device_index).map(|e| e.path.clone()))
    }

    /// Translation of `GAMEINPUT_JoystickGetDeviceSteamVirtualGamepadSlot()`.
    fn device_steam_virtual_gamepad_slot(&self, device_index: usize) -> i32 {
        with_state(|s| {
            s.devices
                .get(device_index)
                .map_or(-1, |e| e.steam_virtual_gamepad_slot)
        })
    }

    /// Translation of `GAMEINPUT_JoystickGetDevicePlayerIndex()`.
    fn device_player_index(&self, _device_index: usize) -> i32 {
        -1
    }

    /// Translation of `GAMEINPUT_JoystickSetDevicePlayerIndex()`.
    fn set_device_player_index(&self, _device_index: usize, _player_index: i32) {}

    /// Translation of `GAMEINPUT_JoystickGetDeviceGUID()`.
    fn device_guid(&self, device_index: usize) -> Guid {
        with_state(|s| s.devices.get(device_index).map_or(Guid::ZERO, |e| e.guid))
    }

    /// Translation of `GAMEINPUT_JoystickGetDeviceInstanceID()`.
    fn device_instance_id(&self, device_index: usize) -> JoystickID {
        with_state(|s| s.devices.get(device_index).map_or(0, |e| e.device_instance))
    }

    /// Translation of `GAMEINPUT_JoystickOpen()`.
    fn open(&self, joystick: &mut JoystickData, device_index: usize) -> Result<()> {
        let Some((device, raw_type, vendor, product)) = with_state(|s| {
            s.devices
                .get(device_index)
                .map(|e| (e.device.clone(), e.raw_type, e.vendor, e.product))
        }) else {
            return Err(Error::new("No such device"));
        };
        let info = device.info();

        let mut system_button_callback_token = 0;
        if is_gamepad(info) || raw_type != RawType::None {
            joystick.naxes = 6;
            joystick.nbuttons = 11;
            joystick.nhats = 1;

            if info.supported_system_buttons != system_buttons::NONE {
                let mut buttons = system_buttons::GUIDE;

                if is_joystick_xbox_series_x(vendor, product)
                    && (info.supported_system_buttons & system_buttons::SHARE) != 0
                {
                    joystick.nbuttons += 1;
                    buttons |= system_buttons::SHARE;
                }

                if let Some(game_input) = game_input() {
                    // SAFETY: the context is the instance ID, not a pointer.
                    let token = unsafe {
                        game_input.register_system_button_callback(
                            &device,
                            buttons,
                            joystick.instance_id as usize as *mut c_void,
                            internal_system_button_callback,
                        )
                    };
                    system_button_callback_token = token.unwrap_or(0);
                }
            }
        } else if let Some(controller_info) = info.controller_info() {
            joystick.naxes = controller_info.controller_axis_count as usize;
            joystick.nbuttons = controller_info.controller_button_count as usize;
            joystick.nhats = controller_info.controller_switch_count as usize;
        }

        let props = joystick.properties();
        if (info.supported_rumble_motors
            & (rumble_motors::LOW_FREQUENCY | rumble_motors::HIGH_FREQUENCY))
            != 0
        {
            let _ = props.set(PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN, true);
        }
        if (info.supported_rumble_motors
            & (rumble_motors::LEFT_TRIGGER | rumble_motors::RIGHT_TRIGGER))
            != 0
        {
            let _ = props.set(PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN, true);
        }

        if (info.supported_input & kind::SENSORS) != 0 {
            let supported_sensors = info.sensors_info().map_or(0, |s| s.supported_sensors);
            if (supported_sensors & sensors::GYROMETER) != 0 {
                joystick.add_sensor(SensorType::Gyro, 60.0);
            }
            if (supported_sensors & sensors::ACCELEROMETER) != 0 {
                joystick.add_sensor(SensorType::Accel, 60.0);
            }
        }

        let hwdata = HwData {
            instance_id: joystick.instance_id,
            device: device.clone(),
            raw_type,
            report_sensors: false,
            rumble_params: RumbleParams::default(),
            system_button_callback_token,
        };
        with_state(|s| s.open.push(hwdata));
        Ok(())
    }

    /// Translation of `GAMEINPUT_JoystickRumble()`.
    fn rumble(
        &self,
        joystick: JoystickID,
        low_frequency_rumble: u16,
        high_frequency_rumble: u16,
    ) -> Result<()> {
        // don't check for caps here, since SetRumbleState doesn't return any result - we don't need to check it
        with_state(|s| {
            let hwdata = s
                .open
                .iter_mut()
                .find(|h| h.instance_id == joystick)
                .ok_or_else(|| Error::invalid_param("joystick"))?;
            let params = &mut hwdata.rumble_params;
            params.low_frequency = low_frequency_rumble as f32 / u16::MAX as f32;
            params.high_frequency = high_frequency_rumble as f32 / u16::MAX as f32;
            hwdata.device.set_rumble_state(params);
            Ok(())
        })
    }

    /// Translation of `GAMEINPUT_JoystickRumbleTriggers()`.
    fn rumble_triggers(
        &self,
        joystick: JoystickID,
        left_rumble: u16,
        right_rumble: u16,
    ) -> Result<()> {
        // don't check for caps here, since SetRumbleState doesn't return any result - we don't need to check it
        with_state(|s| {
            let hwdata = s
                .open
                .iter_mut()
                .find(|h| h.instance_id == joystick)
                .ok_or_else(|| Error::invalid_param("joystick"))?;
            let params = &mut hwdata.rumble_params;
            params.left_trigger = left_rumble as f32 / u16::MAX as f32;
            params.right_trigger = right_rumble as f32 / u16::MAX as f32;
            hwdata.device.set_rumble_state(params);
            Ok(())
        })
    }

    /// Translation of `GAMEINPUT_JoystickSetLED()`.
    fn set_led(&self, _joystick: JoystickID, _red: u8, _green: u8, _blue: u8) -> Result<()> {
        Err(Error::unsupported())
    }

    /// Translation of `GAMEINPUT_JoystickSendEffect()`.
    fn send_effect(&self, _joystick: JoystickID, _data: &[u8]) -> Result<()> {
        Err(Error::unsupported())
    }

    /// Translation of `GAMEINPUT_JoystickSetSensorsEnabled()`.
    fn set_sensors_enabled(&self, joystick: JoystickID, enabled: bool) -> Result<()> {
        with_state(|s| {
            if let Some(hwdata) = s.open.iter_mut().find(|h| h.instance_id == joystick) {
                hwdata.report_sensors = enabled;
            }
        });
        Ok(())
    }

    /// Translation of `GAMEINPUT_JoystickUpdate()`.
    fn update(&self, joystick: JoystickID) {
        let Some((game_input, device, raw_type, report_sensors, offset)) = with_state(|s| {
            let game_input = s.game_input.as_ref().map(|g| GameInput::clone(g))?;
            s.open.iter().find(|h| h.instance_id == joystick).map(|h| {
                (
                    game_input,
                    h.device.clone(),
                    h.raw_type,
                    h.report_sensors,
                    s.timestamp_offset,
                )
            })
        }) else {
            return;
        };
        let info = device.info();

        let Ok(reading) = game_input.current_reading(info.supported_input, Some(&device)) else {
            // don't SetError here since there can be a legitimate case when there's no reading avail
            return;
        };

        let timestamp = sdl_timestamp(reading.timestamp(), offset);
        let inputs = if raw_type == RawType::RockBandGuitar {
            read_raw_report(&reading).map_or_else(Vec::new, |(raw, len)| guitar_inputs(&raw, len))
        } else if raw_type == RawType::RockBandDrumKit {
            read_raw_report(&reading).map_or_else(Vec::new, |(raw, len)| drum_inputs(&raw, len))
        } else if is_gamepad(info) {
            reading
                .gamepad_state()
                .map_or_else(Vec::new, |state| gamepad_inputs(&state))
        } else {
            let Some((nbuttons, naxes, nhats)) =
                with_joystick(joystick, |j| (j.nbuttons, j.naxes, j.nhats))
            else {
                return;
            };
            read_controller(&reading, nbuttons, naxes, nhats)
        };
        send_inputs(timestamp, joystick, &inputs);

        if report_sensors {
            if let Some(sensor_state) = reading.sensors_state() {
                let supported_sensors = info.sensors_info().map_or(0, |s| s.supported_sensors);
                if (supported_sensors & sensors::GYROMETER) != 0 {
                    let data = [
                        sensor_state.angular_velocity_in_rad_per_sec_x,
                        sensor_state.angular_velocity_in_rad_per_sec_y,
                        sensor_state.angular_velocity_in_rad_per_sec_z,
                    ];
                    send_joystick_sensor(timestamp, joystick, SensorType::Gyro, timestamp, &data);
                }
                if (supported_sensors & sensors::ACCELEROMETER) != 0 {
                    let data = [
                        sensor_state.acceleration_in_g_x * STANDARD_GRAVITY,
                        sensor_state.acceleration_in_g_y * STANDARD_GRAVITY,
                        sensor_state.acceleration_in_g_z * STANDARD_GRAVITY,
                    ];
                    send_joystick_sensor(timestamp, joystick, SensorType::Accel, timestamp, &data);
                }
            }
        }

        // (the reading is released here)
        drop(reading);

        // FIXME: We can poll this at a much lower rate
        // (GAMEINPUT_UpdatePowerInfo() is compiled out upstream: GameInput
        // v1 and later have no battery state)
    }

    /// Translation of `GAMEINPUT_JoystickClose()`.
    fn close(&self, joystick: &mut JoystickData) {
        let hwdata = with_state(|s| {
            let i = s
                .open
                .iter()
                .position(|h| h.instance_id == joystick.instance_id)?;
            Some(s.open.remove(i))
        });
        let Some(hwdata) = hwdata else {
            return;
        };

        if hwdata.system_button_callback_token != 0 {
            if let Some(game_input) = game_input() {
                // (with the joystick lock released: the callback takes it,
                // and UnregisterCallback() waits for a running callback)
                with_joysticks_unlocked(|| {
                    game_input.unregister_callback(hwdata.system_button_callback_token)
                });
            }
        }
    }

    /// Translation of `GAMEINPUT_JoystickQuit()`.
    fn quit(&self) {
        let Some(game_input) = game_input() else {
            return;
        };

        // free the callback
        let token = with_state(|s| std::mem::take(&mut s.callback_token));
        if token != 0 {
            // (with the joystick lock released, as in close())
            with_joysticks_unlocked(|| game_input.unregister_callback(token));
        }

        // free the list (the devices' references go with it), and our
        // reference to GameInput (SDL_QuitGameInput())
        let state = with_state(std::mem::take);
        drop(state);
    }

    /// Translation of `GAMEINPUT_JoystickGetGamepadMapping()`.
    fn gamepad_mapping(&self, device_index: usize) -> Option<GamepadMapping> {
        with_state(|s| {
            let elem = s.devices.get(device_index)?;
            let info = elem.device.info();
            gamepad_mapping_for(
                is_gamepad(info),
                elem.raw_type,
                info.supported_system_buttons,
                elem.vendor,
                elem.product,
            )
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn info(vendor_id: u16, product_id: u16, supported_input: u32) -> DeviceInfo {
        let mut info = DeviceInfo::default();
        info.vendor_id = vendor_id;
        info.product_id = product_id;
        info.supported_input = supported_input;
        info
    }

    #[test]
    fn raw_types_and_subtypes() {
        let raw = kind::RAW_DEVICE_REPORT;
        let guitar = info(
            USB_VENDOR_MADCATZ,
            USB_PRODUCT_MADCATZ_XB1_STRATOCASTER_GUITAR,
            raw,
        );
        assert_eq!(device_raw_type(&guitar), RawType::RockBandGuitar);
        assert_eq!(device_subtype(&guitar), JoystickType::Guitar);
        let drums = info(USB_VENDOR_PDP, USB_PRODUCT_PDP_XB1_DRUM_KIT, raw);
        assert_eq!(device_raw_type(&drums), RawType::RockBandDrumKit);
        assert_eq!(device_subtype(&drums), JoystickType::DrumKit);
        let ghl = info(
            USB_VENDOR_RED_OCTANE,
            USB_PRODUCT_RED_OCTANE_XB1_GUITAR_HERO_LIVE_GUITAR,
            raw,
        );
        assert_eq!(device_raw_type(&ghl), RawType::GuitarHeroLiveGuitar);
        assert_eq!(device_subtype(&ghl), JoystickType::Guitar);
        let adapter = info(
            USB_VENDOR_MADCATZ,
            USB_PRODUCT_MADCATZ_XB1_LEGACY_ADAPTER,
            raw,
        );
        assert_eq!(device_raw_type(&adapter), RawType::LegacyAdapter);
        assert_eq!(device_subtype(&adapter), JoystickType::Unknown);
        let stage = info(
            USB_VENDOR_CRKD,
            USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_GUITAR,
            raw,
        );
        assert_eq!(device_raw_type(&stage), RawType::RockBandGuitar);
        let stage_drums = info(
            USB_VENDOR_RED_OCTANE_GAMES,
            USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_DRUMS,
            raw,
        );
        assert_eq!(device_raw_type(&stage_drums), RawType::RockBandDrumKit);
        // Raw types need raw reports
        let no_raw = info(
            USB_VENDOR_MADCATZ,
            USB_PRODUCT_MADCATZ_XB1_DRUM_KIT,
            kind::CONTROLLER,
        );
        assert_eq!(device_raw_type(&no_raw), RawType::None);
        assert_eq!(device_subtype(&no_raw), JoystickType::Gamepad);

        // The subtype order: wheel, arcade stick, flight stick, gamepad
        let all = kind::RACING_WHEEL | kind::ARCADE_STICK | kind::FLIGHT_STICK | kind::GAMEPAD;
        assert_eq!(device_subtype(&info(0, 0, all)), JoystickType::Wheel);
        assert_eq!(
            device_subtype(&info(0, 0, all & !kind::RACING_WHEEL)),
            JoystickType::ArcadeStick
        );
        assert_eq!(
            device_subtype(&info(0, 0, kind::FLIGHT_STICK | kind::GAMEPAD)),
            JoystickType::FlightStick
        );
        assert_eq!(
            device_subtype(&info(0, 0, kind::GAMEPAD)),
            JoystickType::Gamepad
        );
        assert_eq!(
            device_subtype(&info(0, 0, kind::KEYBOARD)),
            JoystickType::Unknown
        );
        assert!(is_gamepad(&info(0, 0, kind::GAMEPAD | kind::CONTROLLER)));
        assert!(!is_gamepad(&info(0, 0, kind::CONTROLLER)));
    }

    #[test]
    fn device_paths_slots_and_adapters() {
        let mut id = [0u8; 32];
        id[0] = 0xAB;
        id[31] = 0x01;
        let path = device_path(&id);
        assert_eq!(path.len(), 64);
        assert!(path.starts_with("AB00"));
        assert!(path.ends_with("0001"));

        assert_eq!(
            steam_virtual_gamepad_slot(
                "\\\\.\\pipe\\HID#VID_045E&PID_028E&IG_00#28DE&11FF&3#2#4321"
            ),
            2
        );
        assert_eq!(
            steam_virtual_gamepad_slot("\\\\?\\HID#VID_045E&PID_028E&IG_00#28DE&11FF&3#2#4321"),
            -1
        );

        assert!(is_xbox360_wireless_adapter(USB_VENDOR_MICROSOFT, 0x0719));
        assert!(is_xbox360_wireless_adapter(USB_VENDOR_MICROSOFT, 0x02a9));
        assert!(is_xbox360_wireless_adapter(USB_VENDOR_MICROSOFT, 0x0291));
        assert!(!is_xbox360_wireless_adapter(USB_VENDOR_MICROSOFT, 0x02ff));
        assert!(!is_xbox360_wireless_adapter(USB_VENDOR_PDP, 0x0719));
    }

    #[test]
    fn gamepad_states_become_xinput_style_events() {
        let state = GamepadState {
            buttons: gamepad_buttons::A
                | gamepad_buttons::VIEW
                | gamepad_buttons::RIGHT_SHOULDER
                | gamepad_buttons::DPAD_UP
                | gamepad_buttons::DPAD_LEFT,
            left_trigger: 0.0,
            right_trigger: 1.0,
            left_thumbstick_x: -1.0,
            left_thumbstick_y: 1.0,
            right_thumbstick_x: 0.5,
            right_thumbstick_y: -0.5,
        };
        let inputs = gamepad_inputs(&state);
        use Input::*;
        assert_eq!(
            inputs,
            [
                Button(0, true),  // A: south
                Button(1, false), // east
                Button(2, false), // west
                Button(3, false), // north
                Button(4, true),  // view: back
                Button(6, false), // start (no guide)
                Button(7, false), // left stick
                Button(8, false), // right stick
                Button(9, false), // left shoulder
                Button(10, true), // right shoulder
                Hat(0, HAT_UP | HAT_LEFT),
                Axis(0, -32768),
                Axis(1, -32768), // Y is flipped
                Axis(2, 16383),
                Axis(3, 16383),
                Axis(4, -32768),
                Axis(5, 32767),
            ]
        );
        assert_eq!(convert_stick(1.0), 32767);
        assert_eq!(convert_stick(-0.5), -16384);
        assert_eq!(convert_trigger(0.5), 0); // (-0.5, truncated)
    }

    #[test]
    fn controller_readings_and_switches() {
        let inputs = controller_inputs(
            &[true, false],
            &[0.0, 1.0],
            &[switch_position::DOWN_RIGHT, switch_position::CENTER, 99],
        );
        use Input::*;
        assert_eq!(
            inputs,
            [
                Button(0, true),
                Button(1, false),
                Axis(0, -32768),
                Axis(1, 32767),
                Hat(0, HAT_DOWN | HAT_RIGHT),
                Hat(1, HAT_CENTERED),
                Hat(2, HAT_CENTERED),
            ]
        );
        let hats: Vec<u8> = (0..=8).map(switch_hat).collect();
        assert_eq!(
            hats,
            [
                HAT_CENTERED,
                HAT_UP,
                HAT_UP | HAT_RIGHT,
                HAT_RIGHT,
                HAT_DOWN | HAT_RIGHT,
                HAT_DOWN,
                HAT_DOWN | HAT_LEFT,
                HAT_LEFT,
                HAT_UP | HAT_LEFT,
            ]
        );
    }

    #[test]
    fn guitar_reports() {
        let mut raw = [0u8; 40];
        // green (south) + start + strum up, whammy at the top, tilted,
        // solo, pickup position 2
        raw[0] = 0x10 | 0x04;
        raw[1] = 0x01;
        raw[2] = 0xD0;
        raw[3] = 0xFF;
        raw[4] = 0x20;
        raw[6] = 1;
        use Input::*;
        assert!(guitar_inputs(&raw, 9).is_empty());
        assert_eq!(
            guitar_inputs(&raw, 10),
            [
                Button(0, true),
                Button(1, false),
                Button(2, false),
                Button(3, false),
                Button(4, false),
                Button(6, true),
                Button(8, false),
                Button(9, false),
                Hat(0, HAT_UP),
                Axis(GamepadAxis::RightX as u8, 32767),
                Button(GamepadButton::RightShoulder as u8, true),
                Axis(GamepadAxis::LeftTrigger as u8, 32767),
                Axis(GamepadAxis::RightY as u8, -1792),
            ]
        );
        // A pickup position past the table sends no pickup axis
        raw[4] = 0x70;
        let inputs = guitar_inputs(&raw, 10);
        assert_eq!(inputs.len(), 12);
        assert_eq!(inputs[11], Axis(GamepadAxis::LeftTrigger as u8, 32767));
    }

    #[test]
    fn drum_reports() {
        let mut raw = [0u8; 40];
        // red pad (east, rawData[2] high nibble), yellow cymbal (rawData[4]
        // high nibble: up and north), back
        raw[0] = 0x08;
        raw[2] = 0x30;
        raw[4] = 0x40;
        use Input::*;
        assert!(drum_inputs(&raw, 5).is_empty());
        assert_eq!(
            drum_inputs(&raw, 6),
            [
                Hat(0, HAT_UP),
                Button(GamepadButton::Back as u8, true),
                Button(GamepadButton::Start as u8, false),
                Button(GamepadButton::LeftShoulder as u8, false),
                Button(GamepadButton::RightShoulder as u8, false),
                Button(GamepadButton::South as u8, false),
                Button(GamepadButton::East as u8, true),
                Button(GamepadButton::West as u8, false),
                Button(GamepadButton::North as u8, true),
                Button(GamepadButton::LeftStick as u8, true),
                Button(GamepadButton::RightStick as u8, true),
            ]
        );
    }

    #[test]
    fn system_buttons_map_to_guide_and_share() {
        assert_eq!(
            system_button_inputs(system_buttons::GUIDE, system_buttons::GUIDE),
            [(GamepadButton::Guide as u8, true)]
        );
        assert_eq!(
            system_button_inputs(
                system_buttons::GUIDE | system_buttons::SHARE,
                system_buttons::SHARE
            ),
            [(GamepadButton::Guide as u8, false), (11, true)]
        );
        assert!(system_button_inputs(0, system_buttons::GUIDE).is_empty());
    }

    #[test]
    fn gamepad_mappings() {
        assert!(gamepad_mapping_for(false, RawType::None, 0, 0, 0).is_none());
        let m = gamepad_mapping_for(true, RawType::None, 0, 0, 0).unwrap();
        assert_eq!(m.a.kind, MappingKind::Button);
        assert_eq!(m.a.target, GamepadButton::South as u8);
        assert_eq!(m.guide.kind, MappingKind::None);
        assert_eq!(m.misc1.kind, MappingKind::None);
        assert_eq!(m.dpleft.kind, MappingKind::Hat);
        assert_eq!(m.dpleft.target, HAT_LEFT);
        assert_eq!(m.righttrigger.kind, MappingKind::Axis);
        assert_eq!(m.righttrigger.target, GamepadAxis::RightTrigger as u8);

        // An Xbox Series X controller with guide and share buttons
        let m = gamepad_mapping_for(
            false,
            RawType::RockBandGuitar,
            system_buttons::GUIDE | system_buttons::SHARE,
            USB_VENDOR_MICROSOFT,
            0x0b12,
        )
        .unwrap();
        assert_eq!(m.guide.target, GamepadButton::Guide as u8);
        assert_eq!(m.misc1.kind, MappingKind::Button);
        assert_eq!(m.misc1.target, 11);
    }

    #[test]
    fn timestamps() {
        let offset = timestamp_offset(5_000_000, 1_000);
        assert_eq!(offset, 4_000);
        assert_eq!(sdl_timestamp(1_500, offset), 5_500_000);
        // (GameInput's clock may be ahead of SDL's)
        let offset = timestamp_offset(1_000, 10);
        assert_eq!(sdl_timestamp(10, offset), 1_000);
    }

    #[test]
    fn init_falls_back_without_game_input() {
        let _l = crate::test_support::test_lock();
        let _lock = lock_joysticks();
        // Without the DLL (Wine, the CI runners) init fails and the driver
        // has no devices nor claims any; the other drivers take over.
        match GAMEINPUT_JOYSTICK_DRIVER.init() {
            Err(e) => {
                crate::test_support::skip("gameinput", format_args!("no GameInput here ({e})"));
                assert_eq!(GAMEINPUT_JOYSTICK_DRIVER.count(), 0);
                assert!(!GAMEINPUT_JOYSTICK_DRIVER.is_device_present(
                    USB_VENDOR_MICROSOFT,
                    USB_PRODUCT_XBOX_ONE_XBOXGIP_CONTROLLER,
                    0,
                    None
                ));
                assert!(
                    !crate::core::windows::gameinput::using_game_input_for_xinput_controllers()
                );
            }
            Ok(()) => println!("note: GameInput is available here"),
        }
        GAMEINPUT_JOYSTICK_DRIVER.quit();
        assert!(game_input().is_none());
    }
}
