// Rust translation of the hint name constants in include/SDL3/SDL_hints.h
// from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

//! Every `SDL_HINT_*` name from the public header, in header order, without
//! the `SDL_HINT_` prefix: `hints::VIDEO_DRIVER` is `SDL_HINT_VIDEO_DRIVER`.
//! Generated mechanically from `SDL_hints.h`; see the upstream header for the
//! documentation of each hint's meaning and accepted values.

/// Translation of `SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED`.
pub const ALLOW_ALT_TAB_WHILE_GRABBED: &str = "SDL_ALLOW_ALT_TAB_WHILE_GRABBED";
/// Translation of `SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY`.
pub const ANDROID_ALLOW_RECREATE_ACTIVITY: &str = "SDL_ANDROID_ALLOW_RECREATE_ACTIVITY";
/// Translation of `SDL_HINT_ANDROID_BLOCK_ON_PAUSE`.
pub const ANDROID_BLOCK_ON_PAUSE: &str = "SDL_ANDROID_BLOCK_ON_PAUSE";
/// Translation of `SDL_HINT_ANDROID_LOW_LATENCY_AUDIO`.
pub const ANDROID_LOW_LATENCY_AUDIO: &str = "SDL_ANDROID_LOW_LATENCY_AUDIO";
/// Translation of `SDL_HINT_ANDROID_AAUDIO_INPUT_PRESET`.
pub const ANDROID_AAUDIO_INPUT_PRESET: &str = "SDL_ANDROID_AAUDIO_INPUT_PRESET";
/// Translation of `SDL_HINT_ANDROID_TRAP_BACK_BUTTON`.
pub const ANDROID_TRAP_BACK_BUTTON: &str = "SDL_ANDROID_TRAP_BACK_BUTTON";
/// Translation of `SDL_HINT_ANDROID_ALLOW_PERSISTENT_FOLDER_ACCESS`.
pub const ANDROID_ALLOW_PERSISTENT_FOLDER_ACCESS: &str =
    "SDL_ANDROID_ALLOW_PERSISTENT_FOLDER_ACCESS";
/// Translation of `SDL_HINT_APP_ID`.
pub const APP_ID: &str = "SDL_APP_ID";
/// Translation of `SDL_HINT_APP_NAME`.
pub const APP_NAME: &str = "SDL_APP_NAME";
/// Translation of `SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS`.
pub const APPLE_TV_CONTROLLER_UI_EVENTS: &str = "SDL_APPLE_TV_CONTROLLER_UI_EVENTS";
/// Translation of `SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION`.
pub const APPLE_TV_REMOTE_ALLOW_ROTATION: &str = "SDL_APPLE_TV_REMOTE_ALLOW_ROTATION";
/// Translation of `SDL_HINT_AUDIO_ALSA_DEFAULT_DEVICE`.
pub const AUDIO_ALSA_DEFAULT_DEVICE: &str = "SDL_AUDIO_ALSA_DEFAULT_DEVICE";
/// Translation of `SDL_HINT_AUDIO_ALSA_DEFAULT_PLAYBACK_DEVICE`.
pub const AUDIO_ALSA_DEFAULT_PLAYBACK_DEVICE: &str = "SDL_AUDIO_ALSA_DEFAULT_PLAYBACK_DEVICE";
/// Translation of `SDL_HINT_AUDIO_ALSA_DEFAULT_RECORDING_DEVICE`.
pub const AUDIO_ALSA_DEFAULT_RECORDING_DEVICE: &str = "SDL_AUDIO_ALSA_DEFAULT_RECORDING_DEVICE";
/// Translation of `SDL_HINT_AUDIO_CATEGORY`.
pub const AUDIO_CATEGORY: &str = "SDL_AUDIO_CATEGORY";
/// Translation of `SDL_HINT_AUDIO_CHANNELS`.
pub const AUDIO_CHANNELS: &str = "SDL_AUDIO_CHANNELS";
/// Translation of `SDL_HINT_AUDIO_DEVICE_APP_ICON_NAME`.
pub const AUDIO_DEVICE_APP_ICON_NAME: &str = "SDL_AUDIO_DEVICE_APP_ICON_NAME";
/// Translation of `SDL_HINT_AUDIO_DEVICE_SAMPLE_FRAMES`.
pub const AUDIO_DEVICE_SAMPLE_FRAMES: &str = "SDL_AUDIO_DEVICE_SAMPLE_FRAMES";
/// Translation of `SDL_HINT_AUDIO_DEVICE_STREAM_NAME`.
pub const AUDIO_DEVICE_STREAM_NAME: &str = "SDL_AUDIO_DEVICE_STREAM_NAME";
/// Translation of `SDL_HINT_AUDIO_DEVICE_STREAM_ROLE`.
pub const AUDIO_DEVICE_STREAM_ROLE: &str = "SDL_AUDIO_DEVICE_STREAM_ROLE";
/// Translation of `SDL_HINT_AUDIO_DEVICE_RAW_STREAM`.
pub const AUDIO_DEVICE_RAW_STREAM: &str = "SDL_AUDIO_DEVICE_RAW_STREAM";
/// Translation of `SDL_HINT_AUDIO_DISK_INPUT_FILE`.
pub const AUDIO_DISK_INPUT_FILE: &str = "SDL_AUDIO_DISK_INPUT_FILE";
/// Translation of `SDL_HINT_AUDIO_DISK_OUTPUT_FILE`.
pub const AUDIO_DISK_OUTPUT_FILE: &str = "SDL_AUDIO_DISK_OUTPUT_FILE";
/// Translation of `SDL_HINT_AUDIO_DISK_TIMESCALE`.
pub const AUDIO_DISK_TIMESCALE: &str = "SDL_AUDIO_DISK_TIMESCALE";
/// Translation of `SDL_HINT_AUDIO_DRIVER`.
pub const AUDIO_DRIVER: &str = "SDL_AUDIO_DRIVER";
/// Translation of `SDL_HINT_AUDIO_DUCK_OTHERS`.
pub const AUDIO_DUCK_OTHERS: &str = "SDL_AUDIO_DUCK_OTHERS";
/// Translation of `SDL_HINT_AUDIO_DUMMY_TIMESCALE`.
pub const AUDIO_DUMMY_TIMESCALE: &str = "SDL_AUDIO_DUMMY_TIMESCALE";
/// Translation of `SDL_HINT_AUDIO_FORMAT`.
pub const AUDIO_FORMAT: &str = "SDL_AUDIO_FORMAT";
/// Translation of `SDL_HINT_AUDIO_FREQUENCY`.
pub const AUDIO_FREQUENCY: &str = "SDL_AUDIO_FREQUENCY";
/// Translation of `SDL_HINT_AUDIO_INCLUDE_MONITORS`.
pub const AUDIO_INCLUDE_MONITORS: &str = "SDL_AUDIO_INCLUDE_MONITORS";
/// Translation of `SDL_HINT_AUTO_UPDATE_JOYSTICKS`.
pub const AUTO_UPDATE_JOYSTICKS: &str = "SDL_AUTO_UPDATE_JOYSTICKS";
/// Translation of `SDL_HINT_AUTO_UPDATE_SENSORS`.
pub const AUTO_UPDATE_SENSORS: &str = "SDL_AUTO_UPDATE_SENSORS";
/// Translation of `SDL_HINT_BMP_SAVE_LEGACY_FORMAT`.
pub const BMP_SAVE_LEGACY_FORMAT: &str = "SDL_BMP_SAVE_LEGACY_FORMAT";
/// Translation of `SDL_HINT_CAMERA_DRIVER`.
pub const CAMERA_DRIVER: &str = "SDL_CAMERA_DRIVER";
/// Translation of `SDL_HINT_CPU_FEATURE_MASK`.
pub const CPU_FEATURE_MASK: &str = "SDL_CPU_FEATURE_MASK";
/// Translation of `SDL_HINT_JOYSTICK_DIRECTINPUT`.
pub const JOYSTICK_DIRECTINPUT: &str = "SDL_JOYSTICK_DIRECTINPUT";
/// Translation of `SDL_HINT_FILE_DIALOG_DRIVER`.
pub const FILE_DIALOG_DRIVER: &str = "SDL_FILE_DIALOG_DRIVER";
/// Translation of `SDL_HINT_DISPLAY_USABLE_BOUNDS`.
pub const DISPLAY_USABLE_BOUNDS: &str = "SDL_DISPLAY_USABLE_BOUNDS";
/// Translation of `SDL_HINT_DOS_ALLOW_DIRECT_FRAMEBUFFER`.
pub const DOS_ALLOW_DIRECT_FRAMEBUFFER: &str = "SDL_DOS_ALLOW_DIRECT_FRAMEBUFFER";
/// Translation of `SDL_HINT_INVALID_PARAM_CHECKS`.
pub const INVALID_PARAM_CHECKS: &str = "SDL_INVALID_PARAM_CHECKS";
/// Translation of `SDL_HINT_EMSCRIPTEN_ASYNCIFY`.
pub const EMSCRIPTEN_ASYNCIFY: &str = "SDL_EMSCRIPTEN_ASYNCIFY";
/// Translation of `SDL_HINT_EMSCRIPTEN_CANVAS_SELECTOR`.
pub const EMSCRIPTEN_CANVAS_SELECTOR: &str = "SDL_EMSCRIPTEN_CANVAS_SELECTOR";
/// Translation of `SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT`.
pub const EMSCRIPTEN_KEYBOARD_ELEMENT: &str = "SDL_EMSCRIPTEN_KEYBOARD_ELEMENT";
/// Translation of `SDL_HINT_ENABLE_SCREEN_KEYBOARD`.
pub const ENABLE_SCREEN_KEYBOARD: &str = "SDL_ENABLE_SCREEN_KEYBOARD";
/// Translation of `SDL_HINT_ENABLE_STEAM_SCREEN_KEYBOARD`.
pub const ENABLE_STEAM_SCREEN_KEYBOARD: &str = "SDL_ENABLE_STEAM_SCREEN_KEYBOARD";
/// Translation of `SDL_HINT_EVDEV_DEVICES`.
pub const EVDEV_DEVICES: &str = "SDL_EVDEV_DEVICES";
/// Translation of `SDL_HINT_EVENT_LOGGING`.
pub const EVENT_LOGGING: &str = "SDL_EVENT_LOGGING";
/// Translation of `SDL_HINT_FORCE_RAISEWINDOW`.
pub const FORCE_RAISEWINDOW: &str = "SDL_FORCE_RAISEWINDOW";
/// Translation of `SDL_HINT_FRAMEBUFFER_ACCELERATION`.
pub const FRAMEBUFFER_ACCELERATION: &str = "SDL_FRAMEBUFFER_ACCELERATION";
/// Translation of `SDL_HINT_GAMECONTROLLERCONFIG`.
pub const GAMECONTROLLERCONFIG: &str = "SDL_GAMECONTROLLERCONFIG";
/// Translation of `SDL_HINT_GAMECONTROLLERCONFIG_FILE`.
pub const GAMECONTROLLERCONFIG_FILE: &str = "SDL_GAMECONTROLLERCONFIG_FILE";
/// Translation of `SDL_HINT_GAMECONTROLLERTYPE`.
pub const GAMECONTROLLERTYPE: &str = "SDL_GAMECONTROLLERTYPE";
/// Translation of `SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES`.
pub const GAMECONTROLLER_IGNORE_DEVICES: &str = "SDL_GAMECONTROLLER_IGNORE_DEVICES";
/// Translation of `SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT`.
pub const GAMECONTROLLER_IGNORE_DEVICES_EXCEPT: &str = "SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT";
/// Translation of `SDL_HINT_GAMECONTROLLER_SENSOR_FUSION`.
pub const GAMECONTROLLER_SENSOR_FUSION: &str = "SDL_GAMECONTROLLER_SENSOR_FUSION";
/// Translation of `SDL_HINT_GDK_TEXTINPUT_DEFAULT_TEXT`.
pub const GDK_TEXTINPUT_DEFAULT_TEXT: &str = "SDL_GDK_TEXTINPUT_DEFAULT_TEXT";
/// Translation of `SDL_HINT_GDK_TEXTINPUT_DESCRIPTION`.
pub const GDK_TEXTINPUT_DESCRIPTION: &str = "SDL_GDK_TEXTINPUT_DESCRIPTION";
/// Translation of `SDL_HINT_GDK_TEXTINPUT_MAX_LENGTH`.
pub const GDK_TEXTINPUT_MAX_LENGTH: &str = "SDL_GDK_TEXTINPUT_MAX_LENGTH";
/// Translation of `SDL_HINT_GDK_TEXTINPUT_SCOPE`.
pub const GDK_TEXTINPUT_SCOPE: &str = "SDL_GDK_TEXTINPUT_SCOPE";
/// Translation of `SDL_HINT_GDK_TEXTINPUT_TITLE`.
pub const GDK_TEXTINPUT_TITLE: &str = "SDL_GDK_TEXTINPUT_TITLE";
/// Translation of `SDL_HINT_HIDAPI_LIBUSB`.
pub const HIDAPI_LIBUSB: &str = "SDL_HIDAPI_LIBUSB";
/// Translation of `SDL_HINT_HIDAPI_LIBUSB_GAMECUBE`.
pub const HIDAPI_LIBUSB_GAMECUBE: &str = "SDL_HIDAPI_LIBUSB_GAMECUBE";
/// Translation of `SDL_HINT_HIDAPI_LIBUSB_WHITELIST`.
pub const HIDAPI_LIBUSB_WHITELIST: &str = "SDL_HIDAPI_LIBUSB_WHITELIST";
/// Translation of `SDL_HINT_HIDAPI_UDEV`.
pub const HIDAPI_UDEV: &str = "SDL_HIDAPI_UDEV";
/// Translation of `SDL_HINT_GPU_DRIVER`.
pub const GPU_DRIVER: &str = "SDL_GPU_DRIVER";
/// Translation of `SDL_HINT_OPENXR_LIBRARY`.
pub const OPENXR_LIBRARY: &str = "SDL_OPENXR_LIBRARY";
/// Translation of `SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS`.
pub const HIDAPI_ENUMERATE_ONLY_CONTROLLERS: &str = "SDL_HIDAPI_ENUMERATE_ONLY_CONTROLLERS";
/// Translation of `SDL_HINT_HIDAPI_IGNORE_DEVICES`.
pub const HIDAPI_IGNORE_DEVICES: &str = "SDL_HIDAPI_IGNORE_DEVICES";
/// Translation of `SDL_HINT_IME_IMPLEMENTED_UI`.
pub const IME_IMPLEMENTED_UI: &str = "SDL_IME_IMPLEMENTED_UI";
/// Translation of `SDL_HINT_IOS_HIDE_HOME_INDICATOR`.
pub const IOS_HIDE_HOME_INDICATOR: &str = "SDL_IOS_HIDE_HOME_INDICATOR";
/// Translation of `SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS`.
pub const JOYSTICK_ALLOW_BACKGROUND_EVENTS: &str = "SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS";
/// Translation of `SDL_HINT_JOYSTICK_ARCADESTICK_DEVICES`.
pub const JOYSTICK_ARCADESTICK_DEVICES: &str = "SDL_JOYSTICK_ARCADESTICK_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_ARCADESTICK_DEVICES_EXCLUDED`.
pub const JOYSTICK_ARCADESTICK_DEVICES_EXCLUDED: &str = "SDL_JOYSTICK_ARCADESTICK_DEVICES_EXCLUDED";
/// Translation of `SDL_HINT_JOYSTICK_BLACKLIST_DEVICES`.
pub const JOYSTICK_BLACKLIST_DEVICES: &str = "SDL_JOYSTICK_BLACKLIST_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_BLACKLIST_DEVICES_EXCLUDED`.
pub const JOYSTICK_BLACKLIST_DEVICES_EXCLUDED: &str = "SDL_JOYSTICK_BLACKLIST_DEVICES_EXCLUDED";
/// Translation of `SDL_HINT_JOYSTICK_DEVICE`.
pub const JOYSTICK_DEVICE: &str = "SDL_JOYSTICK_DEVICE";
/// Translation of `SDL_HINT_JOYSTICK_DRUM_DEVICES`.
pub const JOYSTICK_DRUM_DEVICES: &str = "SDL_JOYSTICK_DRUM_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_ENHANCED_REPORTS`.
pub const JOYSTICK_ENHANCED_REPORTS: &str = "SDL_JOYSTICK_ENHANCED_REPORTS";
/// Translation of `SDL_HINT_JOYSTICK_FLIGHTSTICK_DEVICES`.
pub const JOYSTICK_FLIGHTSTICK_DEVICES: &str = "SDL_JOYSTICK_FLIGHTSTICK_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_FLIGHTSTICK_DEVICES_EXCLUDED`.
pub const JOYSTICK_FLIGHTSTICK_DEVICES_EXCLUDED: &str = "SDL_JOYSTICK_FLIGHTSTICK_DEVICES_EXCLUDED";
/// Translation of `SDL_HINT_JOYSTICK_GAMEINPUT`.
pub const JOYSTICK_GAMEINPUT: &str = "SDL_JOYSTICK_GAMEINPUT";
/// Translation of `SDL_HINT_JOYSTICK_GAMEINPUT_RAW`.
pub const JOYSTICK_GAMEINPUT_RAW: &str = "SDL_JOYSTICK_GAMEINPUT_RAW";
/// Translation of `SDL_HINT_JOYSTICK_GAMECUBE_DEVICES`.
pub const JOYSTICK_GAMECUBE_DEVICES: &str = "SDL_JOYSTICK_GAMECUBE_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_GAMECUBE_DEVICES_EXCLUDED`.
pub const JOYSTICK_GAMECUBE_DEVICES_EXCLUDED: &str = "SDL_JOYSTICK_GAMECUBE_DEVICES_EXCLUDED";
/// Translation of `SDL_HINT_JOYSTICK_GUITAR_DEVICES`.
pub const JOYSTICK_GUITAR_DEVICES: &str = "SDL_JOYSTICK_GUITAR_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI`.
pub const JOYSTICK_HIDAPI: &str = "SDL_JOYSTICK_HIDAPI";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_COMBINE_JOY_CONS`.
pub const JOYSTICK_HIDAPI_COMBINE_JOY_CONS: &str = "SDL_JOYSTICK_HIDAPI_COMBINE_JOY_CONS";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE`.
pub const JOYSTICK_HIDAPI_GAMECUBE: &str = "SDL_JOYSTICK_HIDAPI_GAMECUBE";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE_RUMBLE_BRAKE`.
pub const JOYSTICK_HIDAPI_GAMECUBE_RUMBLE_BRAKE: &str = "SDL_JOYSTICK_HIDAPI_GAMECUBE_RUMBLE_BRAKE";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_JOY_CONS`.
pub const JOYSTICK_HIDAPI_JOY_CONS: &str = "SDL_JOYSTICK_HIDAPI_JOY_CONS";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_JOYCON_HOME_LED`.
pub const JOYSTICK_HIDAPI_JOYCON_HOME_LED: &str = "SDL_JOYSTICK_HIDAPI_JOYCON_HOME_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_LUNA`.
pub const JOYSTICK_HIDAPI_LUNA: &str = "SDL_JOYSTICK_HIDAPI_LUNA";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_NINTENDO_CLASSIC`.
pub const JOYSTICK_HIDAPI_NINTENDO_CLASSIC: &str = "SDL_JOYSTICK_HIDAPI_NINTENDO_CLASSIC";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_PS3`.
pub const JOYSTICK_HIDAPI_PS3: &str = "SDL_JOYSTICK_HIDAPI_PS3";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_PS3_SIXAXIS_DRIVER`.
pub const JOYSTICK_HIDAPI_PS3_SIXAXIS_DRIVER: &str = "SDL_JOYSTICK_HIDAPI_PS3_SIXAXIS_DRIVER";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_PS4`.
pub const JOYSTICK_HIDAPI_PS4: &str = "SDL_JOYSTICK_HIDAPI_PS4";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_PS4_REPORT_INTERVAL`.
pub const JOYSTICK_HIDAPI_PS4_REPORT_INTERVAL: &str = "SDL_JOYSTICK_HIDAPI_PS4_REPORT_INTERVAL";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_PS5`.
pub const JOYSTICK_HIDAPI_PS5: &str = "SDL_JOYSTICK_HIDAPI_PS5";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED`.
pub const JOYSTICK_HIDAPI_PS5_PLAYER_LED: &str = "SDL_JOYSTICK_HIDAPI_PS5_PLAYER_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_SHIELD`.
pub const JOYSTICK_HIDAPI_SHIELD: &str = "SDL_JOYSTICK_HIDAPI_SHIELD";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_STADIA`.
pub const JOYSTICK_HIDAPI_STADIA: &str = "SDL_JOYSTICK_HIDAPI_STADIA";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_STEAM`.
pub const JOYSTICK_HIDAPI_STEAM: &str = "SDL_JOYSTICK_HIDAPI_STEAM";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_STEAM_HOME_LED`.
pub const JOYSTICK_HIDAPI_STEAM_HOME_LED: &str = "SDL_JOYSTICK_HIDAPI_STEAM_HOME_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_STEAMDECK`.
pub const JOYSTICK_HIDAPI_STEAMDECK: &str = "SDL_JOYSTICK_HIDAPI_STEAMDECK";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_STEAM_HORI`.
pub const JOYSTICK_HIDAPI_STEAM_HORI: &str = "SDL_JOYSTICK_HIDAPI_STEAM_HORI";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_LG4FF`.
pub const JOYSTICK_HIDAPI_LG4FF: &str = "SDL_JOYSTICK_HIDAPI_LG4FF";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_8BITDO`.
pub const JOYSTICK_HIDAPI_8BITDO: &str = "SDL_JOYSTICK_HIDAPI_8BITDO";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_SINPUT`.
pub const JOYSTICK_HIDAPI_SINPUT: &str = "SDL_JOYSTICK_HIDAPI_SINPUT";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_ZUIKI`.
pub const JOYSTICK_HIDAPI_ZUIKI: &str = "SDL_JOYSTICK_HIDAPI_ZUIKI";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_FLYDIGI`.
pub const JOYSTICK_HIDAPI_FLYDIGI: &str = "SDL_JOYSTICK_HIDAPI_FLYDIGI";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_GAMESIR`.
pub const JOYSTICK_HIDAPI_GAMESIR: &str = "SDL_JOYSTICK_HIDAPI_GAMESIR";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_SWITCH`.
pub const JOYSTICK_HIDAPI_SWITCH: &str = "SDL_JOYSTICK_HIDAPI_SWITCH";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED`.
pub const JOYSTICK_HIDAPI_SWITCH_HOME_LED: &str = "SDL_JOYSTICK_HIDAPI_SWITCH_HOME_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED`.
pub const JOYSTICK_HIDAPI_SWITCH_PLAYER_LED: &str = "SDL_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_SWITCH2`.
pub const JOYSTICK_HIDAPI_SWITCH2: &str = "SDL_JOYSTICK_HIDAPI_SWITCH2";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS`.
pub const JOYSTICK_HIDAPI_VERTICAL_JOY_CONS: &str = "SDL_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_WII`.
pub const JOYSTICK_HIDAPI_WII: &str = "SDL_JOYSTICK_HIDAPI_WII";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_WII_PLAYER_LED`.
pub const JOYSTICK_HIDAPI_WII_PLAYER_LED: &str = "SDL_JOYSTICK_HIDAPI_WII_PLAYER_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_XBOX`.
pub const JOYSTICK_HIDAPI_XBOX: &str = "SDL_JOYSTICK_HIDAPI_XBOX";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_XBOX_360`.
pub const JOYSTICK_HIDAPI_XBOX_360: &str = "SDL_JOYSTICK_HIDAPI_XBOX_360";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED`.
pub const JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED: &str = "SDL_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_WIRELESS`.
pub const JOYSTICK_HIDAPI_XBOX_360_WIRELESS: &str = "SDL_JOYSTICK_HIDAPI_XBOX_360_WIRELESS";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE`.
pub const JOYSTICK_HIDAPI_XBOX_ONE: &str = "SDL_JOYSTICK_HIDAPI_XBOX_ONE";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED`.
pub const JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED: &str = "SDL_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_GIP`.
pub const JOYSTICK_HIDAPI_GIP: &str = "SDL_JOYSTICK_HIDAPI_GIP";
/// Translation of `SDL_HINT_JOYSTICK_HIDAPI_GIP_RESET_FOR_METADATA`.
pub const JOYSTICK_HIDAPI_GIP_RESET_FOR_METADATA: &str =
    "SDL_JOYSTICK_HIDAPI_GIP_RESET_FOR_METADATA";
/// Translation of `SDL_HINT_JOYSTICK_IOKIT`.
pub const JOYSTICK_IOKIT: &str = "SDL_JOYSTICK_IOKIT";
/// Translation of `SDL_HINT_JOYSTICK_LINUX_CLASSIC`.
pub const JOYSTICK_LINUX_CLASSIC: &str = "SDL_JOYSTICK_LINUX_CLASSIC";
/// Translation of `SDL_HINT_JOYSTICK_LINUX_DEADZONES`.
pub const JOYSTICK_LINUX_DEADZONES: &str = "SDL_JOYSTICK_LINUX_DEADZONES";
/// Translation of `SDL_HINT_JOYSTICK_LINUX_DIGITAL_HATS`.
pub const JOYSTICK_LINUX_DIGITAL_HATS: &str = "SDL_JOYSTICK_LINUX_DIGITAL_HATS";
/// Translation of `SDL_HINT_JOYSTICK_LINUX_HAT_DEADZONES`.
pub const JOYSTICK_LINUX_HAT_DEADZONES: &str = "SDL_JOYSTICK_LINUX_HAT_DEADZONES";
/// Translation of `SDL_HINT_JOYSTICK_MFI`.
pub const JOYSTICK_MFI: &str = "SDL_JOYSTICK_MFI";
/// Translation of `SDL_HINT_JOYSTICK_RAWINPUT`.
pub const JOYSTICK_RAWINPUT: &str = "SDL_JOYSTICK_RAWINPUT";
/// Translation of `SDL_HINT_JOYSTICK_RAWINPUT_CORRELATE_XINPUT`.
pub const JOYSTICK_RAWINPUT_CORRELATE_XINPUT: &str = "SDL_JOYSTICK_RAWINPUT_CORRELATE_XINPUT";
/// Translation of `SDL_HINT_JOYSTICK_ROG_CHAKRAM`.
pub const JOYSTICK_ROG_CHAKRAM: &str = "SDL_JOYSTICK_ROG_CHAKRAM";
/// Translation of `SDL_HINT_JOYSTICK_THREAD`.
pub const JOYSTICK_THREAD: &str = "SDL_JOYSTICK_THREAD";
/// Translation of `SDL_HINT_JOYSTICK_THROTTLE_DEVICES`.
pub const JOYSTICK_THROTTLE_DEVICES: &str = "SDL_JOYSTICK_THROTTLE_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_THROTTLE_DEVICES_EXCLUDED`.
pub const JOYSTICK_THROTTLE_DEVICES_EXCLUDED: &str = "SDL_JOYSTICK_THROTTLE_DEVICES_EXCLUDED";
/// Translation of `SDL_HINT_JOYSTICK_WGI`.
pub const JOYSTICK_WGI: &str = "SDL_JOYSTICK_WGI";
/// Translation of `SDL_HINT_JOYSTICK_WHEEL_DEVICES`.
pub const JOYSTICK_WHEEL_DEVICES: &str = "SDL_JOYSTICK_WHEEL_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_WHEEL_DEVICES_EXCLUDED`.
pub const JOYSTICK_WHEEL_DEVICES_EXCLUDED: &str = "SDL_JOYSTICK_WHEEL_DEVICES_EXCLUDED";
/// Translation of `SDL_HINT_JOYSTICK_ZERO_CENTERED_DEVICES`.
pub const JOYSTICK_ZERO_CENTERED_DEVICES: &str = "SDL_JOYSTICK_ZERO_CENTERED_DEVICES";
/// Translation of `SDL_HINT_JOYSTICK_HAPTIC_AXES`.
pub const JOYSTICK_HAPTIC_AXES: &str = "SDL_JOYSTICK_HAPTIC_AXES";
/// Translation of `SDL_HINT_KEYCODE_OPTIONS`.
pub const KEYCODE_OPTIONS: &str = "SDL_KEYCODE_OPTIONS";
/// Translation of `SDL_HINT_KMSDRM_DEVICE_INDEX`.
pub const KMSDRM_DEVICE_INDEX: &str = "SDL_KMSDRM_DEVICE_INDEX";
/// Translation of `SDL_HINT_KMSDRM_REQUIRE_DRM_MASTER`.
pub const KMSDRM_REQUIRE_DRM_MASTER: &str = "SDL_KMSDRM_REQUIRE_DRM_MASTER";
/// Translation of `SDL_HINT_KMSDRM_ATOMIC`.
pub const KMSDRM_ATOMIC: &str = "SDL_KMSDRM_ATOMIC";
/// Translation of `SDL_HINT_LOGGING`.
pub const LOGGING: &str = "SDL_LOGGING";
/// Translation of `SDL_HINT_MAC_BACKGROUND_APP`.
pub const MAC_BACKGROUND_APP: &str = "SDL_MAC_BACKGROUND_APP";
/// Translation of `SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK`.
pub const MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK: &str = "SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK";
/// Translation of `SDL_HINT_MAC_OPENGL_ASYNC_DISPATCH`.
pub const MAC_OPENGL_ASYNC_DISPATCH: &str = "SDL_MAC_OPENGL_ASYNC_DISPATCH";
/// Translation of `SDL_HINT_MAC_OPTION_AS_ALT`.
pub const MAC_OPTION_AS_ALT: &str = "SDL_MAC_OPTION_AS_ALT";
/// Translation of `SDL_HINT_MAC_SCROLL_MOMENTUM`.
pub const MAC_SCROLL_MOMENTUM: &str = "SDL_MAC_SCROLL_MOMENTUM";
/// Translation of `SDL_HINT_MAC_USE_GCMOUSE`.
pub const MAC_USE_GCMOUSE: &str = "SDL_MAC_USE_GCMOUSE";
/// Translation of `SDL_HINT_MAC_PRESS_AND_HOLD`.
pub const MAC_PRESS_AND_HOLD: &str = "SDL_MAC_PRESS_AND_HOLD";
/// Translation of `SDL_HINT_MAIN_CALLBACK_RATE`.
pub const MAIN_CALLBACK_RATE: &str = "SDL_MAIN_CALLBACK_RATE";
/// Translation of `SDL_HINT_MOUSE_AUTO_CAPTURE`.
pub const MOUSE_AUTO_CAPTURE: &str = "SDL_MOUSE_AUTO_CAPTURE";
/// Translation of `SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS`.
pub const MOUSE_DOUBLE_CLICK_RADIUS: &str = "SDL_MOUSE_DOUBLE_CLICK_RADIUS";
/// Translation of `SDL_HINT_MOUSE_DOUBLE_CLICK_TIME`.
pub const MOUSE_DOUBLE_CLICK_TIME: &str = "SDL_MOUSE_DOUBLE_CLICK_TIME";
/// Translation of `SDL_HINT_MOUSE_DEFAULT_SYSTEM_CURSOR`.
pub const MOUSE_DEFAULT_SYSTEM_CURSOR: &str = "SDL_MOUSE_DEFAULT_SYSTEM_CURSOR";
/// Translation of `SDL_HINT_MOUSE_DPI_SCALE_CURSORS`.
pub const MOUSE_DPI_SCALE_CURSORS: &str = "SDL_MOUSE_DPI_SCALE_CURSORS";
/// Translation of `SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE`.
pub const MOUSE_EMULATE_WARP_WITH_RELATIVE: &str = "SDL_MOUSE_EMULATE_WARP_WITH_RELATIVE";
/// Translation of `SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH`.
pub const MOUSE_FOCUS_CLICKTHROUGH: &str = "SDL_MOUSE_FOCUS_CLICKTHROUGH";
/// Translation of `SDL_HINT_MOUSE_NORMAL_SPEED_SCALE`.
pub const MOUSE_NORMAL_SPEED_SCALE: &str = "SDL_MOUSE_NORMAL_SPEED_SCALE";
/// Translation of `SDL_HINT_MOUSE_RELATIVE_MODE_CENTER`.
pub const MOUSE_RELATIVE_MODE_CENTER: &str = "SDL_MOUSE_RELATIVE_MODE_CENTER";
/// Translation of `SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE`.
pub const MOUSE_RELATIVE_SPEED_SCALE: &str = "SDL_MOUSE_RELATIVE_SPEED_SCALE";
/// Translation of `SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE`.
pub const MOUSE_RELATIVE_SYSTEM_SCALE: &str = "SDL_MOUSE_RELATIVE_SYSTEM_SCALE";
/// Translation of `SDL_HINT_MOUSE_RELATIVE_WARP_MOTION`.
pub const MOUSE_RELATIVE_WARP_MOTION: &str = "SDL_MOUSE_RELATIVE_WARP_MOTION";
/// Translation of `SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE`.
pub const MOUSE_RELATIVE_CURSOR_VISIBLE: &str = "SDL_MOUSE_RELATIVE_CURSOR_VISIBLE";
/// Translation of `SDL_HINT_MOUSE_TOUCH_EVENTS`.
pub const MOUSE_TOUCH_EVENTS: &str = "SDL_MOUSE_TOUCH_EVENTS";
/// Translation of `SDL_HINT_MUTE_CONSOLE_KEYBOARD`.
pub const MUTE_CONSOLE_KEYBOARD: &str = "SDL_MUTE_CONSOLE_KEYBOARD";
/// Translation of `SDL_HINT_NO_SIGNAL_HANDLERS`.
pub const NO_SIGNAL_HANDLERS: &str = "SDL_NO_SIGNAL_HANDLERS";
/// Translation of `SDL_HINT_OPENGL_LIBRARY`.
pub const OPENGL_LIBRARY: &str = "SDL_OPENGL_LIBRARY";
/// Translation of `SDL_HINT_EGL_LIBRARY`.
pub const EGL_LIBRARY: &str = "SDL_EGL_LIBRARY";
/// Translation of `SDL_HINT_OPENGL_ES_DRIVER`.
pub const OPENGL_ES_DRIVER: &str = "SDL_OPENGL_ES_DRIVER";
/// Translation of `SDL_HINT_OPENGL_FORCE_SRGB_FRAMEBUFFER`.
pub const OPENGL_FORCE_SRGB_FRAMEBUFFER: &str = "SDL_OPENGL_FORCE_SRGB_FRAMEBUFFER";
/// Translation of `SDL_HINT_OPENVR_LIBRARY`.
pub const OPENVR_LIBRARY: &str = "SDL_OPENVR_LIBRARY";
/// Translation of `SDL_HINT_ORIENTATIONS`.
pub const ORIENTATIONS: &str = "SDL_ORIENTATIONS";
/// Translation of `SDL_HINT_POLL_SENTINEL`.
pub const POLL_SENTINEL: &str = "SDL_POLL_SENTINEL";
/// Translation of `SDL_HINT_PREFERRED_LOCALES`.
pub const PREFERRED_LOCALES: &str = "SDL_PREFERRED_LOCALES";
/// Translation of `SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE`.
pub const QUIT_ON_LAST_WINDOW_CLOSE: &str = "SDL_QUIT_ON_LAST_WINDOW_CLOSE";
/// Translation of `SDL_HINT_RENDER_DIRECT3D_THREADSAFE`.
pub const RENDER_DIRECT3D_THREADSAFE: &str = "SDL_RENDER_DIRECT3D_THREADSAFE";
/// Translation of `SDL_HINT_RENDER_DIRECT3D11_DEBUG`.
pub const RENDER_DIRECT3D11_DEBUG: &str = "SDL_RENDER_DIRECT3D11_DEBUG";
/// Translation of `SDL_HINT_RENDER_DIRECT3D11_WARP`.
pub const RENDER_DIRECT3D11_WARP: &str = "SDL_RENDER_DIRECT3D11_WARP";
/// Translation of `SDL_HINT_RENDER_VULKAN_DEBUG`.
pub const RENDER_VULKAN_DEBUG: &str = "SDL_RENDER_VULKAN_DEBUG";
/// Translation of `SDL_HINT_RENDER_GPU_DEBUG`.
pub const RENDER_GPU_DEBUG: &str = "SDL_RENDER_GPU_DEBUG";
/// Translation of `SDL_HINT_RENDER_GPU_LOW_POWER`.
pub const RENDER_GPU_LOW_POWER: &str = "SDL_RENDER_GPU_LOW_POWER";
/// Translation of `SDL_HINT_RENDER_DRIVER`.
pub const RENDER_DRIVER: &str = "SDL_RENDER_DRIVER";
/// Translation of `SDL_HINT_RENDER_LINE_METHOD`.
pub const RENDER_LINE_METHOD: &str = "SDL_RENDER_LINE_METHOD";
/// Translation of `SDL_HINT_RENDER_METAL_PREFER_LOW_POWER_DEVICE`.
pub const RENDER_METAL_PREFER_LOW_POWER_DEVICE: &str = "SDL_RENDER_METAL_PREFER_LOW_POWER_DEVICE";
/// Translation of `SDL_HINT_RENDER_VSYNC`.
pub const RENDER_VSYNC: &str = "SDL_RENDER_VSYNC";
/// Translation of `SDL_HINT_RETURN_KEY_HIDES_IME`.
pub const RETURN_KEY_HIDES_IME: &str = "SDL_RETURN_KEY_HIDES_IME";
/// Translation of `SDL_HINT_ROG_GAMEPAD_MICE`.
pub const ROG_GAMEPAD_MICE: &str = "SDL_ROG_GAMEPAD_MICE";
/// Translation of `SDL_HINT_ROG_GAMEPAD_MICE_EXCLUDED`.
pub const ROG_GAMEPAD_MICE_EXCLUDED: &str = "SDL_ROG_GAMEPAD_MICE_EXCLUDED";
/// Translation of `SDL_HINT_PS2_GS_WIDTH`.
pub const PS2_GS_WIDTH: &str = "SDL_PS2_GS_WIDTH";
/// Translation of `SDL_HINT_PS2_GS_HEIGHT`.
pub const PS2_GS_HEIGHT: &str = "SDL_PS2_GS_HEIGHT";
/// Translation of `SDL_HINT_PS2_GS_PROGRESSIVE`.
pub const PS2_GS_PROGRESSIVE: &str = "SDL_PS2_GS_PROGRESSIVE";
/// Translation of `SDL_HINT_PS2_GS_MODE`.
pub const PS2_GS_MODE: &str = "SDL_PS2_GS_MODE";
/// Translation of `SDL_HINT_RPI_VIDEO_LAYER`.
pub const RPI_VIDEO_LAYER: &str = "SDL_RPI_VIDEO_LAYER";
/// Translation of `SDL_HINT_SCREENSAVER_INHIBIT_ACTIVITY_NAME`.
pub const SCREENSAVER_INHIBIT_ACTIVITY_NAME: &str = "SDL_SCREENSAVER_INHIBIT_ACTIVITY_NAME";
/// Translation of `SDL_HINT_SHUTDOWN_DBUS_ON_QUIT`.
pub const SHUTDOWN_DBUS_ON_QUIT: &str = "SDL_SHUTDOWN_DBUS_ON_QUIT";
/// Translation of `SDL_HINT_STORAGE_TITLE_DRIVER`.
pub const STORAGE_TITLE_DRIVER: &str = "SDL_STORAGE_TITLE_DRIVER";
/// Translation of `SDL_HINT_STORAGE_USER_DRIVER`.
pub const STORAGE_USER_DRIVER: &str = "SDL_STORAGE_USER_DRIVER";
/// Translation of `SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL`.
pub const THREAD_FORCE_REALTIME_TIME_CRITICAL: &str = "SDL_THREAD_FORCE_REALTIME_TIME_CRITICAL";
/// Translation of `SDL_HINT_THREAD_PRIORITY_POLICY`.
pub const THREAD_PRIORITY_POLICY: &str = "SDL_THREAD_PRIORITY_POLICY";
/// Translation of `SDL_HINT_TIMER_RESOLUTION`.
pub const TIMER_RESOLUTION: &str = "SDL_TIMER_RESOLUTION";
/// Translation of `SDL_HINT_TOUCH_MOUSE_EVENTS`.
pub const TOUCH_MOUSE_EVENTS: &str = "SDL_TOUCH_MOUSE_EVENTS";
/// Translation of `SDL_HINT_TRACKPAD_IS_TOUCH_ONLY`.
pub const TRACKPAD_IS_TOUCH_ONLY: &str = "SDL_TRACKPAD_IS_TOUCH_ONLY";
/// Translation of `SDL_HINT_TV_REMOTE_AS_JOYSTICK`.
pub const TV_REMOTE_AS_JOYSTICK: &str = "SDL_TV_REMOTE_AS_JOYSTICK";
/// Translation of `SDL_HINT_VIDEO_ALLOW_SCREENSAVER`.
pub const VIDEO_ALLOW_SCREENSAVER: &str = "SDL_VIDEO_ALLOW_SCREENSAVER";
/// Translation of `SDL_HINT_VIDEO_DISPLAY_PRIORITY`.
pub const VIDEO_DISPLAY_PRIORITY: &str = "SDL_VIDEO_DISPLAY_PRIORITY";
/// Translation of `SDL_HINT_VIDEO_DOUBLE_BUFFER`.
pub const VIDEO_DOUBLE_BUFFER: &str = "SDL_VIDEO_DOUBLE_BUFFER";
/// Translation of `SDL_HINT_VIDEO_DRIVER`.
pub const VIDEO_DRIVER: &str = "SDL_VIDEO_DRIVER";
/// Translation of `SDL_HINT_VIDEO_DUMMY_SAVE_FRAMES`.
pub const VIDEO_DUMMY_SAVE_FRAMES: &str = "SDL_VIDEO_DUMMY_SAVE_FRAMES";
/// Translation of `SDL_HINT_VIDEO_EGL_ALLOW_GETDISPLAY_FALLBACK`.
pub const VIDEO_EGL_ALLOW_GETDISPLAY_FALLBACK: &str = "SDL_VIDEO_EGL_ALLOW_GETDISPLAY_FALLBACK";
/// Translation of `SDL_HINT_VIDEO_FORCE_EGL`.
pub const VIDEO_FORCE_EGL: &str = "SDL_VIDEO_FORCE_EGL";
/// Translation of `SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES`.
pub const VIDEO_MAC_FULLSCREEN_SPACES: &str = "SDL_VIDEO_MAC_FULLSCREEN_SPACES";
/// Translation of `SDL_HINT_VIDEO_MAC_FULLSCREEN_MENU_VISIBILITY`.
pub const VIDEO_MAC_FULLSCREEN_MENU_VISIBILITY: &str = "SDL_VIDEO_MAC_FULLSCREEN_MENU_VISIBILITY";
/// Translation of `SDL_HINT_VIDEO_METAL_AUTO_RESIZE_DRAWABLE`.
pub const VIDEO_METAL_AUTO_RESIZE_DRAWABLE: &str = "SDL_VIDEO_METAL_AUTO_RESIZE_DRAWABLE";
/// Translation of `SDL_HINT_VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE`.
pub const VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE: &str = "SDL_VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE";
/// Translation of `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS`.
pub const VIDEO_MINIMIZE_ON_FOCUS_LOSS: &str = "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS";
/// Translation of `SDL_HINT_VIDEO_OFFSCREEN_SAVE_FRAMES`.
pub const VIDEO_OFFSCREEN_SAVE_FRAMES: &str = "SDL_VIDEO_OFFSCREEN_SAVE_FRAMES";
/// Translation of `SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS`.
pub const VIDEO_SYNC_WINDOW_OPERATIONS: &str = "SDL_VIDEO_SYNC_WINDOW_OPERATIONS";
/// Translation of `SDL_HINT_VIDEO_WAYLAND_ALLOW_LIBDECOR`.
pub const VIDEO_WAYLAND_ALLOW_LIBDECOR: &str = "SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR";
/// Translation of `SDL_HINT_VIDEO_WAYLAND_MODE_EMULATION`.
pub const VIDEO_WAYLAND_MODE_EMULATION: &str = "SDL_VIDEO_WAYLAND_MODE_EMULATION";
/// Translation of `SDL_HINT_VIDEO_WAYLAND_MODE_SCALING`.
pub const VIDEO_WAYLAND_MODE_SCALING: &str = "SDL_VIDEO_WAYLAND_MODE_SCALING";
/// Translation of `SDL_HINT_VIDEO_WAYLAND_PREFER_LIBDECOR`.
pub const VIDEO_WAYLAND_PREFER_LIBDECOR: &str = "SDL_VIDEO_WAYLAND_PREFER_LIBDECOR";
/// Translation of `SDL_HINT_VIDEO_WAYLAND_SCALE_TO_DISPLAY`.
pub const VIDEO_WAYLAND_SCALE_TO_DISPLAY: &str = "SDL_VIDEO_WAYLAND_SCALE_TO_DISPLAY";
/// Translation of `SDL_HINT_VIDEO_WIN_D3DCOMPILER`.
pub const VIDEO_WIN_D3DCOMPILER: &str = "SDL_VIDEO_WIN_D3DCOMPILER";
/// Translation of `SDL_HINT_VIDEO_X11_ENABLE_XSYNC_EXT`.
pub const VIDEO_X11_ENABLE_XSYNC_EXT: &str = "SDL_VIDEO_X11_ENABLE_XSYNC_EXT";
/// Translation of `SDL_HINT_VIDEO_X11_EXTERNAL_WINDOW_INPUT`.
pub const VIDEO_X11_EXTERNAL_WINDOW_INPUT: &str = "SDL_VIDEO_X11_EXTERNAL_WINDOW_INPUT";
/// Translation of `SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR`.
pub const VIDEO_X11_NET_WM_BYPASS_COMPOSITOR: &str = "SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR";
/// Translation of `SDL_HINT_VIDEO_X11_NET_WM_PING`.
pub const VIDEO_X11_NET_WM_PING: &str = "SDL_VIDEO_X11_NET_WM_PING";
/// Translation of `SDL_HINT_VIDEO_X11_NODIRECTCOLOR`.
pub const VIDEO_X11_NODIRECTCOLOR: &str = "SDL_VIDEO_X11_NODIRECTCOLOR";
/// Translation of `SDL_HINT_VIDEO_X11_SCALING_FACTOR`.
pub const VIDEO_X11_SCALING_FACTOR: &str = "SDL_VIDEO_X11_SCALING_FACTOR";
/// Translation of `SDL_HINT_VIDEO_X11_VISUALID`.
pub const VIDEO_X11_VISUALID: &str = "SDL_VIDEO_X11_VISUALID";
/// Translation of `SDL_HINT_VIDEO_X11_WINDOW_VISUALID`.
pub const VIDEO_X11_WINDOW_VISUALID: &str = "SDL_VIDEO_X11_WINDOW_VISUALID";
/// Translation of `SDL_HINT_VIDEO_X11_XRANDR`.
pub const VIDEO_X11_XRANDR: &str = "SDL_VIDEO_X11_XRANDR";
/// Translation of `SDL_HINT_VISIONOS_HDR_HEADROOM_UI`.
pub const VISIONOS_HDR_HEADROOM_UI: &str = "SDL_VISIONOS_HDR_HEADROOM_UI";
/// Translation of `SDL_HINT_VITA_ENABLE_BACK_TOUCH`.
pub const VITA_ENABLE_BACK_TOUCH: &str = "SDL_VITA_ENABLE_BACK_TOUCH";
/// Translation of `SDL_HINT_VITA_ENABLE_FRONT_TOUCH`.
pub const VITA_ENABLE_FRONT_TOUCH: &str = "SDL_VITA_ENABLE_FRONT_TOUCH";
/// Translation of `SDL_HINT_VITA_MODULE_PATH`.
pub const VITA_MODULE_PATH: &str = "SDL_VITA_MODULE_PATH";
/// Translation of `SDL_HINT_VITA_PVR_INIT`.
pub const VITA_PVR_INIT: &str = "SDL_VITA_PVR_INIT";
/// Translation of `SDL_HINT_VITA_RESOLUTION`.
pub const VITA_RESOLUTION: &str = "SDL_VITA_RESOLUTION";
/// Translation of `SDL_HINT_VITA_PVR_OPENGL`.
pub const VITA_PVR_OPENGL: &str = "SDL_VITA_PVR_OPENGL";
/// Translation of `SDL_HINT_VITA_TOUCH_MOUSE_DEVICE`.
pub const VITA_TOUCH_MOUSE_DEVICE: &str = "SDL_VITA_TOUCH_MOUSE_DEVICE";
/// Translation of `SDL_HINT_VULKAN_DISPLAY`.
pub const VULKAN_DISPLAY: &str = "SDL_VULKAN_DISPLAY";
/// Translation of `SDL_HINT_VULKAN_LIBRARY`.
pub const VULKAN_LIBRARY: &str = "SDL_VULKAN_LIBRARY";
/// Translation of `SDL_HINT_WAVE_FACT_CHUNK`.
pub const WAVE_FACT_CHUNK: &str = "SDL_WAVE_FACT_CHUNK";
/// Translation of `SDL_HINT_WAVE_CHUNK_LIMIT`.
pub const WAVE_CHUNK_LIMIT: &str = "SDL_WAVE_CHUNK_LIMIT";
/// Translation of `SDL_HINT_WAVE_RIFF_CHUNK_SIZE`.
pub const WAVE_RIFF_CHUNK_SIZE: &str = "SDL_WAVE_RIFF_CHUNK_SIZE";
/// Translation of `SDL_HINT_WAVE_TRUNCATION`.
pub const WAVE_TRUNCATION: &str = "SDL_WAVE_TRUNCATION";
/// Translation of `SDL_HINT_WINDOW_ACTIVATE_WHEN_RAISED`.
pub const WINDOW_ACTIVATE_WHEN_RAISED: &str = "SDL_WINDOW_ACTIVATE_WHEN_RAISED";
/// Translation of `SDL_HINT_WINDOW_ACTIVATE_WHEN_SHOWN`.
pub const WINDOW_ACTIVATE_WHEN_SHOWN: &str = "SDL_WINDOW_ACTIVATE_WHEN_SHOWN";
/// Translation of `SDL_HINT_WINDOW_ALLOW_TOPMOST`.
pub const WINDOW_ALLOW_TOPMOST: &str = "SDL_WINDOW_ALLOW_TOPMOST";
/// Translation of `SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN`.
pub const WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN: &str =
    "SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN";
/// Translation of `SDL_HINT_WINDOWS_CLOSE_ON_ALT_F4`.
pub const WINDOWS_CLOSE_ON_ALT_F4: &str = "SDL_WINDOWS_CLOSE_ON_ALT_F4";
/// Translation of `SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS`.
pub const WINDOWS_ENABLE_MENU_MNEMONICS: &str = "SDL_WINDOWS_ENABLE_MENU_MNEMONICS";
/// Translation of `SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP`.
pub const WINDOWS_ENABLE_MESSAGELOOP: &str = "SDL_WINDOWS_ENABLE_MESSAGELOOP";
/// Translation of `SDL_HINT_WINDOWS_GAMEINPUT`.
pub const WINDOWS_GAMEINPUT: &str = "SDL_WINDOWS_GAMEINPUT";
/// Translation of `SDL_HINT_WINDOWS_RAW_KEYBOARD`.
pub const WINDOWS_RAW_KEYBOARD: &str = "SDL_WINDOWS_RAW_KEYBOARD";
/// Translation of `SDL_HINT_WINDOWS_RAW_KEYBOARD_EXCLUDE_HOTKEYS`.
pub const WINDOWS_RAW_KEYBOARD_EXCLUDE_HOTKEYS: &str = "SDL_WINDOWS_RAW_KEYBOARD_EXCLUDE_HOTKEYS";
/// Translation of `SDL_HINT_WINDOWS_RAW_KEYBOARD_INPUTSINK`.
pub const WINDOWS_RAW_KEYBOARD_INPUTSINK: &str = "SDL_WINDOWS_RAW_KEYBOARD_INPUTSINK";
/// Translation of `SDL_HINT_WINDOWS_RAW_MOUSE_NOLEGACY`.
pub const WINDOWS_RAW_MOUSE_NOLEGACY: &str = "SDL_WINDOWS_RAW_MOUSE_NOLEGACY";
/// Translation of `SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL`.
pub const WINDOWS_FORCE_SEMAPHORE_KERNEL: &str = "SDL_WINDOWS_FORCE_SEMAPHORE_KERNEL";
/// Translation of `SDL_HINT_WINDOWS_INTRESOURCE_ICON`.
pub const WINDOWS_INTRESOURCE_ICON: &str = "SDL_WINDOWS_INTRESOURCE_ICON";
/// Translation of `SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL`.
pub const WINDOWS_INTRESOURCE_ICON_SMALL: &str = "SDL_WINDOWS_INTRESOURCE_ICON_SMALL";
/// Translation of `SDL_HINT_WINDOWS_USE_D3D9EX`.
pub const WINDOWS_USE_D3D9EX: &str = "SDL_WINDOWS_USE_D3D9EX";
/// Translation of `SDL_HINT_WINDOWS_ERASE_BACKGROUND_MODE`.
pub const WINDOWS_ERASE_BACKGROUND_MODE: &str = "SDL_WINDOWS_ERASE_BACKGROUND_MODE";
/// Translation of `SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT`.
pub const X11_FORCE_OVERRIDE_REDIRECT: &str = "SDL_X11_FORCE_OVERRIDE_REDIRECT";
/// Translation of `SDL_HINT_X11_WINDOW_TYPE`.
pub const X11_WINDOW_TYPE: &str = "SDL_X11_WINDOW_TYPE";
/// Translation of `SDL_HINT_X11_XCB_LIBRARY`.
pub const X11_XCB_LIBRARY: &str = "SDL_X11_XCB_LIBRARY";
/// Translation of `SDL_HINT_XINPUT_ENABLED`.
pub const XINPUT_ENABLED: &str = "SDL_XINPUT_ENABLED";
/// Translation of `SDL_HINT_ASSERT`.
pub const ASSERT: &str = "SDL_ASSERT";
/// Translation of `SDL_HINT_PEN_MOUSE_EVENTS`.
pub const PEN_MOUSE_EVENTS: &str = "SDL_PEN_MOUSE_EVENTS";
/// Translation of `SDL_HINT_PEN_TOUCH_EVENTS`.
pub const PEN_TOUCH_EVENTS: &str = "SDL_PEN_TOUCH_EVENTS";
