// Rust bindings of the alpha_modifier_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/alpha-modifier-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2024 Xaver Hugl
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `alpha_modifier_v1` protocol (`alpha-modifier-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// wp_alpha_modifier_v1
// ---------------------------------------------------------------------------

static WP_ALPHA_MODIFIER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static WP_ALPHA_MODIFIER_V1_GET_SURFACE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&WP_ALPHA_MODIFIER_SURFACE_V1_INTERFACE),
    Some(&super::wayland::WL_SURFACE_INTERFACE),
];
static WP_ALPHA_MODIFIER_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: WP_ALPHA_MODIFIER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_surface".as_ptr(),
        signature: c"no".as_ptr(),
        types: WP_ALPHA_MODIFIER_V1_GET_SURFACE_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `wp_alpha_modifier_v1` (`wp_alpha_modifier_v1_interface`).
pub(crate) static WP_ALPHA_MODIFIER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"wp_alpha_modifier_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: WP_ALPHA_MODIFIER_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `wp_alpha_modifier_v1.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct WpAlphaModifierV1Error(pub(crate) u32);

impl WpAlphaModifierV1Error {
    /// wl_surface already has a alpha modifier object
    pub(crate) const ALREADY_CONSTRUCTED: WpAlphaModifierV1Error = WpAlphaModifierV1Error(0);
}

/// `wp_alpha_modifier_v1`: surface alpha modifier manager
#[derive(Debug)]
pub(crate) enum WpAlphaModifierV1 {}

impl WpAlphaModifierV1 {
    /// The version `wp_alpha_modifier_v1.destroy` appeared in (`WP_ALPHA_MODIFIER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `wp_alpha_modifier_v1.get_surface` appeared in (`WP_ALPHA_MODIFIER_V1_GET_SURFACE_SINCE_VERSION`).
    pub(crate) const GET_SURFACE_SINCE_VERSION: u32 = 1;
}

impl Interface for WpAlphaModifierV1 {
    const NAME: &'static str = "wp_alpha_modifier_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &WP_ALPHA_MODIFIER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `wp_alpha_modifier_v1`, for anything that is a proxy of it.
pub(crate) trait WpAlphaModifierV1Requests: AsProxy<Interface = WpAlphaModifierV1> {
    /// `wp_alpha_modifier_v1.get_surface`: create a new toplevel decoration object
    fn get_surface(
        &self,
        surface: Obj<'_, super::wayland::WlSurface>,
    ) -> Proxy<WpAlphaModifierSurfaceV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: surface.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe {
            proxy.marshal_constructor::<WpAlphaModifierSurfaceV1>(1, &mut args, proxy.version(), 0)
        }
    }
}

impl<T: AsProxy<Interface = WpAlphaModifierV1>> WpAlphaModifierV1Requests for T {}

impl Proxy<WpAlphaModifierV1> {
    /// `wp_alpha_modifier_v1.destroy`: destroy the alpha modifier manager object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// wp_alpha_modifier_surface_v1
// ---------------------------------------------------------------------------

static WP_ALPHA_MODIFIER_SURFACE_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static WP_ALPHA_MODIFIER_SURFACE_V1_SET_MULTIPLIER_REQUEST_TYPES: [IfacePtr; 1] = [None];
static WP_ALPHA_MODIFIER_SURFACE_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: WP_ALPHA_MODIFIER_SURFACE_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_multiplier".as_ptr(),
        signature: c"u".as_ptr(),
        types: WP_ALPHA_MODIFIER_SURFACE_V1_SET_MULTIPLIER_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `wp_alpha_modifier_surface_v1` (`wp_alpha_modifier_surface_v1_interface`).
pub(crate) static WP_ALPHA_MODIFIER_SURFACE_V1_INTERFACE: wl_interface = wl_interface {
    name: c"wp_alpha_modifier_surface_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: WP_ALPHA_MODIFIER_SURFACE_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `wp_alpha_modifier_surface_v1.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct WpAlphaModifierSurfaceV1Error(pub(crate) u32);

impl WpAlphaModifierSurfaceV1Error {
    /// wl_surface was destroyed
    pub(crate) const NO_SURFACE: WpAlphaModifierSurfaceV1Error = WpAlphaModifierSurfaceV1Error(0);
}

/// `wp_alpha_modifier_surface_v1`: alpha modifier object for a surface
#[derive(Debug)]
pub(crate) enum WpAlphaModifierSurfaceV1 {}

impl WpAlphaModifierSurfaceV1 {
    /// The version `wp_alpha_modifier_surface_v1.destroy` appeared in (`WP_ALPHA_MODIFIER_SURFACE_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `wp_alpha_modifier_surface_v1.set_multiplier` appeared in (`WP_ALPHA_MODIFIER_SURFACE_V1_SET_MULTIPLIER_SINCE_VERSION`).
    pub(crate) const SET_MULTIPLIER_SINCE_VERSION: u32 = 1;
}

impl Interface for WpAlphaModifierSurfaceV1 {
    const NAME: &'static str = "wp_alpha_modifier_surface_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &WP_ALPHA_MODIFIER_SURFACE_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `wp_alpha_modifier_surface_v1`, for anything that is a proxy of it.
pub(crate) trait WpAlphaModifierSurfaceV1Requests:
    AsProxy<Interface = WpAlphaModifierSurfaceV1>
{
    /// `wp_alpha_modifier_surface_v1.set_multiplier`: specify the alpha multiplier
    fn set_multiplier(&self, factor: u32) {
        let proxy = self.obj();
        let mut args = [wl_argument { u: factor }];
        // SAFETY: the arguments match the request's signature, "u".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = WpAlphaModifierSurfaceV1>> WpAlphaModifierSurfaceV1Requests for T {}

impl Proxy<WpAlphaModifierSurfaceV1> {
    /// `wp_alpha_modifier_surface_v1.destroy`: destroy the alpha modifier object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
