// Rust bindings of the fractional_scale_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/fractional-scale-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2022 Kenny Levinsen
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `fractional_scale_v1` protocol (`fractional-scale-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// wp_fractional_scale_manager_v1
// ---------------------------------------------------------------------------

static WP_FRACTIONAL_SCALE_MANAGER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static WP_FRACTIONAL_SCALE_MANAGER_V1_GET_FRACTIONAL_SCALE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&WP_FRACTIONAL_SCALE_V1_INTERFACE),
    Some(&super::wayland::WL_SURFACE_INTERFACE),
];
static WP_FRACTIONAL_SCALE_MANAGER_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: WP_FRACTIONAL_SCALE_MANAGER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_fractional_scale".as_ptr(),
        signature: c"no".as_ptr(),
        types: WP_FRACTIONAL_SCALE_MANAGER_V1_GET_FRACTIONAL_SCALE_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `wp_fractional_scale_manager_v1` (`wp_fractional_scale_manager_v1_interface`).
pub(crate) static WP_FRACTIONAL_SCALE_MANAGER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"wp_fractional_scale_manager_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: WP_FRACTIONAL_SCALE_MANAGER_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `wp_fractional_scale_manager_v1.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct WpFractionalScaleManagerV1Error(pub(crate) u32);

impl WpFractionalScaleManagerV1Error {
    /// the surface already has a fractional_scale object associated
    pub(crate) const FRACTIONAL_SCALE_EXISTS: WpFractionalScaleManagerV1Error =
        WpFractionalScaleManagerV1Error(0);
}

/// `wp_fractional_scale_manager_v1`: fractional surface scale information
#[derive(Debug)]
pub(crate) enum WpFractionalScaleManagerV1 {}

impl WpFractionalScaleManagerV1 {
    /// The version `wp_fractional_scale_manager_v1.destroy` appeared in (`WP_FRACTIONAL_SCALE_MANAGER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `wp_fractional_scale_manager_v1.get_fractional_scale` appeared in (`WP_FRACTIONAL_SCALE_MANAGER_V1_GET_FRACTIONAL_SCALE_SINCE_VERSION`).
    pub(crate) const GET_FRACTIONAL_SCALE_SINCE_VERSION: u32 = 1;
}

impl Interface for WpFractionalScaleManagerV1 {
    const NAME: &'static str = "wp_fractional_scale_manager_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &WP_FRACTIONAL_SCALE_MANAGER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `wp_fractional_scale_manager_v1`, for anything that is a proxy of it.
pub(crate) trait WpFractionalScaleManagerV1Requests:
    AsProxy<Interface = WpFractionalScaleManagerV1>
{
    /// `wp_fractional_scale_manager_v1.get_fractional_scale`: extend surface interface for scale information
    fn get_fractional_scale(
        &self,
        surface: Obj<'_, super::wayland::WlSurface>,
    ) -> Proxy<WpFractionalScaleV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: surface.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe {
            proxy.marshal_constructor::<WpFractionalScaleV1>(1, &mut args, proxy.version(), 0)
        }
    }
}

impl<T: AsProxy<Interface = WpFractionalScaleManagerV1>> WpFractionalScaleManagerV1Requests for T {}

impl Proxy<WpFractionalScaleManagerV1> {
    /// `wp_fractional_scale_manager_v1.destroy`: unbind the fractional surface scale interface
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// wp_fractional_scale_v1
// ---------------------------------------------------------------------------

static WP_FRACTIONAL_SCALE_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static WP_FRACTIONAL_SCALE_V1_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: WP_FRACTIONAL_SCALE_V1_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static WP_FRACTIONAL_SCALE_V1_PREFERRED_SCALE_EVENT_TYPES: [IfacePtr; 1] = [None];
static WP_FRACTIONAL_SCALE_V1_EVENTS: [wl_message; 1] = [wl_message {
    name: c"preferred_scale".as_ptr(),
    signature: c"u".as_ptr(),
    types: WP_FRACTIONAL_SCALE_V1_PREFERRED_SCALE_EVENT_TYPES.as_ptr(),
}];
/// The `wl_interface` of `wp_fractional_scale_v1` (`wp_fractional_scale_v1_interface`).
pub(crate) static WP_FRACTIONAL_SCALE_V1_INTERFACE: wl_interface = wl_interface {
    name: c"wp_fractional_scale_v1".as_ptr(),
    version: 1,
    method_count: 1,
    methods: WP_FRACTIONAL_SCALE_V1_REQUESTS.as_ptr(),
    event_count: 1,
    events: WP_FRACTIONAL_SCALE_V1_EVENTS.as_ptr(),
};

/// `wp_fractional_scale_v1`: fractional scale interface to a wl_surface
#[derive(Debug)]
pub(crate) enum WpFractionalScaleV1 {}

impl WpFractionalScaleV1 {
    /// The version `wp_fractional_scale_v1.destroy` appeared in (`WP_FRACTIONAL_SCALE_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `wp_fractional_scale_v1.preferred_scale` appeared in (`WP_FRACTIONAL_SCALE_V1_PREFERRED_SCALE_SINCE_VERSION`).
    pub(crate) const PREFERRED_SCALE_SINCE_VERSION: u32 = 1;
}

/// The events of `wp_fractional_scale_v1`.
#[derive(Debug)]
pub(crate) enum WpFractionalScaleV1Event {
    /// `wp_fractional_scale_v1.preferred_scale`: notify of new preferred scale
    PreferredScale {
        /// the new preferred scale
        scale: u32,
    },
}

impl Interface for WpFractionalScaleV1 {
    const NAME: &'static str = "wp_fractional_scale_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = WpFractionalScaleV1Event;

    fn interface() -> &'static wl_interface {
        &WP_FRACTIONAL_SCALE_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(WpFractionalScaleV1Event::PreferredScale {
                    // SAFETY: argument 0 is a `uint`.
                    scale: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `wp_fractional_scale_v1`, for anything that is a proxy of it.
pub(crate) trait WpFractionalScaleV1Requests:
    AsProxy<Interface = WpFractionalScaleV1>
{
}

impl<T: AsProxy<Interface = WpFractionalScaleV1>> WpFractionalScaleV1Requests for T {}

impl Proxy<WpFractionalScaleV1> {
    /// `wp_fractional_scale_v1.destroy`: remove surface scale information for surface
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
