// Rust bindings of the pointer_gestures_unstable_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/pointer-gestures-unstable-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//  (no copyright notice in the file; wayland-protocols is MIT licensed)

//! The `pointer_gestures_unstable_v1` protocol (`pointer-gestures-unstable-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// zwp_pointer_gestures_v1
// ---------------------------------------------------------------------------

static ZWP_POINTER_GESTURES_V1_GET_SWIPE_GESTURE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&ZWP_POINTER_GESTURE_SWIPE_V1_INTERFACE),
    Some(&super::wayland::WL_POINTER_INTERFACE),
];
static ZWP_POINTER_GESTURES_V1_GET_PINCH_GESTURE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&ZWP_POINTER_GESTURE_PINCH_V1_INTERFACE),
    Some(&super::wayland::WL_POINTER_INTERFACE),
];
static ZWP_POINTER_GESTURES_V1_RELEASE_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_POINTER_GESTURES_V1_GET_HOLD_GESTURE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&ZWP_POINTER_GESTURE_HOLD_V1_INTERFACE),
    Some(&super::wayland::WL_POINTER_INTERFACE),
];
static ZWP_POINTER_GESTURES_V1_REQUESTS: [wl_message; 4] = [
    wl_message {
        name: c"get_swipe_gesture".as_ptr(),
        signature: c"no".as_ptr(),
        types: ZWP_POINTER_GESTURES_V1_GET_SWIPE_GESTURE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_pinch_gesture".as_ptr(),
        signature: c"no".as_ptr(),
        types: ZWP_POINTER_GESTURES_V1_GET_PINCH_GESTURE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"release".as_ptr(),
        signature: c"2".as_ptr(),
        types: ZWP_POINTER_GESTURES_V1_RELEASE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_hold_gesture".as_ptr(),
        signature: c"3no".as_ptr(),
        types: ZWP_POINTER_GESTURES_V1_GET_HOLD_GESTURE_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_pointer_gestures_v1` (`zwp_pointer_gestures_v1_interface`).
pub(crate) static ZWP_POINTER_GESTURES_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_pointer_gestures_v1".as_ptr(),
    version: 3,
    method_count: 4,
    methods: ZWP_POINTER_GESTURES_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `zwp_pointer_gestures_v1`: touchpad gestures
#[derive(Debug)]
pub(crate) enum ZwpPointerGesturesV1 {}

impl ZwpPointerGesturesV1 {
    /// The version `zwp_pointer_gestures_v1.get_swipe_gesture` appeared in (`ZWP_POINTER_GESTURES_V1_GET_SWIPE_GESTURE_SINCE_VERSION`).
    pub(crate) const GET_SWIPE_GESTURE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gestures_v1.get_pinch_gesture` appeared in (`ZWP_POINTER_GESTURES_V1_GET_PINCH_GESTURE_SINCE_VERSION`).
    pub(crate) const GET_PINCH_GESTURE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gestures_v1.release` appeared in (`ZWP_POINTER_GESTURES_V1_RELEASE_SINCE_VERSION`).
    pub(crate) const RELEASE_SINCE_VERSION: u32 = 2;
    /// The version `zwp_pointer_gestures_v1.get_hold_gesture` appeared in (`ZWP_POINTER_GESTURES_V1_GET_HOLD_GESTURE_SINCE_VERSION`).
    pub(crate) const GET_HOLD_GESTURE_SINCE_VERSION: u32 = 3;
}

impl Interface for ZwpPointerGesturesV1 {
    const NAME: &'static str = "zwp_pointer_gestures_v1";
    const VERSION: u32 = 3;
    const DESTRUCTOR: Option<(u32, u32)> = Some((2, 2));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &ZWP_POINTER_GESTURES_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `zwp_pointer_gestures_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPointerGesturesV1Requests:
    AsProxy<Interface = ZwpPointerGesturesV1>
{
    /// `zwp_pointer_gestures_v1.get_swipe_gesture`: get swipe gesture
    fn get_swipe_gesture(
        &self,
        pointer: Obj<'_, super::wayland::WlPointer>,
    ) -> Proxy<ZwpPointerGestureSwipeV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: pointer.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe {
            proxy.marshal_constructor::<ZwpPointerGestureSwipeV1>(0, &mut args, proxy.version(), 0)
        }
    }

    /// `zwp_pointer_gestures_v1.get_pinch_gesture`: get pinch gesture
    fn get_pinch_gesture(
        &self,
        pointer: Obj<'_, super::wayland::WlPointer>,
    ) -> Proxy<ZwpPointerGesturePinchV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: pointer.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe {
            proxy.marshal_constructor::<ZwpPointerGesturePinchV1>(1, &mut args, proxy.version(), 0)
        }
    }

    /// `zwp_pointer_gestures_v1.get_hold_gesture`: get hold gesture
    fn get_hold_gesture(
        &self,
        pointer: Obj<'_, super::wayland::WlPointer>,
    ) -> Proxy<ZwpPointerGestureHoldV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: pointer.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "3no".
        unsafe {
            proxy.marshal_constructor::<ZwpPointerGestureHoldV1>(3, &mut args, proxy.version(), 0)
        }
    }
}

impl<T: AsProxy<Interface = ZwpPointerGesturesV1>> ZwpPointerGesturesV1Requests for T {}

impl Proxy<ZwpPointerGesturesV1> {
    /// `zwp_pointer_gestures_v1.release`: destroy the pointer gesture object
    pub(crate) fn release(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "2".
        unsafe { proxy.marshal(2, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_pointer_gesture_swipe_v1
// ---------------------------------------------------------------------------

static ZWP_POINTER_GESTURE_SWIPE_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_POINTER_GESTURE_SWIPE_V1_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: ZWP_POINTER_GESTURE_SWIPE_V1_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_POINTER_GESTURE_SWIPE_V1_BEGIN_EVENT_TYPES: [IfacePtr; 4] = [
    None,
    None,
    Some(&super::wayland::WL_SURFACE_INTERFACE),
    None,
];
static ZWP_POINTER_GESTURE_SWIPE_V1_UPDATE_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_POINTER_GESTURE_SWIPE_V1_END_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_POINTER_GESTURE_SWIPE_V1_EVENTS: [wl_message; 3] = [
    wl_message {
        name: c"begin".as_ptr(),
        signature: c"uuou".as_ptr(),
        types: ZWP_POINTER_GESTURE_SWIPE_V1_BEGIN_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"update".as_ptr(),
        signature: c"uff".as_ptr(),
        types: ZWP_POINTER_GESTURE_SWIPE_V1_UPDATE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"end".as_ptr(),
        signature: c"uui".as_ptr(),
        types: ZWP_POINTER_GESTURE_SWIPE_V1_END_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_pointer_gesture_swipe_v1` (`zwp_pointer_gesture_swipe_v1_interface`).
pub(crate) static ZWP_POINTER_GESTURE_SWIPE_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_pointer_gesture_swipe_v1".as_ptr(),
    version: 2,
    method_count: 1,
    methods: ZWP_POINTER_GESTURE_SWIPE_V1_REQUESTS.as_ptr(),
    event_count: 3,
    events: ZWP_POINTER_GESTURE_SWIPE_V1_EVENTS.as_ptr(),
};

/// `zwp_pointer_gesture_swipe_v1`: a swipe gesture object
#[derive(Debug)]
pub(crate) enum ZwpPointerGestureSwipeV1 {}

impl ZwpPointerGestureSwipeV1 {
    /// The version `zwp_pointer_gesture_swipe_v1.destroy` appeared in (`ZWP_POINTER_GESTURE_SWIPE_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gesture_swipe_v1.begin` appeared in (`ZWP_POINTER_GESTURE_SWIPE_V1_BEGIN_SINCE_VERSION`).
    pub(crate) const BEGIN_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gesture_swipe_v1.update` appeared in (`ZWP_POINTER_GESTURE_SWIPE_V1_UPDATE_SINCE_VERSION`).
    pub(crate) const UPDATE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gesture_swipe_v1.end` appeared in (`ZWP_POINTER_GESTURE_SWIPE_V1_END_SINCE_VERSION`).
    pub(crate) const END_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_pointer_gesture_swipe_v1`.
#[derive(Debug)]
pub(crate) enum ZwpPointerGestureSwipeV1Event<'a> {
    /// `zwp_pointer_gesture_swipe_v1.begin`: multi-finger swipe begin
    Begin {
        serial: u32,
        /// timestamp with millisecond granularity
        time: u32,
        surface: Option<Obj<'a, super::wayland::WlSurface>>,
        /// number of fingers
        fingers: u32,
    },
    /// `zwp_pointer_gesture_swipe_v1.update`: multi-finger swipe motion
    Update {
        /// timestamp with millisecond granularity
        time: u32,
        /// delta x coordinate in surface coordinate space
        dx: Fixed,
        /// delta y coordinate in surface coordinate space
        dy: Fixed,
    },
    /// `zwp_pointer_gesture_swipe_v1.end`: multi-finger swipe end
    End {
        serial: u32,
        /// timestamp with millisecond granularity
        time: u32,
        /// 1 if the gesture was cancelled, 0 otherwise
        cancelled: i32,
    },
}

impl Interface for ZwpPointerGestureSwipeV1 {
    const NAME: &'static str = "zwp_pointer_gesture_swipe_v1";
    const VERSION: u32 = 2;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = ZwpPointerGestureSwipeV1Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_POINTER_GESTURE_SWIPE_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 4 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 4) };
                Some(ZwpPointerGestureSwipeV1Event::Begin {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    time: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `object`.
                    surface: unsafe { arg_obj(conn, &a[2]) },
                    // SAFETY: argument 3 is a `uint`.
                    fingers: unsafe { a[3].u },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpPointerGestureSwipeV1Event::Update {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `fixed`.
                    dx: Fixed(unsafe { a[1].f }),
                    // SAFETY: argument 2 is a `fixed`.
                    dy: Fixed(unsafe { a[2].f }),
                })
            }
            2 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpPointerGestureSwipeV1Event::End {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    time: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `int`.
                    cancelled: unsafe { a[2].i },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_pointer_gesture_swipe_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPointerGestureSwipeV1Requests:
    AsProxy<Interface = ZwpPointerGestureSwipeV1>
{
}

impl<T: AsProxy<Interface = ZwpPointerGestureSwipeV1>> ZwpPointerGestureSwipeV1Requests for T {}

impl Proxy<ZwpPointerGestureSwipeV1> {
    /// `zwp_pointer_gesture_swipe_v1.destroy`: destroy the pointer swipe gesture object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_pointer_gesture_pinch_v1
// ---------------------------------------------------------------------------

static ZWP_POINTER_GESTURE_PINCH_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_POINTER_GESTURE_PINCH_V1_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: ZWP_POINTER_GESTURE_PINCH_V1_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_POINTER_GESTURE_PINCH_V1_BEGIN_EVENT_TYPES: [IfacePtr; 4] = [
    None,
    None,
    Some(&super::wayland::WL_SURFACE_INTERFACE),
    None,
];
static ZWP_POINTER_GESTURE_PINCH_V1_UPDATE_EVENT_TYPES: [IfacePtr; 5] =
    [None, None, None, None, None];
static ZWP_POINTER_GESTURE_PINCH_V1_END_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_POINTER_GESTURE_PINCH_V1_EVENTS: [wl_message; 3] = [
    wl_message {
        name: c"begin".as_ptr(),
        signature: c"uuou".as_ptr(),
        types: ZWP_POINTER_GESTURE_PINCH_V1_BEGIN_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"update".as_ptr(),
        signature: c"uffff".as_ptr(),
        types: ZWP_POINTER_GESTURE_PINCH_V1_UPDATE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"end".as_ptr(),
        signature: c"uui".as_ptr(),
        types: ZWP_POINTER_GESTURE_PINCH_V1_END_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_pointer_gesture_pinch_v1` (`zwp_pointer_gesture_pinch_v1_interface`).
pub(crate) static ZWP_POINTER_GESTURE_PINCH_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_pointer_gesture_pinch_v1".as_ptr(),
    version: 2,
    method_count: 1,
    methods: ZWP_POINTER_GESTURE_PINCH_V1_REQUESTS.as_ptr(),
    event_count: 3,
    events: ZWP_POINTER_GESTURE_PINCH_V1_EVENTS.as_ptr(),
};

/// `zwp_pointer_gesture_pinch_v1`: a pinch gesture object
#[derive(Debug)]
pub(crate) enum ZwpPointerGesturePinchV1 {}

impl ZwpPointerGesturePinchV1 {
    /// The version `zwp_pointer_gesture_pinch_v1.destroy` appeared in (`ZWP_POINTER_GESTURE_PINCH_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gesture_pinch_v1.begin` appeared in (`ZWP_POINTER_GESTURE_PINCH_V1_BEGIN_SINCE_VERSION`).
    pub(crate) const BEGIN_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gesture_pinch_v1.update` appeared in (`ZWP_POINTER_GESTURE_PINCH_V1_UPDATE_SINCE_VERSION`).
    pub(crate) const UPDATE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_pointer_gesture_pinch_v1.end` appeared in (`ZWP_POINTER_GESTURE_PINCH_V1_END_SINCE_VERSION`).
    pub(crate) const END_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_pointer_gesture_pinch_v1`.
#[derive(Debug)]
pub(crate) enum ZwpPointerGesturePinchV1Event<'a> {
    /// `zwp_pointer_gesture_pinch_v1.begin`: multi-finger pinch begin
    Begin {
        serial: u32,
        /// timestamp with millisecond granularity
        time: u32,
        surface: Option<Obj<'a, super::wayland::WlSurface>>,
        /// number of fingers
        fingers: u32,
    },
    /// `zwp_pointer_gesture_pinch_v1.update`: multi-finger pinch motion
    Update {
        /// timestamp with millisecond granularity
        time: u32,
        /// delta x coordinate in surface coordinate space
        dx: Fixed,
        /// delta y coordinate in surface coordinate space
        dy: Fixed,
        /// scale relative to the initial finger position
        scale: Fixed,
        /// angle in degrees cw relative to the previous event
        rotation: Fixed,
    },
    /// `zwp_pointer_gesture_pinch_v1.end`: multi-finger pinch end
    End {
        serial: u32,
        /// timestamp with millisecond granularity
        time: u32,
        /// 1 if the gesture was cancelled, 0 otherwise
        cancelled: i32,
    },
}

impl Interface for ZwpPointerGesturePinchV1 {
    const NAME: &'static str = "zwp_pointer_gesture_pinch_v1";
    const VERSION: u32 = 2;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = ZwpPointerGesturePinchV1Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_POINTER_GESTURE_PINCH_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 4 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 4) };
                Some(ZwpPointerGesturePinchV1Event::Begin {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    time: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `object`.
                    surface: unsafe { arg_obj(conn, &a[2]) },
                    // SAFETY: argument 3 is a `uint`.
                    fingers: unsafe { a[3].u },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 5 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 5) };
                Some(ZwpPointerGesturePinchV1Event::Update {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `fixed`.
                    dx: Fixed(unsafe { a[1].f }),
                    // SAFETY: argument 2 is a `fixed`.
                    dy: Fixed(unsafe { a[2].f }),
                    // SAFETY: argument 3 is a `fixed`.
                    scale: Fixed(unsafe { a[3].f }),
                    // SAFETY: argument 4 is a `fixed`.
                    rotation: Fixed(unsafe { a[4].f }),
                })
            }
            2 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpPointerGesturePinchV1Event::End {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    time: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `int`.
                    cancelled: unsafe { a[2].i },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_pointer_gesture_pinch_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPointerGesturePinchV1Requests:
    AsProxy<Interface = ZwpPointerGesturePinchV1>
{
}

impl<T: AsProxy<Interface = ZwpPointerGesturePinchV1>> ZwpPointerGesturePinchV1Requests for T {}

impl Proxy<ZwpPointerGesturePinchV1> {
    /// `zwp_pointer_gesture_pinch_v1.destroy`: destroy the pinch gesture object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_pointer_gesture_hold_v1
// ---------------------------------------------------------------------------

static ZWP_POINTER_GESTURE_HOLD_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_POINTER_GESTURE_HOLD_V1_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"3".as_ptr(),
    types: ZWP_POINTER_GESTURE_HOLD_V1_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_POINTER_GESTURE_HOLD_V1_BEGIN_EVENT_TYPES: [IfacePtr; 4] = [
    None,
    None,
    Some(&super::wayland::WL_SURFACE_INTERFACE),
    None,
];
static ZWP_POINTER_GESTURE_HOLD_V1_END_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_POINTER_GESTURE_HOLD_V1_EVENTS: [wl_message; 2] = [
    wl_message {
        name: c"begin".as_ptr(),
        signature: c"3uuou".as_ptr(),
        types: ZWP_POINTER_GESTURE_HOLD_V1_BEGIN_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"end".as_ptr(),
        signature: c"3uui".as_ptr(),
        types: ZWP_POINTER_GESTURE_HOLD_V1_END_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_pointer_gesture_hold_v1` (`zwp_pointer_gesture_hold_v1_interface`).
pub(crate) static ZWP_POINTER_GESTURE_HOLD_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_pointer_gesture_hold_v1".as_ptr(),
    version: 3,
    method_count: 1,
    methods: ZWP_POINTER_GESTURE_HOLD_V1_REQUESTS.as_ptr(),
    event_count: 2,
    events: ZWP_POINTER_GESTURE_HOLD_V1_EVENTS.as_ptr(),
};

/// `zwp_pointer_gesture_hold_v1`: a hold gesture object
#[derive(Debug)]
pub(crate) enum ZwpPointerGestureHoldV1 {}

impl ZwpPointerGestureHoldV1 {
    /// The version `zwp_pointer_gesture_hold_v1.destroy` appeared in (`ZWP_POINTER_GESTURE_HOLD_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 3;
    /// The version `zwp_pointer_gesture_hold_v1.begin` appeared in (`ZWP_POINTER_GESTURE_HOLD_V1_BEGIN_SINCE_VERSION`).
    pub(crate) const BEGIN_SINCE_VERSION: u32 = 3;
    /// The version `zwp_pointer_gesture_hold_v1.end` appeared in (`ZWP_POINTER_GESTURE_HOLD_V1_END_SINCE_VERSION`).
    pub(crate) const END_SINCE_VERSION: u32 = 3;
}

/// The events of `zwp_pointer_gesture_hold_v1`.
#[derive(Debug)]
pub(crate) enum ZwpPointerGestureHoldV1Event<'a> {
    /// `zwp_pointer_gesture_hold_v1.begin`: multi-finger hold begin
    Begin {
        serial: u32,
        /// timestamp with millisecond granularity
        time: u32,
        surface: Option<Obj<'a, super::wayland::WlSurface>>,
        /// number of fingers
        fingers: u32,
    },
    /// `zwp_pointer_gesture_hold_v1.end`: multi-finger hold end
    End {
        serial: u32,
        /// timestamp with millisecond granularity
        time: u32,
        /// 1 if the gesture was cancelled, 0 otherwise
        cancelled: i32,
    },
}

impl Interface for ZwpPointerGestureHoldV1 {
    const NAME: &'static str = "zwp_pointer_gesture_hold_v1";
    const VERSION: u32 = 3;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 3));
    type Event<'a> = ZwpPointerGestureHoldV1Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_POINTER_GESTURE_HOLD_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 4 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 4) };
                Some(ZwpPointerGestureHoldV1Event::Begin {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    time: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `object`.
                    surface: unsafe { arg_obj(conn, &a[2]) },
                    // SAFETY: argument 3 is a `uint`.
                    fingers: unsafe { a[3].u },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpPointerGestureHoldV1Event::End {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    time: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `int`.
                    cancelled: unsafe { a[2].i },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_pointer_gesture_hold_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPointerGestureHoldV1Requests:
    AsProxy<Interface = ZwpPointerGestureHoldV1>
{
}

impl<T: AsProxy<Interface = ZwpPointerGestureHoldV1>> ZwpPointerGestureHoldV1Requests for T {}

impl Proxy<ZwpPointerGestureHoldV1> {
    /// `zwp_pointer_gesture_hold_v1.destroy`: destroy the hold gesture object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "3".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
