// Rust bindings of the relative_pointer_unstable_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/relative-pointer-unstable-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2014      Jonas Ådahl
//      Copyright © 2015      Red Hat Inc.
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `relative_pointer_unstable_v1` protocol (`relative-pointer-unstable-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// zwp_relative_pointer_manager_v1
// ---------------------------------------------------------------------------

static ZWP_RELATIVE_POINTER_MANAGER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_RELATIVE_POINTER_MANAGER_V1_GET_RELATIVE_POINTER_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&ZWP_RELATIVE_POINTER_V1_INTERFACE),
    Some(&super::wayland::WL_POINTER_INTERFACE),
];
static ZWP_RELATIVE_POINTER_MANAGER_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_RELATIVE_POINTER_MANAGER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_relative_pointer".as_ptr(),
        signature: c"no".as_ptr(),
        types: ZWP_RELATIVE_POINTER_MANAGER_V1_GET_RELATIVE_POINTER_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_relative_pointer_manager_v1` (`zwp_relative_pointer_manager_v1_interface`).
pub(crate) static ZWP_RELATIVE_POINTER_MANAGER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_relative_pointer_manager_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_RELATIVE_POINTER_MANAGER_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `zwp_relative_pointer_manager_v1`: get relative pointer objects
#[derive(Debug)]
pub(crate) enum ZwpRelativePointerManagerV1 {}

impl ZwpRelativePointerManagerV1 {
    /// The version `zwp_relative_pointer_manager_v1.destroy` appeared in (`ZWP_RELATIVE_POINTER_MANAGER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_relative_pointer_manager_v1.get_relative_pointer` appeared in (`ZWP_RELATIVE_POINTER_MANAGER_V1_GET_RELATIVE_POINTER_SINCE_VERSION`).
    pub(crate) const GET_RELATIVE_POINTER_SINCE_VERSION: u32 = 1;
}

impl Interface for ZwpRelativePointerManagerV1 {
    const NAME: &'static str = "zwp_relative_pointer_manager_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &ZWP_RELATIVE_POINTER_MANAGER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `zwp_relative_pointer_manager_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpRelativePointerManagerV1Requests:
    AsProxy<Interface = ZwpRelativePointerManagerV1>
{
    /// `zwp_relative_pointer_manager_v1.get_relative_pointer`: get a relative pointer object
    fn get_relative_pointer(
        &self,
        pointer: Obj<'_, super::wayland::WlPointer>,
    ) -> Proxy<ZwpRelativePointerV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: pointer.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe {
            proxy.marshal_constructor::<ZwpRelativePointerV1>(1, &mut args, proxy.version(), 0)
        }
    }
}

impl<T: AsProxy<Interface = ZwpRelativePointerManagerV1>> ZwpRelativePointerManagerV1Requests
    for T
{
}

impl Proxy<ZwpRelativePointerManagerV1> {
    /// `zwp_relative_pointer_manager_v1.destroy`: destroy the relative pointer manager object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_relative_pointer_v1
// ---------------------------------------------------------------------------

static ZWP_RELATIVE_POINTER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_RELATIVE_POINTER_V1_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: ZWP_RELATIVE_POINTER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_RELATIVE_POINTER_V1_RELATIVE_MOTION_EVENT_TYPES: [IfacePtr; 6] =
    [None, None, None, None, None, None];
static ZWP_RELATIVE_POINTER_V1_EVENTS: [wl_message; 1] = [wl_message {
    name: c"relative_motion".as_ptr(),
    signature: c"uuffff".as_ptr(),
    types: ZWP_RELATIVE_POINTER_V1_RELATIVE_MOTION_EVENT_TYPES.as_ptr(),
}];
/// The `wl_interface` of `zwp_relative_pointer_v1` (`zwp_relative_pointer_v1_interface`).
pub(crate) static ZWP_RELATIVE_POINTER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_relative_pointer_v1".as_ptr(),
    version: 1,
    method_count: 1,
    methods: ZWP_RELATIVE_POINTER_V1_REQUESTS.as_ptr(),
    event_count: 1,
    events: ZWP_RELATIVE_POINTER_V1_EVENTS.as_ptr(),
};

/// `zwp_relative_pointer_v1`: relative pointer object
#[derive(Debug)]
pub(crate) enum ZwpRelativePointerV1 {}

impl ZwpRelativePointerV1 {
    /// The version `zwp_relative_pointer_v1.destroy` appeared in (`ZWP_RELATIVE_POINTER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_relative_pointer_v1.relative_motion` appeared in (`ZWP_RELATIVE_POINTER_V1_RELATIVE_MOTION_SINCE_VERSION`).
    pub(crate) const RELATIVE_MOTION_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_relative_pointer_v1`.
#[derive(Debug)]
pub(crate) enum ZwpRelativePointerV1Event {
    /// `zwp_relative_pointer_v1.relative_motion`: relative pointer motion
    RelativeMotion {
        /// high 32 bits of a 64 bit timestamp with microsecond granularity
        utime_hi: u32,
        /// low 32 bits of a 64 bit timestamp with microsecond granularity
        utime_lo: u32,
        /// the x component of the motion vector
        dx: Fixed,
        /// the y component of the motion vector
        dy: Fixed,
        /// the x component of the unaccelerated motion vector
        dx_unaccel: Fixed,
        /// the y component of the unaccelerated motion vector
        dy_unaccel: Fixed,
    },
}

impl Interface for ZwpRelativePointerV1 {
    const NAME: &'static str = "zwp_relative_pointer_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = ZwpRelativePointerV1Event;

    fn interface() -> &'static wl_interface {
        &ZWP_RELATIVE_POINTER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 6 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 6) };
                Some(ZwpRelativePointerV1Event::RelativeMotion {
                    // SAFETY: argument 0 is a `uint`.
                    utime_hi: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    utime_lo: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `fixed`.
                    dx: Fixed(unsafe { a[2].f }),
                    // SAFETY: argument 3 is a `fixed`.
                    dy: Fixed(unsafe { a[3].f }),
                    // SAFETY: argument 4 is a `fixed`.
                    dx_unaccel: Fixed(unsafe { a[4].f }),
                    // SAFETY: argument 5 is a `fixed`.
                    dy_unaccel: Fixed(unsafe { a[5].f }),
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_relative_pointer_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpRelativePointerV1Requests:
    AsProxy<Interface = ZwpRelativePointerV1>
{
}

impl<T: AsProxy<Interface = ZwpRelativePointerV1>> ZwpRelativePointerV1Requests for T {}

impl Proxy<ZwpRelativePointerV1> {
    /// `zwp_relative_pointer_v1.destroy`: release the relative pointer object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
