// Rust bindings of the tablet_v2 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/tablet-v2.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright 2014 © Stephen "Lyude" Chandler Paul
//      Copyright 2015-2016 © Red Hat, Inc.
//
//      Permission is hereby granted, free of charge, to any person
//      obtaining a copy of this software and associated documentation files
//      (the "Software"), to deal in the Software without restriction,
//      including without limitation the rights to use, copy, modify, merge,
//      publish, distribute, sublicense, and/or sell copies of the Software,
//      and to permit persons to whom the Software is furnished to do so,
//      subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the
//      next paragraph) shall be included in all copies or substantial
//      portions of the Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
//      NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
//      BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
//      ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//      CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//      SOFTWARE.
//

//! The `tablet_v2` protocol (`tablet-v2.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// zwp_tablet_manager_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_MANAGER_V2_GET_TABLET_SEAT_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&ZWP_TABLET_SEAT_V2_INTERFACE),
    Some(&super::wayland::WL_SEAT_INTERFACE),
];
static ZWP_TABLET_MANAGER_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_MANAGER_V2_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"get_tablet_seat".as_ptr(),
        signature: c"no".as_ptr(),
        types: ZWP_TABLET_MANAGER_V2_GET_TABLET_SEAT_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_MANAGER_V2_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_manager_v2` (`zwp_tablet_manager_v2_interface`).
pub(crate) static ZWP_TABLET_MANAGER_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_manager_v2".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_TABLET_MANAGER_V2_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `zwp_tablet_manager_v2`: controller object for graphic tablet devices
#[derive(Debug)]
pub(crate) enum ZwpTabletManagerV2 {}

impl ZwpTabletManagerV2 {
    /// The version `zwp_tablet_manager_v2.get_tablet_seat` appeared in (`ZWP_TABLET_MANAGER_V2_GET_TABLET_SEAT_SINCE_VERSION`).
    pub(crate) const GET_TABLET_SEAT_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_manager_v2.destroy` appeared in (`ZWP_TABLET_MANAGER_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
}

impl Interface for ZwpTabletManagerV2 {
    const NAME: &'static str = "zwp_tablet_manager_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_MANAGER_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `zwp_tablet_manager_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletManagerV2Requests:
    AsProxy<Interface = ZwpTabletManagerV2>
{
    /// `zwp_tablet_manager_v2.get_tablet_seat`: get the tablet seat
    fn get_tablet_seat(&self, seat: Obj<'_, super::wayland::WlSeat>) -> Proxy<ZwpTabletSeatV2> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: seat.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe { proxy.marshal_constructor::<ZwpTabletSeatV2>(0, &mut args, proxy.version(), 0) }
    }
}

impl<T: AsProxy<Interface = ZwpTabletManagerV2>> ZwpTabletManagerV2Requests for T {}

impl Proxy<ZwpTabletManagerV2> {
    /// `zwp_tablet_manager_v2.destroy`: release the memory for the tablet manager object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_seat_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_SEAT_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_SEAT_V2_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: ZWP_TABLET_SEAT_V2_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_TABLET_SEAT_V2_TABLET_ADDED_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_TABLET_V2_INTERFACE)];
static ZWP_TABLET_SEAT_V2_TOOL_ADDED_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_TABLET_TOOL_V2_INTERFACE)];
static ZWP_TABLET_SEAT_V2_PAD_ADDED_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_TABLET_PAD_V2_INTERFACE)];
static ZWP_TABLET_SEAT_V2_EVENTS: [wl_message; 3] = [
    wl_message {
        name: c"tablet_added".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_TABLET_SEAT_V2_TABLET_ADDED_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"tool_added".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_TABLET_SEAT_V2_TOOL_ADDED_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"pad_added".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_TABLET_SEAT_V2_PAD_ADDED_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_seat_v2` (`zwp_tablet_seat_v2_interface`).
pub(crate) static ZWP_TABLET_SEAT_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_seat_v2".as_ptr(),
    version: 1,
    method_count: 1,
    methods: ZWP_TABLET_SEAT_V2_REQUESTS.as_ptr(),
    event_count: 3,
    events: ZWP_TABLET_SEAT_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_seat_v2`: controller object for graphic tablet devices of a seat
#[derive(Debug)]
pub(crate) enum ZwpTabletSeatV2 {}

impl ZwpTabletSeatV2 {
    /// The version `zwp_tablet_seat_v2.destroy` appeared in (`ZWP_TABLET_SEAT_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_seat_v2.tablet_added` appeared in (`ZWP_TABLET_SEAT_V2_TABLET_ADDED_SINCE_VERSION`).
    pub(crate) const TABLET_ADDED_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_seat_v2.tool_added` appeared in (`ZWP_TABLET_SEAT_V2_TOOL_ADDED_SINCE_VERSION`).
    pub(crate) const TOOL_ADDED_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_seat_v2.pad_added` appeared in (`ZWP_TABLET_SEAT_V2_PAD_ADDED_SINCE_VERSION`).
    pub(crate) const PAD_ADDED_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_seat_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletSeatV2Event {
    /// `zwp_tablet_seat_v2.tablet_added`: new device notification
    TabletAdded {
        /// the newly added graphics tablet
        id: Proxy<ZwpTabletV2>,
    },
    /// `zwp_tablet_seat_v2.tool_added`: a new tool has been used with a tablet
    ToolAdded {
        /// the newly added tablet tool
        id: Proxy<ZwpTabletToolV2>,
    },
    /// `zwp_tablet_seat_v2.pad_added`: new pad notification
    PadAdded {
        /// the newly added pad
        id: Proxy<ZwpTabletPadV2>,
    },
}

impl Interface for ZwpTabletSeatV2 {
    const NAME: &'static str = "zwp_tablet_seat_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = ZwpTabletSeatV2Event;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_SEAT_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletSeatV2Event::TabletAdded {
                    // SAFETY: argument 0 is a `new_id`.
                    id: unsafe { arg_new(conn, &a[0])? },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletSeatV2Event::ToolAdded {
                    // SAFETY: argument 0 is a `new_id`.
                    id: unsafe { arg_new(conn, &a[0])? },
                })
            }
            2 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletSeatV2Event::PadAdded {
                    // SAFETY: argument 0 is a `new_id`.
                    id: unsafe { arg_new(conn, &a[0])? },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_seat_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletSeatV2Requests: AsProxy<Interface = ZwpTabletSeatV2> {}

impl<T: AsProxy<Interface = ZwpTabletSeatV2>> ZwpTabletSeatV2Requests for T {}

impl Proxy<ZwpTabletSeatV2> {
    /// `zwp_tablet_seat_v2.destroy`: release the memory for the tablet seat object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_tool_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_TOOL_V2_SET_CURSOR_REQUEST_TYPES: [IfacePtr; 4] = [
    None,
    Some(&super::wayland::WL_SURFACE_INTERFACE),
    None,
    None,
];
static ZWP_TABLET_TOOL_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_TOOL_V2_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"set_cursor".as_ptr(),
        signature: c"u?oii".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_SET_CURSOR_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_TABLET_TOOL_V2_TYPE_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_HARDWARE_SERIAL_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_TOOL_V2_HARDWARE_ID_WACOM_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_TOOL_V2_CAPABILITY_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_DONE_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_TOOL_V2_REMOVED_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_TOOL_V2_PROXIMITY_IN_EVENT_TYPES: [IfacePtr; 3] = [
    None,
    Some(&ZWP_TABLET_V2_INTERFACE),
    Some(&super::wayland::WL_SURFACE_INTERFACE),
];
static ZWP_TABLET_TOOL_V2_PROXIMITY_OUT_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_TOOL_V2_DOWN_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_UP_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_TOOL_V2_MOTION_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_TOOL_V2_PRESSURE_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_DISTANCE_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_TILT_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_TOOL_V2_ROTATION_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_SLIDER_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_WHEEL_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_TOOL_V2_BUTTON_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_TABLET_TOOL_V2_FRAME_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_TOOL_V2_EVENTS: [wl_message; 19] = [
    wl_message {
        name: c"type".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_TYPE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"hardware_serial".as_ptr(),
        signature: c"uu".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_HARDWARE_SERIAL_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"hardware_id_wacom".as_ptr(),
        signature: c"uu".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_HARDWARE_ID_WACOM_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"capability".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_CAPABILITY_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"done".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_DONE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"removed".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_REMOVED_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"proximity_in".as_ptr(),
        signature: c"uoo".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_PROXIMITY_IN_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"proximity_out".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_PROXIMITY_OUT_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"down".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_DOWN_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"up".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_UP_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"motion".as_ptr(),
        signature: c"ff".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_MOTION_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"pressure".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_PRESSURE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"distance".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_DISTANCE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"tilt".as_ptr(),
        signature: c"ff".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_TILT_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"rotation".as_ptr(),
        signature: c"f".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_ROTATION_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"slider".as_ptr(),
        signature: c"i".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_SLIDER_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"wheel".as_ptr(),
        signature: c"fi".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_WHEEL_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"button".as_ptr(),
        signature: c"uuu".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_BUTTON_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"frame".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_TOOL_V2_FRAME_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_tool_v2` (`zwp_tablet_tool_v2_interface`).
pub(crate) static ZWP_TABLET_TOOL_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_tool_v2".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_TABLET_TOOL_V2_REQUESTS.as_ptr(),
    event_count: 19,
    events: ZWP_TABLET_TOOL_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_tool_v2.type`: a physical tool type
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletToolV2Type(pub(crate) u32);

impl ZwpTabletToolV2Type {
    /// Pen
    pub(crate) const PEN: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x140);
    /// Eraser
    pub(crate) const ERASER: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x141);
    /// Brush
    pub(crate) const BRUSH: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x142);
    /// Pencil
    pub(crate) const PENCIL: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x143);
    /// Airbrush
    pub(crate) const AIRBRUSH: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x144);
    /// Finger
    pub(crate) const FINGER: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x145);
    /// Mouse
    pub(crate) const MOUSE: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x146);
    /// Lens
    pub(crate) const LENS: ZwpTabletToolV2Type = ZwpTabletToolV2Type(0x147);
}

/// `zwp_tablet_tool_v2.capability`: capability flags for a tool
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletToolV2Capability(pub(crate) u32);

impl ZwpTabletToolV2Capability {
    /// Tilt axes
    pub(crate) const TILT: ZwpTabletToolV2Capability = ZwpTabletToolV2Capability(1);
    /// Pressure axis
    pub(crate) const PRESSURE: ZwpTabletToolV2Capability = ZwpTabletToolV2Capability(2);
    /// Distance axis
    pub(crate) const DISTANCE: ZwpTabletToolV2Capability = ZwpTabletToolV2Capability(3);
    /// Z-rotation axis
    pub(crate) const ROTATION: ZwpTabletToolV2Capability = ZwpTabletToolV2Capability(4);
    /// Slider axis
    pub(crate) const SLIDER: ZwpTabletToolV2Capability = ZwpTabletToolV2Capability(5);
    /// Wheel axis
    pub(crate) const WHEEL: ZwpTabletToolV2Capability = ZwpTabletToolV2Capability(6);
}

/// `zwp_tablet_tool_v2.button_state`: physical button state
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletToolV2ButtonState(pub(crate) u32);

impl ZwpTabletToolV2ButtonState {
    /// button is not pressed
    pub(crate) const RELEASED: ZwpTabletToolV2ButtonState = ZwpTabletToolV2ButtonState(0);
    /// button is pressed
    pub(crate) const PRESSED: ZwpTabletToolV2ButtonState = ZwpTabletToolV2ButtonState(1);
}

/// `zwp_tablet_tool_v2.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletToolV2Error(pub(crate) u32);

impl ZwpTabletToolV2Error {
    /// given wl_surface has another role
    pub(crate) const ROLE: ZwpTabletToolV2Error = ZwpTabletToolV2Error(0);
}

/// `zwp_tablet_tool_v2`: a physical tablet tool
#[derive(Debug)]
pub(crate) enum ZwpTabletToolV2 {}

impl ZwpTabletToolV2 {
    /// The version `zwp_tablet_tool_v2.set_cursor` appeared in (`ZWP_TABLET_TOOL_V2_SET_CURSOR_SINCE_VERSION`).
    pub(crate) const SET_CURSOR_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.destroy` appeared in (`ZWP_TABLET_TOOL_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.type` appeared in (`ZWP_TABLET_TOOL_V2_TYPE_SINCE_VERSION`).
    pub(crate) const TYPE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.hardware_serial` appeared in (`ZWP_TABLET_TOOL_V2_HARDWARE_SERIAL_SINCE_VERSION`).
    pub(crate) const HARDWARE_SERIAL_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.hardware_id_wacom` appeared in (`ZWP_TABLET_TOOL_V2_HARDWARE_ID_WACOM_SINCE_VERSION`).
    pub(crate) const HARDWARE_ID_WACOM_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.capability` appeared in (`ZWP_TABLET_TOOL_V2_CAPABILITY_SINCE_VERSION`).
    pub(crate) const CAPABILITY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.done` appeared in (`ZWP_TABLET_TOOL_V2_DONE_SINCE_VERSION`).
    pub(crate) const DONE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.removed` appeared in (`ZWP_TABLET_TOOL_V2_REMOVED_SINCE_VERSION`).
    pub(crate) const REMOVED_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.proximity_in` appeared in (`ZWP_TABLET_TOOL_V2_PROXIMITY_IN_SINCE_VERSION`).
    pub(crate) const PROXIMITY_IN_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.proximity_out` appeared in (`ZWP_TABLET_TOOL_V2_PROXIMITY_OUT_SINCE_VERSION`).
    pub(crate) const PROXIMITY_OUT_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.down` appeared in (`ZWP_TABLET_TOOL_V2_DOWN_SINCE_VERSION`).
    pub(crate) const DOWN_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.up` appeared in (`ZWP_TABLET_TOOL_V2_UP_SINCE_VERSION`).
    pub(crate) const UP_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.motion` appeared in (`ZWP_TABLET_TOOL_V2_MOTION_SINCE_VERSION`).
    pub(crate) const MOTION_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.pressure` appeared in (`ZWP_TABLET_TOOL_V2_PRESSURE_SINCE_VERSION`).
    pub(crate) const PRESSURE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.distance` appeared in (`ZWP_TABLET_TOOL_V2_DISTANCE_SINCE_VERSION`).
    pub(crate) const DISTANCE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.tilt` appeared in (`ZWP_TABLET_TOOL_V2_TILT_SINCE_VERSION`).
    pub(crate) const TILT_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.rotation` appeared in (`ZWP_TABLET_TOOL_V2_ROTATION_SINCE_VERSION`).
    pub(crate) const ROTATION_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.slider` appeared in (`ZWP_TABLET_TOOL_V2_SLIDER_SINCE_VERSION`).
    pub(crate) const SLIDER_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.wheel` appeared in (`ZWP_TABLET_TOOL_V2_WHEEL_SINCE_VERSION`).
    pub(crate) const WHEEL_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.button` appeared in (`ZWP_TABLET_TOOL_V2_BUTTON_SINCE_VERSION`).
    pub(crate) const BUTTON_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_tool_v2.frame` appeared in (`ZWP_TABLET_TOOL_V2_FRAME_SINCE_VERSION`).
    pub(crate) const FRAME_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_tool_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletToolV2Event<'a> {
    /// `zwp_tablet_tool_v2.type`: tool type
    Type {
        /// the physical tool type
        tool_type: ZwpTabletToolV2Type,
    },
    /// `zwp_tablet_tool_v2.hardware_serial`: unique hardware serial number of the tool
    HardwareSerial {
        /// the unique serial number of the tool, most significant bits
        hardware_serial_hi: u32,
        /// the unique serial number of the tool, least significant bits
        hardware_serial_lo: u32,
    },
    /// `zwp_tablet_tool_v2.hardware_id_wacom`: hardware id notification in Wacom's format
    HardwareIdWacom {
        /// the hardware id, most significant bits
        hardware_id_hi: u32,
        /// the hardware id, least significant bits
        hardware_id_lo: u32,
    },
    /// `zwp_tablet_tool_v2.capability`: tool capability notification
    Capability {
        /// the capability
        capability: ZwpTabletToolV2Capability,
    },
    /// `zwp_tablet_tool_v2.done`: tool description events sequence complete
    Done,
    /// `zwp_tablet_tool_v2.removed`: tool removed
    Removed,
    /// `zwp_tablet_tool_v2.proximity_in`: proximity in event
    ProximityIn {
        serial: u32,
        /// The tablet the tool is in proximity of
        tablet: Option<Obj<'a, ZwpTabletV2>>,
        /// The current surface the tablet tool is over
        surface: Option<Obj<'a, super::wayland::WlSurface>>,
    },
    /// `zwp_tablet_tool_v2.proximity_out`: proximity out event
    ProximityOut,
    /// `zwp_tablet_tool_v2.down`: tablet tool is making contact
    Down { serial: u32 },
    /// `zwp_tablet_tool_v2.up`: tablet tool is no longer making contact
    Up,
    /// `zwp_tablet_tool_v2.motion`: motion event
    Motion {
        /// surface-local x coordinate
        x: Fixed,
        /// surface-local y coordinate
        y: Fixed,
    },
    /// `zwp_tablet_tool_v2.pressure`: pressure change event
    Pressure {
        /// The current pressure value
        pressure: u32,
    },
    /// `zwp_tablet_tool_v2.distance`: distance change event
    Distance {
        /// The current distance value
        distance: u32,
    },
    /// `zwp_tablet_tool_v2.tilt`: tilt change event
    Tilt {
        /// The current value of the X tilt axis
        tilt_x: Fixed,
        /// The current value of the Y tilt axis
        tilt_y: Fixed,
    },
    /// `zwp_tablet_tool_v2.rotation`: z-rotation change event
    Rotation {
        /// The current rotation of the Z axis
        degrees: Fixed,
    },
    /// `zwp_tablet_tool_v2.slider`: Slider position change event
    Slider {
        /// The current position of slider
        position: i32,
    },
    /// `zwp_tablet_tool_v2.wheel`: Wheel delta event
    Wheel {
        /// The wheel delta in degrees
        degrees: Fixed,
        /// The wheel delta in discrete clicks
        clicks: i32,
    },
    /// `zwp_tablet_tool_v2.button`: button event
    Button {
        serial: u32,
        /// The button whose state has changed
        button: u32,
        /// Whether the button was pressed or released
        state: ZwpTabletToolV2ButtonState,
    },
    /// `zwp_tablet_tool_v2.frame`: frame event
    Frame {
        /// The time of the event with millisecond granularity
        time: u32,
    },
}

impl Interface for ZwpTabletToolV2 {
    const NAME: &'static str = "zwp_tablet_tool_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpTabletToolV2Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_TOOL_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Type {
                    // SAFETY: argument 0 is a `uint`.
                    tool_type: ZwpTabletToolV2Type(unsafe { a[0].u }),
                })
            }
            1 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletToolV2Event::HardwareSerial {
                    // SAFETY: argument 0 is a `uint`.
                    hardware_serial_hi: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    hardware_serial_lo: unsafe { a[1].u },
                })
            }
            2 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletToolV2Event::HardwareIdWacom {
                    // SAFETY: argument 0 is a `uint`.
                    hardware_id_hi: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    hardware_id_lo: unsafe { a[1].u },
                })
            }
            3 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Capability {
                    // SAFETY: argument 0 is a `uint`.
                    capability: ZwpTabletToolV2Capability(unsafe { a[0].u }),
                })
            }
            4 => Some(ZwpTabletToolV2Event::Done),
            5 => Some(ZwpTabletToolV2Event::Removed),
            6 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpTabletToolV2Event::ProximityIn {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `object`.
                    tablet: unsafe { arg_obj(conn, &a[1]) },
                    // SAFETY: argument 2 is a `object`.
                    surface: unsafe { arg_obj(conn, &a[2]) },
                })
            }
            7 => Some(ZwpTabletToolV2Event::ProximityOut),
            8 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Down {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                })
            }
            9 => Some(ZwpTabletToolV2Event::Up),
            10 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletToolV2Event::Motion {
                    // SAFETY: argument 0 is a `fixed`.
                    x: Fixed(unsafe { a[0].f }),
                    // SAFETY: argument 1 is a `fixed`.
                    y: Fixed(unsafe { a[1].f }),
                })
            }
            11 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Pressure {
                    // SAFETY: argument 0 is a `uint`.
                    pressure: unsafe { a[0].u },
                })
            }
            12 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Distance {
                    // SAFETY: argument 0 is a `uint`.
                    distance: unsafe { a[0].u },
                })
            }
            13 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletToolV2Event::Tilt {
                    // SAFETY: argument 0 is a `fixed`.
                    tilt_x: Fixed(unsafe { a[0].f }),
                    // SAFETY: argument 1 is a `fixed`.
                    tilt_y: Fixed(unsafe { a[1].f }),
                })
            }
            14 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Rotation {
                    // SAFETY: argument 0 is a `fixed`.
                    degrees: Fixed(unsafe { a[0].f }),
                })
            }
            15 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Slider {
                    // SAFETY: argument 0 is a `int`.
                    position: unsafe { a[0].i },
                })
            }
            16 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletToolV2Event::Wheel {
                    // SAFETY: argument 0 is a `fixed`.
                    degrees: Fixed(unsafe { a[0].f }),
                    // SAFETY: argument 1 is a `int`.
                    clicks: unsafe { a[1].i },
                })
            }
            17 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpTabletToolV2Event::Button {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    button: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `uint`.
                    state: ZwpTabletToolV2ButtonState(unsafe { a[2].u }),
                })
            }
            18 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletToolV2Event::Frame {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_tool_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletToolV2Requests: AsProxy<Interface = ZwpTabletToolV2> {
    /// `zwp_tablet_tool_v2.set_cursor`: set the tablet tool's surface
    fn set_cursor(
        &self,
        serial: u32,
        surface: Option<Obj<'_, super::wayland::WlSurface>>,
        hotspot_x: i32,
        hotspot_y: i32,
    ) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { u: serial },
            wl_argument {
                o: surface.map_or(ptr::null_mut(), |o| o.raw()),
            },
            wl_argument { i: hotspot_x },
            wl_argument { i: hotspot_y },
        ];
        // SAFETY: the arguments match the request's signature, "u?oii".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpTabletToolV2>> ZwpTabletToolV2Requests for T {}

impl Proxy<ZwpTabletToolV2> {
    /// `zwp_tablet_tool_v2.destroy`: destroy the tool object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_V2_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: ZWP_TABLET_V2_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_TABLET_V2_NAME_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_V2_ID_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_V2_PATH_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_V2_DONE_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_V2_REMOVED_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_V2_EVENTS: [wl_message; 5] = [
    wl_message {
        name: c"name".as_ptr(),
        signature: c"s".as_ptr(),
        types: ZWP_TABLET_V2_NAME_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"id".as_ptr(),
        signature: c"uu".as_ptr(),
        types: ZWP_TABLET_V2_ID_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"path".as_ptr(),
        signature: c"s".as_ptr(),
        types: ZWP_TABLET_V2_PATH_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"done".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_V2_DONE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"removed".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_V2_REMOVED_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_v2` (`zwp_tablet_v2_interface`).
pub(crate) static ZWP_TABLET_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_v2".as_ptr(),
    version: 1,
    method_count: 1,
    methods: ZWP_TABLET_V2_REQUESTS.as_ptr(),
    event_count: 5,
    events: ZWP_TABLET_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_v2`: graphics tablet device
#[derive(Debug)]
pub(crate) enum ZwpTabletV2 {}

impl ZwpTabletV2 {
    /// The version `zwp_tablet_v2.destroy` appeared in (`ZWP_TABLET_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_v2.name` appeared in (`ZWP_TABLET_V2_NAME_SINCE_VERSION`).
    pub(crate) const NAME_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_v2.id` appeared in (`ZWP_TABLET_V2_ID_SINCE_VERSION`).
    pub(crate) const ID_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_v2.path` appeared in (`ZWP_TABLET_V2_PATH_SINCE_VERSION`).
    pub(crate) const PATH_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_v2.done` appeared in (`ZWP_TABLET_V2_DONE_SINCE_VERSION`).
    pub(crate) const DONE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_v2.removed` appeared in (`ZWP_TABLET_V2_REMOVED_SINCE_VERSION`).
    pub(crate) const REMOVED_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletV2Event<'a> {
    /// `zwp_tablet_v2.name`: tablet device name
    Name {
        /// the device name
        name: &'a CStr,
    },
    /// `zwp_tablet_v2.id`: tablet device USB vendor/product id
    Id {
        /// USB vendor id
        vid: u32,
        /// USB product id
        pid: u32,
    },
    /// `zwp_tablet_v2.path`: path to the device
    Path {
        /// path to local device
        path: &'a CStr,
    },
    /// `zwp_tablet_v2.done`: tablet description events sequence complete
    Done,
    /// `zwp_tablet_v2.removed`: tablet removed event
    Removed,
}

impl Interface for ZwpTabletV2 {
    const NAME: &'static str = "zwp_tablet_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = ZwpTabletV2Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletV2Event::Name {
                    // SAFETY: argument 0 is a `string`.
                    name: unsafe { arg_str(&a[0]) }.unwrap_or_default(),
                })
            }
            1 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletV2Event::Id {
                    // SAFETY: argument 0 is a `uint`.
                    vid: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    pid: unsafe { a[1].u },
                })
            }
            2 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletV2Event::Path {
                    // SAFETY: argument 0 is a `string`.
                    path: unsafe { arg_str(&a[0]) }.unwrap_or_default(),
                })
            }
            3 => Some(ZwpTabletV2Event::Done),
            4 => Some(ZwpTabletV2Event::Removed),
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletV2Requests: AsProxy<Interface = ZwpTabletV2> {}

impl<T: AsProxy<Interface = ZwpTabletV2>> ZwpTabletV2Requests for T {}

impl Proxy<ZwpTabletV2> {
    /// `zwp_tablet_v2.destroy`: destroy the tablet object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_pad_ring_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_PAD_RING_V2_SET_FEEDBACK_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_PAD_RING_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_RING_V2_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"set_feedback".as_ptr(),
        signature: c"su".as_ptr(),
        types: ZWP_TABLET_PAD_RING_V2_SET_FEEDBACK_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_RING_V2_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_TABLET_PAD_RING_V2_SOURCE_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_RING_V2_ANGLE_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_RING_V2_STOP_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_RING_V2_FRAME_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_RING_V2_EVENTS: [wl_message; 4] = [
    wl_message {
        name: c"source".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_RING_V2_SOURCE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"angle".as_ptr(),
        signature: c"f".as_ptr(),
        types: ZWP_TABLET_PAD_RING_V2_ANGLE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"stop".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_RING_V2_STOP_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"frame".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_RING_V2_FRAME_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_pad_ring_v2` (`zwp_tablet_pad_ring_v2_interface`).
pub(crate) static ZWP_TABLET_PAD_RING_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_pad_ring_v2".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_TABLET_PAD_RING_V2_REQUESTS.as_ptr(),
    event_count: 4,
    events: ZWP_TABLET_PAD_RING_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_pad_ring_v2.source`: ring axis source
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletPadRingV2Source(pub(crate) u32);

impl ZwpTabletPadRingV2Source {
    /// finger
    pub(crate) const FINGER: ZwpTabletPadRingV2Source = ZwpTabletPadRingV2Source(1);
}

/// `zwp_tablet_pad_ring_v2`: pad ring
#[derive(Debug)]
pub(crate) enum ZwpTabletPadRingV2 {}

impl ZwpTabletPadRingV2 {
    /// The version `zwp_tablet_pad_ring_v2.set_feedback` appeared in (`ZWP_TABLET_PAD_RING_V2_SET_FEEDBACK_SINCE_VERSION`).
    pub(crate) const SET_FEEDBACK_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_ring_v2.destroy` appeared in (`ZWP_TABLET_PAD_RING_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_ring_v2.source` appeared in (`ZWP_TABLET_PAD_RING_V2_SOURCE_SINCE_VERSION`).
    pub(crate) const SOURCE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_ring_v2.angle` appeared in (`ZWP_TABLET_PAD_RING_V2_ANGLE_SINCE_VERSION`).
    pub(crate) const ANGLE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_ring_v2.stop` appeared in (`ZWP_TABLET_PAD_RING_V2_STOP_SINCE_VERSION`).
    pub(crate) const STOP_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_ring_v2.frame` appeared in (`ZWP_TABLET_PAD_RING_V2_FRAME_SINCE_VERSION`).
    pub(crate) const FRAME_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_pad_ring_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletPadRingV2Event {
    /// `zwp_tablet_pad_ring_v2.source`: ring event source
    Source {
        /// the event source
        source: ZwpTabletPadRingV2Source,
    },
    /// `zwp_tablet_pad_ring_v2.angle`: angle changed
    Angle {
        /// the current angle in degrees
        degrees: Fixed,
    },
    /// `zwp_tablet_pad_ring_v2.stop`: interaction stopped
    Stop,
    /// `zwp_tablet_pad_ring_v2.frame`: end of a ring event sequence
    Frame {
        /// timestamp with millisecond granularity
        time: u32,
    },
}

impl Interface for ZwpTabletPadRingV2 {
    const NAME: &'static str = "zwp_tablet_pad_ring_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpTabletPadRingV2Event;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_PAD_RING_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadRingV2Event::Source {
                    // SAFETY: argument 0 is a `uint`.
                    source: ZwpTabletPadRingV2Source(unsafe { a[0].u }),
                })
            }
            1 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadRingV2Event::Angle {
                    // SAFETY: argument 0 is a `fixed`.
                    degrees: Fixed(unsafe { a[0].f }),
                })
            }
            2 => Some(ZwpTabletPadRingV2Event::Stop),
            3 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadRingV2Event::Frame {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_pad_ring_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletPadRingV2Requests:
    AsProxy<Interface = ZwpTabletPadRingV2>
{
    /// `zwp_tablet_pad_ring_v2.set_feedback`: set compositor feedback
    fn set_feedback(&self, description: &str, serial: u32) {
        let proxy = self.obj();
        let c_description = cstring_arg(description);
        let mut args = [
            wl_argument {
                s: c_description.as_ptr(),
            },
            wl_argument { u: serial },
        ];
        // SAFETY: the arguments match the request's signature, "su".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpTabletPadRingV2>> ZwpTabletPadRingV2Requests for T {}

impl Proxy<ZwpTabletPadRingV2> {
    /// `zwp_tablet_pad_ring_v2.destroy`: destroy the ring object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_pad_strip_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_PAD_STRIP_V2_SET_FEEDBACK_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_TABLET_PAD_STRIP_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_STRIP_V2_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"set_feedback".as_ptr(),
        signature: c"su".as_ptr(),
        types: ZWP_TABLET_PAD_STRIP_V2_SET_FEEDBACK_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_STRIP_V2_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_TABLET_PAD_STRIP_V2_SOURCE_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_STRIP_V2_POSITION_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_STRIP_V2_STOP_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_STRIP_V2_FRAME_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_STRIP_V2_EVENTS: [wl_message; 4] = [
    wl_message {
        name: c"source".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_STRIP_V2_SOURCE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"position".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_STRIP_V2_POSITION_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"stop".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_STRIP_V2_STOP_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"frame".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_STRIP_V2_FRAME_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_pad_strip_v2` (`zwp_tablet_pad_strip_v2_interface`).
pub(crate) static ZWP_TABLET_PAD_STRIP_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_pad_strip_v2".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_TABLET_PAD_STRIP_V2_REQUESTS.as_ptr(),
    event_count: 4,
    events: ZWP_TABLET_PAD_STRIP_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_pad_strip_v2.source`: strip axis source
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletPadStripV2Source(pub(crate) u32);

impl ZwpTabletPadStripV2Source {
    /// finger
    pub(crate) const FINGER: ZwpTabletPadStripV2Source = ZwpTabletPadStripV2Source(1);
}

/// `zwp_tablet_pad_strip_v2`: pad strip
#[derive(Debug)]
pub(crate) enum ZwpTabletPadStripV2 {}

impl ZwpTabletPadStripV2 {
    /// The version `zwp_tablet_pad_strip_v2.set_feedback` appeared in (`ZWP_TABLET_PAD_STRIP_V2_SET_FEEDBACK_SINCE_VERSION`).
    pub(crate) const SET_FEEDBACK_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_strip_v2.destroy` appeared in (`ZWP_TABLET_PAD_STRIP_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_strip_v2.source` appeared in (`ZWP_TABLET_PAD_STRIP_V2_SOURCE_SINCE_VERSION`).
    pub(crate) const SOURCE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_strip_v2.position` appeared in (`ZWP_TABLET_PAD_STRIP_V2_POSITION_SINCE_VERSION`).
    pub(crate) const POSITION_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_strip_v2.stop` appeared in (`ZWP_TABLET_PAD_STRIP_V2_STOP_SINCE_VERSION`).
    pub(crate) const STOP_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_strip_v2.frame` appeared in (`ZWP_TABLET_PAD_STRIP_V2_FRAME_SINCE_VERSION`).
    pub(crate) const FRAME_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_pad_strip_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletPadStripV2Event {
    /// `zwp_tablet_pad_strip_v2.source`: strip event source
    Source {
        /// the event source
        source: ZwpTabletPadStripV2Source,
    },
    /// `zwp_tablet_pad_strip_v2.position`: position changed
    Position {
        /// the current position
        position: u32,
    },
    /// `zwp_tablet_pad_strip_v2.stop`: interaction stopped
    Stop,
    /// `zwp_tablet_pad_strip_v2.frame`: end of a strip event sequence
    Frame {
        /// timestamp with millisecond granularity
        time: u32,
    },
}

impl Interface for ZwpTabletPadStripV2 {
    const NAME: &'static str = "zwp_tablet_pad_strip_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpTabletPadStripV2Event;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_PAD_STRIP_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadStripV2Event::Source {
                    // SAFETY: argument 0 is a `uint`.
                    source: ZwpTabletPadStripV2Source(unsafe { a[0].u }),
                })
            }
            1 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadStripV2Event::Position {
                    // SAFETY: argument 0 is a `uint`.
                    position: unsafe { a[0].u },
                })
            }
            2 => Some(ZwpTabletPadStripV2Event::Stop),
            3 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadStripV2Event::Frame {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_pad_strip_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletPadStripV2Requests:
    AsProxy<Interface = ZwpTabletPadStripV2>
{
    /// `zwp_tablet_pad_strip_v2.set_feedback`: set compositor feedback
    fn set_feedback(&self, description: &str, serial: u32) {
        let proxy = self.obj();
        let c_description = cstring_arg(description);
        let mut args = [
            wl_argument {
                s: c_description.as_ptr(),
            },
            wl_argument { u: serial },
        ];
        // SAFETY: the arguments match the request's signature, "su".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpTabletPadStripV2>> ZwpTabletPadStripV2Requests for T {}

impl Proxy<ZwpTabletPadStripV2> {
    /// `zwp_tablet_pad_strip_v2.destroy`: destroy the strip object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_pad_group_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_PAD_GROUP_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_GROUP_V2_REQUESTS: [wl_message; 1] = [wl_message {
    name: c"destroy".as_ptr(),
    signature: c"".as_ptr(),
    types: ZWP_TABLET_PAD_GROUP_V2_DESTROY_REQUEST_TYPES.as_ptr(),
}];
static ZWP_TABLET_PAD_GROUP_V2_BUTTONS_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_GROUP_V2_RING_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_TABLET_PAD_RING_V2_INTERFACE)];
static ZWP_TABLET_PAD_GROUP_V2_STRIP_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_TABLET_PAD_STRIP_V2_INTERFACE)];
static ZWP_TABLET_PAD_GROUP_V2_MODES_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_GROUP_V2_DONE_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_GROUP_V2_MODE_SWITCH_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_TABLET_PAD_GROUP_V2_EVENTS: [wl_message; 6] = [
    wl_message {
        name: c"buttons".as_ptr(),
        signature: c"a".as_ptr(),
        types: ZWP_TABLET_PAD_GROUP_V2_BUTTONS_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"ring".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_TABLET_PAD_GROUP_V2_RING_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"strip".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_TABLET_PAD_GROUP_V2_STRIP_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"modes".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_GROUP_V2_MODES_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"done".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_GROUP_V2_DONE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"mode_switch".as_ptr(),
        signature: c"uuu".as_ptr(),
        types: ZWP_TABLET_PAD_GROUP_V2_MODE_SWITCH_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_pad_group_v2` (`zwp_tablet_pad_group_v2_interface`).
pub(crate) static ZWP_TABLET_PAD_GROUP_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_pad_group_v2".as_ptr(),
    version: 1,
    method_count: 1,
    methods: ZWP_TABLET_PAD_GROUP_V2_REQUESTS.as_ptr(),
    event_count: 6,
    events: ZWP_TABLET_PAD_GROUP_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_pad_group_v2`: a set of buttons, rings and strips
#[derive(Debug)]
pub(crate) enum ZwpTabletPadGroupV2 {}

impl ZwpTabletPadGroupV2 {
    /// The version `zwp_tablet_pad_group_v2.destroy` appeared in (`ZWP_TABLET_PAD_GROUP_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_group_v2.buttons` appeared in (`ZWP_TABLET_PAD_GROUP_V2_BUTTONS_SINCE_VERSION`).
    pub(crate) const BUTTONS_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_group_v2.ring` appeared in (`ZWP_TABLET_PAD_GROUP_V2_RING_SINCE_VERSION`).
    pub(crate) const RING_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_group_v2.strip` appeared in (`ZWP_TABLET_PAD_GROUP_V2_STRIP_SINCE_VERSION`).
    pub(crate) const STRIP_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_group_v2.modes` appeared in (`ZWP_TABLET_PAD_GROUP_V2_MODES_SINCE_VERSION`).
    pub(crate) const MODES_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_group_v2.done` appeared in (`ZWP_TABLET_PAD_GROUP_V2_DONE_SINCE_VERSION`).
    pub(crate) const DONE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_group_v2.mode_switch` appeared in (`ZWP_TABLET_PAD_GROUP_V2_MODE_SWITCH_SINCE_VERSION`).
    pub(crate) const MODE_SWITCH_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_pad_group_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletPadGroupV2Event<'a> {
    /// `zwp_tablet_pad_group_v2.buttons`: buttons announced
    Buttons {
        /// buttons in this group
        buttons: &'a [u8],
    },
    /// `zwp_tablet_pad_group_v2.ring`: ring announced
    Ring { ring: Proxy<ZwpTabletPadRingV2> },
    /// `zwp_tablet_pad_group_v2.strip`: strip announced
    Strip { strip: Proxy<ZwpTabletPadStripV2> },
    /// `zwp_tablet_pad_group_v2.modes`: mode-switch ability announced
    Modes {
        /// the number of modes
        modes: u32,
    },
    /// `zwp_tablet_pad_group_v2.done`: tablet group description events sequence complete
    Done,
    /// `zwp_tablet_pad_group_v2.mode_switch`: mode switch event
    ModeSwitch {
        /// the time of the event with millisecond granularity
        time: u32,
        serial: u32,
        /// the new mode of the pad
        mode: u32,
    },
}

impl Interface for ZwpTabletPadGroupV2 {
    const NAME: &'static str = "zwp_tablet_pad_group_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = ZwpTabletPadGroupV2Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_PAD_GROUP_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadGroupV2Event::Buttons {
                    // SAFETY: argument 0 is a `array`.
                    buttons: unsafe { arg_array(&a[0]) },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadGroupV2Event::Ring {
                    // SAFETY: argument 0 is a `new_id`.
                    ring: unsafe { arg_new(conn, &a[0])? },
                })
            }
            2 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadGroupV2Event::Strip {
                    // SAFETY: argument 0 is a `new_id`.
                    strip: unsafe { arg_new(conn, &a[0])? },
                })
            }
            3 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadGroupV2Event::Modes {
                    // SAFETY: argument 0 is a `uint`.
                    modes: unsafe { a[0].u },
                })
            }
            4 => Some(ZwpTabletPadGroupV2Event::Done),
            5 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpTabletPadGroupV2Event::ModeSwitch {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    serial: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `uint`.
                    mode: unsafe { a[2].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_pad_group_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletPadGroupV2Requests:
    AsProxy<Interface = ZwpTabletPadGroupV2>
{
}

impl<T: AsProxy<Interface = ZwpTabletPadGroupV2>> ZwpTabletPadGroupV2Requests for T {}

impl Proxy<ZwpTabletPadGroupV2> {
    /// `zwp_tablet_pad_group_v2.destroy`: destroy the pad object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_tablet_pad_v2
// ---------------------------------------------------------------------------

static ZWP_TABLET_PAD_V2_SET_FEEDBACK_REQUEST_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_TABLET_PAD_V2_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_V2_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"set_feedback".as_ptr(),
        signature: c"usu".as_ptr(),
        types: ZWP_TABLET_PAD_V2_SET_FEEDBACK_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_V2_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_TABLET_PAD_V2_GROUP_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_TABLET_PAD_GROUP_V2_INTERFACE)];
static ZWP_TABLET_PAD_V2_PATH_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_V2_BUTTONS_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_TABLET_PAD_V2_DONE_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_V2_BUTTON_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static ZWP_TABLET_PAD_V2_ENTER_EVENT_TYPES: [IfacePtr; 3] = [
    None,
    Some(&ZWP_TABLET_V2_INTERFACE),
    Some(&super::wayland::WL_SURFACE_INTERFACE),
];
static ZWP_TABLET_PAD_V2_LEAVE_EVENT_TYPES: [IfacePtr; 2] =
    [None, Some(&super::wayland::WL_SURFACE_INTERFACE)];
static ZWP_TABLET_PAD_V2_REMOVED_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_TABLET_PAD_V2_EVENTS: [wl_message; 8] = [
    wl_message {
        name: c"group".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_TABLET_PAD_V2_GROUP_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"path".as_ptr(),
        signature: c"s".as_ptr(),
        types: ZWP_TABLET_PAD_V2_PATH_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"buttons".as_ptr(),
        signature: c"u".as_ptr(),
        types: ZWP_TABLET_PAD_V2_BUTTONS_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"done".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_V2_DONE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"button".as_ptr(),
        signature: c"uuu".as_ptr(),
        types: ZWP_TABLET_PAD_V2_BUTTON_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"enter".as_ptr(),
        signature: c"uoo".as_ptr(),
        types: ZWP_TABLET_PAD_V2_ENTER_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"leave".as_ptr(),
        signature: c"uo".as_ptr(),
        types: ZWP_TABLET_PAD_V2_LEAVE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"removed".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_TABLET_PAD_V2_REMOVED_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_tablet_pad_v2` (`zwp_tablet_pad_v2_interface`).
pub(crate) static ZWP_TABLET_PAD_V2_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_tablet_pad_v2".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_TABLET_PAD_V2_REQUESTS.as_ptr(),
    event_count: 8,
    events: ZWP_TABLET_PAD_V2_EVENTS.as_ptr(),
};

/// `zwp_tablet_pad_v2.button_state`: physical button state
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct ZwpTabletPadV2ButtonState(pub(crate) u32);

impl ZwpTabletPadV2ButtonState {
    /// the button is not pressed
    pub(crate) const RELEASED: ZwpTabletPadV2ButtonState = ZwpTabletPadV2ButtonState(0);
    /// the button is pressed
    pub(crate) const PRESSED: ZwpTabletPadV2ButtonState = ZwpTabletPadV2ButtonState(1);
}

/// `zwp_tablet_pad_v2`: a set of buttons, rings and strips
#[derive(Debug)]
pub(crate) enum ZwpTabletPadV2 {}

impl ZwpTabletPadV2 {
    /// The version `zwp_tablet_pad_v2.set_feedback` appeared in (`ZWP_TABLET_PAD_V2_SET_FEEDBACK_SINCE_VERSION`).
    pub(crate) const SET_FEEDBACK_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.destroy` appeared in (`ZWP_TABLET_PAD_V2_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.group` appeared in (`ZWP_TABLET_PAD_V2_GROUP_SINCE_VERSION`).
    pub(crate) const GROUP_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.path` appeared in (`ZWP_TABLET_PAD_V2_PATH_SINCE_VERSION`).
    pub(crate) const PATH_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.buttons` appeared in (`ZWP_TABLET_PAD_V2_BUTTONS_SINCE_VERSION`).
    pub(crate) const BUTTONS_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.done` appeared in (`ZWP_TABLET_PAD_V2_DONE_SINCE_VERSION`).
    pub(crate) const DONE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.button` appeared in (`ZWP_TABLET_PAD_V2_BUTTON_SINCE_VERSION`).
    pub(crate) const BUTTON_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.enter` appeared in (`ZWP_TABLET_PAD_V2_ENTER_SINCE_VERSION`).
    pub(crate) const ENTER_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.leave` appeared in (`ZWP_TABLET_PAD_V2_LEAVE_SINCE_VERSION`).
    pub(crate) const LEAVE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_tablet_pad_v2.removed` appeared in (`ZWP_TABLET_PAD_V2_REMOVED_SINCE_VERSION`).
    pub(crate) const REMOVED_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_tablet_pad_v2`.
#[derive(Debug)]
pub(crate) enum ZwpTabletPadV2Event<'a> {
    /// `zwp_tablet_pad_v2.group`: group announced
    Group {
        pad_group: Proxy<ZwpTabletPadGroupV2>,
    },
    /// `zwp_tablet_pad_v2.path`: path to the device
    Path {
        /// path to local device
        path: &'a CStr,
    },
    /// `zwp_tablet_pad_v2.buttons`: buttons announced
    Buttons {
        /// the number of buttons
        buttons: u32,
    },
    /// `zwp_tablet_pad_v2.done`: pad description event sequence complete
    Done,
    /// `zwp_tablet_pad_v2.button`: physical button state
    Button {
        /// the time of the event with millisecond granularity
        time: u32,
        /// the index of the button that changed state
        button: u32,
        state: ZwpTabletPadV2ButtonState,
    },
    /// `zwp_tablet_pad_v2.enter`: enter event
    Enter {
        /// serial number of the enter event
        serial: u32,
        /// the tablet the pad is attached to
        tablet: Option<Obj<'a, ZwpTabletV2>>,
        /// surface the pad is focused on
        surface: Option<Obj<'a, super::wayland::WlSurface>>,
    },
    /// `zwp_tablet_pad_v2.leave`: leave event
    Leave {
        /// serial number of the leave event
        serial: u32,
        /// surface the pad is no longer focused on
        surface: Option<Obj<'a, super::wayland::WlSurface>>,
    },
    /// `zwp_tablet_pad_v2.removed`: pad removed event
    Removed,
}

impl Interface for ZwpTabletPadV2 {
    const NAME: &'static str = "zwp_tablet_pad_v2";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpTabletPadV2Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_TABLET_PAD_V2_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadV2Event::Group {
                    // SAFETY: argument 0 is a `new_id`.
                    pad_group: unsafe { arg_new(conn, &a[0])? },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadV2Event::Path {
                    // SAFETY: argument 0 is a `string`.
                    path: unsafe { arg_str(&a[0]) }.unwrap_or_default(),
                })
            }
            2 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpTabletPadV2Event::Buttons {
                    // SAFETY: argument 0 is a `uint`.
                    buttons: unsafe { a[0].u },
                })
            }
            3 => Some(ZwpTabletPadV2Event::Done),
            4 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpTabletPadV2Event::Button {
                    // SAFETY: argument 0 is a `uint`.
                    time: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `uint`.
                    button: unsafe { a[1].u },
                    // SAFETY: argument 2 is a `uint`.
                    state: ZwpTabletPadV2ButtonState(unsafe { a[2].u }),
                })
            }
            5 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(ZwpTabletPadV2Event::Enter {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `object`.
                    tablet: unsafe { arg_obj(conn, &a[1]) },
                    // SAFETY: argument 2 is a `object`.
                    surface: unsafe { arg_obj(conn, &a[2]) },
                })
            }
            6 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpTabletPadV2Event::Leave {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                    // SAFETY: argument 1 is a `object`.
                    surface: unsafe { arg_obj(conn, &a[1]) },
                })
            }
            7 => Some(ZwpTabletPadV2Event::Removed),
            _ => None,
        }
    }
}

/// The requests of `zwp_tablet_pad_v2`, for anything that is a proxy of it.
pub(crate) trait ZwpTabletPadV2Requests: AsProxy<Interface = ZwpTabletPadV2> {
    /// `zwp_tablet_pad_v2.set_feedback`: set compositor feedback
    fn set_feedback(&self, button: u32, description: &str, serial: u32) {
        let proxy = self.obj();
        let c_description = cstring_arg(description);
        let mut args = [
            wl_argument { u: button },
            wl_argument {
                s: c_description.as_ptr(),
            },
            wl_argument { u: serial },
        ];
        // SAFETY: the arguments match the request's signature, "usu".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpTabletPadV2>> ZwpTabletPadV2Requests for T {}

impl Proxy<ZwpTabletPadV2> {
    /// `zwp_tablet_pad_v2.destroy`: destroy the pad object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
