// Rust bindings of the viewporter Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/viewporter.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2013-2016 Collabora, Ltd.
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `viewporter` protocol (`viewporter.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// wp_viewporter
// ---------------------------------------------------------------------------

static WP_VIEWPORTER_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static WP_VIEWPORTER_GET_VIEWPORT_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&WP_VIEWPORT_INTERFACE),
    Some(&super::wayland::WL_SURFACE_INTERFACE),
];
static WP_VIEWPORTER_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: WP_VIEWPORTER_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_viewport".as_ptr(),
        signature: c"no".as_ptr(),
        types: WP_VIEWPORTER_GET_VIEWPORT_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `wp_viewporter` (`wp_viewporter_interface`).
pub(crate) static WP_VIEWPORTER_INTERFACE: wl_interface = wl_interface {
    name: c"wp_viewporter".as_ptr(),
    version: 1,
    method_count: 2,
    methods: WP_VIEWPORTER_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `wp_viewporter.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct WpViewporterError(pub(crate) u32);

impl WpViewporterError {
    /// the surface already has a viewport object associated
    pub(crate) const VIEWPORT_EXISTS: WpViewporterError = WpViewporterError(0);
}

/// `wp_viewporter`: surface cropping and scaling
#[derive(Debug)]
pub(crate) enum WpViewporter {}

impl WpViewporter {
    /// The version `wp_viewporter.destroy` appeared in (`WP_VIEWPORTER_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `wp_viewporter.get_viewport` appeared in (`WP_VIEWPORTER_GET_VIEWPORT_SINCE_VERSION`).
    pub(crate) const GET_VIEWPORT_SINCE_VERSION: u32 = 1;
}

impl Interface for WpViewporter {
    const NAME: &'static str = "wp_viewporter";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &WP_VIEWPORTER_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `wp_viewporter`, for anything that is a proxy of it.
pub(crate) trait WpViewporterRequests: AsProxy<Interface = WpViewporter> {
    /// `wp_viewporter.get_viewport`: extend surface interface for crop and scale
    fn get_viewport(&self, surface: Obj<'_, super::wayland::WlSurface>) -> Proxy<WpViewport> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: surface.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe { proxy.marshal_constructor::<WpViewport>(1, &mut args, proxy.version(), 0) }
    }
}

impl<T: AsProxy<Interface = WpViewporter>> WpViewporterRequests for T {}

impl Proxy<WpViewporter> {
    /// `wp_viewporter.destroy`: unbind from the cropping and scaling interface
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// wp_viewport
// ---------------------------------------------------------------------------

static WP_VIEWPORT_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static WP_VIEWPORT_SET_SOURCE_REQUEST_TYPES: [IfacePtr; 4] = [None, None, None, None];
static WP_VIEWPORT_SET_DESTINATION_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static WP_VIEWPORT_REQUESTS: [wl_message; 3] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: WP_VIEWPORT_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_source".as_ptr(),
        signature: c"ffff".as_ptr(),
        types: WP_VIEWPORT_SET_SOURCE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_destination".as_ptr(),
        signature: c"ii".as_ptr(),
        types: WP_VIEWPORT_SET_DESTINATION_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `wp_viewport` (`wp_viewport_interface`).
pub(crate) static WP_VIEWPORT_INTERFACE: wl_interface = wl_interface {
    name: c"wp_viewport".as_ptr(),
    version: 1,
    method_count: 3,
    methods: WP_VIEWPORT_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `wp_viewport.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct WpViewportError(pub(crate) u32);

impl WpViewportError {
    /// negative or zero values in width or height
    pub(crate) const BAD_VALUE: WpViewportError = WpViewportError(0);
    /// destination size is not integer
    pub(crate) const BAD_SIZE: WpViewportError = WpViewportError(1);
    /// source rectangle extends outside of the content area
    pub(crate) const OUT_OF_BUFFER: WpViewportError = WpViewportError(2);
    /// the wl_surface was destroyed
    pub(crate) const NO_SURFACE: WpViewportError = WpViewportError(3);
}

/// `wp_viewport`: crop and scale interface to a wl_surface
#[derive(Debug)]
pub(crate) enum WpViewport {}

impl WpViewport {
    /// The version `wp_viewport.destroy` appeared in (`WP_VIEWPORT_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `wp_viewport.set_source` appeared in (`WP_VIEWPORT_SET_SOURCE_SINCE_VERSION`).
    pub(crate) const SET_SOURCE_SINCE_VERSION: u32 = 1;
    /// The version `wp_viewport.set_destination` appeared in (`WP_VIEWPORT_SET_DESTINATION_SINCE_VERSION`).
    pub(crate) const SET_DESTINATION_SINCE_VERSION: u32 = 1;
}

impl Interface for WpViewport {
    const NAME: &'static str = "wp_viewport";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &WP_VIEWPORT_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `wp_viewport`, for anything that is a proxy of it.
pub(crate) trait WpViewportRequests: AsProxy<Interface = WpViewport> {
    /// `wp_viewport.set_source`: set the source rectangle for cropping
    fn set_source(&self, x: Fixed, y: Fixed, width: Fixed, height: Fixed) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { f: x.0 },
            wl_argument { f: y.0 },
            wl_argument { f: width.0 },
            wl_argument { f: height.0 },
        ];
        // SAFETY: the arguments match the request's signature, "ffff".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }

    /// `wp_viewport.set_destination`: set the surface size for scaling
    fn set_destination(&self, width: i32, height: i32) {
        let proxy = self.obj();
        let mut args = [wl_argument { i: width }, wl_argument { i: height }];
        // SAFETY: the arguments match the request's signature, "ii".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = WpViewport>> WpViewportRequests for T {}

impl Proxy<WpViewport> {
    /// `wp_viewport.destroy`: remove scaling and cropping from the surface
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
