// Rust bindings of the wp_primary_selection_unstable_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/primary-selection-unstable-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2015, 2016 Red Hat
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `wp_primary_selection_unstable_v1` protocol (`primary-selection-unstable-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// zwp_primary_selection_device_manager_v1
// ---------------------------------------------------------------------------

static ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_CREATE_SOURCE_REQUEST_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_PRIMARY_SELECTION_SOURCE_V1_INTERFACE)];
static ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_GET_DEVICE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&ZWP_PRIMARY_SELECTION_DEVICE_V1_INTERFACE),
    Some(&super::wayland::WL_SEAT_INTERFACE),
];
static ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_REQUESTS: [wl_message; 3] = [
    wl_message {
        name: c"create_source".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_CREATE_SOURCE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_device".as_ptr(),
        signature: c"no".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_GET_DEVICE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_primary_selection_device_manager_v1` (`zwp_primary_selection_device_manager_v1_interface`).
pub(crate) static ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_primary_selection_device_manager_v1".as_ptr(),
    version: 1,
    method_count: 3,
    methods: ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `zwp_primary_selection_device_manager_v1`: X primary selection emulation
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionDeviceManagerV1 {}

impl ZwpPrimarySelectionDeviceManagerV1 {
    /// The version `zwp_primary_selection_device_manager_v1.create_source` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_CREATE_SOURCE_SINCE_VERSION`).
    pub(crate) const CREATE_SOURCE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_device_manager_v1.get_device` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_GET_DEVICE_SINCE_VERSION`).
    pub(crate) const GET_DEVICE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_device_manager_v1.destroy` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
}

impl Interface for ZwpPrimarySelectionDeviceManagerV1 {
    const NAME: &'static str = "zwp_primary_selection_device_manager_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((2, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &ZWP_PRIMARY_SELECTION_DEVICE_MANAGER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `zwp_primary_selection_device_manager_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPrimarySelectionDeviceManagerV1Requests:
    AsProxy<Interface = ZwpPrimarySelectionDeviceManagerV1>
{
    /// `zwp_primary_selection_device_manager_v1.create_source`: create a new primary selection source
    fn create_source(&self) -> Proxy<ZwpPrimarySelectionSourceV1> {
        let proxy = self.obj();
        let mut args = [wl_argument { o: ptr::null_mut() }];
        // SAFETY: the arguments match the request's signature, "n".
        unsafe {
            proxy.marshal_constructor::<ZwpPrimarySelectionSourceV1>(
                0,
                &mut args,
                proxy.version(),
                0,
            )
        }
    }

    /// `zwp_primary_selection_device_manager_v1.get_device`: create a new primary selection device
    fn get_device(
        &self,
        seat: Obj<'_, super::wayland::WlSeat>,
    ) -> Proxy<ZwpPrimarySelectionDeviceV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: seat.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe {
            proxy.marshal_constructor::<ZwpPrimarySelectionDeviceV1>(
                1,
                &mut args,
                proxy.version(),
                0,
            )
        }
    }
}

impl<T: AsProxy<Interface = ZwpPrimarySelectionDeviceManagerV1>>
    ZwpPrimarySelectionDeviceManagerV1Requests for T
{
}

impl Proxy<ZwpPrimarySelectionDeviceManagerV1> {
    /// `zwp_primary_selection_device_manager_v1.destroy`: destroy the primary selection device manager
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(2, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_primary_selection_device_v1
// ---------------------------------------------------------------------------

static ZWP_PRIMARY_SELECTION_DEVICE_V1_SET_SELECTION_REQUEST_TYPES: [IfacePtr; 2] =
    [Some(&ZWP_PRIMARY_SELECTION_SOURCE_V1_INTERFACE), None];
static ZWP_PRIMARY_SELECTION_DEVICE_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_PRIMARY_SELECTION_DEVICE_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"set_selection".as_ptr(),
        signature: c"?ou".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_V1_SET_SELECTION_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_PRIMARY_SELECTION_DEVICE_V1_DATA_OFFER_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_PRIMARY_SELECTION_OFFER_V1_INTERFACE)];
static ZWP_PRIMARY_SELECTION_DEVICE_V1_SELECTION_EVENT_TYPES: [IfacePtr; 1] =
    [Some(&ZWP_PRIMARY_SELECTION_OFFER_V1_INTERFACE)];
static ZWP_PRIMARY_SELECTION_DEVICE_V1_EVENTS: [wl_message; 2] = [
    wl_message {
        name: c"data_offer".as_ptr(),
        signature: c"n".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_V1_DATA_OFFER_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"selection".as_ptr(),
        signature: c"?o".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_DEVICE_V1_SELECTION_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_primary_selection_device_v1` (`zwp_primary_selection_device_v1_interface`).
pub(crate) static ZWP_PRIMARY_SELECTION_DEVICE_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_primary_selection_device_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_PRIMARY_SELECTION_DEVICE_V1_REQUESTS.as_ptr(),
    event_count: 2,
    events: ZWP_PRIMARY_SELECTION_DEVICE_V1_EVENTS.as_ptr(),
};

/// `zwp_primary_selection_device_v1`
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionDeviceV1 {}

impl ZwpPrimarySelectionDeviceV1 {
    /// The version `zwp_primary_selection_device_v1.set_selection` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_V1_SET_SELECTION_SINCE_VERSION`).
    pub(crate) const SET_SELECTION_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_device_v1.destroy` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_device_v1.data_offer` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_V1_DATA_OFFER_SINCE_VERSION`).
    pub(crate) const DATA_OFFER_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_device_v1.selection` appeared in (`ZWP_PRIMARY_SELECTION_DEVICE_V1_SELECTION_SINCE_VERSION`).
    pub(crate) const SELECTION_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_primary_selection_device_v1`.
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionDeviceV1Event<'a> {
    /// `zwp_primary_selection_device_v1.data_offer`: introduce a new wp_primary_selection_offer
    DataOffer {
        offer: Proxy<ZwpPrimarySelectionOfferV1>,
    },
    /// `zwp_primary_selection_device_v1.selection`: advertise a new primary selection
    Selection {
        id: Option<Obj<'a, ZwpPrimarySelectionOfferV1>>,
    },
}

impl Interface for ZwpPrimarySelectionDeviceV1 {
    const NAME: &'static str = "zwp_primary_selection_device_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpPrimarySelectionDeviceV1Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_PRIMARY_SELECTION_DEVICE_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpPrimarySelectionDeviceV1Event::DataOffer {
                    // SAFETY: argument 0 is a `new_id`.
                    offer: unsafe { arg_new(conn, &a[0])? },
                })
            }
            1 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpPrimarySelectionDeviceV1Event::Selection {
                    // SAFETY: argument 0 is a `object`.
                    id: unsafe { arg_obj(conn, &a[0]) },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_primary_selection_device_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPrimarySelectionDeviceV1Requests:
    AsProxy<Interface = ZwpPrimarySelectionDeviceV1>
{
    /// `zwp_primary_selection_device_v1.set_selection`: set the primary selection
    fn set_selection(&self, source: Option<Obj<'_, ZwpPrimarySelectionSourceV1>>, serial: u32) {
        let proxy = self.obj();
        let mut args = [
            wl_argument {
                o: source.map_or(ptr::null_mut(), |o| o.raw()),
            },
            wl_argument { u: serial },
        ];
        // SAFETY: the arguments match the request's signature, "?ou".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpPrimarySelectionDeviceV1>> ZwpPrimarySelectionDeviceV1Requests
    for T
{
}

impl Proxy<ZwpPrimarySelectionDeviceV1> {
    /// `zwp_primary_selection_device_v1.destroy`: destroy the primary selection device
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_primary_selection_offer_v1
// ---------------------------------------------------------------------------

static ZWP_PRIMARY_SELECTION_OFFER_V1_RECEIVE_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_PRIMARY_SELECTION_OFFER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_PRIMARY_SELECTION_OFFER_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"receive".as_ptr(),
        signature: c"sh".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_OFFER_V1_RECEIVE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_OFFER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_PRIMARY_SELECTION_OFFER_V1_OFFER_EVENT_TYPES: [IfacePtr; 1] = [None];
static ZWP_PRIMARY_SELECTION_OFFER_V1_EVENTS: [wl_message; 1] = [wl_message {
    name: c"offer".as_ptr(),
    signature: c"s".as_ptr(),
    types: ZWP_PRIMARY_SELECTION_OFFER_V1_OFFER_EVENT_TYPES.as_ptr(),
}];
/// The `wl_interface` of `zwp_primary_selection_offer_v1` (`zwp_primary_selection_offer_v1_interface`).
pub(crate) static ZWP_PRIMARY_SELECTION_OFFER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_primary_selection_offer_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_PRIMARY_SELECTION_OFFER_V1_REQUESTS.as_ptr(),
    event_count: 1,
    events: ZWP_PRIMARY_SELECTION_OFFER_V1_EVENTS.as_ptr(),
};

/// `zwp_primary_selection_offer_v1`: offer to transfer primary selection contents
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionOfferV1 {}

impl ZwpPrimarySelectionOfferV1 {
    /// The version `zwp_primary_selection_offer_v1.receive` appeared in (`ZWP_PRIMARY_SELECTION_OFFER_V1_RECEIVE_SINCE_VERSION`).
    pub(crate) const RECEIVE_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_offer_v1.destroy` appeared in (`ZWP_PRIMARY_SELECTION_OFFER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_offer_v1.offer` appeared in (`ZWP_PRIMARY_SELECTION_OFFER_V1_OFFER_SINCE_VERSION`).
    pub(crate) const OFFER_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_primary_selection_offer_v1`.
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionOfferV1Event<'a> {
    /// `zwp_primary_selection_offer_v1.offer`: advertise offered mime type
    Offer { mime_type: &'a CStr },
}

impl Interface for ZwpPrimarySelectionOfferV1 {
    const NAME: &'static str = "zwp_primary_selection_offer_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpPrimarySelectionOfferV1Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_PRIMARY_SELECTION_OFFER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(ZwpPrimarySelectionOfferV1Event::Offer {
                    // SAFETY: argument 0 is a `string`.
                    mime_type: unsafe { arg_str(&a[0]) }.unwrap_or_default(),
                })
            }
            _ => None,
        }
    }
}

/// The requests of `zwp_primary_selection_offer_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPrimarySelectionOfferV1Requests:
    AsProxy<Interface = ZwpPrimarySelectionOfferV1>
{
    /// `zwp_primary_selection_offer_v1.receive`: request that the data is transferred
    fn receive(&self, mime_type: &str, fd: BorrowedFd<'_>) {
        let proxy = self.obj();
        let c_mime_type = cstring_arg(mime_type);
        let mut args = [
            wl_argument {
                s: c_mime_type.as_ptr(),
            },
            wl_argument {
                h: std::os::fd::AsRawFd::as_raw_fd(&fd),
            },
        ];
        // SAFETY: the arguments match the request's signature, "sh".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpPrimarySelectionOfferV1>> ZwpPrimarySelectionOfferV1Requests for T {}

impl Proxy<ZwpPrimarySelectionOfferV1> {
    /// `zwp_primary_selection_offer_v1.destroy`: destroy the primary selection offer
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// zwp_primary_selection_source_v1
// ---------------------------------------------------------------------------

static ZWP_PRIMARY_SELECTION_SOURCE_V1_OFFER_REQUEST_TYPES: [IfacePtr; 1] = [None];
static ZWP_PRIMARY_SELECTION_SOURCE_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static ZWP_PRIMARY_SELECTION_SOURCE_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"offer".as_ptr(),
        signature: c"s".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_SOURCE_V1_OFFER_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_SOURCE_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
];
static ZWP_PRIMARY_SELECTION_SOURCE_V1_SEND_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static ZWP_PRIMARY_SELECTION_SOURCE_V1_CANCELLED_EVENT_TYPES: [IfacePtr; 0] = [];
static ZWP_PRIMARY_SELECTION_SOURCE_V1_EVENTS: [wl_message; 2] = [
    wl_message {
        name: c"send".as_ptr(),
        signature: c"sh".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_SOURCE_V1_SEND_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"cancelled".as_ptr(),
        signature: c"".as_ptr(),
        types: ZWP_PRIMARY_SELECTION_SOURCE_V1_CANCELLED_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `zwp_primary_selection_source_v1` (`zwp_primary_selection_source_v1_interface`).
pub(crate) static ZWP_PRIMARY_SELECTION_SOURCE_V1_INTERFACE: wl_interface = wl_interface {
    name: c"zwp_primary_selection_source_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: ZWP_PRIMARY_SELECTION_SOURCE_V1_REQUESTS.as_ptr(),
    event_count: 2,
    events: ZWP_PRIMARY_SELECTION_SOURCE_V1_EVENTS.as_ptr(),
};

/// `zwp_primary_selection_source_v1`: offer to replace the contents of the primary selection
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionSourceV1 {}

impl ZwpPrimarySelectionSourceV1 {
    /// The version `zwp_primary_selection_source_v1.offer` appeared in (`ZWP_PRIMARY_SELECTION_SOURCE_V1_OFFER_SINCE_VERSION`).
    pub(crate) const OFFER_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_source_v1.destroy` appeared in (`ZWP_PRIMARY_SELECTION_SOURCE_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_source_v1.send` appeared in (`ZWP_PRIMARY_SELECTION_SOURCE_V1_SEND_SINCE_VERSION`).
    pub(crate) const SEND_SINCE_VERSION: u32 = 1;
    /// The version `zwp_primary_selection_source_v1.cancelled` appeared in (`ZWP_PRIMARY_SELECTION_SOURCE_V1_CANCELLED_SINCE_VERSION`).
    pub(crate) const CANCELLED_SINCE_VERSION: u32 = 1;
}

/// The events of `zwp_primary_selection_source_v1`.
#[derive(Debug)]
pub(crate) enum ZwpPrimarySelectionSourceV1Event<'a> {
    /// `zwp_primary_selection_source_v1.send`: send the primary selection contents
    Send { mime_type: &'a CStr, fd: OwnedFd },
    /// `zwp_primary_selection_source_v1.cancelled`: request for primary selection contents was canceled
    Cancelled,
}

impl Interface for ZwpPrimarySelectionSourceV1 {
    const NAME: &'static str = "zwp_primary_selection_source_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((1, 1));
    type Event<'a> = ZwpPrimarySelectionSourceV1Event<'a>;

    fn interface() -> &'static wl_interface {
        &ZWP_PRIMARY_SELECTION_SOURCE_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(ZwpPrimarySelectionSourceV1Event::Send {
                    // SAFETY: argument 0 is a `string`.
                    mime_type: unsafe { arg_str(&a[0]) }.unwrap_or_default(),
                    // SAFETY: argument 1 is a `fd`.
                    fd: unsafe { arg_fd(&a[1]) },
                })
            }
            1 => Some(ZwpPrimarySelectionSourceV1Event::Cancelled),
            _ => None,
        }
    }
}

/// The requests of `zwp_primary_selection_source_v1`, for anything that is a proxy of it.
pub(crate) trait ZwpPrimarySelectionSourceV1Requests:
    AsProxy<Interface = ZwpPrimarySelectionSourceV1>
{
    /// `zwp_primary_selection_source_v1.offer`: add an offered mime type
    fn offer(&self, mime_type: &str) {
        let proxy = self.obj();
        let c_mime_type = cstring_arg(mime_type);
        let mut args = [wl_argument {
            s: c_mime_type.as_ptr(),
        }];
        // SAFETY: the arguments match the request's signature, "s".
        unsafe { proxy.marshal(0, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = ZwpPrimarySelectionSourceV1>> ZwpPrimarySelectionSourceV1Requests
    for T
{
}

impl Proxy<ZwpPrimarySelectionSourceV1> {
    /// `zwp_primary_selection_source_v1.destroy`: destroy the primary selection source
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
