// Rust bindings of the xdg_shell Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/xdg-shell.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2008-2013 Kristian Høgsberg
//      Copyright © 2013      Rafael Antognolli
//      Copyright © 2013      Jasper St. Pierre
//      Copyright © 2010-2013 Intel Corporation
//      Copyright © 2015-2017 Samsung Electronics Co., Ltd
//      Copyright © 2015-2017 Red Hat Inc.
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `xdg_shell` protocol (`xdg-shell.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// xdg_wm_base
// ---------------------------------------------------------------------------

static XDG_WM_BASE_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_WM_BASE_CREATE_POSITIONER_REQUEST_TYPES: [IfacePtr; 1] =
    [Some(&XDG_POSITIONER_INTERFACE)];
static XDG_WM_BASE_GET_XDG_SURFACE_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&XDG_SURFACE_INTERFACE),
    Some(&super::wayland::WL_SURFACE_INTERFACE),
];
static XDG_WM_BASE_PONG_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_WM_BASE_REQUESTS: [wl_message; 4] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_WM_BASE_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"create_positioner".as_ptr(),
        signature: c"n".as_ptr(),
        types: XDG_WM_BASE_CREATE_POSITIONER_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_xdg_surface".as_ptr(),
        signature: c"no".as_ptr(),
        types: XDG_WM_BASE_GET_XDG_SURFACE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"pong".as_ptr(),
        signature: c"u".as_ptr(),
        types: XDG_WM_BASE_PONG_REQUEST_TYPES.as_ptr(),
    },
];
static XDG_WM_BASE_PING_EVENT_TYPES: [IfacePtr; 1] = [None];
static XDG_WM_BASE_EVENTS: [wl_message; 1] = [wl_message {
    name: c"ping".as_ptr(),
    signature: c"u".as_ptr(),
    types: XDG_WM_BASE_PING_EVENT_TYPES.as_ptr(),
}];
/// The `wl_interface` of `xdg_wm_base` (`xdg_wm_base_interface`).
pub(crate) static XDG_WM_BASE_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_wm_base".as_ptr(),
    version: 7,
    method_count: 4,
    methods: XDG_WM_BASE_REQUESTS.as_ptr(),
    event_count: 1,
    events: XDG_WM_BASE_EVENTS.as_ptr(),
};

/// `xdg_wm_base.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgWmBaseError(pub(crate) u32);

impl XdgWmBaseError {
    /// given wl_surface has another role
    pub(crate) const ROLE: XdgWmBaseError = XdgWmBaseError(0);
    /// xdg_wm_base was destroyed before children
    pub(crate) const DEFUNCT_SURFACES: XdgWmBaseError = XdgWmBaseError(1);
    /// the client tried to map or destroy a non-topmost popup
    pub(crate) const NOT_THE_TOPMOST_POPUP: XdgWmBaseError = XdgWmBaseError(2);
    /// the client specified an invalid popup parent surface
    pub(crate) const INVALID_POPUP_PARENT: XdgWmBaseError = XdgWmBaseError(3);
    /// the client provided an invalid surface state
    pub(crate) const INVALID_SURFACE_STATE: XdgWmBaseError = XdgWmBaseError(4);
    /// the client provided an invalid positioner
    pub(crate) const INVALID_POSITIONER: XdgWmBaseError = XdgWmBaseError(5);
    /// the client didn’t respond to a ping event in time
    pub(crate) const UNRESPONSIVE: XdgWmBaseError = XdgWmBaseError(6);
}

/// `xdg_wm_base`: create desktop-style surfaces
#[derive(Debug)]
pub(crate) enum XdgWmBase {}

impl XdgWmBase {
    /// The version `xdg_wm_base.destroy` appeared in (`XDG_WM_BASE_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_wm_base.create_positioner` appeared in (`XDG_WM_BASE_CREATE_POSITIONER_SINCE_VERSION`).
    pub(crate) const CREATE_POSITIONER_SINCE_VERSION: u32 = 1;
    /// The version `xdg_wm_base.get_xdg_surface` appeared in (`XDG_WM_BASE_GET_XDG_SURFACE_SINCE_VERSION`).
    pub(crate) const GET_XDG_SURFACE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_wm_base.pong` appeared in (`XDG_WM_BASE_PONG_SINCE_VERSION`).
    pub(crate) const PONG_SINCE_VERSION: u32 = 1;
    /// The version `xdg_wm_base.ping` appeared in (`XDG_WM_BASE_PING_SINCE_VERSION`).
    pub(crate) const PING_SINCE_VERSION: u32 = 1;
}

/// The events of `xdg_wm_base`.
#[derive(Debug)]
pub(crate) enum XdgWmBaseEvent {
    /// `xdg_wm_base.ping`: check if the client is alive
    Ping {
        /// pass this to the pong request
        serial: u32,
    },
}

impl Interface for XdgWmBase {
    const NAME: &'static str = "xdg_wm_base";
    const VERSION: u32 = 7;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = XdgWmBaseEvent;

    fn interface() -> &'static wl_interface {
        &XDG_WM_BASE_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(XdgWmBaseEvent::Ping {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `xdg_wm_base`, for anything that is a proxy of it.
pub(crate) trait XdgWmBaseRequests: AsProxy<Interface = XdgWmBase> {
    /// `xdg_wm_base.create_positioner`: create a positioner object
    fn create_positioner(&self) -> Proxy<XdgPositioner> {
        let proxy = self.obj();
        let mut args = [wl_argument { o: ptr::null_mut() }];
        // SAFETY: the arguments match the request's signature, "n".
        unsafe { proxy.marshal_constructor::<XdgPositioner>(1, &mut args, proxy.version(), 0) }
    }

    /// `xdg_wm_base.get_xdg_surface`: create a shell surface from a surface
    fn get_xdg_surface(&self, surface: Obj<'_, super::wayland::WlSurface>) -> Proxy<XdgSurface> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: surface.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe { proxy.marshal_constructor::<XdgSurface>(2, &mut args, proxy.version(), 0) }
    }

    /// `xdg_wm_base.pong`: respond to a ping event
    fn pong(&self, serial: u32) {
        let proxy = self.obj();
        let mut args = [wl_argument { u: serial }];
        // SAFETY: the arguments match the request's signature, "u".
        unsafe { proxy.marshal(3, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgWmBase>> XdgWmBaseRequests for T {}

impl Proxy<XdgWmBase> {
    /// `xdg_wm_base.destroy`: destroy xdg_wm_base
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// xdg_positioner
// ---------------------------------------------------------------------------

static XDG_POSITIONER_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_POSITIONER_SET_SIZE_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static XDG_POSITIONER_SET_ANCHOR_RECT_REQUEST_TYPES: [IfacePtr; 4] = [None, None, None, None];
static XDG_POSITIONER_SET_ANCHOR_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_POSITIONER_SET_GRAVITY_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_POSITIONER_SET_OFFSET_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static XDG_POSITIONER_SET_REACTIVE_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_POSITIONER_SET_PARENT_SIZE_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static XDG_POSITIONER_SET_PARENT_CONFIGURE_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_POSITIONER_REQUESTS: [wl_message; 10] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_POSITIONER_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_size".as_ptr(),
        signature: c"ii".as_ptr(),
        types: XDG_POSITIONER_SET_SIZE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_anchor_rect".as_ptr(),
        signature: c"iiii".as_ptr(),
        types: XDG_POSITIONER_SET_ANCHOR_RECT_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_anchor".as_ptr(),
        signature: c"u".as_ptr(),
        types: XDG_POSITIONER_SET_ANCHOR_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_gravity".as_ptr(),
        signature: c"u".as_ptr(),
        types: XDG_POSITIONER_SET_GRAVITY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_constraint_adjustment".as_ptr(),
        signature: c"u".as_ptr(),
        types: XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_offset".as_ptr(),
        signature: c"ii".as_ptr(),
        types: XDG_POSITIONER_SET_OFFSET_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_reactive".as_ptr(),
        signature: c"3".as_ptr(),
        types: XDG_POSITIONER_SET_REACTIVE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_parent_size".as_ptr(),
        signature: c"3ii".as_ptr(),
        types: XDG_POSITIONER_SET_PARENT_SIZE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_parent_configure".as_ptr(),
        signature: c"3u".as_ptr(),
        types: XDG_POSITIONER_SET_PARENT_CONFIGURE_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_positioner` (`xdg_positioner_interface`).
pub(crate) static XDG_POSITIONER_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_positioner".as_ptr(),
    version: 7,
    method_count: 10,
    methods: XDG_POSITIONER_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `xdg_positioner.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgPositionerError(pub(crate) u32);

impl XdgPositionerError {
    /// invalid input provided
    pub(crate) const INVALID_INPUT: XdgPositionerError = XdgPositionerError(0);
}

/// `xdg_positioner.anchor`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgPositionerAnchor(pub(crate) u32);

impl XdgPositionerAnchor {
    pub(crate) const NONE: XdgPositionerAnchor = XdgPositionerAnchor(0);
    pub(crate) const TOP: XdgPositionerAnchor = XdgPositionerAnchor(1);
    pub(crate) const BOTTOM: XdgPositionerAnchor = XdgPositionerAnchor(2);
    pub(crate) const LEFT: XdgPositionerAnchor = XdgPositionerAnchor(3);
    pub(crate) const RIGHT: XdgPositionerAnchor = XdgPositionerAnchor(4);
    pub(crate) const TOP_LEFT: XdgPositionerAnchor = XdgPositionerAnchor(5);
    pub(crate) const BOTTOM_LEFT: XdgPositionerAnchor = XdgPositionerAnchor(6);
    pub(crate) const TOP_RIGHT: XdgPositionerAnchor = XdgPositionerAnchor(7);
    pub(crate) const BOTTOM_RIGHT: XdgPositionerAnchor = XdgPositionerAnchor(8);
}

/// `xdg_positioner.gravity`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgPositionerGravity(pub(crate) u32);

impl XdgPositionerGravity {
    pub(crate) const NONE: XdgPositionerGravity = XdgPositionerGravity(0);
    pub(crate) const TOP: XdgPositionerGravity = XdgPositionerGravity(1);
    pub(crate) const BOTTOM: XdgPositionerGravity = XdgPositionerGravity(2);
    pub(crate) const LEFT: XdgPositionerGravity = XdgPositionerGravity(3);
    pub(crate) const RIGHT: XdgPositionerGravity = XdgPositionerGravity(4);
    pub(crate) const TOP_LEFT: XdgPositionerGravity = XdgPositionerGravity(5);
    pub(crate) const BOTTOM_LEFT: XdgPositionerGravity = XdgPositionerGravity(6);
    pub(crate) const TOP_RIGHT: XdgPositionerGravity = XdgPositionerGravity(7);
    pub(crate) const BOTTOM_RIGHT: XdgPositionerGravity = XdgPositionerGravity(8);
}

/// `xdg_positioner.constraint_adjustment`: constraint adjustments
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgPositionerConstraintAdjustment(pub(crate) u32);

impl XdgPositionerConstraintAdjustment {
    /// don't move the child surface when constrained
    pub(crate) const NONE: XdgPositionerConstraintAdjustment = XdgPositionerConstraintAdjustment(0);
    /// move along the x axis until unconstrained
    pub(crate) const SLIDE_X: XdgPositionerConstraintAdjustment =
        XdgPositionerConstraintAdjustment(1);
    /// move along the y axis until unconstrained
    pub(crate) const SLIDE_Y: XdgPositionerConstraintAdjustment =
        XdgPositionerConstraintAdjustment(2);
    /// invert the anchor and gravity on the x axis
    pub(crate) const FLIP_X: XdgPositionerConstraintAdjustment =
        XdgPositionerConstraintAdjustment(4);
    /// invert the anchor and gravity on the y axis
    pub(crate) const FLIP_Y: XdgPositionerConstraintAdjustment =
        XdgPositionerConstraintAdjustment(8);
    /// horizontally resize the surface
    pub(crate) const RESIZE_X: XdgPositionerConstraintAdjustment =
        XdgPositionerConstraintAdjustment(16);
    /// vertically resize the surface
    pub(crate) const RESIZE_Y: XdgPositionerConstraintAdjustment =
        XdgPositionerConstraintAdjustment(32);

    /// Whether all the bits of `other` are set.
    pub(crate) const fn contains(self, other: XdgPositionerConstraintAdjustment) -> bool {
        self.0 & other.0 == other.0
    }
}

impl std::ops::BitOr for XdgPositionerConstraintAdjustment {
    type Output = XdgPositionerConstraintAdjustment;
    fn bitor(self, rhs: XdgPositionerConstraintAdjustment) -> XdgPositionerConstraintAdjustment {
        XdgPositionerConstraintAdjustment(self.0 | rhs.0)
    }
}

impl std::ops::BitOrAssign for XdgPositionerConstraintAdjustment {
    fn bitor_assign(&mut self, rhs: XdgPositionerConstraintAdjustment) {
        self.0 |= rhs.0;
    }
}

/// `xdg_positioner`: child surface positioner
#[derive(Debug)]
pub(crate) enum XdgPositioner {}

impl XdgPositioner {
    /// The version `xdg_positioner.destroy` appeared in (`XDG_POSITIONER_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_size` appeared in (`XDG_POSITIONER_SET_SIZE_SINCE_VERSION`).
    pub(crate) const SET_SIZE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_anchor_rect` appeared in (`XDG_POSITIONER_SET_ANCHOR_RECT_SINCE_VERSION`).
    pub(crate) const SET_ANCHOR_RECT_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_anchor` appeared in (`XDG_POSITIONER_SET_ANCHOR_SINCE_VERSION`).
    pub(crate) const SET_ANCHOR_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_gravity` appeared in (`XDG_POSITIONER_SET_GRAVITY_SINCE_VERSION`).
    pub(crate) const SET_GRAVITY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_constraint_adjustment` appeared in (`XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT_SINCE_VERSION`).
    pub(crate) const SET_CONSTRAINT_ADJUSTMENT_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_offset` appeared in (`XDG_POSITIONER_SET_OFFSET_SINCE_VERSION`).
    pub(crate) const SET_OFFSET_SINCE_VERSION: u32 = 1;
    /// The version `xdg_positioner.set_reactive` appeared in (`XDG_POSITIONER_SET_REACTIVE_SINCE_VERSION`).
    pub(crate) const SET_REACTIVE_SINCE_VERSION: u32 = 3;
    /// The version `xdg_positioner.set_parent_size` appeared in (`XDG_POSITIONER_SET_PARENT_SIZE_SINCE_VERSION`).
    pub(crate) const SET_PARENT_SIZE_SINCE_VERSION: u32 = 3;
    /// The version `xdg_positioner.set_parent_configure` appeared in (`XDG_POSITIONER_SET_PARENT_CONFIGURE_SINCE_VERSION`).
    pub(crate) const SET_PARENT_CONFIGURE_SINCE_VERSION: u32 = 3;
}

impl Interface for XdgPositioner {
    const NAME: &'static str = "xdg_positioner";
    const VERSION: u32 = 7;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &XDG_POSITIONER_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `xdg_positioner`, for anything that is a proxy of it.
pub(crate) trait XdgPositionerRequests: AsProxy<Interface = XdgPositioner> {
    /// `xdg_positioner.set_size`: set the size of the to-be positioned rectangle
    fn set_size(&self, width: i32, height: i32) {
        let proxy = self.obj();
        let mut args = [wl_argument { i: width }, wl_argument { i: height }];
        // SAFETY: the arguments match the request's signature, "ii".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }

    /// `xdg_positioner.set_anchor_rect`: set the anchor rectangle within the parent surface
    fn set_anchor_rect(&self, x: i32, y: i32, width: i32, height: i32) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { i: x },
            wl_argument { i: y },
            wl_argument { i: width },
            wl_argument { i: height },
        ];
        // SAFETY: the arguments match the request's signature, "iiii".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }

    /// `xdg_positioner.set_anchor`: set anchor rectangle anchor
    fn set_anchor(&self, anchor: XdgPositionerAnchor) {
        let proxy = self.obj();
        let mut args = [wl_argument { u: anchor.0 }];
        // SAFETY: the arguments match the request's signature, "u".
        unsafe { proxy.marshal(3, &mut args, 0) };
    }

    /// `xdg_positioner.set_gravity`: set child surface gravity
    fn set_gravity(&self, gravity: XdgPositionerGravity) {
        let proxy = self.obj();
        let mut args = [wl_argument { u: gravity.0 }];
        // SAFETY: the arguments match the request's signature, "u".
        unsafe { proxy.marshal(4, &mut args, 0) };
    }

    /// `xdg_positioner.set_constraint_adjustment`: set the adjustment to be done when constrained
    fn set_constraint_adjustment(&self, constraint_adjustment: XdgPositionerConstraintAdjustment) {
        let proxy = self.obj();
        let mut args = [wl_argument {
            u: constraint_adjustment.0,
        }];
        // SAFETY: the arguments match the request's signature, "u".
        unsafe { proxy.marshal(5, &mut args, 0) };
    }

    /// `xdg_positioner.set_offset`: set surface position offset
    fn set_offset(&self, x: i32, y: i32) {
        let proxy = self.obj();
        let mut args = [wl_argument { i: x }, wl_argument { i: y }];
        // SAFETY: the arguments match the request's signature, "ii".
        unsafe { proxy.marshal(6, &mut args, 0) };
    }

    /// `xdg_positioner.set_reactive`: continuously reconstrain the surface
    fn set_reactive(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "3".
        unsafe { proxy.marshal(7, &mut args, 0) };
    }

    /// `xdg_positioner.set_parent_size`
    fn set_parent_size(&self, parent_width: i32, parent_height: i32) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { i: parent_width },
            wl_argument { i: parent_height },
        ];
        // SAFETY: the arguments match the request's signature, "3ii".
        unsafe { proxy.marshal(8, &mut args, 0) };
    }

    /// `xdg_positioner.set_parent_configure`: set parent configure this is a response to
    fn set_parent_configure(&self, serial: u32) {
        let proxy = self.obj();
        let mut args = [wl_argument { u: serial }];
        // SAFETY: the arguments match the request's signature, "3u".
        unsafe { proxy.marshal(9, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgPositioner>> XdgPositionerRequests for T {}

impl Proxy<XdgPositioner> {
    /// `xdg_positioner.destroy`: destroy the xdg_positioner object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// xdg_surface
// ---------------------------------------------------------------------------

static XDG_SURFACE_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_SURFACE_GET_TOPLEVEL_REQUEST_TYPES: [IfacePtr; 1] = [Some(&XDG_TOPLEVEL_INTERFACE)];
static XDG_SURFACE_GET_POPUP_REQUEST_TYPES: [IfacePtr; 3] = [
    Some(&XDG_POPUP_INTERFACE),
    Some(&XDG_SURFACE_INTERFACE),
    Some(&XDG_POSITIONER_INTERFACE),
];
static XDG_SURFACE_SET_WINDOW_GEOMETRY_REQUEST_TYPES: [IfacePtr; 4] = [None, None, None, None];
static XDG_SURFACE_ACK_CONFIGURE_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_SURFACE_REQUESTS: [wl_message; 5] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_SURFACE_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_toplevel".as_ptr(),
        signature: c"n".as_ptr(),
        types: XDG_SURFACE_GET_TOPLEVEL_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_popup".as_ptr(),
        signature: c"n?oo".as_ptr(),
        types: XDG_SURFACE_GET_POPUP_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_window_geometry".as_ptr(),
        signature: c"iiii".as_ptr(),
        types: XDG_SURFACE_SET_WINDOW_GEOMETRY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"ack_configure".as_ptr(),
        signature: c"u".as_ptr(),
        types: XDG_SURFACE_ACK_CONFIGURE_REQUEST_TYPES.as_ptr(),
    },
];
static XDG_SURFACE_CONFIGURE_EVENT_TYPES: [IfacePtr; 1] = [None];
static XDG_SURFACE_EVENTS: [wl_message; 1] = [wl_message {
    name: c"configure".as_ptr(),
    signature: c"u".as_ptr(),
    types: XDG_SURFACE_CONFIGURE_EVENT_TYPES.as_ptr(),
}];
/// The `wl_interface` of `xdg_surface` (`xdg_surface_interface`).
pub(crate) static XDG_SURFACE_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_surface".as_ptr(),
    version: 7,
    method_count: 5,
    methods: XDG_SURFACE_REQUESTS.as_ptr(),
    event_count: 1,
    events: XDG_SURFACE_EVENTS.as_ptr(),
};

/// `xdg_surface.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgSurfaceError(pub(crate) u32);

impl XdgSurfaceError {
    /// Surface was not fully constructed
    pub(crate) const NOT_CONSTRUCTED: XdgSurfaceError = XdgSurfaceError(1);
    /// Surface was already constructed
    pub(crate) const ALREADY_CONSTRUCTED: XdgSurfaceError = XdgSurfaceError(2);
    /// Attaching a buffer to an unconfigured surface
    pub(crate) const UNCONFIGURED_BUFFER: XdgSurfaceError = XdgSurfaceError(3);
    /// Invalid serial number when acking a configure event
    pub(crate) const INVALID_SERIAL: XdgSurfaceError = XdgSurfaceError(4);
    /// Width or height was zero or negative
    pub(crate) const INVALID_SIZE: XdgSurfaceError = XdgSurfaceError(5);
    /// Surface was destroyed before its role object
    pub(crate) const DEFUNCT_ROLE_OBJECT: XdgSurfaceError = XdgSurfaceError(6);
}

/// `xdg_surface`: desktop user interface surface base interface
#[derive(Debug)]
pub(crate) enum XdgSurface {}

impl XdgSurface {
    /// The version `xdg_surface.destroy` appeared in (`XDG_SURFACE_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_surface.get_toplevel` appeared in (`XDG_SURFACE_GET_TOPLEVEL_SINCE_VERSION`).
    pub(crate) const GET_TOPLEVEL_SINCE_VERSION: u32 = 1;
    /// The version `xdg_surface.get_popup` appeared in (`XDG_SURFACE_GET_POPUP_SINCE_VERSION`).
    pub(crate) const GET_POPUP_SINCE_VERSION: u32 = 1;
    /// The version `xdg_surface.set_window_geometry` appeared in (`XDG_SURFACE_SET_WINDOW_GEOMETRY_SINCE_VERSION`).
    pub(crate) const SET_WINDOW_GEOMETRY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_surface.ack_configure` appeared in (`XDG_SURFACE_ACK_CONFIGURE_SINCE_VERSION`).
    pub(crate) const ACK_CONFIGURE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_surface.configure` appeared in (`XDG_SURFACE_CONFIGURE_SINCE_VERSION`).
    pub(crate) const CONFIGURE_SINCE_VERSION: u32 = 1;
}

/// The events of `xdg_surface`.
#[derive(Debug)]
pub(crate) enum XdgSurfaceEvent {
    /// `xdg_surface.configure`: suggest a surface change
    Configure {
        /// serial of the configure event
        serial: u32,
    },
}

impl Interface for XdgSurface {
    const NAME: &'static str = "xdg_surface";
    const VERSION: u32 = 7;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = XdgSurfaceEvent;

    fn interface() -> &'static wl_interface {
        &XDG_SURFACE_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(XdgSurfaceEvent::Configure {
                    // SAFETY: argument 0 is a `uint`.
                    serial: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `xdg_surface`, for anything that is a proxy of it.
pub(crate) trait XdgSurfaceRequests: AsProxy<Interface = XdgSurface> {
    /// `xdg_surface.get_toplevel`: assign the xdg_toplevel surface role
    fn get_toplevel(&self) -> Proxy<XdgToplevel> {
        let proxy = self.obj();
        let mut args = [wl_argument { o: ptr::null_mut() }];
        // SAFETY: the arguments match the request's signature, "n".
        unsafe { proxy.marshal_constructor::<XdgToplevel>(1, &mut args, proxy.version(), 0) }
    }

    /// `xdg_surface.get_popup`: assign the xdg_popup surface role
    fn get_popup(
        &self,
        parent: Option<Obj<'_, XdgSurface>>,
        positioner: Obj<'_, XdgPositioner>,
    ) -> Proxy<XdgPopup> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument {
                o: parent.map_or(ptr::null_mut(), |o| o.raw()),
            },
            wl_argument {
                o: positioner.raw(),
            },
        ];
        // SAFETY: the arguments match the request's signature, "n?oo".
        unsafe { proxy.marshal_constructor::<XdgPopup>(2, &mut args, proxy.version(), 0) }
    }

    /// `xdg_surface.set_window_geometry`: set the new window geometry
    fn set_window_geometry(&self, x: i32, y: i32, width: i32, height: i32) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { i: x },
            wl_argument { i: y },
            wl_argument { i: width },
            wl_argument { i: height },
        ];
        // SAFETY: the arguments match the request's signature, "iiii".
        unsafe { proxy.marshal(3, &mut args, 0) };
    }

    /// `xdg_surface.ack_configure`: ack a configure event
    fn ack_configure(&self, serial: u32) {
        let proxy = self.obj();
        let mut args = [wl_argument { u: serial }];
        // SAFETY: the arguments match the request's signature, "u".
        unsafe { proxy.marshal(4, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgSurface>> XdgSurfaceRequests for T {}

impl Proxy<XdgSurface> {
    /// `xdg_surface.destroy`: destroy the xdg_surface
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// xdg_toplevel
// ---------------------------------------------------------------------------

static XDG_TOPLEVEL_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_SET_PARENT_REQUEST_TYPES: [IfacePtr; 1] = [Some(&XDG_TOPLEVEL_INTERFACE)];
static XDG_TOPLEVEL_SET_TITLE_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_TOPLEVEL_SET_APP_ID_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_TOPLEVEL_SHOW_WINDOW_MENU_REQUEST_TYPES: [IfacePtr; 4] =
    [Some(&super::wayland::WL_SEAT_INTERFACE), None, None, None];
static XDG_TOPLEVEL_MOVE_REQUEST_TYPES: [IfacePtr; 2] =
    [Some(&super::wayland::WL_SEAT_INTERFACE), None];
static XDG_TOPLEVEL_RESIZE_REQUEST_TYPES: [IfacePtr; 3] =
    [Some(&super::wayland::WL_SEAT_INTERFACE), None, None];
static XDG_TOPLEVEL_SET_MAX_SIZE_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static XDG_TOPLEVEL_SET_MIN_SIZE_REQUEST_TYPES: [IfacePtr; 2] = [None, None];
static XDG_TOPLEVEL_SET_MAXIMIZED_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_UNSET_MAXIMIZED_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_SET_FULLSCREEN_REQUEST_TYPES: [IfacePtr; 1] =
    [Some(&super::wayland::WL_OUTPUT_INTERFACE)];
static XDG_TOPLEVEL_UNSET_FULLSCREEN_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_SET_MINIMIZED_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_REQUESTS: [wl_message; 14] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_parent".as_ptr(),
        signature: c"?o".as_ptr(),
        types: XDG_TOPLEVEL_SET_PARENT_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_title".as_ptr(),
        signature: c"s".as_ptr(),
        types: XDG_TOPLEVEL_SET_TITLE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_app_id".as_ptr(),
        signature: c"s".as_ptr(),
        types: XDG_TOPLEVEL_SET_APP_ID_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"show_window_menu".as_ptr(),
        signature: c"ouii".as_ptr(),
        types: XDG_TOPLEVEL_SHOW_WINDOW_MENU_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"move".as_ptr(),
        signature: c"ou".as_ptr(),
        types: XDG_TOPLEVEL_MOVE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"resize".as_ptr(),
        signature: c"ouu".as_ptr(),
        types: XDG_TOPLEVEL_RESIZE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_max_size".as_ptr(),
        signature: c"ii".as_ptr(),
        types: XDG_TOPLEVEL_SET_MAX_SIZE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_min_size".as_ptr(),
        signature: c"ii".as_ptr(),
        types: XDG_TOPLEVEL_SET_MIN_SIZE_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_maximized".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_SET_MAXIMIZED_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"unset_maximized".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_UNSET_MAXIMIZED_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_fullscreen".as_ptr(),
        signature: c"?o".as_ptr(),
        types: XDG_TOPLEVEL_SET_FULLSCREEN_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"unset_fullscreen".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_UNSET_FULLSCREEN_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_minimized".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_SET_MINIMIZED_REQUEST_TYPES.as_ptr(),
    },
];
static XDG_TOPLEVEL_CONFIGURE_EVENT_TYPES: [IfacePtr; 3] = [None, None, None];
static XDG_TOPLEVEL_CLOSE_EVENT_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_CONFIGURE_BOUNDS_EVENT_TYPES: [IfacePtr; 2] = [None, None];
static XDG_TOPLEVEL_WM_CAPABILITIES_EVENT_TYPES: [IfacePtr; 1] = [None];
static XDG_TOPLEVEL_EVENTS: [wl_message; 4] = [
    wl_message {
        name: c"configure".as_ptr(),
        signature: c"iia".as_ptr(),
        types: XDG_TOPLEVEL_CONFIGURE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"close".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_CLOSE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"configure_bounds".as_ptr(),
        signature: c"4ii".as_ptr(),
        types: XDG_TOPLEVEL_CONFIGURE_BOUNDS_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"wm_capabilities".as_ptr(),
        signature: c"5a".as_ptr(),
        types: XDG_TOPLEVEL_WM_CAPABILITIES_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_toplevel` (`xdg_toplevel_interface`).
pub(crate) static XDG_TOPLEVEL_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_toplevel".as_ptr(),
    version: 7,
    method_count: 14,
    methods: XDG_TOPLEVEL_REQUESTS.as_ptr(),
    event_count: 4,
    events: XDG_TOPLEVEL_EVENTS.as_ptr(),
};

/// `xdg_toplevel.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgToplevelError(pub(crate) u32);

impl XdgToplevelError {
    /// provided value is not a valid variant of the resize_edge enum
    pub(crate) const INVALID_RESIZE_EDGE: XdgToplevelError = XdgToplevelError(0);
    /// invalid parent toplevel
    pub(crate) const INVALID_PARENT: XdgToplevelError = XdgToplevelError(1);
    /// client provided an invalid min or max size
    pub(crate) const INVALID_SIZE: XdgToplevelError = XdgToplevelError(2);
}

/// `xdg_toplevel.resize_edge`: edge values for resizing
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgToplevelResizeEdge(pub(crate) u32);

impl XdgToplevelResizeEdge {
    pub(crate) const NONE: XdgToplevelResizeEdge = XdgToplevelResizeEdge(0);
    pub(crate) const TOP: XdgToplevelResizeEdge = XdgToplevelResizeEdge(1);
    pub(crate) const BOTTOM: XdgToplevelResizeEdge = XdgToplevelResizeEdge(2);
    pub(crate) const LEFT: XdgToplevelResizeEdge = XdgToplevelResizeEdge(4);
    pub(crate) const TOP_LEFT: XdgToplevelResizeEdge = XdgToplevelResizeEdge(5);
    pub(crate) const BOTTOM_LEFT: XdgToplevelResizeEdge = XdgToplevelResizeEdge(6);
    pub(crate) const RIGHT: XdgToplevelResizeEdge = XdgToplevelResizeEdge(8);
    pub(crate) const TOP_RIGHT: XdgToplevelResizeEdge = XdgToplevelResizeEdge(9);
    pub(crate) const BOTTOM_RIGHT: XdgToplevelResizeEdge = XdgToplevelResizeEdge(10);
}

/// `xdg_toplevel.state`: types of state on the surface
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgToplevelState(pub(crate) u32);

impl XdgToplevelState {
    /// the surface is maximized
    pub(crate) const MAXIMIZED: XdgToplevelState = XdgToplevelState(1);
    /// the surface is fullscreen
    pub(crate) const FULLSCREEN: XdgToplevelState = XdgToplevelState(2);
    /// the surface is being resized
    pub(crate) const RESIZING: XdgToplevelState = XdgToplevelState(3);
    /// the surface is now activated
    pub(crate) const ACTIVATED: XdgToplevelState = XdgToplevelState(4);
    /// the surface’s left edge is tiled
    pub(crate) const TILED_LEFT: XdgToplevelState = XdgToplevelState(5);
    /// the surface’s right edge is tiled
    pub(crate) const TILED_RIGHT: XdgToplevelState = XdgToplevelState(6);
    /// the surface’s top edge is tiled
    pub(crate) const TILED_TOP: XdgToplevelState = XdgToplevelState(7);
    /// the surface’s bottom edge is tiled
    pub(crate) const TILED_BOTTOM: XdgToplevelState = XdgToplevelState(8);
    /// surface repaint is suspended
    pub(crate) const SUSPENDED: XdgToplevelState = XdgToplevelState(9);
    /// the surface’s left edge is constrained
    pub(crate) const CONSTRAINED_LEFT: XdgToplevelState = XdgToplevelState(10);
    /// the surface’s right edge is constrained
    pub(crate) const CONSTRAINED_RIGHT: XdgToplevelState = XdgToplevelState(11);
    /// the surface’s top edge is constrained
    pub(crate) const CONSTRAINED_TOP: XdgToplevelState = XdgToplevelState(12);
    /// the surface’s bottom edge is tiled
    pub(crate) const CONSTRAINED_BOTTOM: XdgToplevelState = XdgToplevelState(13);
}

/// `xdg_toplevel.wm_capabilities`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgToplevelWmCapabilities(pub(crate) u32);

impl XdgToplevelWmCapabilities {
    /// show_window_menu is available
    pub(crate) const WINDOW_MENU: XdgToplevelWmCapabilities = XdgToplevelWmCapabilities(1);
    /// set_maximized and unset_maximized are available
    pub(crate) const MAXIMIZE: XdgToplevelWmCapabilities = XdgToplevelWmCapabilities(2);
    /// set_fullscreen and unset_fullscreen are available
    pub(crate) const FULLSCREEN: XdgToplevelWmCapabilities = XdgToplevelWmCapabilities(3);
    /// set_minimized is available
    pub(crate) const MINIMIZE: XdgToplevelWmCapabilities = XdgToplevelWmCapabilities(4);
}

/// `xdg_toplevel`: toplevel surface
#[derive(Debug)]
pub(crate) enum XdgToplevel {}

impl XdgToplevel {
    /// The version `xdg_toplevel.destroy` appeared in (`XDG_TOPLEVEL_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_parent` appeared in (`XDG_TOPLEVEL_SET_PARENT_SINCE_VERSION`).
    pub(crate) const SET_PARENT_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_title` appeared in (`XDG_TOPLEVEL_SET_TITLE_SINCE_VERSION`).
    pub(crate) const SET_TITLE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_app_id` appeared in (`XDG_TOPLEVEL_SET_APP_ID_SINCE_VERSION`).
    pub(crate) const SET_APP_ID_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.show_window_menu` appeared in (`XDG_TOPLEVEL_SHOW_WINDOW_MENU_SINCE_VERSION`).
    pub(crate) const SHOW_WINDOW_MENU_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.move` appeared in (`XDG_TOPLEVEL_MOVE_SINCE_VERSION`).
    pub(crate) const MOVE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.resize` appeared in (`XDG_TOPLEVEL_RESIZE_SINCE_VERSION`).
    pub(crate) const RESIZE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_max_size` appeared in (`XDG_TOPLEVEL_SET_MAX_SIZE_SINCE_VERSION`).
    pub(crate) const SET_MAX_SIZE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_min_size` appeared in (`XDG_TOPLEVEL_SET_MIN_SIZE_SINCE_VERSION`).
    pub(crate) const SET_MIN_SIZE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_maximized` appeared in (`XDG_TOPLEVEL_SET_MAXIMIZED_SINCE_VERSION`).
    pub(crate) const SET_MAXIMIZED_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.unset_maximized` appeared in (`XDG_TOPLEVEL_UNSET_MAXIMIZED_SINCE_VERSION`).
    pub(crate) const UNSET_MAXIMIZED_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_fullscreen` appeared in (`XDG_TOPLEVEL_SET_FULLSCREEN_SINCE_VERSION`).
    pub(crate) const SET_FULLSCREEN_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.unset_fullscreen` appeared in (`XDG_TOPLEVEL_UNSET_FULLSCREEN_SINCE_VERSION`).
    pub(crate) const UNSET_FULLSCREEN_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.set_minimized` appeared in (`XDG_TOPLEVEL_SET_MINIMIZED_SINCE_VERSION`).
    pub(crate) const SET_MINIMIZED_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.configure` appeared in (`XDG_TOPLEVEL_CONFIGURE_SINCE_VERSION`).
    pub(crate) const CONFIGURE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.close` appeared in (`XDG_TOPLEVEL_CLOSE_SINCE_VERSION`).
    pub(crate) const CLOSE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel.configure_bounds` appeared in (`XDG_TOPLEVEL_CONFIGURE_BOUNDS_SINCE_VERSION`).
    pub(crate) const CONFIGURE_BOUNDS_SINCE_VERSION: u32 = 4;
    /// The version `xdg_toplevel.wm_capabilities` appeared in (`XDG_TOPLEVEL_WM_CAPABILITIES_SINCE_VERSION`).
    pub(crate) const WM_CAPABILITIES_SINCE_VERSION: u32 = 5;
}

/// The events of `xdg_toplevel`.
#[derive(Debug)]
pub(crate) enum XdgToplevelEvent<'a> {
    /// `xdg_toplevel.configure`: suggest a surface change
    Configure {
        width: i32,
        height: i32,
        states: &'a [u8],
    },
    /// `xdg_toplevel.close`: surface wants to be closed
    Close,
    /// `xdg_toplevel.configure_bounds`: recommended window geometry bounds
    ConfigureBounds { width: i32, height: i32 },
    /// `xdg_toplevel.wm_capabilities`: compositor capabilities
    WmCapabilities {
        /// array of 32-bit capabilities
        capabilities: &'a [u8],
    },
}

impl Interface for XdgToplevel {
    const NAME: &'static str = "xdg_toplevel";
    const VERSION: u32 = 7;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = XdgToplevelEvent<'a>;

    fn interface() -> &'static wl_interface {
        &XDG_TOPLEVEL_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 3 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 3) };
                Some(XdgToplevelEvent::Configure {
                    // SAFETY: argument 0 is a `int`.
                    width: unsafe { a[0].i },
                    // SAFETY: argument 1 is a `int`.
                    height: unsafe { a[1].i },
                    // SAFETY: argument 2 is a `array`.
                    states: unsafe { arg_array(&a[2]) },
                })
            }
            1 => Some(XdgToplevelEvent::Close),
            2 => {
                // SAFETY: libwayland passes the 2 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 2) };
                Some(XdgToplevelEvent::ConfigureBounds {
                    // SAFETY: argument 0 is a `int`.
                    width: unsafe { a[0].i },
                    // SAFETY: argument 1 is a `int`.
                    height: unsafe { a[1].i },
                })
            }
            3 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(XdgToplevelEvent::WmCapabilities {
                    // SAFETY: argument 0 is a `array`.
                    capabilities: unsafe { arg_array(&a[0]) },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `xdg_toplevel`, for anything that is a proxy of it.
pub(crate) trait XdgToplevelRequests: AsProxy<Interface = XdgToplevel> {
    /// `xdg_toplevel.set_parent`: set the parent of this surface
    fn set_parent(&self, parent: Option<Obj<'_, XdgToplevel>>) {
        let proxy = self.obj();
        let mut args = [wl_argument {
            o: parent.map_or(ptr::null_mut(), |o| o.raw()),
        }];
        // SAFETY: the arguments match the request's signature, "?o".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }

    /// `xdg_toplevel.set_title`: set surface title
    fn set_title(&self, title: &str) {
        let proxy = self.obj();
        let c_title = cstring_arg(title);
        let mut args = [wl_argument {
            s: c_title.as_ptr(),
        }];
        // SAFETY: the arguments match the request's signature, "s".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }

    /// `xdg_toplevel.set_app_id`: set application ID
    fn set_app_id(&self, app_id: &str) {
        let proxy = self.obj();
        let c_app_id = cstring_arg(app_id);
        let mut args = [wl_argument {
            s: c_app_id.as_ptr(),
        }];
        // SAFETY: the arguments match the request's signature, "s".
        unsafe { proxy.marshal(3, &mut args, 0) };
    }

    /// `xdg_toplevel.show_window_menu`: show the window menu
    fn show_window_menu(&self, seat: Obj<'_, super::wayland::WlSeat>, serial: u32, x: i32, y: i32) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: seat.raw() },
            wl_argument { u: serial },
            wl_argument { i: x },
            wl_argument { i: y },
        ];
        // SAFETY: the arguments match the request's signature, "ouii".
        unsafe { proxy.marshal(4, &mut args, 0) };
    }

    /// `xdg_toplevel.move`: start an interactive move
    fn r#move(&self, seat: Obj<'_, super::wayland::WlSeat>, serial: u32) {
        let proxy = self.obj();
        let mut args = [wl_argument { o: seat.raw() }, wl_argument { u: serial }];
        // SAFETY: the arguments match the request's signature, "ou".
        unsafe { proxy.marshal(5, &mut args, 0) };
    }

    /// `xdg_toplevel.resize`: start an interactive resize
    fn resize(
        &self,
        seat: Obj<'_, super::wayland::WlSeat>,
        serial: u32,
        edges: XdgToplevelResizeEdge,
    ) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: seat.raw() },
            wl_argument { u: serial },
            wl_argument { u: edges.0 },
        ];
        // SAFETY: the arguments match the request's signature, "ouu".
        unsafe { proxy.marshal(6, &mut args, 0) };
    }

    /// `xdg_toplevel.set_max_size`: set the maximum size
    fn set_max_size(&self, width: i32, height: i32) {
        let proxy = self.obj();
        let mut args = [wl_argument { i: width }, wl_argument { i: height }];
        // SAFETY: the arguments match the request's signature, "ii".
        unsafe { proxy.marshal(7, &mut args, 0) };
    }

    /// `xdg_toplevel.set_min_size`: set the minimum size
    fn set_min_size(&self, width: i32, height: i32) {
        let proxy = self.obj();
        let mut args = [wl_argument { i: width }, wl_argument { i: height }];
        // SAFETY: the arguments match the request's signature, "ii".
        unsafe { proxy.marshal(8, &mut args, 0) };
    }

    /// `xdg_toplevel.set_maximized`: maximize the window
    fn set_maximized(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(9, &mut args, 0) };
    }

    /// `xdg_toplevel.unset_maximized`: unmaximize the window
    fn unset_maximized(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(10, &mut args, 0) };
    }

    /// `xdg_toplevel.set_fullscreen`: set the window as fullscreen on an output
    fn set_fullscreen(&self, output: Option<Obj<'_, super::wayland::WlOutput>>) {
        let proxy = self.obj();
        let mut args = [wl_argument {
            o: output.map_or(ptr::null_mut(), |o| o.raw()),
        }];
        // SAFETY: the arguments match the request's signature, "?o".
        unsafe { proxy.marshal(11, &mut args, 0) };
    }

    /// `xdg_toplevel.unset_fullscreen`: unset the window as fullscreen
    fn unset_fullscreen(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(12, &mut args, 0) };
    }

    /// `xdg_toplevel.set_minimized`: set the window as minimized
    fn set_minimized(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(13, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgToplevel>> XdgToplevelRequests for T {}

impl Proxy<XdgToplevel> {
    /// `xdg_toplevel.destroy`: destroy the xdg_toplevel
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// xdg_popup
// ---------------------------------------------------------------------------

static XDG_POPUP_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_POPUP_GRAB_REQUEST_TYPES: [IfacePtr; 2] =
    [Some(&super::wayland::WL_SEAT_INTERFACE), None];
static XDG_POPUP_REPOSITION_REQUEST_TYPES: [IfacePtr; 2] = [Some(&XDG_POSITIONER_INTERFACE), None];
static XDG_POPUP_REQUESTS: [wl_message; 3] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_POPUP_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"grab".as_ptr(),
        signature: c"ou".as_ptr(),
        types: XDG_POPUP_GRAB_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"reposition".as_ptr(),
        signature: c"3ou".as_ptr(),
        types: XDG_POPUP_REPOSITION_REQUEST_TYPES.as_ptr(),
    },
];
static XDG_POPUP_CONFIGURE_EVENT_TYPES: [IfacePtr; 4] = [None, None, None, None];
static XDG_POPUP_POPUP_DONE_EVENT_TYPES: [IfacePtr; 0] = [];
static XDG_POPUP_REPOSITIONED_EVENT_TYPES: [IfacePtr; 1] = [None];
static XDG_POPUP_EVENTS: [wl_message; 3] = [
    wl_message {
        name: c"configure".as_ptr(),
        signature: c"iiii".as_ptr(),
        types: XDG_POPUP_CONFIGURE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"popup_done".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_POPUP_POPUP_DONE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"repositioned".as_ptr(),
        signature: c"3u".as_ptr(),
        types: XDG_POPUP_REPOSITIONED_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_popup` (`xdg_popup_interface`).
pub(crate) static XDG_POPUP_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_popup".as_ptr(),
    version: 7,
    method_count: 3,
    methods: XDG_POPUP_REQUESTS.as_ptr(),
    event_count: 3,
    events: XDG_POPUP_EVENTS.as_ptr(),
};

/// `xdg_popup.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgPopupError(pub(crate) u32);

impl XdgPopupError {
    /// tried to grab after being mapped
    pub(crate) const INVALID_GRAB: XdgPopupError = XdgPopupError(0);
}

/// `xdg_popup`: short-lived, popup surfaces for menus
#[derive(Debug)]
pub(crate) enum XdgPopup {}

impl XdgPopup {
    /// The version `xdg_popup.destroy` appeared in (`XDG_POPUP_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_popup.grab` appeared in (`XDG_POPUP_GRAB_SINCE_VERSION`).
    pub(crate) const GRAB_SINCE_VERSION: u32 = 1;
    /// The version `xdg_popup.reposition` appeared in (`XDG_POPUP_REPOSITION_SINCE_VERSION`).
    pub(crate) const REPOSITION_SINCE_VERSION: u32 = 3;
    /// The version `xdg_popup.configure` appeared in (`XDG_POPUP_CONFIGURE_SINCE_VERSION`).
    pub(crate) const CONFIGURE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_popup.popup_done` appeared in (`XDG_POPUP_POPUP_DONE_SINCE_VERSION`).
    pub(crate) const POPUP_DONE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_popup.repositioned` appeared in (`XDG_POPUP_REPOSITIONED_SINCE_VERSION`).
    pub(crate) const REPOSITIONED_SINCE_VERSION: u32 = 3;
}

/// The events of `xdg_popup`.
#[derive(Debug)]
pub(crate) enum XdgPopupEvent {
    /// `xdg_popup.configure`: configure the popup surface
    Configure {
        /// x position relative to parent surface window geometry
        x: i32,
        /// y position relative to parent surface window geometry
        y: i32,
        /// window geometry width
        width: i32,
        /// window geometry height
        height: i32,
    },
    /// `xdg_popup.popup_done`: popup interaction is done
    PopupDone,
    /// `xdg_popup.repositioned`: signal the completion of a repositioned request
    Repositioned {
        /// reposition request token
        token: u32,
    },
}

impl Interface for XdgPopup {
    const NAME: &'static str = "xdg_popup";
    const VERSION: u32 = 7;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = XdgPopupEvent;

    fn interface() -> &'static wl_interface {
        &XDG_POPUP_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 4 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 4) };
                Some(XdgPopupEvent::Configure {
                    // SAFETY: argument 0 is a `int`.
                    x: unsafe { a[0].i },
                    // SAFETY: argument 1 is a `int`.
                    y: unsafe { a[1].i },
                    // SAFETY: argument 2 is a `int`.
                    width: unsafe { a[2].i },
                    // SAFETY: argument 3 is a `int`.
                    height: unsafe { a[3].i },
                })
            }
            1 => Some(XdgPopupEvent::PopupDone),
            2 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(XdgPopupEvent::Repositioned {
                    // SAFETY: argument 0 is a `uint`.
                    token: unsafe { a[0].u },
                })
            }
            _ => None,
        }
    }
}

/// The requests of `xdg_popup`, for anything that is a proxy of it.
pub(crate) trait XdgPopupRequests: AsProxy<Interface = XdgPopup> {
    /// `xdg_popup.grab`: make the popup take an explicit grab
    fn grab(&self, seat: Obj<'_, super::wayland::WlSeat>, serial: u32) {
        let proxy = self.obj();
        let mut args = [wl_argument { o: seat.raw() }, wl_argument { u: serial }];
        // SAFETY: the arguments match the request's signature, "ou".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }

    /// `xdg_popup.reposition`: recalculate the popup's location
    fn reposition(&self, positioner: Obj<'_, XdgPositioner>, token: u32) {
        let proxy = self.obj();
        let mut args = [
            wl_argument {
                o: positioner.raw(),
            },
            wl_argument { u: token },
        ];
        // SAFETY: the arguments match the request's signature, "3ou".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgPopup>> XdgPopupRequests for T {}

impl Proxy<XdgPopup> {
    /// `xdg_popup.destroy`: remove xdg_popup interface
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
