// Rust bindings of the xdg_toplevel_icon_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/xdg-toplevel-icon-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2023-2024 Matthias Klumpp
//      Copyright ©      2024 David Edmundson
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `xdg_toplevel_icon_v1` protocol (`xdg-toplevel-icon-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// xdg_toplevel_icon_manager_v1
// ---------------------------------------------------------------------------

static XDG_TOPLEVEL_ICON_MANAGER_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_ICON_MANAGER_V1_CREATE_ICON_REQUEST_TYPES: [IfacePtr; 1] =
    [Some(&XDG_TOPLEVEL_ICON_V1_INTERFACE)];
static XDG_TOPLEVEL_ICON_MANAGER_V1_SET_ICON_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&super::xdg_shell::XDG_TOPLEVEL_INTERFACE),
    Some(&XDG_TOPLEVEL_ICON_V1_INTERFACE),
];
static XDG_TOPLEVEL_ICON_MANAGER_V1_REQUESTS: [wl_message; 3] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_ICON_MANAGER_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"create_icon".as_ptr(),
        signature: c"n".as_ptr(),
        types: XDG_TOPLEVEL_ICON_MANAGER_V1_CREATE_ICON_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_icon".as_ptr(),
        signature: c"o?o".as_ptr(),
        types: XDG_TOPLEVEL_ICON_MANAGER_V1_SET_ICON_REQUEST_TYPES.as_ptr(),
    },
];
static XDG_TOPLEVEL_ICON_MANAGER_V1_ICON_SIZE_EVENT_TYPES: [IfacePtr; 1] = [None];
static XDG_TOPLEVEL_ICON_MANAGER_V1_DONE_EVENT_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_ICON_MANAGER_V1_EVENTS: [wl_message; 2] = [
    wl_message {
        name: c"icon_size".as_ptr(),
        signature: c"i".as_ptr(),
        types: XDG_TOPLEVEL_ICON_MANAGER_V1_ICON_SIZE_EVENT_TYPES.as_ptr(),
    },
    wl_message {
        name: c"done".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_ICON_MANAGER_V1_DONE_EVENT_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_toplevel_icon_manager_v1` (`xdg_toplevel_icon_manager_v1_interface`).
pub(crate) static XDG_TOPLEVEL_ICON_MANAGER_V1_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_toplevel_icon_manager_v1".as_ptr(),
    version: 1,
    method_count: 3,
    methods: XDG_TOPLEVEL_ICON_MANAGER_V1_REQUESTS.as_ptr(),
    event_count: 2,
    events: XDG_TOPLEVEL_ICON_MANAGER_V1_EVENTS.as_ptr(),
};

/// `xdg_toplevel_icon_manager_v1`: interface to manage toplevel icons
#[derive(Debug)]
pub(crate) enum XdgToplevelIconManagerV1 {}

impl XdgToplevelIconManagerV1 {
    /// The version `xdg_toplevel_icon_manager_v1.destroy` appeared in (`XDG_TOPLEVEL_ICON_MANAGER_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel_icon_manager_v1.create_icon` appeared in (`XDG_TOPLEVEL_ICON_MANAGER_V1_CREATE_ICON_SINCE_VERSION`).
    pub(crate) const CREATE_ICON_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel_icon_manager_v1.set_icon` appeared in (`XDG_TOPLEVEL_ICON_MANAGER_V1_SET_ICON_SINCE_VERSION`).
    pub(crate) const SET_ICON_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel_icon_manager_v1.icon_size` appeared in (`XDG_TOPLEVEL_ICON_MANAGER_V1_ICON_SIZE_SINCE_VERSION`).
    pub(crate) const ICON_SIZE_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel_icon_manager_v1.done` appeared in (`XDG_TOPLEVEL_ICON_MANAGER_V1_DONE_SINCE_VERSION`).
    pub(crate) const DONE_SINCE_VERSION: u32 = 1;
}

/// The events of `xdg_toplevel_icon_manager_v1`.
#[derive(Debug)]
pub(crate) enum XdgToplevelIconManagerV1Event {
    /// `xdg_toplevel_icon_manager_v1.icon_size`: describes a supported & preferred icon size
    IconSize {
        /// the edge size of the square icon in surface-local coordinates, e.g. 64
        size: i32,
    },
    /// `xdg_toplevel_icon_manager_v1.done`: all information has been sent
    Done,
}

impl Interface for XdgToplevelIconManagerV1 {
    const NAME: &'static str = "xdg_toplevel_icon_manager_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = XdgToplevelIconManagerV1Event;

    fn interface() -> &'static wl_interface {
        &XDG_TOPLEVEL_ICON_MANAGER_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, args);
        match opcode {
            0 => {
                // SAFETY: libwayland passes the 1 arguments of the
                // event's signature.
                let a = unsafe { std::slice::from_raw_parts(args, 1) };
                Some(XdgToplevelIconManagerV1Event::IconSize {
                    // SAFETY: argument 0 is a `int`.
                    size: unsafe { a[0].i },
                })
            }
            1 => Some(XdgToplevelIconManagerV1Event::Done),
            _ => None,
        }
    }
}

/// The requests of `xdg_toplevel_icon_manager_v1`, for anything that is a proxy of it.
pub(crate) trait XdgToplevelIconManagerV1Requests:
    AsProxy<Interface = XdgToplevelIconManagerV1>
{
    /// `xdg_toplevel_icon_manager_v1.create_icon`: create a new icon instance
    fn create_icon(&self) -> Proxy<XdgToplevelIconV1> {
        let proxy = self.obj();
        let mut args = [wl_argument { o: ptr::null_mut() }];
        // SAFETY: the arguments match the request's signature, "n".
        unsafe { proxy.marshal_constructor::<XdgToplevelIconV1>(1, &mut args, proxy.version(), 0) }
    }

    /// `xdg_toplevel_icon_manager_v1.set_icon`: set an icon on a toplevel window
    fn set_icon(
        &self,
        toplevel: Obj<'_, super::xdg_shell::XdgToplevel>,
        icon: Option<Obj<'_, XdgToplevelIconV1>>,
    ) {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: toplevel.raw() },
            wl_argument {
                o: icon.map_or(ptr::null_mut(), |o| o.raw()),
            },
        ];
        // SAFETY: the arguments match the request's signature, "o?o".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgToplevelIconManagerV1>> XdgToplevelIconManagerV1Requests for T {}

impl Proxy<XdgToplevelIconManagerV1> {
    /// `xdg_toplevel_icon_manager_v1.destroy`: destroy the toplevel icon manager
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// xdg_toplevel_icon_v1
// ---------------------------------------------------------------------------

static XDG_TOPLEVEL_ICON_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_TOPLEVEL_ICON_V1_SET_NAME_REQUEST_TYPES: [IfacePtr; 1] = [None];
static XDG_TOPLEVEL_ICON_V1_ADD_BUFFER_REQUEST_TYPES: [IfacePtr; 2] =
    [Some(&super::wayland::WL_BUFFER_INTERFACE), None];
static XDG_TOPLEVEL_ICON_V1_REQUESTS: [wl_message; 3] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_TOPLEVEL_ICON_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_name".as_ptr(),
        signature: c"s".as_ptr(),
        types: XDG_TOPLEVEL_ICON_V1_SET_NAME_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"add_buffer".as_ptr(),
        signature: c"oi".as_ptr(),
        types: XDG_TOPLEVEL_ICON_V1_ADD_BUFFER_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_toplevel_icon_v1` (`xdg_toplevel_icon_v1_interface`).
pub(crate) static XDG_TOPLEVEL_ICON_V1_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_toplevel_icon_v1".as_ptr(),
    version: 1,
    method_count: 3,
    methods: XDG_TOPLEVEL_ICON_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `xdg_toplevel_icon_v1.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgToplevelIconV1Error(pub(crate) u32);

impl XdgToplevelIconV1Error {
    /// the provided buffer does not satisfy requirements
    pub(crate) const INVALID_BUFFER: XdgToplevelIconV1Error = XdgToplevelIconV1Error(1);
    /// the icon has already been assigned to a toplevel and must not be changed
    pub(crate) const IMMUTABLE: XdgToplevelIconV1Error = XdgToplevelIconV1Error(2);
    /// the provided buffer has been destroyed before the toplevel icon
    pub(crate) const NO_BUFFER: XdgToplevelIconV1Error = XdgToplevelIconV1Error(3);
}

/// `xdg_toplevel_icon_v1`: a toplevel window icon
#[derive(Debug)]
pub(crate) enum XdgToplevelIconV1 {}

impl XdgToplevelIconV1 {
    /// The version `xdg_toplevel_icon_v1.destroy` appeared in (`XDG_TOPLEVEL_ICON_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel_icon_v1.set_name` appeared in (`XDG_TOPLEVEL_ICON_V1_SET_NAME_SINCE_VERSION`).
    pub(crate) const SET_NAME_SINCE_VERSION: u32 = 1;
    /// The version `xdg_toplevel_icon_v1.add_buffer` appeared in (`XDG_TOPLEVEL_ICON_V1_ADD_BUFFER_SINCE_VERSION`).
    pub(crate) const ADD_BUFFER_SINCE_VERSION: u32 = 1;
}

impl Interface for XdgToplevelIconV1 {
    const NAME: &'static str = "xdg_toplevel_icon_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &XDG_TOPLEVEL_ICON_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `xdg_toplevel_icon_v1`, for anything that is a proxy of it.
pub(crate) trait XdgToplevelIconV1Requests: AsProxy<Interface = XdgToplevelIconV1> {
    /// `xdg_toplevel_icon_v1.set_name`: set an icon name
    fn set_name(&self, icon_name: &str) {
        let proxy = self.obj();
        let c_icon_name = cstring_arg(icon_name);
        let mut args = [wl_argument {
            s: c_icon_name.as_ptr(),
        }];
        // SAFETY: the arguments match the request's signature, "s".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }

    /// `xdg_toplevel_icon_v1.add_buffer`: add icon data from a pixel buffer
    fn add_buffer(&self, buffer: Obj<'_, super::wayland::WlBuffer>, scale: i32) {
        let proxy = self.obj();
        let mut args = [wl_argument { o: buffer.raw() }, wl_argument { i: scale }];
        // SAFETY: the arguments match the request's signature, "oi".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgToplevelIconV1>> XdgToplevelIconV1Requests for T {}

impl Proxy<XdgToplevelIconV1> {
    /// `xdg_toplevel_icon_v1.destroy`: destroy the icon object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
