// Rust bindings of the xdg_dialog_v1 Wayland protocol, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/xdg-dialog-v1.xml.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
//      Copyright © 2023 Carlos Garnacho
//
//      Permission is hereby granted, free of charge, to any person obtaining a
//      copy of this software and associated documentation files (the "Software"),
//      to deal in the Software without restriction, including without limitation
//      the rights to use, copy, modify, merge, publish, distribute, sublicense,
//      and/or sell copies of the Software, and to permit persons to whom the
//      Software is furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice (including the next
//      paragraph) shall be included in all copies or substantial portions of the
//      Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
//      THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//

//! The `xdg_dialog_v1` protocol (`xdg-dialog-v1.xml`).

#![allow(dead_code)] // (the bindings cover the whole protocol)
#![allow(
    clippy::too_many_arguments,
    clippy::needless_lifetimes,
    clippy::unused_unit,
    clippy::enum_variant_names
)]

#[allow(unused_imports)]
use std::ffi::CStr;
#[allow(unused_imports)]
use std::os::fd::{BorrowedFd, OwnedFd};
use std::ptr;
use std::sync::Arc;

#[allow(unused_imports)]
use super::super::client::{
    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed,
    Interface, NoEvents, Obj, Proxy, RawObj,
};
#[allow(unused_imports)]
use super::super::sys::{
    wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY,
};

// ---------------------------------------------------------------------------
// xdg_wm_dialog_v1
// ---------------------------------------------------------------------------

static XDG_WM_DIALOG_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_WM_DIALOG_V1_GET_XDG_DIALOG_REQUEST_TYPES: [IfacePtr; 2] = [
    Some(&XDG_DIALOG_V1_INTERFACE),
    Some(&super::xdg_shell::XDG_TOPLEVEL_INTERFACE),
];
static XDG_WM_DIALOG_V1_REQUESTS: [wl_message; 2] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_WM_DIALOG_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"get_xdg_dialog".as_ptr(),
        signature: c"no".as_ptr(),
        types: XDG_WM_DIALOG_V1_GET_XDG_DIALOG_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_wm_dialog_v1` (`xdg_wm_dialog_v1_interface`).
pub(crate) static XDG_WM_DIALOG_V1_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_wm_dialog_v1".as_ptr(),
    version: 1,
    method_count: 2,
    methods: XDG_WM_DIALOG_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `xdg_wm_dialog_v1.error`
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub(crate) struct XdgWmDialogV1Error(pub(crate) u32);

impl XdgWmDialogV1Error {
    /// the xdg_toplevel object has already been used to create a xdg_dialog_v1
    pub(crate) const ALREADY_USED: XdgWmDialogV1Error = XdgWmDialogV1Error(0);
}

/// `xdg_wm_dialog_v1`: create dialogs related to other toplevels
#[derive(Debug)]
pub(crate) enum XdgWmDialogV1 {}

impl XdgWmDialogV1 {
    /// The version `xdg_wm_dialog_v1.destroy` appeared in (`XDG_WM_DIALOG_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_wm_dialog_v1.get_xdg_dialog` appeared in (`XDG_WM_DIALOG_V1_GET_XDG_DIALOG_SINCE_VERSION`).
    pub(crate) const GET_XDG_DIALOG_SINCE_VERSION: u32 = 1;
}

impl Interface for XdgWmDialogV1 {
    const NAME: &'static str = "xdg_wm_dialog_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &XDG_WM_DIALOG_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `xdg_wm_dialog_v1`, for anything that is a proxy of it.
pub(crate) trait XdgWmDialogV1Requests: AsProxy<Interface = XdgWmDialogV1> {
    /// `xdg_wm_dialog_v1.get_xdg_dialog`: create a dialog object
    fn get_xdg_dialog(
        &self,
        toplevel: Obj<'_, super::xdg_shell::XdgToplevel>,
    ) -> Proxy<XdgDialogV1> {
        let proxy = self.obj();
        let mut args = [
            wl_argument { o: ptr::null_mut() },
            wl_argument { o: toplevel.raw() },
        ];
        // SAFETY: the arguments match the request's signature, "no".
        unsafe { proxy.marshal_constructor::<XdgDialogV1>(1, &mut args, proxy.version(), 0) }
    }
}

impl<T: AsProxy<Interface = XdgWmDialogV1>> XdgWmDialogV1Requests for T {}

impl Proxy<XdgWmDialogV1> {
    /// `xdg_wm_dialog_v1.destroy`: destroy the dialog manager object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}

// ---------------------------------------------------------------------------
// xdg_dialog_v1
// ---------------------------------------------------------------------------

static XDG_DIALOG_V1_DESTROY_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_DIALOG_V1_SET_MODAL_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_DIALOG_V1_UNSET_MODAL_REQUEST_TYPES: [IfacePtr; 0] = [];
static XDG_DIALOG_V1_REQUESTS: [wl_message; 3] = [
    wl_message {
        name: c"destroy".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_DIALOG_V1_DESTROY_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"set_modal".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_DIALOG_V1_SET_MODAL_REQUEST_TYPES.as_ptr(),
    },
    wl_message {
        name: c"unset_modal".as_ptr(),
        signature: c"".as_ptr(),
        types: XDG_DIALOG_V1_UNSET_MODAL_REQUEST_TYPES.as_ptr(),
    },
];
/// The `wl_interface` of `xdg_dialog_v1` (`xdg_dialog_v1_interface`).
pub(crate) static XDG_DIALOG_V1_INTERFACE: wl_interface = wl_interface {
    name: c"xdg_dialog_v1".as_ptr(),
    version: 1,
    method_count: 3,
    methods: XDG_DIALOG_V1_REQUESTS.as_ptr(),
    event_count: 0,
    events: ptr::null(),
};

/// `xdg_dialog_v1`: dialog object
#[derive(Debug)]
pub(crate) enum XdgDialogV1 {}

impl XdgDialogV1 {
    /// The version `xdg_dialog_v1.destroy` appeared in (`XDG_DIALOG_V1_DESTROY_SINCE_VERSION`).
    pub(crate) const DESTROY_SINCE_VERSION: u32 = 1;
    /// The version `xdg_dialog_v1.set_modal` appeared in (`XDG_DIALOG_V1_SET_MODAL_SINCE_VERSION`).
    pub(crate) const SET_MODAL_SINCE_VERSION: u32 = 1;
    /// The version `xdg_dialog_v1.unset_modal` appeared in (`XDG_DIALOG_V1_UNSET_MODAL_SINCE_VERSION`).
    pub(crate) const UNSET_MODAL_SINCE_VERSION: u32 = 1;
}

impl Interface for XdgDialogV1 {
    const NAME: &'static str = "xdg_dialog_v1";
    const VERSION: u32 = 1;
    const DESTRUCTOR: Option<(u32, u32)> = Some((0, 1));
    type Event<'a> = NoEvents;

    fn interface() -> &'static wl_interface {
        &XDG_DIALOG_V1_INTERFACE
    }

    unsafe fn decode<'a>(
        conn: &'a Arc<Conn>,
        opcode: u32,
        args: *const wl_argument,
    ) -> Option<Self::Event<'a>> {
        let _ = (conn, opcode, args);
        None
    }
}

/// The requests of `xdg_dialog_v1`, for anything that is a proxy of it.
pub(crate) trait XdgDialogV1Requests: AsProxy<Interface = XdgDialogV1> {
    /// `xdg_dialog_v1.set_modal`: mark dialog as modal
    fn set_modal(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(1, &mut args, 0) };
    }

    /// `xdg_dialog_v1.unset_modal`: mark dialog as not modal
    fn unset_modal(&self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(2, &mut args, 0) };
    }
}

impl<T: AsProxy<Interface = XdgDialogV1>> XdgDialogV1Requests for T {}

impl Proxy<XdgDialogV1> {
    /// `xdg_dialog_v1.destroy`: destroy the dialog object
    pub(crate) fn destroy(self) {
        let proxy = self.obj();
        let mut args: [wl_argument; 0] = [];
        // SAFETY: the arguments match the request's signature, "".
        unsafe { proxy.marshal(0, &mut args, WL_MARSHAL_FLAG_DESTROY) };
        self.forget_destroyed();
    }
}
