// Rust translation of include/SDL3/SDL_keycode.h from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

//! Virtual key codes and modifier flags.

use std::fmt;
use std::ops::{BitAnd, BitAndAssign, BitOr, BitOrAssign, BitXorAssign, Not};

use super::Scancode;

/// The SDL virtual key representation. Translation of `SDL_Keycode`.
///
/// Values of this type are used to represent keyboard keys using the current
/// layout of the keyboard. These values include Unicode values representing
/// the unmodified character that would be generated by pressing the key, or
/// an `SCANCODE_MASK` (`1 << 30`) | scancode for keys that don't generate
/// characters, or an `EXTENDED_MASK` (`1 << 29`) | index for a few extended keys.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Keycode(pub u32);

#[allow(non_upper_case_globals)]
impl Keycode {
    /// Translation of `SDLK_EXTENDED_MASK`.
    pub const EXTENDED_MASK: u32 = 1 << 29;
    /// Translation of `SDLK_SCANCODE_MASK`.
    pub const SCANCODE_MASK: u32 = 1 << 30;

    pub const UNKNOWN: Keycode = Keycode(0x00000000);
    pub const RETURN: Keycode = Keycode(0x0000000d);
    pub const ESCAPE: Keycode = Keycode(0x0000001b);
    pub const BACKSPACE: Keycode = Keycode(0x00000008);
    pub const TAB: Keycode = Keycode(0x00000009);
    pub const SPACE: Keycode = Keycode(0x00000020);
    pub const EXCLAIM: Keycode = Keycode(0x00000021);
    pub const DBLAPOSTROPHE: Keycode = Keycode(0x00000022);
    pub const HASH: Keycode = Keycode(0x00000023);
    pub const DOLLAR: Keycode = Keycode(0x00000024);
    pub const PERCENT: Keycode = Keycode(0x00000025);
    pub const AMPERSAND: Keycode = Keycode(0x00000026);
    pub const APOSTROPHE: Keycode = Keycode(0x00000027);
    pub const LEFTPAREN: Keycode = Keycode(0x00000028);
    pub const RIGHTPAREN: Keycode = Keycode(0x00000029);
    pub const ASTERISK: Keycode = Keycode(0x0000002a);
    pub const PLUS: Keycode = Keycode(0x0000002b);
    pub const COMMA: Keycode = Keycode(0x0000002c);
    pub const MINUS: Keycode = Keycode(0x0000002d);
    pub const PERIOD: Keycode = Keycode(0x0000002e);
    pub const SLASH: Keycode = Keycode(0x0000002f);
    pub const N0: Keycode = Keycode(0x00000030);
    pub const N1: Keycode = Keycode(0x00000031);
    pub const N2: Keycode = Keycode(0x00000032);
    pub const N3: Keycode = Keycode(0x00000033);
    pub const N4: Keycode = Keycode(0x00000034);
    pub const N5: Keycode = Keycode(0x00000035);
    pub const N6: Keycode = Keycode(0x00000036);
    pub const N7: Keycode = Keycode(0x00000037);
    pub const N8: Keycode = Keycode(0x00000038);
    pub const N9: Keycode = Keycode(0x00000039);
    pub const COLON: Keycode = Keycode(0x0000003a);
    pub const SEMICOLON: Keycode = Keycode(0x0000003b);
    pub const LESS: Keycode = Keycode(0x0000003c);
    pub const EQUALS: Keycode = Keycode(0x0000003d);
    pub const GREATER: Keycode = Keycode(0x0000003e);
    pub const QUESTION: Keycode = Keycode(0x0000003f);
    pub const AT: Keycode = Keycode(0x00000040);
    pub const LEFTBRACKET: Keycode = Keycode(0x0000005b);
    pub const BACKSLASH: Keycode = Keycode(0x0000005c);
    pub const RIGHTBRACKET: Keycode = Keycode(0x0000005d);
    pub const CARET: Keycode = Keycode(0x0000005e);
    pub const UNDERSCORE: Keycode = Keycode(0x0000005f);
    pub const GRAVE: Keycode = Keycode(0x00000060);
    pub const A: Keycode = Keycode(0x00000061);
    pub const B: Keycode = Keycode(0x00000062);
    pub const C: Keycode = Keycode(0x00000063);
    pub const D: Keycode = Keycode(0x00000064);
    pub const E: Keycode = Keycode(0x00000065);
    pub const F: Keycode = Keycode(0x00000066);
    pub const G: Keycode = Keycode(0x00000067);
    pub const H: Keycode = Keycode(0x00000068);
    pub const I: Keycode = Keycode(0x00000069);
    pub const J: Keycode = Keycode(0x0000006a);
    pub const K: Keycode = Keycode(0x0000006b);
    pub const L: Keycode = Keycode(0x0000006c);
    pub const M: Keycode = Keycode(0x0000006d);
    pub const N: Keycode = Keycode(0x0000006e);
    pub const O: Keycode = Keycode(0x0000006f);
    pub const P: Keycode = Keycode(0x00000070);
    pub const Q: Keycode = Keycode(0x00000071);
    pub const R: Keycode = Keycode(0x00000072);
    pub const S: Keycode = Keycode(0x00000073);
    pub const T: Keycode = Keycode(0x00000074);
    pub const U: Keycode = Keycode(0x00000075);
    pub const V: Keycode = Keycode(0x00000076);
    pub const W: Keycode = Keycode(0x00000077);
    pub const X: Keycode = Keycode(0x00000078);
    pub const Y: Keycode = Keycode(0x00000079);
    pub const Z: Keycode = Keycode(0x0000007a);
    pub const LEFTBRACE: Keycode = Keycode(0x0000007b);
    pub const PIPE: Keycode = Keycode(0x0000007c);
    pub const RIGHTBRACE: Keycode = Keycode(0x0000007d);
    pub const TILDE: Keycode = Keycode(0x0000007e);
    pub const DELETE: Keycode = Keycode(0x0000007f);
    pub const PLUSMINUS: Keycode = Keycode(0x000000b1);
    pub const CAPSLOCK: Keycode = Keycode(0x40000039);
    pub const F1: Keycode = Keycode(0x4000003a);
    pub const F2: Keycode = Keycode(0x4000003b);
    pub const F3: Keycode = Keycode(0x4000003c);
    pub const F4: Keycode = Keycode(0x4000003d);
    pub const F5: Keycode = Keycode(0x4000003e);
    pub const F6: Keycode = Keycode(0x4000003f);
    pub const F7: Keycode = Keycode(0x40000040);
    pub const F8: Keycode = Keycode(0x40000041);
    pub const F9: Keycode = Keycode(0x40000042);
    pub const F10: Keycode = Keycode(0x40000043);
    pub const F11: Keycode = Keycode(0x40000044);
    pub const F12: Keycode = Keycode(0x40000045);
    pub const PRINTSCREEN: Keycode = Keycode(0x40000046);
    pub const SCROLLLOCK: Keycode = Keycode(0x40000047);
    pub const PAUSE: Keycode = Keycode(0x40000048);
    pub const INSERT: Keycode = Keycode(0x40000049);
    pub const HOME: Keycode = Keycode(0x4000004a);
    pub const PAGEUP: Keycode = Keycode(0x4000004b);
    pub const END: Keycode = Keycode(0x4000004d);
    pub const PAGEDOWN: Keycode = Keycode(0x4000004e);
    pub const RIGHT: Keycode = Keycode(0x4000004f);
    pub const LEFT: Keycode = Keycode(0x40000050);
    pub const DOWN: Keycode = Keycode(0x40000051);
    pub const UP: Keycode = Keycode(0x40000052);
    pub const NUMLOCKCLEAR: Keycode = Keycode(0x40000053);
    pub const KP_DIVIDE: Keycode = Keycode(0x40000054);
    pub const KP_MULTIPLY: Keycode = Keycode(0x40000055);
    pub const KP_MINUS: Keycode = Keycode(0x40000056);
    pub const KP_PLUS: Keycode = Keycode(0x40000057);
    pub const KP_ENTER: Keycode = Keycode(0x40000058);
    pub const KP_1: Keycode = Keycode(0x40000059);
    pub const KP_2: Keycode = Keycode(0x4000005a);
    pub const KP_3: Keycode = Keycode(0x4000005b);
    pub const KP_4: Keycode = Keycode(0x4000005c);
    pub const KP_5: Keycode = Keycode(0x4000005d);
    pub const KP_6: Keycode = Keycode(0x4000005e);
    pub const KP_7: Keycode = Keycode(0x4000005f);
    pub const KP_8: Keycode = Keycode(0x40000060);
    pub const KP_9: Keycode = Keycode(0x40000061);
    pub const KP_0: Keycode = Keycode(0x40000062);
    pub const KP_PERIOD: Keycode = Keycode(0x40000063);
    pub const APPLICATION: Keycode = Keycode(0x40000065);
    pub const POWER: Keycode = Keycode(0x40000066);
    pub const KP_EQUALS: Keycode = Keycode(0x40000067);
    pub const F13: Keycode = Keycode(0x40000068);
    pub const F14: Keycode = Keycode(0x40000069);
    pub const F15: Keycode = Keycode(0x4000006a);
    pub const F16: Keycode = Keycode(0x4000006b);
    pub const F17: Keycode = Keycode(0x4000006c);
    pub const F18: Keycode = Keycode(0x4000006d);
    pub const F19: Keycode = Keycode(0x4000006e);
    pub const F20: Keycode = Keycode(0x4000006f);
    pub const F21: Keycode = Keycode(0x40000070);
    pub const F22: Keycode = Keycode(0x40000071);
    pub const F23: Keycode = Keycode(0x40000072);
    pub const F24: Keycode = Keycode(0x40000073);
    pub const EXECUTE: Keycode = Keycode(0x40000074);
    pub const HELP: Keycode = Keycode(0x40000075);
    pub const MENU: Keycode = Keycode(0x40000076);
    pub const SELECT: Keycode = Keycode(0x40000077);
    pub const STOP: Keycode = Keycode(0x40000078);
    pub const AGAIN: Keycode = Keycode(0x40000079);
    pub const UNDO: Keycode = Keycode(0x4000007a);
    pub const CUT: Keycode = Keycode(0x4000007b);
    pub const COPY: Keycode = Keycode(0x4000007c);
    pub const PASTE: Keycode = Keycode(0x4000007d);
    pub const FIND: Keycode = Keycode(0x4000007e);
    pub const MUTE: Keycode = Keycode(0x4000007f);
    pub const VOLUMEUP: Keycode = Keycode(0x40000080);
    pub const VOLUMEDOWN: Keycode = Keycode(0x40000081);
    pub const KP_COMMA: Keycode = Keycode(0x40000085);
    pub const KP_EQUALSAS400: Keycode = Keycode(0x40000086);
    pub const ALTERASE: Keycode = Keycode(0x40000099);
    pub const SYSREQ: Keycode = Keycode(0x4000009a);
    pub const CANCEL: Keycode = Keycode(0x4000009b);
    pub const CLEAR: Keycode = Keycode(0x4000009c);
    pub const PRIOR: Keycode = Keycode(0x4000009d);
    pub const RETURN2: Keycode = Keycode(0x4000009e);
    pub const SEPARATOR: Keycode = Keycode(0x4000009f);
    pub const OUT: Keycode = Keycode(0x400000a0);
    pub const OPER: Keycode = Keycode(0x400000a1);
    pub const CLEARAGAIN: Keycode = Keycode(0x400000a2);
    pub const CRSEL: Keycode = Keycode(0x400000a3);
    pub const EXSEL: Keycode = Keycode(0x400000a4);
    pub const FRONT: Keycode = Keycode(0x400000a5);
    pub const KP_00: Keycode = Keycode(0x400000b0);
    pub const KP_000: Keycode = Keycode(0x400000b1);
    pub const THOUSANDSSEPARATOR: Keycode = Keycode(0x400000b2);
    pub const DECIMALSEPARATOR: Keycode = Keycode(0x400000b3);
    pub const CURRENCYUNIT: Keycode = Keycode(0x400000b4);
    pub const CURRENCYSUBUNIT: Keycode = Keycode(0x400000b5);
    pub const KP_LEFTPAREN: Keycode = Keycode(0x400000b6);
    pub const KP_RIGHTPAREN: Keycode = Keycode(0x400000b7);
    pub const KP_LEFTBRACE: Keycode = Keycode(0x400000b8);
    pub const KP_RIGHTBRACE: Keycode = Keycode(0x400000b9);
    pub const KP_TAB: Keycode = Keycode(0x400000ba);
    pub const KP_BACKSPACE: Keycode = Keycode(0x400000bb);
    pub const KP_A: Keycode = Keycode(0x400000bc);
    pub const KP_B: Keycode = Keycode(0x400000bd);
    pub const KP_C: Keycode = Keycode(0x400000be);
    pub const KP_D: Keycode = Keycode(0x400000bf);
    pub const KP_E: Keycode = Keycode(0x400000c0);
    pub const KP_F: Keycode = Keycode(0x400000c1);
    pub const KP_XOR: Keycode = Keycode(0x400000c2);
    pub const KP_POWER: Keycode = Keycode(0x400000c3);
    pub const KP_PERCENT: Keycode = Keycode(0x400000c4);
    pub const KP_LESS: Keycode = Keycode(0x400000c5);
    pub const KP_GREATER: Keycode = Keycode(0x400000c6);
    pub const KP_AMPERSAND: Keycode = Keycode(0x400000c7);
    pub const KP_DBLAMPERSAND: Keycode = Keycode(0x400000c8);
    pub const KP_VERTICALBAR: Keycode = Keycode(0x400000c9);
    pub const KP_DBLVERTICALBAR: Keycode = Keycode(0x400000ca);
    pub const KP_COLON: Keycode = Keycode(0x400000cb);
    pub const KP_HASH: Keycode = Keycode(0x400000cc);
    pub const KP_SPACE: Keycode = Keycode(0x400000cd);
    pub const KP_AT: Keycode = Keycode(0x400000ce);
    pub const KP_EXCLAM: Keycode = Keycode(0x400000cf);
    pub const KP_MEMSTORE: Keycode = Keycode(0x400000d0);
    pub const KP_MEMRECALL: Keycode = Keycode(0x400000d1);
    pub const KP_MEMCLEAR: Keycode = Keycode(0x400000d2);
    pub const KP_MEMADD: Keycode = Keycode(0x400000d3);
    pub const KP_MEMSUBTRACT: Keycode = Keycode(0x400000d4);
    pub const KP_MEMMULTIPLY: Keycode = Keycode(0x400000d5);
    pub const KP_MEMDIVIDE: Keycode = Keycode(0x400000d6);
    pub const KP_PLUSMINUS: Keycode = Keycode(0x400000d7);
    pub const KP_CLEAR: Keycode = Keycode(0x400000d8);
    pub const KP_CLEARENTRY: Keycode = Keycode(0x400000d9);
    pub const KP_BINARY: Keycode = Keycode(0x400000da);
    pub const KP_OCTAL: Keycode = Keycode(0x400000db);
    pub const KP_DECIMAL: Keycode = Keycode(0x400000dc);
    pub const KP_HEXADECIMAL: Keycode = Keycode(0x400000dd);
    pub const LCTRL: Keycode = Keycode(0x400000e0);
    pub const LSHIFT: Keycode = Keycode(0x400000e1);
    pub const LALT: Keycode = Keycode(0x400000e2);
    pub const LGUI: Keycode = Keycode(0x400000e3);
    pub const RCTRL: Keycode = Keycode(0x400000e4);
    pub const RSHIFT: Keycode = Keycode(0x400000e5);
    pub const RALT: Keycode = Keycode(0x400000e6);
    pub const RGUI: Keycode = Keycode(0x400000e7);
    pub const MODE: Keycode = Keycode(0x40000101);
    pub const SLEEP: Keycode = Keycode(0x40000102);
    pub const WAKE: Keycode = Keycode(0x40000103);
    pub const CHANNEL_INCREMENT: Keycode = Keycode(0x40000104);
    pub const CHANNEL_DECREMENT: Keycode = Keycode(0x40000105);
    pub const MEDIA_PLAY: Keycode = Keycode(0x40000106);
    pub const MEDIA_PAUSE: Keycode = Keycode(0x40000107);
    pub const MEDIA_RECORD: Keycode = Keycode(0x40000108);
    pub const MEDIA_FAST_FORWARD: Keycode = Keycode(0x40000109);
    pub const MEDIA_REWIND: Keycode = Keycode(0x4000010a);
    pub const MEDIA_NEXT_TRACK: Keycode = Keycode(0x4000010b);
    pub const MEDIA_PREVIOUS_TRACK: Keycode = Keycode(0x4000010c);
    pub const MEDIA_STOP: Keycode = Keycode(0x4000010d);
    pub const MEDIA_EJECT: Keycode = Keycode(0x4000010e);
    pub const MEDIA_PLAY_PAUSE: Keycode = Keycode(0x4000010f);
    pub const MEDIA_SELECT: Keycode = Keycode(0x40000110);
    pub const AC_NEW: Keycode = Keycode(0x40000111);
    pub const AC_OPEN: Keycode = Keycode(0x40000112);
    pub const AC_CLOSE: Keycode = Keycode(0x40000113);
    pub const AC_EXIT: Keycode = Keycode(0x40000114);
    pub const AC_SAVE: Keycode = Keycode(0x40000115);
    pub const AC_PRINT: Keycode = Keycode(0x40000116);
    pub const AC_PROPERTIES: Keycode = Keycode(0x40000117);
    pub const AC_SEARCH: Keycode = Keycode(0x40000118);
    pub const AC_HOME: Keycode = Keycode(0x40000119);
    pub const AC_BACK: Keycode = Keycode(0x4000011a);
    pub const AC_FORWARD: Keycode = Keycode(0x4000011b);
    pub const AC_STOP: Keycode = Keycode(0x4000011c);
    pub const AC_REFRESH: Keycode = Keycode(0x4000011d);
    pub const AC_BOOKMARKS: Keycode = Keycode(0x4000011e);
    pub const SOFTLEFT: Keycode = Keycode(0x4000011f);
    pub const SOFTRIGHT: Keycode = Keycode(0x40000120);
    pub const CALL: Keycode = Keycode(0x40000121);
    pub const ENDCALL: Keycode = Keycode(0x40000122);
    pub const LEFT_TAB: Keycode = Keycode(0x20000001);
    pub const LEVEL5_SHIFT: Keycode = Keycode(0x20000002);
    pub const MULTI_KEY_COMPOSE: Keycode = Keycode(0x20000003);
    pub const LMETA: Keycode = Keycode(0x20000004);
    pub const RMETA: Keycode = Keycode(0x20000005);
    pub const LHYPER: Keycode = Keycode(0x20000006);
    pub const RHYPER: Keycode = Keycode(0x20000007);

    /// Translation of `SDL_SCANCODE_TO_KEYCODE()`.
    pub const fn from_scancode(scancode: Scancode) -> Keycode {
        Keycode(scancode.0 as u32 | Keycode::SCANCODE_MASK)
    }

    /// A keycode for a Unicode character.
    pub const fn from_char(c: char) -> Keycode {
        Keycode(c as u32)
    }

    /// The character this keycode is, if it is one (no mask bits set).
    pub const fn to_char(self) -> Option<char> {
        if self.0 & (Keycode::SCANCODE_MASK | Keycode::EXTENDED_MASK) != 0 {
            None
        } else {
            char::from_u32(self.0)
        }
    }

    pub const fn is_scancode_key(self) -> bool {
        self.0 & Keycode::SCANCODE_MASK != 0
    }

    pub const fn is_extended_key(self) -> bool {
        self.0 & Keycode::EXTENDED_MASK != 0
    }
}

impl fmt::Debug for Keycode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Keycode({:#x})", self.0)
    }
}

/// Valid key modifiers (possibly OR'd together). Translation of `SDL_Keymod`.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Keymod(pub u16);

impl Keymod {
    /// no modifier is applicable.
    pub const NONE: Keymod = Keymod(0x0000);
    /// the left Shift key is down.
    pub const LSHIFT: Keymod = Keymod(0x0001);
    /// the right Shift key is down.
    pub const RSHIFT: Keymod = Keymod(0x0002);
    /// the Level 5 Shift key is down.
    pub const LEVEL5: Keymod = Keymod(0x0004);
    /// the left Ctrl (Control) key is down.
    pub const LCTRL: Keymod = Keymod(0x0040);
    /// the right Ctrl (Control) key is down.
    pub const RCTRL: Keymod = Keymod(0x0080);
    /// the left Alt key is down.
    pub const LALT: Keymod = Keymod(0x0100);
    /// the right Alt key is down.
    pub const RALT: Keymod = Keymod(0x0200);
    /// the left GUI key (often the Windows key) is down.
    pub const LGUI: Keymod = Keymod(0x0400);
    /// the right GUI key (often the Windows key) is down.
    pub const RGUI: Keymod = Keymod(0x0800);
    /// the Num Lock key (may be located on an extended keypad) is down.
    pub const NUM: Keymod = Keymod(0x1000);
    /// the Caps Lock key is down.
    pub const CAPS: Keymod = Keymod(0x2000);
    /// the !AltGr key is down.
    pub const MODE: Keymod = Keymod(0x4000);
    /// the Scroll Lock key is down.
    pub const SCROLL: Keymod = Keymod(0x8000);
    /// Any Ctrl key is down.
    pub const CTRL: Keymod = Keymod(Keymod::LCTRL.0 | Keymod::RCTRL.0);
    /// Any Shift key is down.
    pub const SHIFT: Keymod = Keymod(Keymod::LSHIFT.0 | Keymod::RSHIFT.0);
    /// Any Alt key is down.
    pub const ALT: Keymod = Keymod(Keymod::LALT.0 | Keymod::RALT.0);
    /// Any GUI key is down.
    pub const GUI: Keymod = Keymod(Keymod::LGUI.0 | Keymod::RGUI.0);

    pub const fn contains(self, other: Keymod) -> bool {
        (self.0 & other.0) == other.0
    }
    pub const fn intersects(self, other: Keymod) -> bool {
        (self.0 & other.0) != 0
    }
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
}

impl BitOr for Keymod {
    type Output = Keymod;
    fn bitor(self, rhs: Keymod) -> Keymod {
        Keymod(self.0 | rhs.0)
    }
}
impl BitOrAssign for Keymod {
    fn bitor_assign(&mut self, rhs: Keymod) {
        self.0 |= rhs.0;
    }
}
impl BitAnd for Keymod {
    type Output = Keymod;
    fn bitand(self, rhs: Keymod) -> Keymod {
        Keymod(self.0 & rhs.0)
    }
}
impl BitAndAssign for Keymod {
    fn bitand_assign(&mut self, rhs: Keymod) {
        self.0 &= rhs.0;
    }
}
impl BitXorAssign for Keymod {
    fn bitxor_assign(&mut self, rhs: Keymod) {
        self.0 ^= rhs.0;
    }
}
impl Not for Keymod {
    type Output = Keymod;
    fn not(self) -> Keymod {
        Keymod(!self.0)
    }
}

impl fmt::Debug for Keymod {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Keymod({:#06x})", self.0)
    }
}
