// Rust translation of src/joystick/usb_ids.h from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.
// Generated by tools/gen_joystick_tables.py; do not edit.

//! Useful USB (and Bluetooth) vendor, product and usage values.

#![allow(dead_code)] // (used by the HIDAPI drivers)

pub(crate) const USB_VENDOR_8BITDO: u16 = 0x2dc8;
pub(crate) const USB_VENDOR_AMAZON: u16 = 0x1949;
pub(crate) const USB_VENDOR_ANDGAMER: u16 = 0x38d2;
pub(crate) const USB_VENDOR_APPLE: u16 = 0x05ac;
pub(crate) const USB_VENDOR_ASTRO: u16 = 0x9886;
pub(crate) const USB_VENDOR_ASUS: u16 = 0x0b05;
pub(crate) const USB_VENDOR_BACKBONE: u16 = 0x358a;
pub(crate) const USB_VENDOR_CRKD: u16 = 0x3651;
pub(crate) const USB_VENDOR_CORSAIR: u16 = 0x1b1c;
pub(crate) const USB_VENDOR_GAMESIR: u16 = 0x3537;
pub(crate) const USB_VENDOR_DRAGONRISE: u16 = 0x0079;
pub(crate) const USB_VENDOR_FLYDIGI_V1: u16 = 0x04b4;
pub(crate) const USB_VENDOR_FLYDIGI_V2: u16 = 0x37d7;
pub(crate) const USB_VENDOR_GOOGLE: u16 = 0x18d1;
pub(crate) const USB_VENDOR_HARMONIX: u16 = 0x1bad;
pub(crate) const USB_VENDOR_HORI: u16 = 0x0f0d;
pub(crate) const USB_VENDOR_HP: u16 = 0x03f0;
pub(crate) const USB_VENDOR_HYPERKIN: u16 = 0x2e24;
pub(crate) const USB_VENDOR_LOGITECH: u16 = 0x046d;
pub(crate) const USB_VENDOR_MADCATZ: u16 = 0x0738;
pub(crate) const USB_VENDOR_MAYFLASH: u16 = 0x33df;
pub(crate) const USB_VENDOR_MICROSOFT: u16 = 0x045e;
pub(crate) const USB_VENDOR_NACON: u16 = 0x146b;
pub(crate) const USB_VENDOR_NACON_ALT: u16 = 0x3285;
pub(crate) const USB_VENDOR_NINTENDO: u16 = 0x057e;
pub(crate) const USB_VENDOR_NVIDIA: u16 = 0x0955;
pub(crate) const USB_VENDOR_PDP: u16 = 0x0e6f;
pub(crate) const USB_VENDOR_POWERA: u16 = 0x24c6;
pub(crate) const USB_VENDOR_POWERA_ALT: u16 = 0x20d6;
pub(crate) const USB_VENDOR_QANBA: u16 = 0x2c22;
pub(crate) const USB_VENDOR_RAZER: u16 = 0x1532;
pub(crate) const USB_VENDOR_RED_OCTANE: u16 = 0x1430;
pub(crate) const USB_VENDOR_RED_OCTANE_GAMES: u16 = 0x3958;
pub(crate) const USB_VENDOR_SAITEK: u16 = 0x06a3;
pub(crate) const USB_VENDOR_SCEA: u16 = 0x12ba;
pub(crate) const USB_VENDOR_SHANWAN: u16 = 0x2563;
pub(crate) const USB_VENDOR_SHANWAN_ALT: u16 = 0x20bc;
pub(crate) const USB_VENDOR_SONY: u16 = 0x054c;
pub(crate) const USB_VENDOR_THRUSTMASTER: u16 = 0x044f;
pub(crate) const USB_VENDOR_TURTLE_BEACH: u16 = 0x10f5;
pub(crate) const USB_VENDOR_SWITCH: u16 = 0x2563;
pub(crate) const USB_VENDOR_VALVE: u16 = 0x28de;
pub(crate) const USB_VENDOR_ZEROPLUS: u16 = 0x0c12;
/// Commercial hardware from various companies are registered under this VID
pub(crate) const USB_VENDOR_RASPBERRYPI: u16 = 0x2e8a;
pub(crate) const USB_VENDOR_ZUIKI: u16 = 0x33dd;
/// B + START
pub(crate) const USB_PRODUCT_8BITDO_SF30_PRO: u16 = 0x6000;
/// B + START
pub(crate) const USB_PRODUCT_8BITDO_SF30_PRO_BT: u16 = 0x6100;
/// B + START
pub(crate) const USB_PRODUCT_8BITDO_SN30_PRO: u16 = 0x6001;
/// B + START
pub(crate) const USB_PRODUCT_8BITDO_SN30_PRO_BT: u16 = 0x6101;
/// mode switch to D
pub(crate) const USB_PRODUCT_8BITDO_PRO_2: u16 = 0x6003;
/// mode switch to D
pub(crate) const USB_PRODUCT_8BITDO_PRO_2_BT: u16 = 0x6006;
/// mode switch to D
pub(crate) const USB_PRODUCT_8BITDO_PRO_3: u16 = 0x6009;
/// mode switch to BT
pub(crate) const USB_PRODUCT_8BITDO_ULTIMATE2_WIRELESS: u16 = 0x6012;
/// mode switch to BT
pub(crate) const USB_PRODUCT_8BITDO_ULTIMATE3: u16 = 0x202f;
pub(crate) const USB_PRODUCT_AMAZON_LUNA_CONTROLLER: u16 = 0x0419;
pub(crate) const USB_PRODUCT_ASTRO_C40_XBOX360: u16 = 0x0024;
pub(crate) const USB_PRODUCT_BACKBONE_ONE_IOS: u16 = 0x0103;
pub(crate) const USB_PRODUCT_BACKBONE_ONE_IOS_PS5: u16 = 0x0104;
pub(crate) const USB_PRODUCT_BACKBONE_ONE_PS5_V2: u16 = 0x0304;
pub(crate) const USB_PRODUCT_BDA_XB1_CLASSIC: u16 = 0x581a;
pub(crate) const USB_PRODUCT_BDA_XB1_FIGHTPAD: u16 = 0x791a;
pub(crate) const USB_PRODUCT_BDA_XB1_SPECTRA_PRO: u16 = 0x592a;
pub(crate) const USB_PRODUCT_GOOGLE_STADIA_CONTROLLER: u16 = 0x9400;
pub(crate) const USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER1: u16 = 0x1843;
pub(crate) const USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER2: u16 = 0x1844;
pub(crate) const USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER3: u16 = 0x1846;
pub(crate) const USB_PRODUCT_FLYDIGI_V1_GAMEPAD: u16 = 0x2412;
pub(crate) const USB_PRODUCT_FLYDIGI_V2_APEX: u16 = 0x2501;
pub(crate) const USB_PRODUCT_FLYDIGI_V2_APEX6: u16 = 0x2502;
pub(crate) const USB_PRODUCT_FLYDIGI_V2_VADER: u16 = 0x2401;
/// Wired/2.4G/Bluetooth 8K mode
pub(crate) const USB_PRODUCT_GAMESIR_GAMEPAD_G7_PRO_8K: u16 = 0x10b8;
/// Wired/2.4G/Bluetooth Tarantula 8K
pub(crate) const USB_PRODUCT_GAMESIR_GAMEPAD_TARANTULA_8K: u16 = 0x103c;
pub(crate) const USB_PRODUCT_HARMONIX_WII_RB1_GUITAR: u16 = 0x0004;
pub(crate) const USB_PRODUCT_HARMONIX_WII_RB1_DRUMS: u16 = 0x0005;
pub(crate) const USB_PRODUCT_HARMONIX_WII_RB2_GUITAR: u16 = 0x3010;
pub(crate) const USB_PRODUCT_HARMONIX_WII_RB2_DRUMS: u16 = 0x3110;
pub(crate) const USB_PRODUCT_HARMONIX_WII_RB3_MPA_DRUMS_MODE: u16 = 0x3138;
pub(crate) const USB_PRODUCT_HORI_FIGHTING_STICK_ALPHA_PS4: u16 = 0x011c;
pub(crate) const USB_PRODUCT_HORI_FIGHTING_STICK_ALPHA_PS5: u16 = 0x0184;
pub(crate) const USB_PRODUCT_HORI_STEAM_CONTROLLER: u16 = 0x01ab;
pub(crate) const USB_PRODUCT_HORI_STEAM_CONTROLLER_BT: u16 = 0x0196;
pub(crate) const USB_PRODUCT_LOGITECH_F310: u16 = 0xc216;
pub(crate) const USB_PRODUCT_LOGITECH_CHILLSTREAM: u16 = 0xcad1;
pub(crate) const USB_PRODUCT_MADCATZ_SAITEK_SIDE_PANEL_CONTROL_DECK: u16 = 0x2218;
pub(crate) const USB_PRODUCT_MADCATZ_XB1_STRATOCASTER_GUITAR: u16 = 0x4161;
pub(crate) const USB_PRODUCT_MADCATZ_XB1_DRUM_KIT: u16 = 0x4262;
pub(crate) const USB_PRODUCT_MADCATZ_XB1_LEGACY_ADAPTER: u16 = 0x4164;
pub(crate) const USB_PRODUCT_NACON_REVOLUTION_5_PRO_PS4_WIRELESS: u16 = 0x0d16;
pub(crate) const USB_PRODUCT_NACON_REVOLUTION_5_PRO_PS4_WIRED: u16 = 0x0d17;
pub(crate) const USB_PRODUCT_NACON_REVOLUTION_5_PRO_PS5_WIRELESS: u16 = 0x0d18;
pub(crate) const USB_PRODUCT_NACON_REVOLUTION_5_PRO_PS5_WIRED: u16 = 0x0d19;
pub(crate) const USB_PRODUCT_NACON_REVOLUTION_X_UNLIMITED_BT: u16 = 0x0689;
pub(crate) const USB_PRODUCT_NINTENDO_GAMECUBE_ADAPTER: u16 = 0x0337;
pub(crate) const USB_PRODUCT_NINTENDO_N64_CONTROLLER: u16 = 0x2019;
pub(crate) const USB_PRODUCT_NINTENDO_SEGA_GENESIS_CONTROLLER: u16 = 0x201e;
pub(crate) const USB_PRODUCT_NINTENDO_SNES_CONTROLLER: u16 = 0x2017;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH_JOYCON_GRIP: u16 = 0x200e;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH_JOYCON_LEFT: u16 = 0x2006;
/// Used by joycond
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH_JOYCON_PAIR: u16 = 0x2008;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH_JOYCON_RIGHT: u16 = 0x2007;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH_PRO: u16 = 0x2009;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH2_GAMECUBE_CONTROLLER: u16 = 0x2073;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH2_JOYCON_LEFT: u16 = 0x2067;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH2_JOYCON_PAIR: u16 = 0x2068;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH2_JOYCON_RIGHT: u16 = 0x2066;
pub(crate) const USB_PRODUCT_NINTENDO_SWITCH2_PRO: u16 = 0x2069;
pub(crate) const USB_PRODUCT_NINTENDO_WII_REMOTE: u16 = 0x0306;
pub(crate) const USB_PRODUCT_NINTENDO_WII_REMOTE2: u16 = 0x0330;
pub(crate) const USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V103: u16 = 0x7210;
pub(crate) const USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V104: u16 = 0x7214;
pub(crate) const USB_PRODUCT_PDP_ROCK_CANDY: u16 = 0x0246;
pub(crate) const USB_PRODUCT_PDP_REALMZ_WIRELESS: u16 = 0x018c;
pub(crate) const USB_PRODUCT_PDP_XB1_DRUM_KIT: u16 = 0x0171;
pub(crate) const USB_PRODUCT_PDP_XB1_JAGUAR_GUITAR: u16 = 0x0170;
pub(crate) const USB_PRODUCT_PDP_XB1_RIFFMASTER_GUITAR: u16 = 0x0248;
pub(crate) const USB_PRODUCT_POWERA_MINI: u16 = 0x541a;
pub(crate) const USB_PRODUCT_RAZER_ATROX: u16 = 0x0a00;
pub(crate) const USB_PRODUCT_RAZER_KITSUNE: u16 = 0x1012;
pub(crate) const USB_PRODUCT_RAZER_PANTHERA: u16 = 0x0401;
pub(crate) const USB_PRODUCT_RAZER_PANTHERA_EVO: u16 = 0x1008;
pub(crate) const USB_PRODUCT_RAZER_RAIJU: u16 = 0x1000;
pub(crate) const USB_PRODUCT_RAZER_RAIJU_V3_PRO_PS5_WIRED: u16 = 0x1024;
pub(crate) const USB_PRODUCT_RAZER_RAIJU_V3_PRO_PS5_WIRELESS: u16 = 0x1026;
pub(crate) const USB_PRODUCT_RAZER_TOURNAMENT_EDITION_USB: u16 = 0x1007;
pub(crate) const USB_PRODUCT_RAZER_TOURNAMENT_EDITION_BLUETOOTH: u16 = 0x100a;
pub(crate) const USB_PRODUCT_RAZER_ULTIMATE_EDITION_USB: u16 = 0x1004;
pub(crate) const USB_PRODUCT_RAZER_ULTIMATE_EDITION_BLUETOOTH: u16 = 0x1009;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V2: u16 = 0x0a29;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V2_CHROMA: u16 = 0x0a2e;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V2_PRO_PS5_WIRED: u16 = 0x100b;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V2_PRO_PS5_WIRELESS: u16 = 0x100c;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V2_PRO_XBOX_WIRED: u16 = 0x1010;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V2_PRO_XBOX_WIRELESS: u16 = 0x1011;
pub(crate) const USB_PRODUCT_RAZER_WOLVERINE_V3_PRO: u16 = 0x0a3f;
pub(crate) const USB_PRODUCT_RED_OCTANE_XB1_GUITAR_HERO_LIVE_GUITAR: u16 = 0x0170;
pub(crate) const USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_GUITAR: u16 = 0x4161;
pub(crate) const USB_PRODUCT_RED_OCTANE_XB1_STAGE_TOUR_DRUMS: u16 = 0xd300;
pub(crate) const USB_PRODUCT_SAITEK_CYBORG_V3: u16 = 0xf622;
pub(crate) const USB_PRODUCT_SCEA_PS3_GH_GUITAR: u16 = 0x0100;
pub(crate) const USB_PRODUCT_SCEA_PS3_GH_DRUMS: u16 = 0x0120;
pub(crate) const USB_PRODUCT_SCEA_PS3_RB_GUITAR: u16 = 0x0200;
pub(crate) const USB_PRODUCT_SCEA_PS3_RB_DRUMS: u16 = 0x0210;
pub(crate) const USB_PRODUCT_SCEA_PS3_RB3_MPA_DRUMS_MODE: u16 = 0x0218;
pub(crate) const USB_PRODUCT_SCEA_PS3WIIU_GHLIVE: u16 = 0x074b;
pub(crate) const USB_PRODUCT_SHANWAN_DS3: u16 = 0x0523;
pub(crate) const USB_PRODUCT_SONY_DS3: u16 = 0x0268;
pub(crate) const USB_PRODUCT_SONY_DS4: u16 = 0x05c4;
pub(crate) const USB_PRODUCT_SONY_DS4_DONGLE: u16 = 0x0ba0;
pub(crate) const USB_PRODUCT_SONY_DS4_SLIM: u16 = 0x09cc;
pub(crate) const USB_PRODUCT_SONY_DS4_STRIKEPAD: u16 = 0x05c5;
pub(crate) const USB_PRODUCT_SONY_DS5: u16 = 0x0ce6;
pub(crate) const USB_PRODUCT_SONY_DS5_EDGE: u16 = 0x0df2;
pub(crate) const USB_PRODUCT_STEALTH_ULTRA_WIRED: u16 = 0x7073;
pub(crate) const USB_PRODUCT_SWITCH_RETRO_CONTROLLER: u16 = 0x0575;
pub(crate) const USB_PRODUCT_THRUSTMASTER_ESWAPX_PRO_PS4: u16 = 0xd00e;
pub(crate) const USB_PRODUCT_THRUSTMASTER_T_FLIGHT_HOTAS_ONE: u16 = 0xb68c;
pub(crate) const USB_PRODUCT_VALVE_STEAM_CONTROLLER_DONGLE: u16 = 0x1142;
pub(crate) const USB_PRODUCT_VALVE_STEAM_PROTEUS_DONGLE: u16 = 0x1304;
pub(crate) const USB_PRODUCT_VALVE_STEAM_NEREID_DONGLE: u16 = 0x1305;
pub(crate) const USB_PRODUCT_VICTRIX_FS_PRO: u16 = 0x0203;
pub(crate) const USB_PRODUCT_VICTRIX_FS_PRO_V2: u16 = 0x0207;
/// XUSB driver software PID
pub(crate) const USB_PRODUCT_XBOX360_XUSB_CONTROLLER: u16 = 0x02a1;
pub(crate) const USB_PRODUCT_XBOX360_WIRED_CONTROLLER: u16 = 0x028e;
pub(crate) const USB_PRODUCT_XBOX360_WIRELESS_RECEIVER: u16 = 0x0719;
pub(crate) const USB_PRODUCT_XBOX360_WIRELESS_RECEIVER_THIRDPARTY1: u16 = 0x02a9;
pub(crate) const USB_PRODUCT_XBOX360_WIRELESS_RECEIVER_THIRDPARTY2: u16 = 0x0291;
pub(crate) const USB_PRODUCT_XBOX360_BIGBUTTON_RECEIVER: u16 = 0x02a0;
pub(crate) const USB_PRODUCT_XBOX_ONE_ADAPTIVE: u16 = 0x0b0a;
pub(crate) const USB_PRODUCT_XBOX_ONE_ADAPTIVE_BLUETOOTH: u16 = 0x0b0c;
pub(crate) const USB_PRODUCT_XBOX_ONE_ADAPTIVE_BLE: u16 = 0x0b21;
pub(crate) const USB_PRODUCT_XBOX_ONE_ELITE_SERIES_1: u16 = 0x02e3;
pub(crate) const USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2: u16 = 0x0b00;
pub(crate) const USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLUETOOTH: u16 = 0x0b05;
pub(crate) const USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLE: u16 = 0x0b22;
pub(crate) const USB_PRODUCT_XBOX_ONE_S: u16 = 0x02ea;
pub(crate) const USB_PRODUCT_XBOX_ONE_S_REV1_BLUETOOTH: u16 = 0x02e0;
pub(crate) const USB_PRODUCT_XBOX_ONE_S_REV2_BLUETOOTH: u16 = 0x02fd;
pub(crate) const USB_PRODUCT_XBOX_ONE_S_REV2_BLE: u16 = 0x0b20;
pub(crate) const USB_PRODUCT_XBOX_SERIES_X: u16 = 0x0b12;
pub(crate) const USB_PRODUCT_XBOX_SERIES_X_BLE: u16 = 0x0b13;
/// XBOXGIP driver software PID
pub(crate) const USB_PRODUCT_XBOX_ONE_XBOXGIP_CONTROLLER: u16 = 0x02ff;
pub(crate) const USB_PRODUCT_STEAM_VIRTUAL_GAMEPAD: u16 = 0x11ff;
pub(crate) const USB_PRODUCT_HANDHELDLEGEND_SINPUT_GENERIC: u16 = 0x10c6;
pub(crate) const USB_PRODUCT_HANDHELDLEGEND_PROGCC: u16 = 0x10df;
pub(crate) const USB_PRODUCT_HANDHELDLEGEND_GCULTIMATE: u16 = 0x10dd;
pub(crate) const USB_PRODUCT_BONZIRICHANNEL_FIREBIRD: u16 = 0x10e0;
pub(crate) const USB_PRODUCT_ZUIKI_MASCON_PRO: u16 = 0x0006;
pub(crate) const USB_PRODUCT_ZUIKI_EVOTOP_UWB_DINPUT: u16 = 0x001c;
pub(crate) const USB_PRODUCT_ZUIKI_EVOTOP_PC_DINPUT: u16 = 0x001d;
pub(crate) const USB_PRODUCT_ZUIKI_EVOTOP_PC_BT: u16 = 0x0017;
pub(crate) const USB_PRODUCT_ZUIKI_EVOTOP_AXIS_DINPUT: u16 = 0x0020;
pub(crate) const USB_PRODUCT_VOIDGAMING_PS4FIREBIRD: u16 = 0x10e5;
pub(crate) const USB_PRODUCT_VOIDGAMING_GENESIS_SINPUT: u16 = 0x1014;

// USB usage pages
pub(crate) const USB_USAGEPAGE_GENERIC_DESKTOP: u16 = 0x0001;
pub(crate) const USB_USAGEPAGE_SIMULATION: u16 = 0x0002;
pub(crate) const USB_USAGEPAGE_DEVICE_CONTROLS: u16 = 0x0006;
pub(crate) const USB_USAGEPAGE_BUTTON: u16 = 0x0009;
pub(crate) const USB_USAGEPAGE_CONSUMER: u16 = 0x000c;
pub(crate) const USB_USAGEPAGE_VENDOR_FLYDIGI: u16 = 0xffa0;

// USB usages for USAGE_PAGE_GENERIC_DESKTOP
pub(crate) const USB_USAGE_GENERIC_POINTER: u16 = 0x0001;
pub(crate) const USB_USAGE_GENERIC_MOUSE: u16 = 0x0002;
pub(crate) const USB_USAGE_GENERIC_JOYSTICK: u16 = 0x0004;
pub(crate) const USB_USAGE_GENERIC_GAMEPAD: u16 = 0x0005;
pub(crate) const USB_USAGE_GENERIC_KEYBOARD: u16 = 0x0006;
pub(crate) const USB_USAGE_GENERIC_KEYPAD: u16 = 0x0007;
pub(crate) const USB_USAGE_GENERIC_MULTIAXISCONTROLLER: u16 = 0x0008;
pub(crate) const USB_USAGE_GENERIC_X: u16 = 0x0030;
pub(crate) const USB_USAGE_GENERIC_Y: u16 = 0x0031;
pub(crate) const USB_USAGE_GENERIC_Z: u16 = 0x0032;
pub(crate) const USB_USAGE_GENERIC_RX: u16 = 0x0033;
pub(crate) const USB_USAGE_GENERIC_RY: u16 = 0x0034;
pub(crate) const USB_USAGE_GENERIC_RZ: u16 = 0x0035;
pub(crate) const USB_USAGE_GENERIC_SLIDER: u16 = 0x0036;
pub(crate) const USB_USAGE_GENERIC_DIAL: u16 = 0x0037;
pub(crate) const USB_USAGE_GENERIC_WHEEL: u16 = 0x0038;
pub(crate) const USB_USAGE_GENERIC_HAT: u16 = 0x0039;

// USB usages for USB_USAGEPAGE_SIMULATION
pub(crate) const USB_USAGE_SIMULATION_ACCELERATOR: u16 = 0x00c4;
pub(crate) const USB_USAGE_SIMULATION_BRAKE: u16 = 0x00c5;

// USB usages for USB_USAGEPAGE_DEVICE_CONTROLS
pub(crate) const USB_USAGE_DEVICE_CONTROLS_BATTERY_STRENGTH: u16 = 0x0020;

// USB usages for USB_USAGEPAGE_CONSUMER
pub(crate) const USB_USAGE_CONSUMER_ASSIGN_SELECTION: u16 = 0x0081;
pub(crate) const USB_USAGE_CONSUMER_ORDER_MOVIE: u16 = 0x0085;
pub(crate) const USB_USAGE_CONSUMER_RECORD: u16 = 0x00b2;
pub(crate) const USB_USAGE_CONSUMER_AC_HOME: u16 = 0x0223;
pub(crate) const USB_USAGE_CONSUMER_AC_BACK: u16 = 0x0224;
pub(crate) const BLUETOOTH_VENDOR_AMAZON: u16 = 0x0171;
pub(crate) const BLUETOOTH_PRODUCT_LUNA_CONTROLLER: u16 = 0x0419;
