// Expected values for the ps3 driver tests, generated by running upstream's
// driver (with stubs for the SDL functions it uses) on these inputs.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

/// The reports of each case, with the events they cause.
#[allow(clippy::type_complexity)]
pub(super) const CASES: &[(&str, &[(&[u8], &[&str])])] = &[
    (
        "ps3 analog sensors",
        &[
            (
                &[0x01, 0x04, 0x65, 0xaa, 0x1f, 0xad, 0x1d, 0x5a, 0xda, 0xe5, 0xac, 0x1b, 0x1e, 0x5f, 0x13, 0x70, 0x79, 0x6c, 0xfd, 0x10, 0xff, 0x19, 0xaf, 0x60, 0x1d, 0x04, 0xac, 0xb4, 0x1d, 0x02, 0x2b, 0x46, 0x78, 0x73, 0x3a, 0xf2, 0xdf, 0x5f, 0xae, 0xb7, 0x08, 0x59, 0xd1, 0xee, 0x39, 0x10, 0xcb, 0x48, 0x95],
                &["button 4 1", "button 7 0", "button 8 1", "button 6 0", "hat 0 6", "button 9 0", "button 10 1", "button 3 0", "button 1 1", "button 0 0", "button 2 1", "button 5 1", "axis 4 32253", "axis 5 -28656", "axis 0 -25315", "axis 1 -9638", "axis 2 23258", "axis 3 26085", "axis 6 -25315", "axis 7 -8096", "axis 8 -31740", "axis 9 12207", "axis 10 32767", "axis 11 -26343", "axis 12 -27885", "axis 13 -1671", "axis 14 -5012", "axis 15 -3984", "sensor Accel NOW 44f3e2dd c3a45eb0 43dba6cf", "rumble 01 01 ff 00 ff 00 00 00 00 00 08 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"],
            ),
            (
                &[0x01, 0xcc, 0x89, 0x29, 0x11, 0xff, 0x06, 0xb6, 0x62, 0x2e, 0xdf, 0x3c, 0xf9, 0x35, 0xfd, 0x4b, 0x94, 0x28, 0xca, 0x09, 0x7c, 0x44, 0xb3, 0x02, 0x5e, 0x96, 0x5f, 0xb3, 0xea, 0x6d, 0xac, 0xd4, 0x2d, 0x81, 0x6e, 0x69, 0xaf, 0xe0, 0xe6, 0x87, 0x4c, 0x9c, 0x04, 0xe7, 0xd2, 0x36, 0x5d, 0x2c, 0x60],
                &["button 4 1", "button 7 0", "button 8 0", "button 6 1", "hat 0 8", "button 9 0", "button 10 1", "button 3 0", "button 1 1", "button 0 0", "button 2 0", "button 5 1", "axis 4 19146", "axis 5 -30455", "axis 0 -31226", "axis 1 14006", "axis 2 -7582", "axis 3 -20946", "axis 6 -8610", "axis 7 -32254", "axis 8 5782", "axis 9 13235", "axis 10 -900", "axis 11 -15292", "axis 12 32253", "axis 13 5268", "axis 14 -22488", "axis 15 -13493", "sensor Accel NOW c50d9aef c4916ddd 441162c1"],
            ),
            (
                &[0x01, 0xea, 0xf4, 0x79, 0xf6, 0x86, 0xa0, 0xeb, 0x93, 0x26, 0xe4, 0x62, 0x12, 0xd5, 0x0d, 0xcb, 0xb3, 0x77, 0x15, 0x6a, 0x6a, 0x3a, 0x68, 0xba, 0x8e, 0xdb, 0x74, 0x08, 0x46, 0x9e, 0xf3, 0xce, 0xb3, 0x0a, 0xf8, 0xd0, 0xdd, 0x68, 0xbb, 0xf8, 0x5f, 0xfa, 0x24, 0xf2, 0xd2, 0xfc, 0x18, 0x87, 0xfb],
                &["button 4 0", "button 7 0", "button 8 1", "button 6 0", "hat 0 15", "button 9 0", "button 10 1", "button 3 1", "button 1 1", "button 0 1", "button 2 0", "button 5 0", "axis 4 -27371", "axis 5 -5526", "axis 0 8352", "axis 1 27627", "axis 2 5011", "axis 3 -23002", "axis 6 3726", "axis 7 15034", "axis 8 23515", "axis 9 -6040", "axis 10 -5526", "axis 11 -17862", "axis 12 -29427", "axis 13 13235", "axis 14 -2185", "axis 15 19403", "sensor Accel NOW c32e860f 430321a3 43a89434"],
            ),
            (
                &[0x01, 0xff, 0xba, 0xb4, 0x38, 0x32, 0xa5, 0x9b, 0x1b, 0x3d, 0x10, 0x7c, 0xf7, 0x78, 0xd6, 0x7f, 0xe2, 0x6d, 0xf8, 0x11, 0x91, 0x29, 0x7e, 0x93, 0x95, 0xcb, 0x12, 0xc5, 0x57, 0xce, 0x5a, 0xf1, 0xd4, 0x16, 0x18, 0xd7, 0x19, 0xbc, 0x04, 0x5b, 0x7e, 0x99, 0x65, 0xf1, 0xa2, 0x94, 0x71, 0xc4, 0x2a],
                &[],
            ),
            (
                &[0x01, 0x6a, 0xa9, 0x38, 0xc4, 0x75, 0xc7, 0xad, 0x32, 0x38, 0x02, 0x1f, 0x05, 0x3b, 0x2c, 0x99, 0x1a, 0xfc, 0xeb, 0x15, 0xde, 0xcf, 0x68, 0xba, 0xe0, 0x7c, 0xbc, 0xd6, 0x1e, 0x97, 0x1b, 0x9a, 0x0b, 0x9d, 0xbe, 0x97, 0x63, 0xd3, 0x92, 0xfc, 0xaf, 0xdf, 0xa2, 0x8c, 0x97, 0x23, 0x45, 0x62, 0xeb],
                &["button 4 1", "button 7 0", "button 8 0", "button 6 1", "hat 0 10", "button 9 0", "button 10 1", "button 3 1", "button 1 1", "button 0 0", "button 2 0", "button 5 0", "axis 4 27627", "axis 5 -27371", "axis 0 18375", "axis 1 11693", "axis 2 -19918", "axis 3 -18376", "axis 6 24800", "axis 7 15034", "axis 8 -900", "axis 9 -6040", "axis 10 24286", "axis 11 20431", "axis 12 -21460", "axis 13 -26086", "axis 14 31996", "axis 15 6553", "sensor Accel NOW c43edc60 c438cec1 45230653"],
            ),
            (
                &[0x01, 0x07, 0x65, 0x70, 0xff, 0x58, 0x89, 0x6a, 0xcf, 0xf7, 0xca, 0xee, 0x3f, 0x1c, 0xe9, 0xe4, 0x0a, 0x68, 0xe5, 0xde, 0x93, 0x8d, 0x38, 0x9c, 0x7d, 0xbd, 0xd7, 0x5b, 0x09, 0xd4, 0xe7, 0xe2, 0x33, 0x44, 0x3f, 0x4a, 0x8c, 0xc4, 0xa1, 0x90, 0xd6, 0x01, 0xff, 0x80, 0x00, 0x7f, 0xff, 0x8e, 0x28],
                &["button 4 1", "button 7 0", "button 8 1", "button 6 0", "hat 0 6", "button 9 0", "button 10 0", "button 3 1", "button 1 1", "button 0 1", "button 2 0", "button 5 1", "axis 4 26085", "axis 5 24286", "axis 0 2441", "axis 1 -5526", "axis 2 20431", "axis 3 30711", "axis 6 -643", "axis 7 7324", "axis 8 15805", "axis 9 -18376", "axis 10 5011", "axis 11 3469", "axis 12 27113", "axis 13 -30198", "axis 14 -6040", "axis 15 25828", "sensor Accel NOW 00000000 c52ef524 453481a1"],
            ),
            (
                &[0x01, 0x59, 0x0e, 0xaa, 0x50, 0x1b, 0x50, 0x8a, 0x6a, 0x36, 0x29, 0xe6, 0x70, 0xdf, 0x55, 0x77, 0xba, 0xdc, 0x44, 0x6d, 0x43, 0xbb, 0xa9, 0x08, 0x17, 0xd6, 0xc0, 0xf6, 0x7b, 0x08, 0x61, 0x70, 0xd9, 0x2d, 0xc9, 0x12, 0x72, 0x5b, 0x24, 0x7e, 0xc2, 0xe2, 0xda, 0xb1, 0xb2, 0x04, 0x9e, 0x20, 0x80],
                &["button 4 0", "button 7 1", "button 8 1", "button 6 1", "hat 0 0", "button 9 0", "button 10 1", "button 3 0", "button 1 1", "button 0 0", "button 2 1", "button 5 0", "axis 4 -15292", "axis 5 -4755", "axis 0 -12208", "axis 1 2698", "axis 2 -5526", "axis 3 -18890", "axis 6 -26857", "axis 7 -30712", "axis 8 22230", "axis 9 10665", "axis 10 -15549", "axis 11 15291", "axis 12 -10923", "axis 13 15034", "axis 14 23772", "axis 15 -2185", "sensor Accel NOW c42cfbb6 c268edfd 44df00ef"],
            ),
            (
                &[0x01, 0x37, 0x9a, 0x6f, 0x90, 0x0c, 0xdd, 0x2e, 0x5e, 0x72, 0xf5, 0x09, 0x48, 0xb6, 0x58, 0xd1, 0x97, 0xe9, 0xc3, 0x8c, 0xb1, 0x6e, 0xd3, 0xdd, 0x12, 0x44, 0x62, 0x32, 0x0c, 0x14, 0xa7, 0xaf, 0x3f, 0xfa, 0x0c, 0xde, 0xd6, 0x13, 0xce, 0x13, 0x86, 0xcb, 0x57, 0xa0, 0x47, 0xe4, 0x5b, 0xbe, 0xd1],
                &["button 4 0", "button 7 1", "button 8 0", "button 6 1", "hat 0 9", "button 9 1", "button 10 1", "button 3 0", "button 1 1", "button 0 1", "button 2 0", "button 5 0", "axis 4 17347", "axis 5 3212", "axis 0 24029", "axis 1 -20946", "axis 2 -8610", "axis 3 -3470", "axis 6 -28142", "axis 7 24029", "axis 8 -15292", "axis 9 21459", "axis 10 12721", "axis 11 -4498", "axis 12 -10152", "axis 13 6039", "axis 14 27113", "axis 15 20945", "sensor Accel NOW c497c93f 4424a157 4507b006"],
            ),
            (
                &[0x01, 0xb4, 0x36, 0xd5, 0x88, 0xfe, 0xd2, 0x00, 0x41, 0xf2, 0x87, 0xb1, 0x0f, 0x83, 0x5f, 0x74, 0x65, 0xba, 0x28, 0x46, 0x16, 0x52, 0xdf, 0x88, 0xa2, 0x13, 0xd9, 0xbf, 0x42, 0xef, 0xb7, 0x11, 0xb5, 0xde, 0x07, 0x7f, 0xc9, 0x79, 0xba, 0xe3, 0xa8, 0x58, 0x4a, 0xa9, 0xe8, 0x2d, 0xa8, 0x4d, 0x50],
                &["button 4 0", "button 7 1", "button 8 1", "button 6 0", "hat 0 3", "button 9 1", "button 10 0", "button 3 1", "button 1 0", "button 0 1", "button 2 1", "button 5 0", "axis 4 -22488", "axis 5 -14778", "axis 0 21202", "axis 1 -32768", "axis 2 -16063", "axis 3 29426", "axis 6 8866", "axis 7 2184", "axis 8 -27885", "axis 9 24543", "axis 10 -27114", "axis 11 -11694", "axis 12 -8353", "axis 13 -6811", "axis 14 15034", "axis 15 -2956", "sensor Accel NOW 44efa504 c4727f65 44f4a27c"],
            ),
            (
                &[0x01, 0xe6, 0x98, 0x6b, 0xe2, 0xa9, 0x9a, 0xcf, 0x21, 0x4c, 0x66, 0x2a, 0x8c, 0xd5, 0x90, 0x11, 0x37, 0x98, 0x67, 0x89, 0xbb, 0xad, 0xf3, 0x51, 0x8d, 0x13, 0xad, 0xf5, 0x1c, 0xa1, 0x01, 0x94, 0xac, 0xb0, 0x84, 0x6c, 0xf5, 0x8a, 0xf5, 0x2a, 0x7a, 0x91, 0xf5, 0xf3, 0xab, 0x2f, 0x86, 0x32, 0xba],
                &["button 4 0", "button 7 0", "button 8 0", "button 6 1", "hat 0 9", "button 9 0", "button 10 1", "button 3 0", "button 1 1", "button 0 1", "button 2 0", "button 5 0", "axis 4 -6297", "axis 5 2441", "axis 0 6810", "axis 1 20431", "axis 2 -24287", "axis 3 -13236", "axis 6 3469", "axis 7 -11951", "axis 8 -27885", "axis 9 29683", "axis 10 15291", "axis 11 11693", "axis 12 4240", "axis 13 -18633", "axis 14 6296", "axis 15 -28399", "sensor Accel NOW c51b9275 c47cde4e 439f29ae"],
            ),
            (
                &[0x02, 0x45, 0x20, 0x3d, 0xc3, 0x67, 0x14, 0x88, 0x7a, 0x75, 0x90, 0xc8, 0x63, 0xc7, 0x07, 0xe0, 0x1e, 0xc2, 0x70, 0x03, 0x9a, 0xd1, 0x8b, 0x16, 0x3f, 0x24, 0xf6, 0xc3, 0xde, 0x2b, 0xef, 0x5d, 0x5a, 0xd1, 0xe6, 0x76, 0x13, 0x79, 0xca, 0x42, 0x16, 0xb9, 0x10, 0xaa, 0x05, 0xd9, 0x83, 0x30, 0xc7],
                &[],
            ),
        ],
    ),
    (
        "ps3 digital",
        &[
            (
                &[0x01, 0xcf, 0x85, 0xf0, 0x66, 0xcb, 0xec, 0xef, 0xac, 0x89, 0x4c, 0xfa, 0xb7, 0x1f, 0x18, 0xba, 0xc3, 0x34, 0xdf, 0xb6, 0x60, 0x4a, 0xb2, 0x80, 0x32, 0xcd, 0x39, 0xa1, 0x6e, 0xdf, 0x94, 0x44, 0x14, 0xe1, 0xf3, 0xa6, 0xec, 0xc1, 0xf4, 0x39, 0x43, 0x06, 0xc0, 0x9b, 0x62, 0x9d, 0xe3, 0x3a, 0xd3],
                &["button 4 1", "button 7 0", "button 8 1", "button 6 0", "hat 0 8", "button 9 0", "button 10 0", "button 3 1", "button 1 1", "button 0 1", "button 2 1", "button 5 0", "axis 4 24543", "axis 5 14006", "axis 0 27884", "axis 1 28655", "axis 2 11436", "axis 3 2441", "rumble 01 01 ff 00 ff 00 00 00 00 00 01 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"],
            ),
            (
                &[0x01, 0xef, 0xc3, 0x53, 0x6b, 0xd0, 0x4f, 0x96, 0x1f, 0xee, 0x4d, 0xbd, 0xf3, 0x05, 0x2d, 0x97, 0xfe, 0xc4, 0xd1, 0x9b, 0x45, 0x27, 0xb4, 0xa2, 0xc4, 0x94, 0xd8, 0x64, 0x3e, 0xb8, 0x71, 0xb9, 0xc4, 0x1f, 0x53, 0x8b, 0x08, 0x95, 0x1c, 0x9e, 0x5f, 0x40, 0x21, 0xff, 0x97, 0x7a, 0x1a, 0x4d, 0x7f],
                &["button 4 1", "button 7 1", "button 8 0", "button 6 0", "hat 0 12", "button 9 0", "button 10 0", "button 3 1", "button 1 0", "button 0 1", "button 2 0", "button 5 1", "axis 4 20945", "axis 5 7067", "axis 0 -12465", "axis 1 5782", "axis 2 -24801", "axis 3 28398"],
            ),
            (
                &[0x01, 0x8c, 0xab, 0x2f, 0x7c, 0xfa, 0x80, 0x1b, 0x42, 0xca, 0xf5, 0xdb, 0x8c, 0xf9, 0x2c, 0xb8, 0xe6, 0x7e, 0x41, 0xf6, 0xf9, 0x7f, 0x01, 0xe4, 0xa8, 0x36, 0x6d, 0xa4, 0xec, 0xa2, 0xed, 0xba, 0x70, 0xed, 0x54, 0x57, 0xeb, 0xa0, 0x97, 0x63, 0x41, 0x89, 0x4d, 0x4d, 0x59, 0x68, 0xe6, 0x92, 0xbc],
                &["button 4 1", "button 7 1", "button 8 0", "button 6 1", "hat 0 10", "button 9 1", "button 10 1", "button 3 0", "button 1 1", "button 0 0", "button 2 0", "button 5 0", "axis 4 -16063", "axis 5 30454", "axis 0 128", "axis 1 -25829", "axis 2 -15806", "axis 3 19146"],
            ),
            (
                &[0x01, 0xab, 0x0e, 0xf3, 0x10, 0x79, 0x06, 0x9d, 0xa5, 0x3d, 0xf1, 0x52, 0x5d, 0x2e, 0x09, 0x3b, 0x0d, 0xce, 0x96, 0x6d, 0x41, 0x9e, 0xf5, 0x0a, 0x2c, 0xa4, 0x6b, 0x16, 0x56, 0x9d, 0xac, 0x1a, 0x04, 0x02, 0x29, 0x7b, 0x66, 0xbd, 0x1d, 0x97, 0x83, 0xa8, 0x56, 0xa5, 0xe5, 0xca, 0xc3, 0x49, 0x04],
                &["button 4 0", "button 7 1", "button 8 1", "button 6 1", "hat 0 0", "button 9 0", "button 10 0", "button 3 1", "button 1 1", "button 0 1", "button 2 1", "button 5 0", "axis 4 5782", "axis 5 -4755", "axis 0 -31226", "axis 1 7581", "axis 2 9637", "axis 3 -17091"],
            ),
            (
                &[0x50, 0xc2, 0xfa, 0x73, 0x45, 0x28, 0x14],
                &["hat 0 12", "button 3 0", "button 1 0", "button 0 1", "button 2 0", "button 9 0", "button 10 0", "axis 4 -32768", "axis 5 32767", "button 4 0", "button 6 1", "button 7 0", "button 8 0", "axis 0 31482", "axis 1 -3213", "axis 2 -12208", "axis 3 17090"],
            ),
            (
                &[0xcc, 0x31, 0x0d, 0xbc, 0x5d, 0x0b, 0x5c],
                &["hat 0 0", "button 3 1", "button 1 0", "button 0 1", "button 2 0", "button 9 1", "button 10 1", "axis 4 -32768", "axis 5 32767", "button 4 0", "button 6 0", "button 7 0", "button 8 0", "axis 0 -29427", "axis 1 15548", "axis 2 19660", "axis 3 -20175"],
            ),
            (
                &[0x78, 0x8f, 0x7e, 0x1e, 0x82, 0x1a, 0x85],
                &["hat 0 2", "button 3 0", "button 1 0", "button 0 0", "button 2 1", "button 9 0", "button 10 1", "axis 4 -32768", "axis 5 32767", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "axis 0 -386", "axis 1 -25058", "axis 2 -1928", "axis 3 3983"],
            ),
            (
                &[0x81, 0x0f, 0xeb, 0xe6, 0xab, 0xdc, 0xd0],
                &["hat 0 0", "button 3 0", "button 1 1", "button 0 0", "button 2 1", "button 9 0", "button 10 0", "axis 4 32767", "axis 5 32767", "button 4 1", "button 6 0", "button 7 1", "button 8 1", "axis 0 27627", "axis 1 26342", "axis 2 385", "axis 3 -28913"],
            ),
            (
                &[0x77, 0x41, 0x14, 0xe9, 0x14, 0xb5, 0x89],
                &["hat 0 4", "button 3 1", "button 1 0", "button 0 0", "button 2 0", "button 9 1", "button 10 0", "axis 4 32767", "axis 5 -32768", "button 4 1", "button 6 1", "button 7 0", "button 8 1", "axis 0 -27628", "axis 1 27113", "axis 2 -2185", "axis 3 -16063"],
            ),
            (
                &[0xcf, 0x5c, 0x53, 0xd8, 0x81, 0x2e, 0x0b],
                &["hat 0 3", "button 3 0", "button 1 0", "button 0 0", "button 2 1", "button 9 0", "button 10 1", "axis 4 32767", "axis 5 32767", "button 4 0", "button 6 1", "button 7 0", "button 8 0", "axis 0 -11437", "axis 1 22744", "axis 2 20431", "axis 3 -9124"],
            ),
        ],
    ),
    (
        "ps3 mini",
        &[
            (
                &[0x43, 0x13, 0xe6, 0xfc, 0x4c, 0x15, 0x57],
                &["hat 0 0", "button 3 0", "button 1 0", "button 0 1", "button 2 0", "button 9 1", "button 10 0", "axis 4 32767", "axis 5 -32768", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "axis 0 26342", "axis 1 31996", "axis 2 -15549", "axis 3 -27885", "rumble 01 01 ff 00 ff 00 00 00 00 00 04 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"],
            ),
            (
                &[0xc5, 0x17, 0xc4, 0x88, 0x8a, 0x7d, 0xf3],
                &["hat 0 0", "button 3 0", "button 1 0", "button 0 0", "button 2 1", "button 9 1", "button 10 0", "axis 4 32767", "axis 5 32767", "button 4 1", "button 6 1", "button 7 1", "button 8 0", "axis 0 17604", "axis 1 2184", "axis 2 17861", "axis 3 -26857"],
            ),
            (
                &[0x2f, 0xc8, 0xef, 0xb7, 0xef, 0xd9, 0x11],
                &["hat 0 0", "button 3 0", "button 1 1", "button 0 1", "button 2 1", "button 9 1", "button 10 0", "axis 4 -32768", "axis 5 32767", "button 4 1", "button 6 0", "button 7 1", "button 8 1", "axis 0 28655", "axis 1 14263", "axis 2 -20689", "axis 3 18632"],
            ),
            (
                &[0xd5, 0x50, 0x46, 0x12, 0xec, 0x82, 0xd0],
                &["hat 0 0", "button 3 0", "button 1 1", "button 0 1", "button 2 1", "button 9 0", "button 10 1", "axis 4 -32768", "axis 5 -32768", "button 4 0", "button 6 0", "button 7 0", "button 8 1", "axis 0 -14778", "axis 1 -28142", "axis 2 21973", "axis 3 -12208"],
            ),
            (
                &[0xcd, 0x62, 0xd1, 0x3d, 0xa1, 0x10, 0xe8],
                &["hat 0 3", "button 3 0", "button 1 1", "button 0 0", "button 2 1", "button 9 0", "button 10 0", "axis 4 -32768", "axis 5 -32768", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "axis 0 20945", "axis 1 -17091", "axis 2 19917", "axis 3 -7582"],
            ),
            (
                &[0xe3, 0x11, 0xad, 0xc6, 0xf6, 0x1a, 0xfb],
                &["hat 0 8", "button 3 1", "button 1 1", "button 0 1", "button 2 1", "button 9 0", "button 10 1", "axis 4 -32768", "axis 5 32767", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "axis 0 11693", "axis 1 18118", "axis 2 25571", "axis 3 -28399"],
            ),
        ],
    ),
    (
        "thirdparty analog sensors",
        &[
            (
                &[0x80, 0x91, 0x00, 0xb3, 0xbb, 0x85, 0xd7, 0x31, 0xe8, 0xe5, 0xba, 0xe0, 0x3e, 0x4e, 0x8e, 0x63, 0x79, 0xf7, 0x6b],
                &["button 2 0", "button 0 0", "button 1 0", "button 3 0", "button 9 0", "button 10 0", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "button 5 1", "axis 4 30711", "axis 5 32767", "axis 0 13235", "axis 1 15291", "axis 2 1413", "axis 3 22487", "axis 6 -12722", "axis 7 -16834", "axis 8 3726", "axis 9 24800", "axis 10 -7325", "axis 11 -1671", "axis 12 26085", "axis 13 15034", "axis 14 26856", "axis 15 -20175", "sensor Accel NOW 4231bc14 4231bc14 4231bc14"],
            ),
            (
                &[0x89, 0x54, 0x7c, 0xd0, 0xee, 0xc7, 0x6a, 0x3c, 0x70, 0x00, 0x89, 0x8c, 0x58, 0x23, 0xed, 0x18, 0x45, 0xc2, 0xbb, 0x8c, 0xd8],
                &["button 2 1", "button 0 0", "button 1 0", "button 3 1", "button 9 0", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 0", "button 5 1", "hat 0 0", "axis 4 17090", "axis 5 32767", "axis 0 20688", "axis 1 28398", "axis 2 18375", "axis 3 -5526", "axis 6 -23773", "axis 7 -10152", "axis 8 28141", "axis 9 3212", "axis 10 -26600", "axis 11 -15035", "axis 12 -32768", "axis 13 2441", "axis 14 -3984", "axis 15 -17348", "sensor Accel NOW 44663d44 4231bc14 4231bc14"],
            ),
            (
                &[0x1b, 0xbc, 0x86, 0x21, 0x14, 0xa3, 0xf4, 0xcc, 0xf7, 0x1e, 0x2b, 0x0b, 0xed, 0x9f, 0xc8, 0x43, 0x3c, 0xe7, 0x47, 0x76, 0x40, 0x57, 0x65],
                &["button 2 1", "button 0 1", "button 1 0", "button 3 1", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 1", "button 5 1", "hat 0 8", "axis 4 26599", "axis 5 -14521", "axis 0 -24287", "axis 1 -27628", "axis 2 9123", "axis 3 29940", "axis 6 8095", "axis 7 28141", "axis 8 18632", "axis 9 -29941", "axis 10 -15549", "axis 11 -17348", "axis 12 -25058", "axis 13 -21717", "axis 14 30711", "axis 15 19660", "sensor Accel NOW c4ad75e7 c509f046 4231bc14"],
            ),
            (
                &[0x73, 0x2b, 0x06, 0x35, 0xbf, 0x7c, 0x41, 0x04, 0x42, 0x40, 0xb6, 0xee, 0xb1, 0x0c, 0x1f, 0x3d, 0xbf, 0xb6, 0x9f, 0x85, 0x03, 0xd6, 0x7d, 0x80, 0xa7],
                &["button 2 1", "button 0 1", "button 1 0", "button 3 0", "button 9 1", "button 10 1", "button 4 1", "button 6 1", "button 7 0", "button 8 1", "button 5 0", "hat 0 8", "axis 4 32767", "axis 5 8095", "axis 0 -19147", "axis 1 16319", "axis 2 -900", "axis 3 -16063", "axis 6 -29684", "axis 7 12721", "axis 8 -24801", "axis 9 28398", "axis 10 -17091", "axis 11 16319", "axis 12 -16320", "axis 13 14006", "axis 14 -15806", "axis 15 -31740", "sensor Accel NOW c2070966 c52bf3e2 44fb53f5"],
            ),
            (
                &[0xff, 0xb4, 0xaa, 0xd6, 0xbd, 0x36, 0x9c, 0xe3, 0x4e, 0x04, 0x29, 0x3a, 0x21, 0xef, 0x3a, 0x07, 0x10, 0x2b, 0x69, 0x00, 0x02, 0x99, 0x60, 0xd3, 0x6c, 0xd1, 0xf0],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 1", "button 9 1", "button 10 1", "button 4 0", "button 6 0", "button 7 1", "button 8 0", "button 5 1", "hat 0 0", "axis 4 32767", "axis 5 32767", "axis 0 22230", "axis 1 15805", "axis 2 -18890", "axis 3 7324", "axis 6 28655", "axis 7 -24287", "axis 8 -17862", "axis 9 -17862", "axis 10 -30969", "axis 11 -28656", "axis 12 -31740", "axis 13 -22231", "axis 14 -12722", "axis 15 25571", "sensor Accel NOW 80000000 c5035a92 c51454bd"],
            ),
            (
                &[0x87, 0x45, 0xf1, 0xf0, 0xb4, 0xc8, 0x27, 0xdc, 0xa9, 0xaf, 0x00, 0x29, 0x41, 0x46, 0x6f, 0x69, 0xcd, 0xe9, 0x9d, 0x23, 0xc0, 0x41, 0x74, 0x70, 0x1d, 0x3d, 0xe9, 0x56, 0xa1],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 0", "button 9 0", "button 10 0", "button 4 1", "button 6 0", "button 7 1", "button 8 0", "button 5 0", "hat 0 3", "axis 4 27113", "axis 5 32767", "axis 0 28912", "axis 1 13492", "axis 2 18632", "axis 3 -22745", "axis 6 -14778", "axis 7 -16063", "axis 8 -4241", "axis 9 -22231", "axis 10 -5783", "axis 11 19917", "axis 12 12207", "axis 13 -32768", "axis 14 10665", "axis 15 23772", "sensor Accel NOW 44b6e8c2 c51ea5c3 c41864c3"],
            ),
            (
                &[0xd2, 0x0c, 0x04, 0xb0, 0x73, 0xd0, 0x11, 0x00, 0x4f, 0x9b, 0x55, 0x07, 0x4e, 0x8c, 0x05, 0x25, 0xc9, 0x90, 0x6f, 0x92, 0x0b, 0x24, 0xb9, 0x05, 0x8c, 0xe7, 0x7a, 0x29, 0xe7, 0xe7, 0x15],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 0", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 1", "button 5 0", "hat 0 4", "axis 4 32767", "axis 5 32767", "axis 0 12464", "axis 1 -3213", "axis 2 20688", "axis 3 -28399", "axis 6 3212", "axis 7 -12722", "axis 8 -31483", "axis 9 -30969", "axis 10 -23259", "axis 11 18889", "axis 12 7067", "axis 13 -10923", "axis 14 -12465", "axis 15 -32768", "sensor Accel NOW c3549f3f 44ca568e 4523d271"],
            ),
            (
                &[0xc1, 0xa1, 0xa8, 0xda, 0x95, 0x98, 0xf3, 0xdb, 0x24, 0x4c, 0x65, 0x8e, 0x08, 0xd1, 0xb3, 0x27, 0x27, 0x90, 0xbe, 0xb3, 0x9e, 0xc1, 0x5a, 0xf4, 0x6e, 0xa9, 0xde, 0x00, 0xe4, 0x93, 0x6b, 0x98, 0xca],
                &["button 2 1", "button 0 0", "button 1 0", "button 3 0", "button 9 0", "button 10 0", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "button 5 0", "hat 0 0", "axis 4 32767", "axis 5 32767", "axis 0 23258", "axis 1 5525", "axis 2 6296", "axis 3 29683", "axis 6 20945", "axis 7 -30712", "axis 8 13235", "axis 9 3726", "axis 10 -22745", "axis 11 -22745", "axis 12 -13236", "axis 13 -6811", "axis 14 -23516", "axis 15 23515", "sensor Accel NOW 4509e263 c4f67a98 c5174980"],
            ),
            (
                &[0x8f, 0xfd, 0x49, 0x50, 0xed, 0x33, 0x44, 0xb7, 0x77, 0xde, 0xfe, 0xc3, 0x72, 0x4b, 0x88, 0xde, 0x53, 0x51, 0xab, 0x0c, 0x42, 0x19, 0xcb, 0x92, 0x4f, 0xb0, 0x79, 0x66, 0x77, 0x4e, 0xd5, 0x55, 0x55, 0x64, 0xa9],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 1", "button 9 0", "button 10 0", "button 4 1", "button 6 0", "button 7 1", "button 8 1", "button 5 1", "hat 0 0", "axis 4 -11951", "axis 5 32767", "axis 0 -12208", "axis 1 28141", "axis 2 -19661", "axis 3 -15292", "axis 6 -13493", "axis 7 -3470", "axis 8 2184", "axis 9 17347", "axis 10 24286", "axis 11 -11437", "axis 12 24286", "axis 13 32510", "axis 14 -2185", "axis 15 14263", "sensor Accel NOW c4b1dd68 44987834 c4d76bbe"],
            ),
            (
                &[0xf7, 0xa8, 0x07, 0x47, 0x53, 0x88, 0x5f, 0x1e, 0x51, 0x67, 0x2e, 0x1f, 0xe3, 0xca, 0xa1, 0xd2, 0xf2, 0xc5, 0x38, 0x36, 0x0a, 0x38, 0xb5, 0x5d, 0xc6, 0xcc, 0x67, 0xc4, 0xfa, 0xab, 0x33, 0x73, 0xa2, 0x02, 0x67, 0xd9, 0x8d],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 0", "button 9 1", "button 10 1", "button 4 0", "button 6 0", "button 7 0", "button 8 1", "button 5 0", "hat 0 9", "axis 4 32767", "axis 5 32767", "axis 0 -14521", "axis 1 -11437", "axis 2 2184", "axis 3 -8353", "axis 6 19146", "axis 7 25571", "axis 8 8609", "axis 9 -24801", "axis 10 21202", "axis 11 29426", "axis 12 -6297", "axis 13 -20946", "axis 14 -11951", "axis 15 -25058", "sensor Accel NOW c3366bca 44d53ac4 44a59e0e"],
            ),
            (
                &[0x37, 0x3e, 0x65, 0xc9, 0xea, 0x33, 0xe4, 0xcd, 0xad, 0x06, 0x9e, 0x69, 0x84, 0x8f, 0x2e, 0x6e, 0x1b, 0x46],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 0", "button 9 1", "button 10 1", "button 4 0", "button 6 1", "button 7 1", "button 8 1", "hat 0 6", "axis 4 -25829", "axis 5 -14778", "axis 0 -6811", "axis 1 18889", "axis 2 27370", "axis 3 -19661", "axis 6 1156", "axis 7 -5783", "axis 8 3983", "axis 9 7838", "axis 10 -20946", "axis 11 -4498", "axis 12 11693", "axis 13 -31226", "axis 14 19917", "axis 15 25828"],
            ),
            (
                &[0x25, 0x1d, 0xca, 0x8e, 0x5e, 0x50, 0x49, 0xc4, 0x1f, 0x6a, 0x32, 0x0b, 0xf4, 0x00, 0x3c, 0xd5, 0x4c, 0x44],
                &["button 2 1", "button 0 0", "button 1 1", "button 3 0", "button 9 0", "button 10 1", "button 4 1", "button 6 0", "button 7 1", "button 8 1", "hat 0 3", "axis 4 -13236", "axis 5 -15292", "axis 0 19146", "axis 1 3726", "axis 2 -8610", "axis 3 -12208", "axis 6 29940", "axis 7 -29941", "axis 8 -32768", "axis 9 -19918", "axis 10 -17348", "axis 11 21973", "axis 12 -24801", "axis 13 -5526", "axis 14 17604", "axis 15 -14007"],
            ),
            (
                &[0x31, 0x32, 0xd0, 0x36, 0xb4, 0xd9, 0x87, 0x89, 0xb5, 0xf7, 0xab, 0x56, 0xb0, 0xb9, 0x48, 0x82, 0xa8, 0x9b],
                &["button 2 1", "button 0 0", "button 1 0", "button 3 0", "button 9 1", "button 10 1", "button 4 0", "button 6 1", "button 7 0", "button 8 0", "hat 0 6", "axis 4 10408", "axis 5 7067", "axis 0 20688", "axis 1 -18890", "axis 2 13492", "axis 3 23001", "axis 6 12464", "axis 7 -10666", "axis 8 14777", "axis 9 11179", "axis 10 -14264", "axis 11 642", "axis 12 13749", "axis 13 30711", "axis 14 2441", "axis 15 1927"],
            ),
            (
                &[0x9a, 0xf0, 0xe7, 0x6e, 0x24, 0x67, 0x72, 0x2c, 0x90, 0x42, 0x4e, 0x7c, 0x4a, 0xda, 0x76, 0x03, 0xda, 0xb4],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 1", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 0", "button 8 0", "hat 0 0", "axis 4 23258", "axis 5 13492", "axis 0 26599", "axis 1 -4498", "axis 2 -23516", "axis 3 -6297", "axis 6 -13750", "axis 7 -900", "axis 8 23258", "axis 9 -12722", "axis 10 -2442", "axis 11 -31997", "axis 12 4240", "axis 13 -15806", "axis 14 -21460", "axis 15 -3470"],
            ),
            (
                &[0x97, 0x70, 0x05, 0x69, 0x91, 0x46, 0xa3, 0x59, 0xae, 0x68, 0x3f, 0x0f, 0xa0, 0x66, 0x71, 0x72, 0x3d, 0x8a],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 0", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 0", "button 8 0", "hat 0 9", "axis 4 -17091", "axis 5 2698", "axis 0 -31483", "axis 1 -5783", "axis 2 4497", "axis 3 -14778", "axis 6 8352", "axis 7 -28913", "axis 8 -6554", "axis 9 -16577", "axis 10 -3727", "axis 11 -3470", "axis 12 11950", "axis 13 -6040", "axis 14 -9895", "axis 15 9123"],
            ),
            (
                &[0xfa, 0xb1, 0xf9, 0xa0, 0xa4, 0xec, 0x27, 0x89, 0xd7, 0xa3, 0xef, 0x7f, 0xfb, 0xdf, 0x0e, 0x25, 0x91, 0x22],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 1", "button 9 1", "button 10 1", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "hat 0 0", "axis 4 4497", "axis 5 -24030", "axis 0 31225", "axis 1 8352", "axis 2 9380", "axis 3 27884", "axis 6 31739", "axis 7 -129", "axis 8 24543", "axis 9 28655", "axis 10 -29170", "axis 11 -23259", "axis 12 22487", "axis 13 9123", "axis 14 2441", "axis 15 -22745"],
            ),
            (
                &[0x51, 0x56, 0x11, 0x0f, 0xcf, 0xaa, 0x81, 0xda, 0xe9, 0xc8, 0xda, 0x6e, 0x02, 0x6e, 0x1a, 0x5f, 0xff],
                &[],
            ),
        ],
    ),
    (
        "thirdparty digital",
        &[
            (
                &[0x41, 0x28, 0x96, 0x7d, 0x55, 0x6c, 0xb6, 0xd5, 0x7c, 0x2a, 0x50, 0xd1, 0x4f, 0xa3, 0xcc, 0x2b, 0xfe, 0xea, 0x12, 0xc9, 0xd7, 0x87, 0xfb, 0xbb, 0x97, 0xcd, 0x7b],
                &["button 2 1", "button 0 0", "button 1 0", "button 3 0", "button 9 0", "button 10 0", "button 4 0", "button 6 0", "button 7 0", "button 8 1", "button 5 0", "hat 0 8", "axis 4 32767", "axis 5 -28142", "axis 0 -643", "axis 1 -10923", "axis 2 -5012", "axis 3 14006"],
            ),
            (
                &[0xf0, 0x74, 0xfb, 0x8a, 0xbc, 0xe6, 0x15, 0xd7, 0x0a, 0x39, 0x80, 0x2c, 0x60, 0xd4, 0x60, 0x9f, 0x98, 0x47],
                &["button 2 0", "button 0 0", "button 1 0", "button 3 0", "button 9 1", "button 10 1", "button 4 0", "button 6 0", "button 7 1", "button 8 0", "hat 0 9", "axis 4 6296", "axis 5 -14521", "axis 0 31739", "axis 1 2698", "axis 2 15548", "axis 3 26342"],
            ),
            (
                &[0xb2, 0x7e, 0x58, 0x16, 0x28, 0xf8, 0x56, 0x47, 0xc8, 0x8b, 0x4d, 0xad, 0x43, 0x32, 0xbe, 0xf3, 0x16, 0x4a, 0x67, 0x67, 0x62, 0x48, 0x84, 0x8c, 0x8c, 0x1d, 0xc8],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 0", "button 9 1", "button 10 1", "button 4 0", "button 6 1", "button 7 1", "button 8 1", "button 5 1", "hat 0 0", "axis 4 -13750", "axis 5 32767", "axis 0 -27114", "axis 1 -22488", "axis 2 30968", "axis 3 -10666"],
            ),
            (
                &[0x5e, 0x94, 0x64, 0x1a, 0x63, 0x36, 0x51, 0x10, 0x76, 0xc3, 0x5a, 0x2c, 0x53, 0xbc, 0xa2, 0xd9, 0xe1, 0x33],
                &["button 2 0", "button 0 1", "button 1 1", "button 3 1", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 0", "hat 0 0", "axis 4 25057", "axis 5 -19661", "axis 0 -7068", "axis 1 -26086", "axis 2 -7325", "axis 3 -18890"],
            ),
            (
                &[0x2a, 0x23, 0x43, 0xe2, 0xb7, 0x3a, 0x9d, 0x08, 0x81, 0xa5, 0xa6, 0x07, 0xa0, 0x45, 0xf2, 0xbf, 0x36, 0x11, 0xfd, 0xa8, 0x5d, 0x8b, 0xf7, 0xb2, 0xcf, 0x05, 0x51],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 1", "button 9 0", "button 10 1", "button 4 1", "button 6 1", "button 7 0", "button 8 0", "button 5 0", "hat 0 6", "axis 4 -28399", "axis 5 32253", "axis 0 25314", "axis 1 14263", "axis 2 -17862", "axis 3 7581"],
            ),
            (
                &[0xdc, 0x58, 0x95, 0x0c, 0x96, 0xfc, 0xd9, 0xbc, 0xd7, 0xe8, 0x6b, 0x5e, 0xfe, 0x19, 0x23, 0xdf, 0x6a, 0xce],
                &["button 2 0", "button 0 0", "button 1 1", "button 3 1", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 0", "button 8 1", "hat 0 12", "axis 4 -5526", "axis 5 20174", "axis 0 5525", "axis 1 -29684", "axis 2 5782", "axis 3 31996"],
            ),
            (
                &[0x0f, 0x68, 0xd8, 0xaf, 0x33, 0x6b, 0x7f, 0xba, 0x01, 0x6f, 0xed, 0xf1, 0x97, 0x9b, 0xa0, 0xc5, 0xbb, 0x04, 0x63, 0x40, 0x97, 0xb6, 0x6e, 0xf5, 0x34, 0x84, 0x3d],
                &["button 2 1", "button 0 1", "button 1 1", "button 3 1", "button 9 0", "button 10 0", "button 4 0", "button 6 0", "button 7 0", "button 8 1", "button 5 0", "hat 0 0", "axis 4 -31740", "axis 5 -7325", "axis 0 12207", "axis 1 -19661", "axis 2 -5269", "axis 3 -129"],
            ),
            (
                &[0xa9, 0xb7, 0x90, 0x2c, 0xbf, 0x5e, 0x99, 0xd7, 0x64, 0x3a, 0x07, 0x34, 0x7f, 0xaa, 0xb8, 0x6d, 0x56, 0x9b],
                &["button 2 1", "button 0 0", "button 1 0", "button 3 1", "button 9 0", "button 10 1", "button 4 1", "button 6 1", "button 7 1", "button 8 0", "hat 0 0", "axis 4 -10666", "axis 5 7067", "axis 0 4240", "axis 1 -21460", "axis 2 16319", "axis 3 -8610"],
            ),
            (
                &[0x88, 0x7e, 0x00, 0x81, 0xa3, 0x93, 0x8e, 0x14, 0x8a, 0x1f, 0xf8, 0xcb, 0xe6, 0xbc, 0xc9, 0x19, 0x10, 0xc6, 0x8a, 0x6a, 0x5c, 0xb5, 0xf0, 0xdc, 0x29, 0x3e, 0xc4],
                &["button 2 0", "button 0 0", "button 1 0", "button 3 1", "button 9 0", "button 10 0", "button 4 0", "button 6 1", "button 7 1", "button 8 1", "button 5 1", "hat 0 1", "axis 4 18118", "axis 5 32767", "axis 0 385", "axis 1 9123", "axis 2 5011", "axis 3 3726"],
            ),
            (
                &[0xbe, 0xa9, 0x29, 0x96, 0xc9, 0x71, 0xf1, 0x21, 0x20, 0xbf, 0x1d, 0x7d, 0x09, 0x8f, 0x61, 0x07, 0x69, 0x5c],
                &["button 2 0", "button 0 1", "button 1 1", "button 3 1", "button 9 1", "button 10 1", "button 4 1", "button 6 0", "button 7 0", "button 8 1", "hat 0 0", "axis 4 -5783", "axis 5 -9124", "axis 0 -22231", "axis 1 5782", "axis 2 18889", "axis 3 -3727"],
            ),
        ],
    ),
    (
        "cyborg analog",
        &[
            (
                &[0x73, 0x10, 0x01, 0xb6, 0xae, 0x48, 0x6b, 0x89, 0x6a, 0xe9, 0xd2, 0x27, 0x16, 0xa3, 0x74, 0x1a, 0x1a, 0x4a, 0xd9, 0xac, 0x6e, 0x42, 0xd1, 0x32, 0xfa, 0xa6, 0x2f],
                &["button 2 1", "button 0 1", "button 1 0", "button 3 0", "button 9 1", "button 10 1", "button 4 0", "button 6 0", "button 7 0", "button 8 0", "button 5 1", "hat 0 15", "axis 4 32767", "axis 5 23001", "axis 0 14006", "axis 1 11950", "axis 2 -14264", "axis 3 -5269", "axis 6 9123", "axis 7 -27114", "axis 8 -2956", "axis 9 -22745", "axis 10 -26086", "axis 11 -26086", "axis 12 27113", "axis 13 21202", "axis 14 -5526", "axis 15 2441"],
            ),
            (
                &[0x1d, 0xac, 0x3b, 0x46, 0xbf, 0x5b, 0x18, 0x00, 0xdc, 0x5f, 0x11, 0x99, 0xf8, 0xec, 0xe8, 0xd5, 0x5b, 0x33, 0x32, 0x06, 0xe4, 0x37, 0x0a, 0x83, 0x93, 0x6f, 0x79],
                &["button 2 1", "button 0 0", "button 1 1", "button 3 1", "button 9 1", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 1", "button 5 0", "hat 0 13", "axis 4 -19661", "axis 5 -19918", "axis 0 -14778", "axis 1 16319", "axis 2 -9381", "axis 3 -26600", "axis 6 27884", "axis 7 30968", "axis 8 26856", "axis 9 6553", "axis 10 21973", "axis 11 -9381", "axis 12 -8353", "axis 13 -28399", "axis 14 23772", "axis 15 -32768"],
            ),
            (
                &[0xca, 0xd4, 0x21, 0xa1, 0x3c, 0x8c, 0x79, 0xac, 0x00, 0xe5, 0x6c, 0x76, 0x43, 0xda, 0x4f, 0xfc, 0x2b, 0x81, 0x35, 0x84, 0x9b, 0x1b, 0x0d, 0x8a, 0xab, 0xdd, 0x78],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 1", "button 9 0", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 0", "button 5 1", "hat 0 7", "axis 4 32767", "axis 5 32767", "axis 0 8609", "axis 1 -17348", "axis 2 3212", "axis 3 -1671", "axis 6 23258", "axis 7 -15549", "axis 8 -12465", "axis 9 -2442", "axis 10 31996", "axis 11 -21717", "axis 12 26085", "axis 13 -5012", "axis 14 -32768", "axis 15 11436"],
            ),
            (
                &[0x6e, 0x7f, 0x7c, 0x6c, 0xdf, 0x44, 0x7b, 0x00, 0x00, 0xe9, 0x34, 0x3f, 0x71, 0x9e, 0xa8, 0x9c, 0xc5, 0x0d, 0x06, 0xf6, 0x23, 0x5b, 0xfd, 0x3d, 0x56, 0xdd, 0xc1],
                &["button 2 0", "button 0 1", "button 1 1", "button 3 1", "button 9 0", "button 10 1", "button 4 1", "button 6 1", "button 7 1", "button 8 1", "button 5 1", "hat 0 5", "axis 4 32767", "axis 5 -31226", "axis 0 -5012", "axis 1 24543", "axis 2 -15292", "axis 3 -1157", "axis 6 7838", "axis 7 -3727", "axis 8 10408", "axis 9 -16577", "axis 10 7324", "axis 11 17861", "axis 12 27113", "axis 13 -19404", "axis 14 -32768", "axis 15 -32768"],
            ),
            (
                &[0x1d, 0xc3, 0x9a, 0xdf, 0xd6, 0x0d, 0x85, 0xc1, 0xdc, 0x00, 0x77, 0x01, 0x2e, 0x6b, 0xee, 0x6e, 0x76, 0xa3, 0x88, 0xdf, 0xe6, 0x9b, 0x3d, 0xba, 0xcd, 0x9b, 0x5f],
                &["button 2 1", "button 0 0", "button 1 1", "button 3 1", "button 9 1", "button 10 0", "button 4 1", "button 6 1", "button 7 0", "button 8 0", "button 5 0", "hat 0 14", "axis 4 9123", "axis 5 2184", "axis 0 24543", "axis 1 22230", "axis 2 -29427", "axis 3 1413", "axis 6 -5269", "axis 7 -20946", "axis 8 28398", "axis 9 -32511", "axis 10 -4498", "axis 11 -2442", "axis 12 -32768", "axis 13 -2185", "axis 14 23772", "axis 15 16833"],
            ),
            (
                &[0x42, 0xfb, 0xf6, 0x53, 0xa5, 0xda, 0xf4, 0x00, 0xc1, 0x00, 0x81, 0x4d, 0xba, 0x37, 0x96, 0x9b, 0x3c, 0x04, 0x6b, 0x03, 0x91, 0x97, 0x59, 0x91, 0x62, 0x3f, 0x91],
                &["button 2 0", "button 0 1", "button 1 0", "button 3 0", "button 9 0", "button 10 0", "button 4 1", "button 6 1", "button 7 0", "button 8 1", "button 5 1", "hat 0 12", "axis 4 32767", "axis 5 -5269", "axis 0 -11437", "axis 1 9637", "axis 2 23258", "axis 3 29940", "axis 6 -18633", "axis 7 15034", "axis 8 5782", "axis 9 -12979", "axis 10 7067", "axis 11 -17348", "axis 12 -32768", "axis 13 385", "axis 14 16833", "axis 15 -32768"],
            ),
            (
                &[0x8b, 0x4c, 0x4b, 0x7f, 0x71, 0x2a, 0x68, 0xfc, 0x00, 0x00, 0xbd, 0x36, 0x3a, 0x5b, 0xc8, 0x5f, 0x8f, 0xbd, 0xf6, 0x18, 0xe8, 0x06, 0x05, 0x9c, 0xe0, 0xf4, 0x1a],
                &["button 2 1", "button 0 1", "button 1 0", "button 3 1", "button 9 0", "button 10 0", "button 4 0", "button 6 0", "button 7 1", "button 8 1", "button 5 0", "hat 0 6", "axis 4 15805", "axis 5 32767", "axis 0 -129", "axis 1 -3727", "axis 2 -21974", "axis 3 -6040", "axis 6 -9381", "axis 7 -17862", "axis 8 18632", "axis 9 -18890", "axis 10 -8353", "axis 11 3983", "axis 12 -32768", "axis 13 15805", "axis 14 -32768", "axis 15 31996"],
            ),
            (
                &[0xad, 0xf1, 0x09, 0xa1, 0x3e, 0xaf, 0x16, 0x00, 0x00, 0x00, 0x8c, 0x7b, 0xff, 0xbb, 0x82, 0x3d, 0xa0, 0x5b, 0x86, 0x4b, 0x42, 0x02, 0x24, 0x90, 0x29, 0x96, 0x37],
                &["button 2 1", "button 0 0", "button 1 1", "button 3 1", "button 9 0", "button 10 1", "button 4 1", "button 6 0", "button 7 0", "button 8 0", "button 5 1", "hat 0 4", "axis 4 -9381", "axis 5 32767", "axis 0 8609", "axis 1 -16834", "axis 2 12207", "axis 3 -27114", "axis 6 15291", "axis 7 32767", "axis 8 642", "axis 9 -1157", "axis 10 -17091", "axis 11 8352", "axis 12 -32768", "axis 13 3212", "axis 14 -32768", "axis 15 -32768"],
            ),
        ],
    ),
    (
        "sixaxis analog sensors",
        &[
            (
                &[0x00, 0x97, 0x3d, 0xf2, 0x76, 0xb5, 0xe0, 0xac, 0x04, 0x3c, 0x60, 0x70, 0x1d, 0xe6, 0x9b, 0x40, 0x2c, 0x98, 0x1d, 0x2d, 0xd3, 0x4c, 0xa6, 0x18, 0xcb, 0xc0, 0x60, 0x45, 0x7e, 0xe0, 0xdd, 0xa5, 0x66, 0xf4, 0xd2, 0xe0, 0x23, 0x89, 0x95, 0x24, 0x5f, 0x21, 0x58, 0xb0, 0x62, 0x9a, 0x23, 0x1f, 0x74],
                &["button 4 0", "button 7 1", "button 8 0", "button 6 0", "hat 0 15", "button 9 1", "button 10 0", "button 3 1", "button 1 1", "button 0 1", "button 2 0", "button 5 1", "axis 4 -21203", "axis 5 21459", "axis 0 11436", "axis 1 -31740", "axis 2 -17348", "axis 3 -8096", "axis 6 16576", "axis 7 19403", "axis 8 -8096", "axis 9 -26600", "axis 10 -13236", "axis 11 9894", "axis 12 -16320", "axis 13 6296", "axis 14 -25315", "axis 15 -21460", "sensor Accel NOW 44f0c047 c437fbb2 c5062449", "rumble 00 01 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"],
            ),
            (
                &[0x00, 0x4a, 0x57, 0x17, 0x9a, 0x43, 0x4a, 0x48, 0xaa, 0x85, 0x4d, 0x2f, 0x2e, 0x18, 0x98, 0xff, 0x4a, 0xeb, 0xd5, 0xb2, 0x1e, 0xc4, 0x9e, 0xd6, 0x9f, 0xef, 0xb9, 0x1a, 0x34, 0xa3, 0x15, 0x9c, 0x10, 0x32, 0x83, 0xf0, 0x52, 0xf9, 0x36, 0xf0, 0xde, 0x02, 0xf9, 0x46, 0xf9, 0x79, 0x32, 0xba, 0xa7, 0xd5],
                &["button 4 1", "button 7 1", "button 8 1", "button 6 0", "hat 0 1", "button 9 0", "button 10 1", "button 3 1", "button 1 0", "button 0 0", "button 2 1", "button 5 1", "axis 4 12978", "axis 5 -25058", "axis 0 -14264", "axis 1 10922", "axis 2 1413", "axis 3 -12979", "axis 6 28655", "axis 7 8095", "axis 8 14777", "axis 9 22230", "axis 10 17604", "axis 11 7838", "axis 12 32767", "axis 13 27627", "axis 14 21973", "axis 15 -13750", "sensor Accel NOW c341ca32 c4875461 433d5d23"],
            ),
            (
                &[0x00, 0x44, 0x10, 0xc2, 0xc4, 0xc3, 0x90, 0xf4, 0xf2, 0x2e, 0x12, 0x4c, 0x3c, 0xd5, 0x29, 0x27, 0x82, 0xb4, 0x9c, 0x6c, 0x60, 0x60, 0xe1, 0x54, 0x06, 0xad, 0x5a, 0xfc, 0xd7, 0x20, 0x51, 0xac, 0xc4, 0x18, 0xb5, 0xe5, 0x67, 0xbb, 0x92, 0x2c, 0xdf, 0xa1, 0x52, 0x99, 0x6e, 0x43, 0xb5, 0x1e, 0xd4, 0x22, 0x92],
                &["button 4 0", "button 7 1", "button 8 0", "button 6 0", "hat 0 12", "button 9 1", "button 10 0", "button 3 0", "button 1 0", "button 0 1", "button 2 1", "button 5 1", "axis 4 -5012", "axis 5 -8096", "axis 0 29940", "axis 1 29426", "axis 2 -20946", "axis 3 -28142", "axis 6 11693", "axis 7 -31226", "axis 8 -9638", "axis 9 -11180", "axis 10 -8096", "axis 11 25057", "axis 12 -22745", "axis 13 13492", "axis 14 7324", "axis 15 642", "sensor Accel NOW 44dfd6c7 44d58031 c516551d"],
            ),
            (
                &[0x00, 0x45, 0x29, 0xb1, 0xb3, 0xf7, 0x72, 0x71, 0x9c, 0xf5, 0x6f, 0x85, 0x08, 0xdc, 0x0e, 0x78, 0x94, 0xb5, 0x33, 0x1a, 0x57, 0xde, 0x30, 0x53, 0xbe, 0xba, 0x02, 0xab, 0x29, 0x18, 0x51, 0x95, 0x42, 0x64, 0x26, 0x7f, 0x21, 0x90, 0x6a, 0x9a, 0x22, 0xc0, 0x22, 0x69, 0x81, 0xb8, 0x6c, 0x0b, 0xba, 0x06, 0x39, 0x49],
                &["button 4 1", "button 7 0", "button 8 0", "button 6 0", "hat 0 11", "button 9 0", "button 10 0", "button 3 1", "button 1 1", "button 0 0", "button 2 1", "button 5 1", "axis 4 -26086", "axis 5 -10409", "axis 0 -3727", "axis 1 7324", "axis 2 30197", "axis 3 -4241", "axis 6 15034", "axis 7 16062", "axis 8 -32254", "axis 9 -11437", "axis 10 24286", "axis 11 -20432", "axis 12 -1928", "axis 13 13749", "axis 14 -19661", "axis 15 5268", "sensor Accel NOW 443408d4 c513406b 45321eab"],
            ),
            (
                &[0x00, 0x0d, 0x62, 0xa5, 0x29, 0x9d, 0xb0, 0x7f, 0x68, 0x9a, 0x23, 0x9c, 0x51, 0xee, 0x07, 0xb1, 0x3f, 0xac, 0x5a, 0x7d, 0xc4, 0xff, 0x4a, 0x93, 0x88, 0xd5, 0x73, 0xe6, 0xe8, 0x4b, 0xd5, 0x16, 0x4a, 0xd7, 0x97, 0x7d, 0x42, 0x37, 0x7d, 0xf8, 0x66, 0x1d, 0x2a, 0x75, 0xf1, 0x97, 0x17, 0x41, 0x1a, 0x40, 0x4f, 0x0f, 0x32],
                &["button 4 1", "button 7 0", "button 8 1", "button 6 0", "hat 0 10", "button 9 0", "button 10 1", "button 3 0", "button 1 1", "button 0 0", "button 2 0", "button 5 1", "axis 4 -643", "axis 5 17604", "axis 0 -129", "axis 1 -6040", "axis 2 6810", "axis 3 -23773", "axis 6 21973", "axis 7 2184", "axis 8 -3213", "axis 9 5011", "axis 10 32767", "axis 11 -13750", "axis 12 12721", "axis 13 11436", "axis 14 -9638", "axis 15 -16577", "sensor Accel NOW 4460ba7f c3ec2402 43b63f5b"],
            ),
            (
                &[0x01, 0x5b, 0x7b, 0x5e, 0xe4, 0x76, 0x0a, 0xdd, 0x15, 0xdf, 0xf0, 0x4e, 0xd9, 0xcb, 0xd4, 0x93, 0x44, 0x5a, 0xd1, 0x55, 0x66, 0x83, 0xf1, 0xd4, 0x24, 0xbf, 0x6b, 0x6e, 0xd5, 0x78, 0x9c, 0xf1, 0x9c, 0x30, 0xc7, 0xa0, 0x88, 0x72, 0x8d, 0x07, 0x6c, 0x79, 0x2a, 0x7f, 0x7f, 0xa1, 0x75, 0x7f, 0xb4, 0x91, 0x96, 0xa9, 0xd8, 0x26],
                &[],
            ),
            (
                &[0x00, 0xf0, 0x33, 0x9b, 0xa5, 0x42, 0x3f, 0x4c, 0x64, 0x82, 0x93, 0x5e, 0x5e, 0x33, 0x34, 0xde, 0x63, 0x7f, 0x57, 0x62, 0xfe, 0x29, 0xe3, 0xd5, 0x52, 0x38, 0xab, 0x03, 0xaf, 0x61, 0x67, 0xe4, 0xf7, 0x31, 0x77, 0xa8, 0xb3, 0xff, 0x58, 0x86, 0xf4, 0x94, 0xe2, 0x45, 0xeb, 0x96, 0x47, 0x87, 0x48, 0xb9, 0xcc, 0xd8, 0x53, 0xa6, 0x45],
                &["button 4 1", "button 7 1", "button 8 0", "button 6 1", "hat 0 9", "button 9 1", "button 10 0", "button 3 0", "button 1 1", "button 0 0", "button 2 1", "button 5 0", "axis 4 -7582", "axis 5 32510", "axis 0 -13236", "axis 1 -7068", "axis 2 642", "axis 3 5011", "axis 6 -18376", "axis 7 -11694", "axis 8 11179", "axis 9 21973", "axis 10 -22231", "axis 11 25571", "axis 12 24286", "axis 13 -129", "axis 14 -10409", "axis 15 -7325", "sensor Accel NOW c4303749 c4c11876 43f8f0ff"],
            ),
            (
                &[0x00, 0x8b, 0x4b, 0x1e, 0x2b, 0xc0, 0x10, 0x8c, 0x15, 0x44, 0xcf, 0x8a, 0xa1, 0xe5, 0xe8, 0x51, 0x5b, 0xda, 0xad, 0x64, 0x4d, 0xb2, 0xe1, 0x57, 0xd1, 0x00, 0xf2, 0x64, 0x37, 0xc4, 0xf6, 0xaf, 0x1c, 0x98, 0x67, 0x55, 0x85, 0x9f, 0x9f, 0x37, 0xbe, 0x2d, 0x12, 0x87, 0xf5, 0x36, 0x4d, 0x17, 0x95, 0x78, 0xb2, 0x5c, 0x64, 0x68, 0xf0, 0x45],
                &["button 4 0", "button 7 1", "button 8 1", "button 6 1", "hat 0 1", "button 9 0", "button 10 1", "button 3 0", "button 1 1", "button 0 0", "button 2 0", "button 5 0", "axis 4 -7068", "axis 5 -12979", "axis 0 3212", "axis 1 -27371", "axis 2 -15292", "axis 3 20431", "axis 6 -32768", "axis 7 20945", "axis 8 29426", "axis 9 -10409", "axis 10 12978", "axis 11 25057", "axis 12 -11951", "axis 13 23258", "axis 14 11693", "axis 15 -9381", "sensor Accel NOW 43b7a2d3 c4d08b0f 438e05da"],
            ),
        ],
    ),
];

/// The driver calls, with what they do.
pub(super) const CALLS: &[(&str, &[&str])] = &[
    ("player 0", &["rumble 01 01 ff 00 ff 00 00 00 00 00 02 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("player 1", &["rumble 01 01 ff 00 ff 00 00 00 00 00 04 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("player 2", &["rumble 01 01 ff 00 ff 00 00 00 00 00 08 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("player 3", &["rumble 01 01 ff 00 ff 00 00 00 00 00 10 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("player 4", &["rumble 01 01 ff 00 ff 00 00 00 00 00 02 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("player 7", &["rumble 01 01 ff 00 ff 00 00 00 00 00 10 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("player -1", &["rumble 01 01 ff 00 ff 00 00 00 00 00 01 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("rumble 1234 0000", &["rumble 01 01 ff 00 ff 12 00 00 00 00 01 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("rumble 0000 00ff", &["rumble 01 01 ff 00 ff 00 00 00 00 00 01 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("rumble ffff 0100", &["rumble 01 01 ff 01 ff ff 00 00 00 00 01 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 ff 27 10 00 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("effect 0", &["rumble 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis effect 0", &["rumble 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("effect 1", &["rumble 01 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis effect 1", &["rumble 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("effect 10", &["rumble 01 80 81 82 83 84 85 86 87 88 89 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis effect 10", &["rumble 80 81 82 83 84 85 86 87 88 89 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("effect 48", &["rumble 01 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af"]),
    ("sixaxis effect 48", &["rumble 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af 00"]),
    ("effect 49", &["rumble 01 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af"]),
    ("sixaxis effect 49", &["rumble 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af b0"]),
    ("effect 60", &["rumble 01 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af"]),
    ("sixaxis effect 60", &["rumble 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af b0"]),
    ("sixaxis player 0", &["rumble 00 01 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis player 1", &["rumble 00 01 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis player 2", &["rumble 00 01 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis player 3", &["rumble 00 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis player 4", &["rumble 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis player 7", &["rumble 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis rumble 1234 0000", &["rumble 00 02 00 00 00 ff 00 ff 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis rumble 0000 00ff", &["rumble 00 02 00 00 00 ff 00 ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
    ("sixaxis rumble ffff 0100", &["rumble 00 02 00 00 00 ff 01 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"]),
];
