// Rust translation of src/video/windows/SDL_windowsgameinput.cpp and
// SDL_windowsgameinput.h from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

//! Raw keyboard and mouse input through GameInput, in place of the raw
//! input thread, when the `SDL_WINDOWS_GAMEINPUT` hint is set and
//! GameInput is available (else the driver keeps using raw input). Every
//! keyboard and mouse GameInput reports is a keyboard or mouse of its own;
//! the event pump reads their readings since the last ones and sends the
//! differences, to the window with keyboard focus.
//!
//! Upstream sends the events while holding the context's lock; here they
//! are collected under the lock and sent after it is released (in the same
//! order), so event watchers never run with it held.

use std::ffi::c_void;
use std::sync::{Arc, Mutex, MutexGuard};
use std::time::Duration;

use windows_sys::Win32::UI::WindowsAndMessaging::WHEEL_DELTA;

use super::window::window_data;
use super::VideoData;
use crate::core::windows::error_from_hresult;
use crate::core::windows::gameinput::{
    init_game_input as init_shared_game_input, kind, CallbackToken, Device, GameInputRef, KeyState,
    MouseState, Reading, BLOCKING_ENUMERATION, DEVICE_CONNECTED, GAMEINPUT_E_READING_NOT_FOUND,
};
use crate::error::Result;
use crate::events::keyboard::Scancode;
use crate::events::mouse::{
    MouseWheelDirection, BUTTON_LEFT, BUTTON_MIDDLE, BUTTON_RIGHT, BUTTON_X1, BUTTON_X2,
};
use crate::events::scancodes_windows::WINDOWS_SCANCODE_TABLE;
use crate::events::{keyboard as sdl_keyboard, mouse, WindowID};

/// GameInputMouseWheelTiltRight is the highest button.
/// Translation of `MAX_GAMEINPUT_BUTTONS`.
const MAX_GAMEINPUT_BUTTONS: usize = 7;

/// The SDL button of each GameInput mouse button bit. Translation of
/// `GAMEINPUT_button_map`.
const GAMEINPUT_BUTTON_MAP: [u8; MAX_GAMEINPUT_BUTTONS] = [
    BUTTON_LEFT,
    BUTTON_RIGHT,
    BUTTON_MIDDLE,
    BUTTON_X1,
    BUTTON_X2,
    6,
    7,
];

/// A keyboard or mouse. Translation of `GAMEINPUT_Device`.
struct GameInputDevice {
    device: Device,
    /// generated by SDL
    instance_id: u32,
    registered: bool,
    delete_requested: bool,
    last_mouse_reading: Option<Reading>,
    last_keyboard_reading: Option<Reading>,
}

/// The part of `WIN_GameInputData` its `lock` guards, which the device
/// callback (on GameInput's thread) reaches through its context.
struct Devices {
    devices: Vec<GameInputDevice>,
    enabled_input: u32,
}

/// Translation of `WIN_GameInputData` (`_this->internal->gameinput_context`).
pub(crate) struct GameInputData {
    game_input: GameInputRef,
    gameinput_callback_token: CallbackToken,
    /// The devices, behind `lock`; the device callback's context.
    devices: Arc<Mutex<Devices>>,
    timestamp_offset: u64,
}

impl GameInputData {
    fn lock(&self) -> MutexGuard<'_, Devices> {
        lock_devices(&self.devices)
    }
}

fn lock_devices(devices: &Mutex<Devices>) -> MutexGuard<'_, Devices> {
    devices.lock().unwrap_or_else(|e| e.into_inner())
}

/// Something to do once the lock is released.
#[derive(Clone, Copy, Debug, PartialEq)]
enum Action {
    AddMouse(u32),
    AddKeyboard(u32),
    RemoveMouse(u32),
    RemoveKeyboard(u32),
    Mouse {
        timestamp: u64,
        window: WindowID,
        mouse_id: u32,
        input: MouseInput,
    },
    Key {
        timestamp: u64,
        keyboard_id: u32,
        key: KeyInput,
    },
    ResetKeyboard,
}

/// A mouse event of a reading, in the order upstream sends them.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(super) enum MouseInput {
    Motion(f32, f32),
    Button(u8, bool),
    /// Invalidate mouse button flags
    InvalidateButtonFlags,
    /// (sent to the window with mouse focus)
    Wheel(f32, f32),
}

/// A key event of a reading: the raw scan code, its scancode, and whether
/// it's down.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(super) struct KeyInput {
    pub(super) rawcode: i32,
    pub(super) scancode: Scancode,
    pub(super) down: bool,
}

/// Translation of `GAMEINPUT_InternalAddOrFind()`.
fn internal_add_or_find(devices: &Mutex<Devices>, device: Device) {
    let mut data = lock_devices(devices);
    if let Some(existing) = data.devices.iter_mut().find(|d| d.device.same(&device)) {
        // we're already added
        existing.delete_requested = false;
        return;
    }

    // (info->displayName could give us a product string, but it's NULL
    // for all the devices upstream tested)
    data.devices.push(GameInputDevice {
        device,
        instance_id: crate::utils::next_object_id(),
        registered: false,
        delete_requested: false,
        last_mouse_reading: None,
        last_keyboard_reading: None,
    });
}

/// Translation of `GAMEINPUT_InternalRemoveByIndex()`: the events of the
/// removal are queued in `actions`.
fn internal_remove_by_index(data: &mut Devices, idx: usize, actions: &mut Vec<Action>) {
    if idx >= data.devices.len() {
        return;
    }
    let device = data.devices.remove(idx);
    if device.registered {
        let supported_input = device.device.info().supported_input;
        if (supported_input & kind::MOUSE) != 0 {
            actions.push(Action::RemoveMouse(device.instance_id));
        }
        if (supported_input & kind::KEYBOARD) != 0 {
            actions.push(Action::RemoveKeyboard(device.instance_id));
        }
    }
    // (the readings and the device are released with it)
}

/// Translation of `GAMEINPUT_InternalDeviceCallback()`; the context is the
/// `Mutex<Devices>` of the `GameInputData`.
unsafe extern "system" fn internal_device_callback(
    _callback_token: CallbackToken,
    context: *mut c_void,
    device: *mut c_void,
    _timestamp: u64,
    current_status: u32,
    _previous_status: u32,
) {
    if device.is_null() {
        // This should never happen, but ignore it if it does
        return;
    }
    // SAFETY: the context is the devices of the GameInputData, which
    // outlive the callback's registration.
    let devices = unsafe { &*context.cast::<Mutex<Devices>>() };

    if (current_status & DEVICE_CONNECTED) != 0 {
        // SAFETY: GameInput passes a live device.
        if let Ok(device) = unsafe { Device::from_borrowed(device) } {
            internal_add_or_find(devices, device);
        }
        // (a failure sets the error "IGameInputDevice_GetDeviceInfo"
        // upstream, which nobody reads)
    } else {
        // Note (upstream): upstream looks through the devices without
        // taking the lock here.
        let mut data = lock_devices(devices);
        if let Some(d) = data.devices.iter_mut().find(|d| d.device.is(device)) {
            // will be deleted on the next Detect call
            d.delete_requested = true;
        }
    }
}

/// The offset of SDL's microsecond clock from GameInput's.
fn timestamp_offset(now_ns: u64, game_input_us: u64) -> u64 {
    (now_ns / 1000).wrapping_sub(game_input_us)
}

/// Translation of `WIN_InitGameInput()`: on failure the driver has no
/// GameInput context, and uses raw input.
pub(crate) fn init_game_input(data: &VideoData) -> Result<()> {
    let mut context = data.gameinput.lock().unwrap_or_else(|e| e.into_inner());
    if context.is_some() {
        return Ok(());
    }

    let game_input = init_shared_game_input()?;
    let devices = Arc::new(Mutex::new(Devices {
        devices: Vec::new(),
        enabled_input: kind::UNKNOWN,
    }));

    // SAFETY: the context is the devices, which the GameInputData keeps
    // until the callback is unregistered (in quit_game_input()).
    let token = unsafe {
        game_input.register_device_callback(
            kind::MOUSE | kind::KEYBOARD,
            DEVICE_CONNECTED,
            BLOCKING_ENUMERATION,
            Arc::as_ptr(&devices).cast_mut().cast(),
            internal_device_callback,
        )
    }
    .map_err(|hr| error_from_hresult(Some("IGameInput::RegisterDeviceCallback"), hr))?;
    // (on failure, WIN_QuitGameInput(): the devices and our reference to
    // GameInput are dropped)

    // Calculate the relative offset between SDL timestamps and GameInput timestamps
    let now = crate::timer::ticks_ns();
    let timestamp_us = game_input.current_timestamp();

    *context = Some(Arc::new(GameInputData {
        game_input,
        gameinput_callback_token: token,
        devices,
        timestamp_offset: timestamp_offset(now, timestamp_us),
    }));
    Ok(())
}

/// SDL's timestamp of a reading.
fn reading_timestamp(data: &GameInputData, reading: &Reading) -> u64 {
    reading
        .timestamp()
        .wrapping_add(data.timestamp_offset)
        .wrapping_mul(1000)
}

/// The events of a device's first mouse reading: every button's state.
/// Translation of `GAMEINPUT_InitialMouseReading()`.
pub(super) fn initial_mouse_inputs(state: &MouseState) -> Vec<MouseInput> {
    let mut inputs: Vec<MouseInput> = GAMEINPUT_BUTTON_MAP
        .iter()
        .enumerate()
        .map(|(i, &button)| {
            let mask = 1u32 << i;
            MouseInput::Button(button, (state.buttons & mask) != 0)
        })
        .collect();

    // Invalidate mouse button flags
    inputs.push(MouseInput::InvalidateButtonFlags);
    inputs
}

/// The events of the difference of two mouse readings. Translation of
/// `GAMEINPUT_HandleMouseDelta()`.
pub(super) fn mouse_delta_inputs(last: &MouseState, state: &MouseState) -> Vec<MouseInput> {
    let mut inputs = Vec::new();
    let delta_buttons = state.buttons ^ last.buttons;
    let delta_x = state.position_x.wrapping_sub(last.position_x);
    let delta_y = state.position_y.wrapping_sub(last.position_y);
    let delta_wheel_x = state.wheel_x.wrapping_sub(last.wheel_x);
    let delta_wheel_y = state.wheel_y.wrapping_sub(last.wheel_y);

    if delta_x != 0 || delta_y != 0 {
        inputs.push(MouseInput::Motion(delta_x as f32, delta_y as f32));
    }
    if delta_buttons != 0 {
        for (i, &button) in GAMEINPUT_BUTTON_MAP.iter().enumerate() {
            let mask = 1u32 << i;
            if (delta_buttons & mask) != 0 {
                let down = (state.buttons & mask) != 0;
                inputs.push(MouseInput::Button(button, down));
            }
        }

        // Invalidate mouse button flags
        inputs.push(MouseInput::InvalidateButtonFlags);
    }
    if delta_wheel_x != 0 || delta_wheel_y != 0 {
        let f_amount_x = delta_wheel_x as f32 / WHEEL_DELTA as f32;
        let f_amount_y = delta_wheel_y as f32 / WHEEL_DELTA as f32;
        inputs.push(MouseInput::Wheel(f_amount_x, f_amount_y));
    }
    inputs
}

/// Translation of `GetScancodeFromKeyState()`.
pub(super) fn scancode_from_key_state(state: &KeyState) -> Scancode {
    let mut index = (state.scan_code & 0xFF) as u8;
    if (state.scan_code & 0xFF00) == 0xE000 {
        index |= 0x80;
    }
    WINDOWS_SCANCODE_TABLE[index as usize]
}

/// Translation of `KeysHaveScancode()`.
fn keys_have_scancode(keys: &[KeyState], scancode: Scancode) -> bool {
    keys.iter().any(|k| scancode_from_key_state(k) == scancode)
}

/// The key events of a device's first keyboard reading, given SDL's
/// keyboard state: releases of the keys no longer down, then presses of
/// the ones down; `None` when no key is down (the keyboard is reset).
/// Translation of `GAMEINPUT_InitialKeyboardReading()`.
pub(super) fn initial_keyboard_inputs(
    keys: &[KeyState],
    keyboard_state: &[bool],
) -> Option<Vec<KeyInput>> {
    if keys.is_empty() {
        // FIXME: We probably need to track key state by keyboardID
        return None;
    }

    let mut inputs = Vec::new();
    // Go through and send key up events for any key that's not held down
    for (i, &pressed) in keyboard_state.iter().enumerate() {
        let scancode = Scancode(i as u16);
        if pressed && !keys_have_scancode(keys, scancode) {
            // Note (upstream): upstream passes keys[i].scanCode, indexing
            // the reading's keys with the scancode (past the keys read, or
            // the array); here that's the raw code where it is a key read,
            // else 0.
            let rawcode = keys.get(i).map_or(0, |k| k.scan_code as i32);
            inputs.push(KeyInput {
                rawcode,
                scancode,
                down: false,
            });
        }
    }

    // Go through and send key down events for any key that's held down
    inputs.extend(keys.iter().map(|k| KeyInput {
        rawcode: k.scan_code as i32,
        scancode: scancode_from_key_state(k),
        down: true,
    }));
    Some(inputs)
}

/// The key events of the difference of two keyboard readings (each in
/// GameInput's order). Translation of `GAMEINPUT_HandleKeyboardDelta()`.
pub(super) fn keyboard_delta_inputs(last: &[KeyState], keys: &[KeyState]) -> Vec<KeyInput> {
    let key = |k: &KeyState, down| KeyInput {
        rawcode: k.scan_code as i32,
        scancode: scancode_from_key_state(k),
        down,
    };
    let mut inputs = Vec::new();
    let (mut index_last, mut index_keys) = (0, 0);
    while index_last < last.len() || index_keys < keys.len() {
        if index_last < last.len() && index_keys < keys.len() {
            if last[index_last].scan_code == keys[index_keys].scan_code {
                // No change
                index_last += 1;
                index_keys += 1;
            } else {
                // This key was released
                inputs.push(key(&last[index_last], false));
                index_last += 1;
            }
        } else if index_last < last.len() {
            // This key was released
            inputs.push(key(&last[index_last], false));
            index_last += 1;
        } else {
            // This key was pressed
            inputs.push(key(&keys[index_keys], true));
            index_keys += 1;
        }
    }
    inputs
}

/// Queue a reading's mouse events.
fn push_mouse(
    actions: &mut Vec<Action>,
    timestamp: u64,
    window: WindowID,
    mouse_id: u32,
    inputs: Vec<MouseInput>,
) {
    actions.extend(inputs.into_iter().map(|input| Action::Mouse {
        timestamp,
        window,
        mouse_id,
        input,
    }));
}

/// Queue a reading's key events.
fn push_keys(actions: &mut Vec<Action>, timestamp: u64, keyboard_id: u32, keys: Vec<KeyInput>) {
    actions.extend(keys.into_iter().map(|key| Action::Key {
        timestamp,
        keyboard_id,
        key,
    }));
}

/// The mouse state of two readings.
fn mouse_states(last: &Reading, reading: &Reading) -> Option<(MouseState, MouseState)> {
    Some((last.mouse_state()?, reading.mouse_state()?))
}

/// Read the device's mouse readings since the last one.
fn update_mouse(
    data: &GameInputData,
    window: WindowID,
    device: &mut GameInputDevice,
    actions: &mut Vec<Action>,
) {
    let game_input = &data.game_input;
    let mouse_id = device.instance_id;
    let handle_delta = |last: &Reading, reading: &Reading, actions: &mut Vec<Action>| {
        if let Some((last, state)) = mouse_states(last, reading) {
            let timestamp = reading_timestamp(data, reading);
            push_mouse(
                actions,
                timestamp,
                window,
                mouse_id,
                mouse_delta_inputs(&last, &state),
            );
        }
    };

    if let Some(mut last) = device.last_mouse_reading.take() {
        let hr = loop {
            match game_input.next_reading(&last, kind::MOUSE, Some(&device.device)) {
                Ok(reading) => {
                    handle_delta(&last, &reading, actions);
                    last = reading;
                }
                Err(hr) => break hr,
            }
        };
        if hr != GAMEINPUT_E_READING_NOT_FOUND {
            if let Ok(reading) = game_input.current_reading(kind::MOUSE, Some(&device.device)) {
                handle_delta(&last, &reading, actions);
                last = reading;
            }
        }
        device.last_mouse_reading = Some(last);
    } else if let Ok(reading) = game_input.current_reading(kind::MOUSE, Some(&device.device)) {
        if let Some(state) = reading.mouse_state() {
            let timestamp = reading_timestamp(data, &reading);
            push_mouse(
                actions,
                timestamp,
                window,
                mouse_id,
                initial_mouse_inputs(&state),
            );
        }
        device.last_mouse_reading = Some(reading);
    }
}

/// Read the device's keyboard readings since the last one.
fn update_keyboard(data: &GameInputData, device: &mut GameInputDevice, actions: &mut Vec<Action>) {
    let game_input = &data.game_input;
    let keyboard_id = device.instance_id;
    let max_keys = device
        .device
        .info()
        .keyboard_info()
        .map_or(0, |k| k.max_simultaneous_keys) as usize;
    let handle_delta = |last: &Reading, reading: &Reading, actions: &mut Vec<Action>| {
        let timestamp = reading_timestamp(data, reading);
        let last_keys = last.key_state(max_keys);
        let keys = reading.key_state(max_keys);
        push_keys(
            actions,
            timestamp,
            keyboard_id,
            keyboard_delta_inputs(&last_keys, &keys),
        );
    };

    if let Some(mut last) = device.last_keyboard_reading.take() {
        let hr = loop {
            match game_input.next_reading(&last, kind::KEYBOARD, Some(&device.device)) {
                Ok(reading) => {
                    handle_delta(&last, &reading, actions);
                    last = reading;
                }
                Err(hr) => break hr,
            }
        };
        if hr != GAMEINPUT_E_READING_NOT_FOUND {
            if let Ok(reading) = game_input.current_reading(kind::KEYBOARD, Some(&device.device)) {
                handle_delta(&last, &reading, actions);
                last = reading;
            }
        }
        device.last_keyboard_reading = Some(last);
    } else if let Ok(reading) = game_input.current_reading(kind::KEYBOARD, Some(&device.device)) {
        let timestamp = reading_timestamp(data, &reading);
        let keys = reading.key_state(max_keys);
        match initial_keyboard_inputs(&keys, &sdl_keyboard::keyboard_state()) {
            Some(inputs) => push_keys(actions, timestamp, keyboard_id, inputs),
            None => actions.push(Action::ResetKeyboard),
        }
        device.last_keyboard_reading = Some(reading);
    }
}

/// The GameInput context of the driver, if it has one.
fn context(data: &VideoData) -> Option<Arc<GameInputData>> {
    data.gameinput
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .clone()
}

/// Whether the driver reads the keyboard and mouse through GameInput
/// (`_this->internal->gameinput_context != NULL`).
pub(crate) fn has_game_input(data: &VideoData) -> bool {
    data.gameinput
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .is_some()
}

/// Send the queued events.
fn dispatch(actions: Vec<Action>) {
    for action in actions {
        match action {
            Action::AddMouse(id) => mouse::add_mouse(id, None),
            Action::AddKeyboard(id) => sdl_keyboard::add_keyboard(id, None),
            Action::RemoveMouse(id) => mouse::remove_mouse(id),
            Action::RemoveKeyboard(id) => sdl_keyboard::remove_keyboard(id),
            Action::ResetKeyboard => sdl_keyboard::reset_keyboard(),
            Action::Key {
                timestamp,
                keyboard_id,
                key,
            } => {
                sdl_keyboard::send_keyboard_key(
                    Duration::from_nanos(timestamp),
                    keyboard_id,
                    key.rawcode,
                    key.scancode,
                    key.down,
                );
            }
            Action::Mouse {
                timestamp,
                window,
                mouse_id,
                input,
            } => {
                let timestamp = Duration::from_nanos(timestamp);
                match input {
                    MouseInput::Motion(x, y) => {
                        mouse::send_mouse_motion(timestamp, Some(window), mouse_id, true, x, y)
                    }
                    MouseInput::Button(button, down) => {
                        mouse::send_mouse_button(timestamp, Some(window), mouse_id, button, down)
                    }
                    MouseInput::InvalidateButtonFlags => {
                        if let Some(windowdata) = window_data(window) {
                            windowdata.state.with(|s| s.mouse_button_flags = usize::MAX);
                        }
                    }
                    MouseInput::Wheel(x, y) => mouse::send_mouse_wheel(
                        timestamp,
                        mouse::mouse_focus(),
                        mouse_id,
                        x,
                        y,
                        MouseWheelDirection::Normal,
                    ),
                }
            }
        }
    }
}

/// Read the keyboards and mice. Translation of `WIN_UpdateGameInput()`.
pub(crate) fn update_game_input(data: &VideoData) {
    let Some(ctx) = context(data) else {
        return;
    };

    let mut actions = Vec::new();
    {
        let mut devices = ctx.lock();
        let enabled_input = devices.enabled_input;

        // Key events and relative mouse motion both go to the window with keyboard focus
        let window = sdl_keyboard::keyboard_focus();

        let mut i = 0;
        while i < devices.devices.len() {
            let device = &mut devices.devices[i];
            let supported_input = device.device.info().supported_input;

            if !device.registered {
                if (supported_input & kind::MOUSE) != 0 {
                    actions.push(Action::AddMouse(device.instance_id));
                }
                if (supported_input & kind::KEYBOARD) != 0 {
                    actions.push(Action::AddKeyboard(device.instance_id));
                }
                device.registered = true;
            }

            if device.delete_requested {
                internal_remove_by_index(&mut devices, i, &mut actions);
                continue;
            }
            i += 1;

            if (supported_input & enabled_input) == 0 {
                continue;
            }

            let Some(window) = window else {
                continue;
            };

            if (enabled_input & kind::MOUSE) != 0 {
                update_mouse(&ctx, window, device, &mut actions);
            }

            if (enabled_input & kind::KEYBOARD) != 0 {
                if sdl_keyboard::text_input_active(window) {
                    // Reset raw input while text input is active
                    device.last_keyboard_reading = None;
                } else {
                    update_keyboard(&ctx, device, &mut actions);
                }
            }
        }
    }

    dispatch(actions);
}

/// Follow the raw keyboard and mouse settings. Translation of
/// `WIN_UpdateGameInputEnabled()`.
pub(crate) fn update_game_input_enabled(data: &VideoData) -> Result<()> {
    let Some(ctx) = context(data) else {
        return Ok(());
    };
    let (raw_mouse_enabled, raw_keyboard_enabled) = data
        .state
        .with(|s| (s.raw_mouse_enabled, s.raw_keyboard_enabled));

    let mut devices = ctx.lock();
    devices.enabled_input = (if raw_mouse_enabled {
        kind::MOUSE
    } else {
        kind::UNKNOWN
    }) | (if raw_keyboard_enabled {
        kind::KEYBOARD
    } else {
        kind::UNKNOWN
    });

    // Reset input if not enabled
    for device in &mut devices.devices {
        if !raw_mouse_enabled {
            device.last_mouse_reading = None;
        }
        if !raw_keyboard_enabled {
            device.last_keyboard_reading = None;
        }
    }

    Ok(())
}

/// Translation of `WIN_QuitGameInput()`.
pub(crate) fn quit_game_input(data: &VideoData) {
    let Some(ctx) = data
        .gameinput
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .take()
    else {
        return;
    };

    // free the callback
    if ctx.gameinput_callback_token != 0 {
        ctx.game_input
            .unregister_callback(ctx.gameinput_callback_token);
    }

    // free the list
    let mut actions = Vec::new();
    {
        let mut devices = ctx.lock();
        while !devices.devices.is_empty() {
            internal_remove_by_index(&mut devices, 0, &mut actions);
        }
    }
    dispatch(actions);

    // (our reference to GameInput goes with the context: SDL_QuitGameInput())
    drop(ctx);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(scan_code: u32) -> KeyState {
        KeyState {
            scan_code,
            ..KeyState::default()
        }
    }

    #[test]
    fn scancodes_of_key_states() {
        assert_eq!(scancode_from_key_state(&key(0x1E)), Scancode::A);
        // Extended keys (E0 prefix) are in the upper half of the table
        assert_eq!(scancode_from_key_state(&key(0xE04D)), Scancode::RIGHT);
        assert_eq!(scancode_from_key_state(&key(0x4D)), Scancode::KP_6);
        assert_eq!(scancode_from_key_state(&key(0xE01D)), Scancode::RCTRL);
    }

    #[test]
    fn keyboard_deltas() {
        let a = key(0x1E);
        let s = key(0x1F);
        let d = key(0x20);
        let k = |sc, down| KeyInput {
            rawcode: sc as i32,
            scancode: scancode_from_key_state(&key(sc)),
            down,
        };
        assert!(keyboard_delta_inputs(&[a, s], &[a, s]).is_empty());
        assert_eq!(keyboard_delta_inputs(&[a], &[a, s]), [k(0x1F, true)]);
        assert_eq!(keyboard_delta_inputs(&[a, s], &[s]), [k(0x1E, false)]);
        // (upstream's merge: a mismatch releases the old key and keeps going)
        assert_eq!(
            keyboard_delta_inputs(&[a, s], &[d]),
            [k(0x1E, false), k(0x1F, false), k(0x20, true)]
        );
        assert_eq!(keyboard_delta_inputs(&[], &[d]), [k(0x20, true)]);
    }

    #[test]
    fn initial_keyboard_readings() {
        let mut state = [false; Scancode::COUNT];
        assert_eq!(initial_keyboard_inputs(&[], &state), None);

        state[Scancode::B.0 as usize] = true;
        state[Scancode::A.0 as usize] = true;
        let inputs = initial_keyboard_inputs(&[key(0x1E)], &state).unwrap();
        assert_eq!(
            inputs,
            [
                // B (scancode 5) isn't down any more; its raw code is past
                // the one key read
                KeyInput {
                    rawcode: 0,
                    scancode: Scancode::B,
                    down: false
                },
                KeyInput {
                    rawcode: 0x1E,
                    scancode: Scancode::A,
                    down: true
                },
            ]
        );
    }

    #[test]
    fn mouse_readings() {
        let state = MouseState {
            buttons: 0x01 | 0x10 | 0x40,
            ..MouseState::default()
        };
        use MouseInput::*;
        assert_eq!(
            initial_mouse_inputs(&state),
            [
                Button(BUTTON_LEFT, true),
                Button(BUTTON_RIGHT, false),
                Button(BUTTON_MIDDLE, false),
                Button(BUTTON_X1, false),
                Button(BUTTON_X2, true),
                Button(6, false),
                Button(7, true),
                InvalidateButtonFlags,
            ]
        );

        let last = MouseState {
            buttons: 0x01,
            position_x: 10,
            position_y: 10,
            wheel_y: 120,
            ..MouseState::default()
        };
        let now = MouseState {
            buttons: 0x02,
            position_x: 13,
            position_y: 8,
            wheel_x: -60,
            wheel_y: 360,
            ..MouseState::default()
        };
        assert_eq!(
            mouse_delta_inputs(&last, &now),
            [
                Motion(3.0, -2.0),
                Button(BUTTON_LEFT, false),
                Button(BUTTON_RIGHT, true),
                InvalidateButtonFlags,
                Wheel(-0.5, 2.0),
            ]
        );
        assert!(mouse_delta_inputs(&now, &now).is_empty());
    }

    #[test]
    fn button_bits_match_the_header() {
        use crate::core::windows::gameinput::mouse_buttons;
        let bits = [
            mouse_buttons::LEFT_BUTTON,
            mouse_buttons::RIGHT_BUTTON,
            mouse_buttons::MIDDLE_BUTTON,
            mouse_buttons::BUTTON4,
            mouse_buttons::BUTTON5,
            mouse_buttons::WHEEL_TILT_LEFT,
            mouse_buttons::WHEEL_TILT_RIGHT,
        ];
        for (i, bit) in bits.into_iter().enumerate() {
            assert_eq!(bit, 1 << i);
        }
        assert_eq!(bits.len(), MAX_GAMEINPUT_BUTTONS);
    }

    #[test]
    fn timestamps() {
        assert_eq!(timestamp_offset(2_000_000, 500), 1_500);
    }
}
