#!/usr/bin/env python3
"""Generate sdl3/src/render/debug_font.rs from SDL's
src/render/SDL_render_debug_font.h.

Usage: gen_debug_font.py <SDL source dir> > sdl3/src/render/debug_font.rs

The glyphs are 8x8 bitmaps, one byte per row with the leftmost pixel in
the lowest bit, for code points 33-126 and 161-255 plus a final
"missing character" glyph.
"""
import re
import sys

src_dir = sys.argv[1]
text = open(f"{src_dir}/src/render/SDL_render_debug_font.h", encoding="utf-8", errors="replace").read()
body = text[text.index("SDL_RenderDebugTextFontData[] = {"):text.index("SDL_COMPILE_TIME_ASSERT")]
num_glyphs = int(re.search(r"#define SDL_DEBUG_FONT_NUM_GLYPHS (\d+)", text).group(1))

glyphs = []
current = None
for line in body.splitlines():
    m = re.match(r"\s*\* (\d+) 0x[0-9a-f]+", line)
    if m:
        current = (int(m.group(1)), [])
        glyphs.append(current)
        continue
    m = re.match(r"\s*(0x[0-9a-fA-F]{2}),", line)
    if m:
        current[1].append(m.group(1).lower())

glyphs = [g for g in glyphs if g[1]]
assert len(glyphs) == num_glyphs, len(glyphs)
assert all(len(rows) == 8 for _, rows in glyphs)

out = []
out.append("// Rust translation of src/render/SDL_render_debug_font.h from Simple DirectMedia Layer.")
out.append("// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>")
out.append("// This is an altered (translated) version of the original software; see LICENSE.txt.")
out.append("// Generated by tools/gen_debug_font.py; do not edit.")
out.append("")
out.append("//! The 8x8 bitmap font of `SDL_RenderDebugText()`.")
out.append("")
out.append("/// The number of glyphs. Translation of `SDL_DEBUG_FONT_NUM_GLYPHS`.")
out.append(f"pub(crate) const DEBUG_FONT_NUM_GLYPHS: usize = {num_glyphs};")
out.append("")
out.append("/// The glyph rows, eight bytes per glyph. Translation of `SDL_RenderDebugTextFontData`.")
out.append("#[rustfmt::skip]")
out.append(f"pub(crate) static DEBUG_TEXT_FONT_DATA: [u8; {num_glyphs * 8}] = [")
for code, rows in glyphs:
    label = "missing character" if code == 256 else f"U+{code:04X}"
    out.append(f"    {', '.join(rows)}, // {label}")
out.append("];")
print("\n".join(out))
