#!/usr/bin/env python3
"""Generate the joystick data tables from SDL's sources:

  sdl3/src/joystick/usb_ids.rs     from src/joystick/usb_ids.h
  sdl3/src/joystick/tables.rs      from src/joystick/controller_list.h and
                                   the initial_* VID/PID lists of
                                   src/joystick/SDL_joystick.c

Usage: gen_joystick_tables.py <SDL source dir> <output dir>
"""
import re
import sys

src_dir, out_dir = sys.argv[1], sys.argv[2]
joy = f"{src_dir}/src/joystick"

HEADER = """// Rust translation of {what} from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.
// Generated by tools/gen_joystick_tables.py; do not edit.
"""


def rust_comment(text):
    return text.strip().replace("*/", "").strip()


# usb_ids.h
lines = []
defined = {}
for line in open(f"{joy}/usb_ids.h", encoding="utf-8"):
    m = re.match(r"#define ((?:USB|BLUETOOTH)_\w+)\s+(0[xX][0-9a-fA-F]+|\d+)\s*(?://\s*(.*))?$", line.rstrip())
    if m:
        name, value, comment = m.groups()
        if name in defined:
            # (C allows an identical redefinition)
            if int(defined[name], 0) != int(value, 0):
                raise SystemExit(f"conflicting definitions of {name}")
            continue
        defined[name] = value
        if comment:
            lines.append(f"/// {rust_comment(comment)}")
        lines.append(f"pub(crate) const {name}: u16 = {value.lower()};")
        continue
    m = re.match(r"\s*//\s*(.*)$", line)
    if m and lines is not None and not line.startswith("// Definitions"):
        lines.append("")
        lines.append(f"// {m.group(1)}")

with open(f"{out_dir}/usb_ids.rs", "w") as out:
    out.write(HEADER.format(what="src/joystick/usb_ids.h"))
    out.write("\n//! Useful USB (and Bluetooth) vendor, product and usage values.\n\n")
    out.write("#![allow(dead_code)] // (used by the HIDAPI drivers)\n\n")
    text = "\n".join(lines).strip() + "\n"
    out.write(re.sub(r"\n{3,}", "\n\n", text))

# controller_list.h
controllers = []
for line in open(f"{joy}/controller_list.h", encoding="utf-8"):
    if re.match(r"\s*//", line):
        continue
    m = re.match(r"\s*\{\s*MAKE_CONTROLLER_ID\s*\(\s*(0[xX][0-9a-fA-F]+),\s*(0[xX][0-9a-fA-F]+)\s*\),\s*k_eControllerType_(\w+),\s*(NULL|\"[^\"]*\")\s*\},?\s*(?://\s*(.*))?$", line.rstrip())
    if m:
        vid, pid, ctype, name, comment = m.groups()
        if ctype[0].isdigit():
            ctype = {"8BitDoController": "EightBitDoController"}[ctype]
        controllers.append((int(vid, 16), int(pid, 16), ctype, None if name == "NULL" else name, comment))
    elif "MAKE_CONTROLLER_ID" in line and "#define" not in line:
        raise SystemExit(f"unparsed controller line: {line!r}")

# The VID/PID lists of SDL_joystick.c
text = open(f"{joy}/SDL_joystick.c", encoding="utf-8").read()
lists = []
for m in re.finditer(r"static Uint32 (initial_\w+)\[\] = \{(.*?)\n\};", text, re.S):
    name, body = m.groups()
    entries = []
    for e in re.finditer(r"MAKE_VIDPID\(\s*(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+)\s*\)", body):
        entries.append((int(e.group(1), 16), int(e.group(2), 16)))
    lists.append((name, entries))

with open(f"{out_dir}/tables.rs", "w") as out:
    out.write(HEADER.format(what="src/joystick/controller_list.h and the VID/PID lists of src/joystick/SDL_joystick.c"))
    out.write("\n//! The known controllers and the built in VID/PID lists.\n\n")
    out.write("use super::controller_type::{ControllerDescription, ControllerType};\n\n")
    out.write("/// `MAKE_CONTROLLER_ID()` / `MAKE_VIDPID()`.\n")
    out.write("pub(crate) const fn make_vidpid(vid: u16, pid: u16) -> u32 {\n    ((vid as u32) << 16) | pid as u32\n}\n\n")
    out.write("/// Translation of `arrControllers`.\n")
    out.write("#[rustfmt::skip]\n")
    out.write("pub(crate) static CONTROLLERS: &[ControllerDescription] = &[\n")
    for vid, pid, ctype, name, comment in controllers:
        nm = f"Some({name})" if name else "None"
        c = f" // {comment.strip()}" if comment else ""
        out.write(f"    ControllerDescription {{ device_id: make_vidpid(0x{vid:04x}, 0x{pid:04x}), controller_type: ControllerType::{ctype}, name: {nm} }},{c}\n")
    out.write("];\n")
    for name, entries in lists:
        out.write(f"\n/// Translation of `{name}`.\n")
        out.write("#[rustfmt::skip]\n")
        out.write(f"pub(crate) static {name.upper()}: &[u32] = &[\n")
        for vid, pid in entries:
            out.write(f"    make_vidpid(0x{vid:04x}, 0x{pid:04x}),\n")
        out.write("];\n")
print(f"{len(controllers)} controllers, {len(lists)} lists", file=sys.stderr)
