#!/usr/bin/env python3
"""Generate sdl3/src/render/direct3d12/shaders.rs from SDL's
src/render/direct3d12/SDL_shaders_d3d12.c, SDL_shaders_d3d12.h and the
precompiled shader headers they include (D3D12_*.h, made by
compile_shaders.bat with dxc: DXIL, shader model 6.0, and the serialized
root signatures, version 1.1).

Usage: gen_d3d12_render_shaders.py <SDL source dir> > sdl3/src/render/direct3d12/shaders.rs

The bytecode is kept as byte arrays, as upstream has it, sixteen to a
line; the shader and root signature tables and their accessors
(D3D12_GetVertexShader() and the others) are translated around them. The
Xbox headers (*_One.h, *_Series.h, from compile_shaders_xbox.bat) are not
translated, as upstream leaves them out on Windows.
"""
import re
import sys

src_dir = sys.argv[1]
d3d_dir = f"{src_dir}/src/render/direct3d12"


def read(name):
    return open(f"{d3d_dir}/{name}", encoding="utf-8").read()


def enum_values(text, name):
    body = re.search(r"typedef enum\s*\{([^}]*)\}\s*" + name + ";", text, re.S).group(1)
    values = [s.strip() for s in body.split(",") if s.strip()]
    assert values[-1].startswith("NUM_"), values
    return values[:-1]


header = read("SDL_shaders_d3d12.h")
shaders = enum_values(header, "D3D12_Shader")
rootsigs = enum_values(header, "D3D12_RootSignature")

source = read("SDL_shaders_d3d12.c")
# `#define <name> <C name>` then `#include "<header>"`, for each blob.
includes = re.findall(r'#define (g_\w+) (D3D12_\w+)\s*#include "(D3D12_\w+\.h)"', source)
assert len(includes) == 12, includes

# D3D12_shaders[]: (pixel shader, vertex shader, root signature) per shader.
table = re.search(r"\} D3D12_shaders\[\] = \{(.*?)\};", source, re.S).group(1)
entries = re.findall(
    r"\{\s*(\w+), sizeof\(\1\),\s*(\w+), sizeof\(\2\),\s*(ROOTSIG_\w+)\s*\}", table
)
assert len(entries) == len(shaders), (entries, shaders)
assert all(r in rootsigs for _, _, r in entries), entries

# D3D12_rootsigs[]: the root signature blob of each D3D12_RootSignature.
rs_table = re.search(r"\} D3D12_rootsigs\[\] = \{(.*?)\};", source, re.S).group(1)
rs_entries = re.findall(r"\{\s*(\w+), sizeof\(\1\)\s*\}", rs_table)
assert len(rs_entries) == len(rootsigs), (rs_entries, rootsigs)

# The bytecode of each header.
blobs = {}
compilers = set()
for macro, name, include in includes:
    text = read(include)
    body = re.search(r"const unsigned char " + macro + r"\[\] =\s*\{(.*?)\};", text, re.S).group(1)
    data = bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", body))
    # A DXBC container: the magic, a digest, version 1.0, the total size,
    # then the offsets of its parts.
    assert data[:4] == b"DXBC", f"{include}: not a DXBC container"
    assert data[20:24] == b"\x01\x00\x00\x00", f"{include}: version"
    assert int.from_bytes(data[24:28], "little") == len(data), f"{include}: size"
    parts = int.from_bytes(data[28:32], "little")
    offsets = [int.from_bytes(data[32 + 4 * i:36 + 4 * i], "little") for i in range(parts)]
    fourccs = [data[o:o + 4] for o in offsets]
    if "RootSig" in include:
        # A serialized root signature (an RTS0 part, version 1.1).
        assert fourccs == [b"RTS0"], f"{include}: {fourccs}"
        assert int.from_bytes(data[offsets[0] + 8:offsets[0] + 12], "little") == 2, include
    else:
        # DXIL, signed (a nonzero digest), as Direct3D 12 needs.
        assert b"DXIL" in fourccs, f"{include}: no DXIL part ({fourccs})"
        assert any(data[4:20]), f"{include}: unsigned"
        compilers.update(re.findall(r'!\{!"(dxcoob [^"]*)"\}', text))
    blobs[name] = (include, data)
assert len(compilers) == 1, compilers
used = {p for p, _, _ in entries} | {v for _, v, _ in entries} | set(rs_entries)
assert used == set(blobs), (used, set(blobs))


def rust_const(c_name):
    """D3D12_PixelShader_Colors_PQ -> D3D12_PIXEL_SHADER_COLORS_PQ"""
    s = re.sub(r"(?<=[a-z])(?=[A-Z])", "_", c_name)
    return s.upper()


def rust_variant(c_name):
    """SHADER_RGB_SIMPLE -> RgbSimple"""
    return "".join(p.capitalize() for p in c_name.split("_")[1:])


out = []
out.append("// Rust translation of src/render/direct3d12/SDL_shaders_d3d12.c, SDL_shaders_d3d12.h")
out.append("// and the shader headers they include, from Simple DirectMedia Layer.")
out.append("// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>")
out.append("// This is an altered (translated) version of the original software; see LICENSE.txt.")
out.append("// Generated by tools/gen_d3d12_render_shaders.py; do not edit.")
out.append("")
out.append("//! The shaders of the Direct3D 12 renderer: DXIL (shader model 6.0)")
out.append("//! compiled from the HLSL sources upstream (`compile_shaders.bat`, with")
out.append(f"//! {compilers.pop()}), a pixel and a vertex shader per [`Shader`],")
out.append("//! and the root signatures (version 1.1) the vertex shaders declare, one")
out.append("//! per [`RootSignature`].")
out.append("")
out.append("/// The shaders. Translation of `D3D12_Shader`.")
out.append("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
out.append("pub(super) enum Shader {")
for s in shaders:
    out.append(f"    {rust_variant(s)},")
out.append("}")
out.append("")
out.append("impl Shader {")
out.append("    /// The number of shaders (`NUM_SHADERS`).")
out.append(f"    pub(super) const COUNT: usize = {len(shaders)};")
out.append("")
out.append("    /// All the shaders, in order.")
out.append("    pub(super) const ALL: [Shader; Shader::COUNT] = [")
for s in shaders:
    out.append(f"        Shader::{rust_variant(s)},")
out.append("    ];")
out.append("")
out.append("    /// The bytecode of the shader's vertex shader. Translation of")
out.append("    /// `D3D12_GetVertexShader()`.")
out.append("    pub(super) fn vertex_shader(self) -> &'static [u8] {")
out.append("        D3D12_SHADERS[self as usize].vs_shader_data")
out.append("    }")
out.append("")
out.append("    /// The bytecode of the shader's pixel shader. Translation of")
out.append("    /// `D3D12_GetPixelShader()`.")
out.append("    pub(super) fn pixel_shader(self) -> &'static [u8] {")
out.append("        D3D12_SHADERS[self as usize].ps_shader_data")
out.append("    }")
out.append("")
out.append("    /// The root signature the shader's vertex shader declares.")
out.append("    /// Translation of `D3D12_GetRootSignatureType()`.")
out.append("    pub(super) fn root_signature_type(self) -> RootSignature {")
out.append("        D3D12_SHADERS[self as usize].root_sig")
out.append("    }")
out.append("}")
out.append("")
out.append("/// The root signatures. Translation of `D3D12_RootSignature`.")
out.append("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
out.append("pub(super) enum RootSignature {")
for r in rootsigs:
    out.append(f"    {rust_variant(r)},")
out.append("}")
out.append("")
out.append("impl RootSignature {")
out.append("    /// The number of root signatures (`NUM_ROOTSIGS`).")
out.append(f"    pub(super) const COUNT: usize = {len(rootsigs)};")
out.append("")
out.append("    /// All the root signatures, in order.")
out.append("    pub(super) const ALL: [RootSignature; RootSignature::COUNT] = [")
for r in rootsigs:
    out.append(f"        RootSignature::{rust_variant(r)},")
out.append("    ];")
out.append("")
out.append("    /// The serialized root signature. Translation of")
out.append("    /// `D3D12_GetRootSignatureData()`.")
out.append("    pub(super) fn data(self) -> &'static [u8] {")
out.append("        D3D12_ROOTSIGS[self as usize]")
out.append("    }")
out.append("}")
out.append("")
out.append("/// An entry of `D3D12_shaders`.")
out.append("struct ShaderEntry {")
out.append("    ps_shader_data: &'static [u8],")
out.append("    vs_shader_data: &'static [u8],")
out.append("    root_sig: RootSignature,")
out.append("}")
out.append("")
out.append("/// The shaders of each [`Shader`]. Translation of `D3D12_shaders`.")
out.append("static D3D12_SHADERS: [ShaderEntry; Shader::COUNT] = [")
for ps, vs, rs in entries:
    out.append("    ShaderEntry {")
    out.append(f"        ps_shader_data: &{rust_const(ps)},")
    out.append(f"        vs_shader_data: &{rust_const(vs)},")
    out.append(f"        root_sig: RootSignature::{rust_variant(rs)},")
    out.append("    },")
out.append("];")
out.append("")
out.append("/// The serialized root signature of each [`RootSignature`]. Translation")
out.append("/// of `D3D12_rootsigs`.")
out.append("static D3D12_ROOTSIGS: [&[u8]; RootSignature::COUNT] = [")
for rs in rs_entries:
    out.append(f"    &{rust_const(rs)},")
out.append("];")
for _, name, _ in includes:
    include, data = blobs[name]
    out.append("")
    out.append(f"/// `{name}`, from `{include}`.")
    out.append("#[rustfmt::skip]")
    out.append(f"static {rust_const(name)}: [u8; {len(data)}] = [")
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    out.append("];")
print("\n".join(out))
