#!/usr/bin/env python3
"""Generate sdl3/src/gpu/d3d12/shaders.rs from SDL's
src/gpu/d3d12/D3D12_Blit.h: the precompiled blit shaders of the GPU API's
Direct3D 12 backend (made by compile_shaders.bat with fxc, shader model
5.1, from D3D_Blit.hlsl).

Usage: gen_d3d12_shaders.py <SDL source dir> > sdl3/src/gpu/d3d12/shaders.rs

The bytecode is kept as byte arrays, as upstream has it, sixteen to a
line. The Xbox headers (D3D12_Blit_One.h, D3D12_Blit_Series.h) are not
translated.
"""
import re
import sys

src_dir = sys.argv[1]
d3d_dir = f"{src_dir}/src/gpu/d3d12"

text = open(f"{d3d_dir}/D3D12_Blit.h", encoding="utf-8").read()
source = open(f"{d3d_dir}/SDL_gpu_d3d12.c", encoding="utf-8").read()

# The names SDL_gpu_d3d12.c gives the arrays (`#define g_X D3D12_X`), in
# the order of the header.
renames = dict(re.findall(r"#define (g_\w+)\s+(D3D12_\w+)", source))
blobs = re.findall(r"const BYTE (g_\w+)\[\] =\s*\{(.*?)\};", text, re.S)
assert [name for name, _ in blobs] == list(renames), (blobs, renames)
compilers = set(re.findall(r"// Generated by (.*)", text))
assert len(compilers) == 1, compilers
models = set(re.findall(r"^([vp]s_\d_\d)$", text, re.M))
assert models == {"vs_5_1", "ps_5_1"}, models


def rust_const(c_name):
    """D3D12_BlitFrom2DArray -> D3D12_BLIT_FROM_2D_ARRAY"""
    s = re.sub(r"(?<=[a-z])(?=[A-Z0-9])", "_", c_name)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", s)
    return s.upper()


out = []
out.append("// Rust translation of src/gpu/d3d12/D3D12_Blit.h from Simple DirectMedia Layer.")
out.append("// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>")
out.append("// This is an altered (translated) version of the original software; see LICENSE.txt.")
out.append("// Generated by tools/gen_d3d12_shaders.py; do not edit.")
out.append("")
out.append("//! The blit shaders of the Direct3D 12 backend: DXBC bytecode (shader")
out.append("//! model 5.1) compiled from `D3D_Blit.hlsl` upstream (`compile_shaders.bat`,")
out.append(f"//! with the {compilers.pop().strip()}): a fullscreen vertex")
out.append("//! shader and a pixel shader per source texture type.")
for c_name, body in blobs:
    data = bytes(int(b) for b in re.findall(r"\b\d+\b", body))
    assert data[:4] == b"DXBC", f"{c_name}: not DXBC"
    assert int.from_bytes(data[24:28], "little") == len(data), f"{c_name}: size"
    name = renames[c_name]
    out.append("")
    out.append(f"/// `{name}` (`{c_name}`).")
    out.append("#[rustfmt::skip]")
    out.append(f"pub(super) static {rust_const(name)}: [u8; {len(data)}] = [")
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    out.append("];")
print("\n".join(out))
