#!/usr/bin/env python3
"""Generate sdl3-shadercross/src/spirv_cross/spirv.rs from the SPIR-V
headers SPIRV-Cross builds with: its copy of SPIRV-Headers' spirv.hpp
(the C++ token header, identical to SPIRV-Headers'
include/spirv/unified1/spirv.hpp at the revision SDL_shadercross pins),
GLSL.std.450.h and the instruction numbers of
NonSemanticShaderDebugInfo100.h.

Usage: gen_spirv_headers.py <SPIRV-Cross dir> > sdl3-shadercross/src/spirv_cross/spirv.rs

Each C++ enum becomes a `u32` type alias with one constant per token,
keeping the C++ names (`spv::OpLoad` is `OpLoad`), since SPIRV-Cross
converts freely between the enums and raw words. `HasResultAndType()`
becomes `has_result_and_type()`.
"""
import re
import sys

src_dir = sys.argv[1]


def read(name):
    return open(f"{src_dir}/{name}", encoding="utf-8").read()


def parse_value(v, known):
    v = v.strip()
    if v in known:
        return known[v]
    return int(v, 0)


def emit_enums(text, out, known):
    for m in re.finditer(r"^enum (\w+) \{\n(.*?)^\};", text, re.S | re.M):
        name, body = m.group(1), m.group(2)
        out.append(f"pub type {name} = u32;")
        for line in body.split("\n"):
            line = line.split("//")[0].strip().rstrip(",")
            if not line:
                continue
            if "=" in line:
                tok, val = [s.strip() for s in line.split("=")]
                value = parse_value(val, known)
            else:
                # An implicit value (GLSLstd450Count): one past the previous.
                tok, value = line, value + 1
            known[tok] = value
            out.append(f"pub const {tok}: {name} = 0x{value:x};")
        out.append("")


out = []
out.append("""// Rust translation of the SPIR-V token headers SPIRV-Cross builds with:
// spirv.hpp (SPIRV-Headers, include/spirv/unified1/spirv.hpp),
// GLSL.std.450.h and NonSemanticShaderDebugInfo100.h.
// Generated by tools/gen_spirv_headers.py; do not edit.
//
// spirv.hpp:
// Copyright: 2014-2024 The Khronos Group Inc.
// License: MIT
//
// GLSL.std.450.h:
// Copyright 2014-2016,2021 The Khronos Group, Inc.
// SPDX-License-Identifier: MIT
//
// NonSemanticShaderDebugInfo100.h:
// Copyright (c) 2018-2024 The Khronos Group Inc.
//
// MODIFICATIONS TO THIS FILE MAY MEAN IT NO LONGER ACCURATELY REFLECTS
// KHRONOS STANDARDS. THE UNMODIFIED, NORMATIVE VERSIONS OF KHRONOS
// SPECIFICATIONS AND HEADER INFORMATION ARE LOCATED AT
// https://www.khronos.org/registry/
//
// This is an altered (translated) version of the original headers; see
// LICENSE.txt for the Khronos license (MIT) they are used under.

//! The SPIR-V, GLSL.std.450 and NonSemantic.Shader.DebugInfo.100 tokens
//! (`spirv.hpp`, `GLSL.std.450.h`, `NonSemanticShaderDebugInfo100.h`).
""")

known = {}
hpp = read("spirv.hpp")
for m in re.finditer(r"^static const unsigned int (\w+) = (\w+);", hpp, re.M):
    value = int(m.group(2), 0)
    known[m.group(1)] = value
    out.append(f"pub const {m.group(1)}: u32 = 0x{value:x};")
out.append("")
out.append("pub type Id = u32;")
out.append("")
emit_enums(hpp, out, known)

# HasResultAndType()
body = re.search(r"inline void HasResultAndType\(.*?\{\n(.*?)\n\}\n", hpp, re.S).group(1)
cases = re.findall(r"case (\w+): \*hasResult = (true|false); \*hasResultType = (true|false); break;", body)
out.append("/// `HasResultAndType()`: whether `opcode` has a result id and a result type,")
out.append("/// as `(has_result, has_result_type)`.")
out.append("pub fn has_result_and_type(opcode: Op) -> (bool, bool) {")
out.append("    match opcode {")
groups = {}
seen = set()
for tok, r, t in cases:
    # Aliases (OpFooKHR = OpFooEXT) share a value: one arm per value.
    if known[tok] in seen:
        continue
    seen.add(known[tok])
    groups.setdefault((r, t), []).append(tok)
for (r, t), toks in groups.items():
    if (r, t) == ("false", "false"):
        continue
    out.append("        " + "\n        | ".join(toks) + f" => ({r}, {t}),")
out.append("        _ => (false, false),")
out.append("    }")
out.append("}")
out.append("")

glsl = read("GLSL.std.450.h")
for m in re.finditer(r"^static const int (\w+) = (\w+);", glsl, re.M):
    out.append(f"pub const {m.group(1)}: u32 = {int(m.group(2), 0)};")
out.append("")
emit_enums(glsl, out, known)

# NonSemanticShaderDebugInfo100.h: the instruction numbers the parser reads.
dbg = read("NonSemanticShaderDebugInfo100.h")
dbg = re.search(r"^enum NonSemanticShaderDebugInfo100Instructions \{\n.*?^\};", dbg, re.S | re.M).group(0)
emit_enums(dbg, out, known)

sys.stdout.write("\n".join(out).rstrip("\n") + "\n")
