#!/usr/bin/env python3
"""Generate sdl3/src/joystick/gamepad_db.rs from SDL's
src/joystick/SDL_gamepad_db.h.

Usage: gen_gamepad_db.py <SDL source dir> > sdl3/src/joystick/gamepad_db.rs

Each `#ifdef` section of the C table becomes a static, compiled in on the
platforms whose SDL builds define the section's macro (and empty
elsewhere); `SECTIONS` lists them in the order of the C table.
"""
import re
import sys

src_dir = sys.argv[1]
text = open(f"{src_dir}/src/joystick/SDL_gamepad_db.h", encoding="utf-8").read()
body = text[text.index("static const char *s_GamepadMappings[] = {"):]
body = body[:body.index("\n};")]

# The platforms on which SDL's build defines each section's macro.
CFG = {
    "SDL_JOYSTICK_PRIVATE": None,  # (never in a public build)
    "SDL_JOYSTICK_XINPUT": 'target_os = "windows"',
    "SDL_JOYSTICK_WGI": 'target_os = "windows"',
    "SDL_JOYSTICK_DINPUT": 'target_os = "windows"',
    "SDL_PLATFORM_MACOS": 'target_os = "macos"',
    "defined(SDL_JOYSTICK_LINUX) || defined(SDL_PLATFORM_OPENBSD)": 'any(target_os = "linux", target_os = "openbsd")',
    "SDL_PLATFORM_OPENBSD": 'target_os = "openbsd"',
    "SDL_PLATFORM_ANDROID": 'target_os = "android"',
    "SDL_JOYSTICK_MFI": 'any(target_os = "macos", target_os = "ios", target_os = "tvos", target_os = "visionos")',
    "SDL_JOYSTICK_EMSCRIPTEN": 'target_os = "emscripten"',
    "SDL_JOYSTICK_PS2": None,
    "SDL_JOYSTICK_PSP": 'target_os = "psp"',
    "SDL_JOYSTICK_VITA": 'target_os = "vita"',
    "SDL_JOYSTICK_N3DS": 'target_os = "horizon"',
}

sections = []
current = None
for line in body.splitlines()[1:]:
    s = line.strip()
    m = re.match(r"#ifdef (\w+)$", s) or re.match(r"#if (.+)$", s)
    if m:
        cond = m.group(1)
        if cond not in CFG:
            raise SystemExit(f"unknown condition {cond!r}")
        current = (cond, [])
        sections.append(current)
        continue
    if s == "#endif":
        current = None
        continue
    if s in ("NULL", "SDL_PRIVATE_GAMEPAD_DEFINITIONS") or not s:
        continue
    m = re.match(r'"([^"\\]*)",\s*(?:/\*.*\*/|//.*)?$', s)
    if not m:
        raise SystemExit(f"unparsed line: {line!r}")
    if current is None:
        raise SystemExit(f"mapping outside a section: {line!r}")
    current[1].append(m.group(1))

out = sys.stdout
out.write("""// Rust translation of src/joystick/SDL_gamepad_db.h from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.
// Generated by tools/gen_gamepad_db.py; do not edit.

//! The default gamepad mappings (`s_GamepadMappings`).
//!
//! The easiest way to generate a new mapping is to start Steam in Big
//! Picture mode, configure your joystick and then look in config/config.vdf
//! in your Steam installation directory for the "SDL_GamepadBind" entry.
""")
names = []
for i, (cond, entries) in enumerate(sections):
    name = f"SECTION_{i}"
    names.append(name)
    cfg = CFG[cond]
    out.write(f"\n/// `#if {cond}`\n")
    if cfg is None:
        out.write(f"static {name}: &[&str] = &[]; // ({len(entries)} mappings, for a platform Rust doesn't target)\n")
        continue
    out.write(f"#[cfg({cfg})]\n#[rustfmt::skip]\nstatic {name}: &[&str] = &[\n")
    for e in entries:
        out.write(f'    "{e}",\n')
    out.write(f"];\n#[cfg(not({cfg}))]\nstatic {name}: &[&str] = &[];\n")

out.write(f"\n/// The sections of the mapping table, in order.\npub(crate) static SECTIONS: [&[&str]; {len(names)}] = [{', '.join(names)}];\n")
