#!/usr/bin/env python3
"""Regenerate sdl3/src/stdlib/casefolding.rs from upstream SDL's
src/stdlib/SDL_casefolding.h.

usage: tools/gen_casefolding.py path/to/SDL/src/stdlib/SDL_casefolding.h
"""
import re
import sys

HEADER = """// Rust translation of src/stdlib/SDL_casefolding.h from Simple DirectMedia Layer.
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.

//! Unicode case-folding data.
//!
//! Upstream's header (generated by `build-scripts/makecasefoldhashtable.pl`)
//! stores these mappings in small hash tables keyed by
//! `(cp ^ (cp >> 8)) & 0xFF`. The same mappings are reproduced here as
//! tables sorted by code point and searched with a binary search (as the
//! upstream FIXME suggests); every lookup returns exactly what the hash
//! tables return. Regenerate with `tools/gen_casefolding.py` if upstream's
//! data changes.
"""


def main(path):
    s = open(path).read()
    tables = {("1", "16"): [], ("2", "16"): [], ("3", "16"): [], ("1", "32"): []}
    pat = r"static const CaseFoldMapping(\d)_(\d+) case_fold\d_\d+_\d+\[\] = \{(.*?)\};"
    for m in re.finditer(pat, s, re.S):
        for e in re.finditer(r"\{([^}]*)\}", m.group(3)):
            vals = [int(v.strip(), 16) for v in e.group(1).split(",") if v.strip()]
            tables[(m.group(1), m.group(2))].append(tuple(vals))
    out = [HEADER]

    def emit(doc, name, ty, rows, width):
        out.append(f"/// {doc}")
        out.append(f"pub(super) static {name}: [{ty}; {len(rows)}] = [")
        for row in sorted(rows):
            out.append("    (" + ", ".join(f"0x{v:0{width}X}" for v in row) + "),")
        out.append("];\n")

    emit("Code points in the BMP that fold to one code point: `(from, to)`.",
         "CASE_FOLD1_16", "(u16, u16)", tables[("1", "16")], 4)
    emit("Code points that fold to two code points: `(from, to0, to1)`.",
         "CASE_FOLD2_16", "(u16, u16, u16)", tables[("2", "16")], 4)
    emit("Code points that fold to three code points: `(from, to0, to1, to2)`.",
         "CASE_FOLD3_16", "(u16, u16, u16, u16)", tables[("3", "16")], 4)
    emit("Code points above the BMP that fold to one code point: `(from, to)`.",
         "CASE_FOLD1_32", "(u32, u32)", tables[("1", "32")], 5)
    sys.stdout.write("\n".join(out).rstrip() + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
