#!/usr/bin/env python3
"""Generate sdl3/src/render/direct3d11/shaders.rs from SDL's
src/render/direct3d11/SDL_shaders_d3d11.c, SDL_shaders_d3d11.h and the
precompiled shader headers they include (D3D11_*.h, made by
compile_shaders.bat with fxc).

Usage: gen_d3d11_shaders.py <SDL source dir> > sdl3/src/render/direct3d11/shaders.rs

The DXBC bytecode is kept as byte arrays, as upstream has it, sixteen to a
line; the shader table and its accessors are translated around them. The
creation functions of SDL_shaders_d3d11.c call the device, so they are
translated by hand in mod.rs.
"""
import re
import sys

src_dir = sys.argv[1]
d3d_dir = f"{src_dir}/src/render/direct3d11"


def read(name):
    return open(f"{d3d_dir}/{name}", encoding="utf-8").read()


# The D3D11_Shader enum, in order.
header = read("SDL_shaders_d3d11.h")
enum_body = re.search(r"typedef enum\s*\{(.*?)\}\s*D3D11_Shader;", header, re.S).group(1)
shaders = [s.strip() for s in enum_body.split(",") if s.strip()]
assert shaders[0] == "SHADER_NONE", shaders
assert shaders[-1] == "NUM_SHADERS", shaders
shaders = shaders[1:-1]

# The table: one pixel shader per D3D11_Shader (after SHADER_NONE's empty
# entry), and the one vertex shader.
source = read("SDL_shaders_d3d11.c")
includes = re.findall(r'#define g_main (\w+)\s*#include "(D3D11_\w+\.h)"', source)
table = re.search(r"D3D11_shaders\[\] = \{(.*?)\};", source, re.S).group(1)
entries = re.findall(r"\{\s*(\w+), (?:sizeof\(\1\)|0)\s*\}", table)
assert entries[0] == "NULL", entries
pixel_shaders = entries[1:]
assert len(pixel_shaders) == len(shaders), (pixel_shaders, shaders)
vertex_shader = "D3D11_VertexShader"
assert f"ID3D11Device_CreateVertexShader(d3dDevice,\n                                             {vertex_shader}," in source

# The bytecode of each header.
blobs = {}
compilers = set()
for name, include in includes:
    text = read(include)
    compilers.add(re.search(r"// Generated by (.*)", text).group(1).strip())
    body = re.search(r"const BYTE g_main\[\] =\s*\{(.*?)\};", text, re.S).group(1)
    data = bytes(int(b) for b in re.findall(r"\b\d+\b", body))
    assert data[:4] == b"DXBC", f"{include}: not DXBC"
    assert int.from_bytes(data[24:28], "little") == len(data), f"{include}: size"
    blobs[name] = (include, data)
assert len(compilers) == 1, compilers
used = set(pixel_shaders) | {vertex_shader}
assert used <= set(blobs), used - set(blobs)


def rust_const(c_name):
    """D3D11_PixelShader_Colors_PQ -> D3D11_PIXEL_SHADER_COLORS_PQ"""
    s = re.sub(r"(?<=[a-z])(?=[A-Z])", "_", c_name)
    return s.upper()


def rust_variant(c_name):
    """SHADER_RGB_SIMPLE -> RgbSimple"""
    return "".join(p.capitalize() for p in c_name.split("_")[1:])


out = []
out.append("// Rust translation of src/render/direct3d11/SDL_shaders_d3d11.c, SDL_shaders_d3d11.h")
out.append("// and the shader headers they include, from Simple DirectMedia Layer.")
out.append("// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>")
out.append("// This is an altered (translated) version of the original software; see LICENSE.txt.")
out.append("// Generated by tools/gen_d3d11_shaders.py; do not edit.")
out.append("")
out.append("//! The shaders of the Direct3D 11 renderer: DXBC bytecode compiled from")
out.append("//! the HLSL sources upstream (`compile_shaders.bat`, with the")
out.append(f"//! {compilers.pop()}): one vertex shader, and a")
out.append("//! pixel shader per [`Shader`]. The functions that create them on a")
out.append("//! device are in the renderer (`D3D11_CreateVertexShader()`,")
out.append("//! `D3D11_CreatePixelShader()`).")
out.append("")
out.append("/// The pixel shaders. Translation of `D3D11_Shader` (`SHADER_NONE` is")
out.append("/// no shader: `None` where upstream keeps it).")
out.append("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
out.append("pub(super) enum Shader {")
for s in shaders:
    out.append(f"    {rust_variant(s)},")
out.append("}")
out.append("")
out.append("impl Shader {")
out.append("    /// The number of shaders (`NUM_SHADERS` without `SHADER_NONE`).")
out.append(f"    pub(super) const COUNT: usize = {len(shaders)};")
out.append("")
out.append("    /// All the shaders, in order (for the tests).")
out.append("    #[cfg_attr(not(test), allow(dead_code))]")
out.append("    pub(super) const ALL: [Shader; Shader::COUNT] = [")
for s in shaders:
    out.append(f"        Shader::{rust_variant(s)},")
out.append("    ];")
out.append("")
out.append("    /// The bytecode of the pixel shader (`D3D11_shaders[shader]`).")
out.append("    pub(super) fn pixel_shader(self) -> &'static [u8] {")
out.append("        D3D11_SHADERS[self as usize]")
out.append("    }")
out.append("}")
out.append("")
out.append("/// The bytecode of SDL's one and only vertex shader.")
out.append("pub(super) fn vertex_shader() -> &'static [u8] {")
out.append(f"    &{rust_const(vertex_shader)}")
out.append("}")
out.append("")
out.append("/// The pixel shader of each [`Shader`]. Translation of `D3D11_shaders`.")
out.append("static D3D11_SHADERS: [&[u8]; Shader::COUNT] = [")
for ps in pixel_shaders:
    out.append(f"    &{rust_const(ps)},")
out.append("];")
for name, _ in includes:
    include, data = blobs[name]
    out.append("")
    out.append(f"/// `{name}`, from `{include}`.")
    out.append("#[rustfmt::skip]")
    out.append(f"static {rust_const(name)}: [u8; {len(data)}] = [")
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    out.append("];")
print("\n".join(out))
