#!/usr/bin/env python3
"""Generate sdl3/src/render/vulkan/shaders.rs from SDL's
src/render/vulkan/SDL_shaders_vulkan.c, SDL_shaders_vulkan.h and the
precompiled SPIR-V headers they include (VULKAN_*.h, made by
compile_shaders.bat with glslangValidator).

Usage: gen_vulkan_shaders.py <SDL source dir> > sdl3/src/render/vulkan/shaders.rs

The SPIR-V words are kept as u32 arrays, as upstream has them, eight to a
line; the shader table and its accessors are translated around them.
"""
import re
import sys

src_dir = sys.argv[1]
vk_dir = f"{src_dir}/src/render/vulkan"


def read(name):
    return open(f"{vk_dir}/{name}", encoding="utf-8").read()


# The VULKAN_Shader enum, in order.
header = read("SDL_shaders_vulkan.h")
enum_body = re.search(r"typedef enum\s*\{(.*?)\}\s*VULKAN_Shader;", header, re.S).group(1)
shaders = [s.strip() for s in enum_body.split(",") if s.strip()]
assert shaders[-1] == "NUM_SHADERS", shaders
shaders = shaders[:-1]

# The table: one (pixel shader, vertex shader) pair per VULKAN_Shader.
source = read("SDL_shaders_vulkan.c")
includes = re.findall(r'#include "(VULKAN_\w+\.h)"', source)
table = re.search(r"VULKAN_shaders\[NUM_SHADERS\] = \{(.*?)\};", source, re.S).group(1)
pairs = re.findall(r"\{\s*(\w+), sizeof\(\1\),\s*(\w+), sizeof\(\2\)\s*\}", table)
assert len(pairs) == len(shaders), (pairs, shaders)

# The SPIR-V of each header.
blobs = {}
versions = set()
for include in includes:
    text = read(include)
    versions.add(re.search(r"//\s*(\d+\.\d+\.\d+)", text).group(1))
    m = re.search(r"static const uint32_t (\w+)\[\] = \{(.*?)\};", text, re.S)
    name, body = m.group(1), m.group(2)
    words = [int(w, 16) for w in re.findall(r"0x[0-9a-fA-F]{8}", body)]
    assert words[0] == 0x07230203, f"{include}: not SPIR-V"
    blobs[name] = words
assert len(versions) == 1, versions
used = {n for pair in pairs for n in pair}
assert used <= set(blobs), used - set(blobs)


def rust_const(c_name):
    """VULKAN_PixelShader_Colors_PQ -> VULKAN_PIXEL_SHADER_COLORS_PQ"""
    s = re.sub(r"(?<=[a-z])(?=[A-Z])", "_", c_name)
    return s.upper()


def rust_variant(c_name):
    """SHADER_RGB_SIMPLE -> RgbSimple"""
    return "".join(p.capitalize() for p in c_name.split("_")[1:])


out = []
out.append("// Rust translation of src/render/vulkan/SDL_shaders_vulkan.c, SDL_shaders_vulkan.h")
out.append("// and the SPIR-V headers they include, from Simple DirectMedia Layer.")
out.append("// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>")
out.append("// This is an altered (translated) version of the original software; see LICENSE.txt.")
out.append("// Generated by tools/gen_vulkan_shaders.py; do not edit.")
out.append("")
out.append("//! The shaders of the Vulkan renderer: SPIR-V compiled from the HLSL")
out.append("//! sources upstream (`compile_shaders.bat`, glslangValidator")
out.append(f"//! {versions.pop()}), one vertex shader and a pixel shader per [`Shader`].")
out.append("")
out.append("/// The shaders. Translation of `VULKAN_Shader`.")
out.append("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
out.append("pub(super) enum Shader {")
for s in shaders:
    out.append(f"    {rust_variant(s)},")
out.append("}")
out.append("")
out.append("impl Shader {")
out.append("    /// Translation of `NUM_SHADERS`.")
out.append(f"    pub(super) const COUNT: usize = {len(shaders)};")
out.append("")
out.append("    /// All the shaders, in order.")
out.append("    pub(super) const ALL: [Shader; Shader::COUNT] = [")
for s in shaders:
    out.append(f"        Shader::{rust_variant(s)},")
out.append("    ];")
out.append("")
out.append("    /// The SPIR-V of the vertex shader. Translation of `VULKAN_GetVertexShader()`.")
out.append("    pub(super) fn vertex_shader(self) -> &'static [u32] {")
out.append("        VULKAN_SHADERS[self as usize].1")
out.append("    }")
out.append("")
out.append("    /// The SPIR-V of the pixel shader. Translation of `VULKAN_GetPixelShader()`.")
out.append("    pub(super) fn pixel_shader(self) -> &'static [u32] {")
out.append("        VULKAN_SHADERS[self as usize].0")
out.append("    }")
out.append("}")
out.append("")
out.append("/// The pixel and vertex shader of each [`Shader`]. Translation of `VULKAN_shaders`.")
out.append("static VULKAN_SHADERS: [(&[u32], &[u32]); Shader::COUNT] = [")
for ps, vs in pairs:
    out.append("    (")
    out.append(f"        {rust_const(ps)}.as_slice(),")
    out.append(f"        {rust_const(vs)}.as_slice(),")
    out.append("    ),")
out.append("];")
for include in includes:
    name = re.sub(r"\.h$", "", include)
    words = blobs[name]
    out.append("")
    out.append(f"/// `{name}`, from `{include}`.")
    out.append("#[rustfmt::skip]")
    out.append(f"static {rust_const(name)}: [u32; {len(words)}] = [")
    for i in range(0, len(words), 8):
        out.append("    " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",")
    out.append("];")
print("\n".join(out))
