#!/usr/bin/env python3
"""Generate the Rust bindings of the Wayland protocols the Wayland video
driver uses, as wayland-scanner does for upstream's C build:

  sdl3/src/video/drivers/wayland/protocols/<protocol>.rs   one per XML file
  sdl3/src/video/drivers/wayland/protocols/mod.rs

from the protocol descriptions in tools/wayland-protocols/ (copied verbatim,
with their copyright notices, from upstream SDL's wayland-protocols/
directory, which includes the core wayland.xml).

For every interface this emits:

* the `wl_interface` and `wl_message` tables as statics (what
  `wayland-scanner private-code` emits), which libwayland-client uses to
  marshal requests and demarshal events;
* a marker type implementing `client::Interface`, with the `*_SINCE_VERSION`
  constants of the C header;
* the enums as `u32` newtypes with associated constants;
* an event enum and its decoder (the listener: handlers are closures given
  to `Proxy::listen`);
* the requests as methods of a `<Interface>Requests` trait implemented for
  everything that is `AsProxy` of that interface, and the destructors as
  methods consuming a `Proxy`.

Usage: gen_wayland_protocols.py [<protocol dir> [<output dir>]]
"""
import os
import subprocess
import sys
import xml.etree.ElementTree as ET

here = os.path.dirname(os.path.abspath(__file__))
proto_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "wayland-protocols")
out_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    here, "..", "sdl3", "src", "video", "drivers", "wayland", "protocols")

HEADER = """// Rust bindings of {what}, generated from the protocol description
// that Simple DirectMedia Layer ships in wayland-protocols/{file}.
// Generated by tools/gen_wayland_protocols.py; do not edit.
//
// The protocol description is:
{copyright}
"""

RUST_KEYWORDS = set(
    "as break const continue crate else enum extern false fn for if impl in let loop match mod move mut "
    "pub ref return self Self static struct super trait true type unsafe use where while async await dyn "
    "abstract become box do final macro override priv typeof unsized virtual yield try gen".split())


def camel(name):
    return "".join(p[:1].upper() + p[1:] for p in name.split("_") if p)


def upper(name):
    return name.upper()


def ident(name):
    if name in ("self", "super", "crate", "Self"):
        return name + "_"
    if name in RUST_KEYWORDS:
        return "r#" + name
    return name


def const_ident(name):
    n = upper(name)
    if n[:1].isdigit():
        n = "_" + n
    if n in ("SELF", "SUPER", "CRATE"):
        n += "_"
    return n


def summary_of(elem):
    s = elem.get("summary")
    if s is None:
        d = elem.find("description")
        if d is not None:
            s = d.get("summary")
    if s is None:
        return ""
    return " ".join(s.split())


def doc_line(text):
    text = text.replace("\\", "\\\\")
    return text


class Arg:
    def __init__(self, e):
        self.name = e.get("name")
        self.type = e.get("type")
        self.interface = e.get("interface")
        self.allow_null = e.get("allow-null") == "true"
        self.enum = e.get("enum")
        self.summary = summary_of(e)


class Message:
    def __init__(self, e, index, kind):
        self.name = e.get("name")
        self.index = index
        self.kind = kind
        self.since = int(e.get("since", "1"))
        self.destructor = e.get("type") == "destructor"
        self.args = [Arg(a) for a in e.findall("arg")]
        self.summary = summary_of(e)

    def signature(self):
        s = "" if self.since == 1 else str(self.since)
        for a in self.args:
            if a.allow_null:
                s += "?"
            if a.type == "new_id" and a.interface is None:
                s += "su"
            s += {
                "int": "i", "uint": "u", "fixed": "f", "string": "s", "object": "o",
                "new_id": "n", "array": "a", "fd": "h",
            }[a.type]
        return s

    def types(self):
        t = []
        for a in self.args:
            if a.type == "new_id" and a.interface is None:
                t += [None, None]
            if a.type in ("object", "new_id"):
                t.append(a.interface)
            else:
                t.append(None)
        return t


class Enum:
    def __init__(self, e, iface):
        self.name = e.get("name")
        self.iface = iface
        self.bitfield = e.get("bitfield") == "true"
        self.summary = summary_of(e)
        self.entries = []
        for en in e.findall("entry"):
            self.entries.append((en.get("name"), en.get("value"), summary_of(en)))

    def rust_name(self):
        return camel(self.iface) + camel(self.name)


class Interface:
    def __init__(self, e, proto):
        self.name = e.get("name")
        self.version = int(e.get("version"))
        self.proto = proto
        self.summary = summary_of(e)
        self.requests = [Message(r, i, "request") for i, r in enumerate(e.findall("request"))]
        self.events = [Message(v, i, "event") for i, v in enumerate(e.findall("event"))]
        self.enums = [Enum(n, self.name) for n in e.findall("enum")]

    def rust(self):
        return camel(self.name)

    def static(self):
        return upper(self.name) + "_INTERFACE"


class Protocol:
    def __init__(self, path):
        root = ET.parse(path).getroot()
        self.file = os.path.basename(path)
        self.name = root.get("name")
        c = root.find("copyright")
        self.copyright = c.text if c is not None else None
        self.interfaces = [Interface(i, self) for i in root.findall("interface")]


protocols = [Protocol(os.path.join(proto_dir, f)) for f in sorted(os.listdir(proto_dir)) if f.endswith(".xml")]
interfaces = {}
enums = {}
for p in protocols:
    for i in p.interfaces:
        interfaces[i.name] = i
        for en in i.enums:
            enums[(i.name, en.name)] = en


def module_of(proto):
    return proto.name


def iface_path(name, here_proto):
    i = interfaces[name]
    if i.proto is here_proto:
        return i.rust()
    return f"super::{module_of(i.proto)}::{i.rust()}"


def iface_static_path(name, here_proto):
    i = interfaces[name]
    if i.proto is here_proto:
        return i.static()
    return f"super::{module_of(i.proto)}::{i.static()}"


def enum_path(ref, iface, here_proto):
    if "." in ref:
        iname, ename = ref.split(".")
    else:
        iname, ename = iface.name, ref
    en = enums[(iname, ename)]
    i = interfaces[iname]
    if i.proto is here_proto:
        return en.rust_name()
    return f"super::{module_of(i.proto)}::{en.rust_name()}"


def event_has_lifetime(iface):
    for ev in iface.events:
        for a in ev.args:
            if a.type in ("string", "object", "array"):
                return True
    return False


def gen_protocol(p):
    out = []
    w = out.append
    cr = p.copyright or "(no copyright notice in the file; wayland-protocols is MIT licensed)"
    cr_lines = "\n".join(("//" + ("  " + l if l.strip() else "")).rstrip() for l in cr.strip("\n").split("\n"))
    w(HEADER.format(what=f"the {p.name} Wayland protocol", file=p.file, copyright=cr_lines))
    w(f"//! The `{p.name}` protocol (`{p.file}`).\n")
    w("#![allow(dead_code)] // (the bindings cover the whole protocol)")
    w("#![allow(clippy::too_many_arguments, clippy::needless_lifetimes, clippy::unused_unit,\n    clippy::enum_variant_names)]\n")
    w("#[allow(unused_imports)]")
    w("use std::ffi::CStr;")
    w("#[allow(unused_imports)]")
    w("use std::os::fd::{BorrowedFd, OwnedFd};")
    w("use std::ptr;")
    w("use std::sync::Arc;\n")
    w("#[allow(unused_imports)]")
    w("use super::super::client::{")
    w("    arg_array, arg_fd, arg_new, arg_obj, arg_raw_obj, arg_str, cstring_arg, AsProxy, Conn, Fixed, Interface, NoEvents, Obj, Proxy, RawObj,")
    w("};")
    w("#[allow(unused_imports)]")
    w("use super::super::sys::{wl_argument, wl_array, wl_interface, wl_message, IfacePtr, WL_MARSHAL_FLAG_DESTROY};\n")

    for iface in p.interfaces:
        gen_interface(iface, p, w)

    return "\n".join(out).rstrip() + "\n"


def rust_req_arg_type(a, iface, p):
    if a.type == "int":
        if a.enum:
            return enum_path(a.enum, iface, p)
        return "i32"
    if a.type == "uint":
        if a.enum:
            return enum_path(a.enum, iface, p)
        return "u32"
    if a.type == "fixed":
        return "Fixed"
    if a.type == "string":
        return "Option<&str>" if a.allow_null else "&str"
    if a.type == "object":
        if a.interface is None:
            return "Option<RawObj>" if a.allow_null else "RawObj"
        t = f"Obj<'_, {iface_path(a.interface, p)}>"
        return f"Option<{t}>" if a.allow_null else t
    if a.type == "fd":
        return "BorrowedFd<'_>"
    if a.type == "array":
        return "&[u8]"
    raise SystemExit(f"unexpected request argument type {a.type}")


def rust_ev_arg_type(a, iface, p, lt):
    if a.type == "int":
        if a.enum:
            return enum_path(a.enum, iface, p)
        return "i32"
    if a.type == "uint":
        if a.enum:
            return enum_path(a.enum, iface, p)
        return "u32"
    if a.type == "fixed":
        return "Fixed"
    if a.type == "string":
        return f"Option<&{lt} CStr>" if a.allow_null else f"&{lt} CStr"
    if a.type == "object":
        if a.interface is None:
            return "Option<RawObj>"
        return f"Option<Obj<{lt}, {iface_path(a.interface, p)}>>"
    if a.type == "new_id":
        return f"Proxy<{iface_path(a.interface, p)}>"
    if a.type == "fd":
        return "OwnedFd"
    if a.type == "array":
        return f"&{lt} [u8]"
    raise SystemExit(f"unexpected event argument type {a.type}")


def gen_messages(iface, p, w, msgs, kind):
    if not msgs:
        return "ptr::null()"
    tname = f"{upper(iface.name)}_{upper(kind)}S"
    for m in msgs:
        types = m.types()
        tn = f"{upper(iface.name)}_{upper(m.name)}_{upper(kind)}_TYPES"
        vals = ", ".join(
            f"Some(&{iface_static_path(t, p)})" if t else "None" for t in types)
        w(f"static {tn}: [IfacePtr; {len(types)}] = [{vals}];")
    w(f"static {tname}: [wl_message; {len(msgs)}] = [")
    for m in msgs:
        tn = f"{upper(iface.name)}_{upper(m.name)}_{upper(kind)}_TYPES"
        w("    wl_message {")
        w(f"        name: c\"{m.name}\".as_ptr(),")
        w(f"        signature: c\"{m.signature()}\".as_ptr(),")
        w(f"        types: {tn}.as_ptr(),")
        w("    },")
    w("];")
    return f"{tname}.as_ptr()"


def default_destructor(iface):
    ds = [r for r in iface.requests if r.destructor and not any(a.type == "new_id" for a in r.args)]
    no_args = [r for r in ds if not r.args]
    for name in ("destroy", "release"):
        for r in no_args:
            if r.name == name:
                return r
    return no_args[0] if no_args else None


def gen_interface(iface, p, w):
    R = iface.rust()
    w(f"// ---------------------------------------------------------------------------")
    w(f"// {iface.name}")
    w(f"// ---------------------------------------------------------------------------\n")

    # Tables
    reqs = gen_messages(iface, p, w, iface.requests, "request")
    evs = gen_messages(iface, p, w, iface.events, "event")
    w(f"/// The `wl_interface` of `{iface.name}` (`{iface.name}_interface`).")
    w(f"pub(crate) static {iface.static()}: wl_interface = wl_interface {{")
    w(f"    name: c\"{iface.name}\".as_ptr(),")
    w(f"    version: {iface.version},")
    w(f"    method_count: {len(iface.requests)},")
    w(f"    methods: {reqs},")
    w(f"    event_count: {len(iface.events)},")
    w(f"    events: {evs},")
    w("};\n")

    # Enums
    for en in iface.enums:
        n = en.rust_name()
        w(f"/// `{iface.name}.{en.name}`" + (f": {doc_line(en.summary)}" if en.summary else ""))
        w("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]")
        w(f"pub(crate) struct {n}(pub(crate) u32);\n")
        w(f"impl {n} {{")
        for (ename, value, summary) in en.entries:
            if summary:
                w(f"    /// {doc_line(summary)}")
            w(f"    pub(crate) const {const_ident(ename)}: {n} = {n}({value});")
        if en.bitfield:
            w("")
            w("    /// Whether all the bits of `other` are set.")
            w(f"    pub(crate) const fn contains(self, other: {n}) -> bool {{")
            w("        self.0 & other.0 == other.0")
            w("    }")
        w("}\n")
        if en.bitfield:
            w(f"impl std::ops::BitOr for {n} {{")
            w(f"    type Output = {n};")
            w(f"    fn bitor(self, rhs: {n}) -> {n} {{")
            w(f"        {n}(self.0 | rhs.0)")
            w("    }")
            w("}\n")
            w(f"impl std::ops::BitOrAssign for {n} {{")
            w(f"    fn bitor_assign(&mut self, rhs: {n}) {{")
            w("        self.0 |= rhs.0;")
            w("    }")
            w("}\n")

    # Marker type
    w(f"/// `{iface.name}`" + (f": {doc_line(iface.summary)}" if iface.summary else ""))
    w("#[derive(Debug)]")
    w(f"pub(crate) enum {R} {{}}\n")
    since = []
    for m in iface.requests + iface.events:
        since.append((m.name, m.since))
    seen = set()
    if since:
        w(f"impl {R} {{")
        for name, s in since:
            if name in seen:
                continue
            seen.add(name)
            w(f"    /// The version `{iface.name}.{name}` appeared in (`{upper(iface.name)}_{upper(name)}_SINCE_VERSION`).")
            w(f"    pub(crate) const {upper(name)}_SINCE_VERSION: u32 = {s};")
        w("}\n")

    has_lt = event_has_lifetime(iface)
    ev_name = f"{R}Event"
    if iface.events:
        ev_ty = f"{ev_name}<'a>" if has_lt else ev_name
        w(f"/// The events of `{iface.name}`.")
        w("#[derive(Debug)]")
        w(f"pub(crate) enum {ev_name}{'<' + chr(39) + 'a>' if has_lt else ''} {{")
        for ev in iface.events:
            if ev.summary:
                w(f"    /// `{iface.name}.{ev.name}`: {doc_line(ev.summary)}")
            if ev.args:
                w(f"    {camel(ev.name)} {{")
                for a in ev.args:
                    if a.summary:
                        w(f"        /// {doc_line(a.summary)}")
                    w(f"        {ident(a.name)}: {rust_ev_arg_type(a, iface, p, chr(39) + 'a')},")
                w("    },")
            else:
                w(f"    {camel(ev.name)},")
        w("}\n")
    else:
        ev_ty = "NoEvents"

    dtor = default_destructor(iface)
    w(f"impl Interface for {R} {{")
    w(f"    const NAME: &'static str = \"{iface.name}\";")
    w(f"    const VERSION: u32 = {iface.version};")
    if dtor is not None:
        w(f"    const DESTRUCTOR: Option<(u32, u32)> = Some(({dtor.index}, {dtor.since}));")
    else:
        w("    const DESTRUCTOR: Option<(u32, u32)> = None;")
    w(f"    type Event<'a> = {ev_ty};\n")
    w("    fn interface() -> &'static wl_interface {")
    w(f"        &{iface.static()}")
    w("    }\n")
    w("    unsafe fn decode<'a>(")
    w("        conn: &'a Arc<Conn>,")
    w("        opcode: u32,")
    w("        args: *const wl_argument,")
    w("    ) -> Option<Self::Event<'a>> {")
    if not iface.events:
        w("        let _ = (conn, opcode, args);")
        w("        None")
    else:
        w("        let _ = (conn, args);")
        w("        match opcode {")
        for ev in iface.events:
            n = len(ev.args)
            if n == 0:
                w(f"            {ev.index} => Some({ev_name}::{camel(ev.name)}),")
                continue
            w(f"            {ev.index} => {{")
            w(f"                // SAFETY: libwayland passes the {n} arguments of the")
            w("                // event's signature.")
            w(f"                let a = unsafe {{ std::slice::from_raw_parts(args, {n}) }};")
            w(f"                Some({ev_name}::{camel(ev.name)} {{")
            for k, a in enumerate(ev.args):
                v = None
                if a.type == "int":
                    v = f"unsafe {{ a[{k}].i }}"
                    if a.enum:
                        v = f"{enum_path(a.enum, iface, p)}({v} as u32)"
                elif a.type == "uint":
                    v = f"unsafe {{ a[{k}].u }}"
                    if a.enum:
                        v = f"{enum_path(a.enum, iface, p)}({v})"
                elif a.type == "fixed":
                    v = f"Fixed(unsafe {{ a[{k}].f }})"
                elif a.type == "string":
                    v = f"unsafe {{ arg_str(&a[{k}]) }}"
                    if not a.allow_null:
                        v = f"{v}.unwrap_or_default()"
                elif a.type == "object":
                    if a.interface is None:
                        v = f"unsafe {{ arg_raw_obj(&a[{k}]) }}"
                    else:
                        v = f"unsafe {{ arg_obj(conn, &a[{k}]) }}"
                elif a.type == "new_id":
                    v = f"unsafe {{ arg_new(conn, &a[{k}])? }}"
                elif a.type == "fd":
                    v = f"unsafe {{ arg_fd(&a[{k}]) }}"
                elif a.type == "array":
                    v = f"unsafe {{ arg_array(&a[{k}]) }}"
                w(f"                    // SAFETY: argument {k} is a `{a.type}`.")
                w(f"                    {ident(a.name)}: {v},")
            w("                })")
            w("            }")
        w("            _ => None,")
        w("        }")
    w("    }")
    w("}\n")

    # Requests
    normal = [r for r in iface.requests if not r.destructor]
    destructors = [r for r in iface.requests if r.destructor]
    tr = f"{R}Requests"
    w(f"/// The requests of `{iface.name}`, for anything that is a proxy of it.")
    w(f"pub(crate) trait {tr}: AsProxy<Interface = {R}> {{")
    for r in normal:
        gen_request(iface, p, w, r, as_trait=True)
    w("}\n")
    w(f"impl<T: AsProxy<Interface = {R}>> {tr} for T {{}}\n")
    if destructors:
        w(f"impl Proxy<{R}> {{")
        for r in destructors:
            gen_request(iface, p, w, r, as_trait=False)
        w("}\n")


def gen_request(iface, p, w, r, as_trait):
    params = []
    pre = []
    args = []
    ret = None
    generic = ""
    for a in r.args:
        nm = ident(a.name)
        if a.type == "new_id":
            if a.interface is None:
                generic = "<J: Interface>"
                params.append("version: u32")
                args.append("wl_argument { s: J::interface().name }")
                args.append("wl_argument { u: version }")
                args.append("wl_argument { o: ptr::null_mut() }")
                ret = ("J", "version")
            else:
                args.append("wl_argument { o: ptr::null_mut() }")
                ret = (iface_path(a.interface, p), None)
            continue
        params.append(f"{nm}: {rust_req_arg_type(a, iface, p)}")
        if a.type == "int":
            args.append(f"wl_argument {{ i: {nm}.0 as i32 }}" if a.enum else f"wl_argument {{ i: {nm} }}")
        elif a.type == "uint":
            args.append(f"wl_argument {{ u: {nm}.0 }}" if a.enum else f"wl_argument {{ u: {nm} }}")
        elif a.type == "fixed":
            args.append(f"wl_argument {{ f: {nm}.0 }}")
        elif a.type == "string":
            if a.allow_null:
                pre.append(f"let c_{a.name} = {nm}.map(cstring_arg);")
                args.append(f"wl_argument {{ s: c_{a.name}.as_ref().map_or(ptr::null(), |s| s.as_ptr()) }}")
            else:
                pre.append(f"let c_{a.name} = cstring_arg({nm});")
                args.append(f"wl_argument {{ s: c_{a.name}.as_ptr() }}")
        elif a.type == "object":
            if a.interface is None:
                if a.allow_null:
                    args.append(f"wl_argument {{ o: {nm}.map_or(ptr::null_mut(), |o| o.raw()) }}")
                else:
                    args.append(f"wl_argument {{ o: {nm}.raw() }}")
            elif a.allow_null:
                args.append(f"wl_argument {{ o: {nm}.map_or(ptr::null_mut(), |o| o.raw()) }}")
            else:
                args.append(f"wl_argument {{ o: {nm}.raw() }}")
        elif a.type == "fd":
            args.append(f"wl_argument {{ h: std::os::fd::AsRawFd::as_raw_fd(&{nm}) }}")
        elif a.type == "array":
            pre.append(f"let mut {a.name}_a = wl_array {{ size: {nm}.len(), alloc: {nm}.len(), data: {nm}.as_ptr() as *mut _ }};")
            args.append(f"wl_argument {{ a: &mut {a.name}_a }}")
    selfp = "&self" if as_trait else "self"
    if ret:
        rett = f" -> Proxy<{ret[0]}>"
    else:
        rett = ""
    doc = f"    /// `{iface.name}.{r.name}`" + (f": {doc_line(r.summary)}" if r.summary else "")
    w(doc)
    vis = "" if as_trait else "pub(crate) "
    w(f"    {vis}fn {ident(r.name)}{generic}({', '.join([selfp] + params)}){rett} {{")
    if as_trait:
        w("        let proxy = self.obj();")
    else:
        w("        let proxy = self.obj();")
    for l in pre:
        w(f"        {l}")
    if args:
        w(f"        let mut args = [{', '.join(args)}];")
    else:
        w("        let mut args: [wl_argument; 0] = [];")
    flags = "WL_MARSHAL_FLAG_DESTROY" if r.destructor else "0"
    if ret:
        iface_t, ver = ret
        version = ver if ver else "proxy.version()"
        w(f"        // SAFETY: the arguments match the request's signature, \"{r.signature()}\".")
        if r.destructor:
            w(f"        let new = unsafe {{ proxy.marshal_constructor::<{iface_t}>({r.index}, &mut args, {version}, {flags}) }};")
            w("        self.forget_destroyed();")
            w("        new")
        else:
            w(f"        unsafe {{ proxy.marshal_constructor::<{iface_t}>({r.index}, &mut args, {version}, {flags}) }}")
    else:
        w(f"        // SAFETY: the arguments match the request's signature, \"{r.signature()}\".")
        w(f"        unsafe {{ proxy.marshal({r.index}, &mut args, {flags}) }};")
        if r.destructor:
            w("        self.forget_destroyed();")
    w("    }\n")


os.makedirs(out_dir, exist_ok=True)
mods = []
for p in protocols:
    name = module_of(p)
    mods.append((name, p))
    with open(os.path.join(out_dir, f"{name}.rs"), "w") as f:
        f.write(gen_protocol(p))

written = [os.path.join(out_dir, f"{name}.rs") for name, _ in mods]
with open(os.path.join(out_dir, "mod.rs"), "w") as f:
    f.write("""// Rust bindings of the Wayland protocols used by the Wayland video driver of
// Simple DirectMedia Layer (wayland-protocols/*.xml upstream).
// Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>
// This is an altered (translated) version of the original software; see LICENSE.txt.
// Generated by tools/gen_wayland_protocols.py; do not edit.

//! The Wayland protocols, as wayland-scanner would generate them for C:
//! one module per protocol description (each file carries the copyright
//! notice of its protocol).

""")
    for name, p in mods:
        f.write(f"pub(crate) mod {name};\n")

# Format like the rest of the crate (rustfmt finds the repository's
# rustfmt.toml).
written.append(os.path.join(out_dir, "mod.rs"))
subprocess.run(["rustfmt", "--edition", "2021"] + written, check=True)
