// Rust translation of src/hb-ot-shaper-vowel-constraints.cc from HarfBuzz (8.5.0, as SDL_ttf's
// external/harfbuzz pins it), made by tools/gen_harfbuzz_tables.py.
// Generated by HarfBuzz's gen-vowel-constraints.py from the Unicode data (Scripts.txt) and ms-use/IndicShapingInvalidCluster.txt.
// This is an altered (translated) version of the original software; see
// LICENSE.txt (HarfBuzz's "Old MIT" license, and the Unicode License for the data).

//! The vowel sequences that get a dotted circle inserted, by script.
//!
//! `_hb_preprocess_text_vowel_constraints` is generated C code; its cases are
//! translated as the rules below, which `hb_ot_shaper_vowel_constraints.rs` runs.

use super::hb_common::*;

/// A rule: the following characters that match (`Second`), or
/// the two that must follow, after which the dotted circle goes (`Third`).
#[derive(Debug, Clone, Copy)]
pub(crate) enum VowelRule {
    Second(&'static [u32]),
    Third(u32, u32),
}

/// The rules by script, as `(first character, rule)`.
#[rustfmt::skip]
pub(crate) static VOWEL_CONSTRAINTS: [(HbScript, &[(u32, VowelRule)]); 16] = [
    (
        HB_SCRIPT_DEVANAGARI,
        &[
            (0x0905, VowelRule::Second(&[0x093A, 0x093B, 0x093E, 0x0945, 0x0946, 0x0949, 0x094A, 0x094B, 0x094C, 0x094F, 0x0956, 0x0957])),
            (0x0906, VowelRule::Second(&[0x093A, 0x0945, 0x0946, 0x0947, 0x0948])),
            (0x0909, VowelRule::Second(&[0x0941])),
            (0x090F, VowelRule::Second(&[0x0945, 0x0946, 0x0947])),
            (0x0930, VowelRule::Third(0x094D, 0x0907)),
        ],
    ),
    (
        HB_SCRIPT_BENGALI,
        &[
            (0x0985, VowelRule::Second(&[0x09BE])),
            (0x098B, VowelRule::Second(&[0x09C3])),
            (0x098C, VowelRule::Second(&[0x09E2])),
        ],
    ),
    (
        HB_SCRIPT_GURMUKHI,
        &[
            (0x0A05, VowelRule::Second(&[0x0A3E, 0x0A48, 0x0A4C])),
            (0x0A72, VowelRule::Second(&[0x0A3F, 0x0A40, 0x0A47])),
            (0x0A73, VowelRule::Second(&[0x0A41, 0x0A42, 0x0A4B])),
        ],
    ),
    (
        HB_SCRIPT_GUJARATI,
        &[
            (0x0A85, VowelRule::Second(&[0x0ABE, 0x0AC5, 0x0AC7, 0x0AC8, 0x0AC9, 0x0ACB, 0x0ACC])),
            (0x0AC5, VowelRule::Second(&[0x0ABE])),
        ],
    ),
    (
        HB_SCRIPT_ORIYA,
        &[
            (0x0B05, VowelRule::Second(&[0x0B3E])),
            (0x0B0F, VowelRule::Second(&[0x0B57])),
            (0x0B13, VowelRule::Second(&[0x0B57])),
        ],
    ),
    (
        HB_SCRIPT_TAMIL,
        &[
            (0x0B85, VowelRule::Second(&[0x0BC2])),
        ],
    ),
    (
        HB_SCRIPT_TELUGU,
        &[
            (0x0C12, VowelRule::Second(&[0x0C4C, 0x0C55])),
            (0x0C3F, VowelRule::Second(&[0x0C55])),
            (0x0C46, VowelRule::Second(&[0x0C55])),
            (0x0C4A, VowelRule::Second(&[0x0C55])),
        ],
    ),
    (
        HB_SCRIPT_KANNADA,
        &[
            (0x0C89, VowelRule::Second(&[0x0CBE])),
            (0x0C8B, VowelRule::Second(&[0x0CBE])),
            (0x0C92, VowelRule::Second(&[0x0CCC])),
        ],
    ),
    (
        HB_SCRIPT_MALAYALAM,
        &[
            (0x0D07, VowelRule::Second(&[0x0D57])),
            (0x0D09, VowelRule::Second(&[0x0D57])),
            (0x0D0E, VowelRule::Second(&[0x0D46])),
            (0x0D12, VowelRule::Second(&[0x0D3E, 0x0D57])),
        ],
    ),
    (
        HB_SCRIPT_SINHALA,
        &[
            (0x0D85, VowelRule::Second(&[0x0DCF, 0x0DD0, 0x0DD1])),
            (0x0D8B, VowelRule::Second(&[0x0DDF])),
            (0x0D8F, VowelRule::Second(&[0x0DDF])),
            (0x0D94, VowelRule::Second(&[0x0DDF])),
            (0x0D8D, VowelRule::Second(&[0x0DD8])),
            (0x0D91, VowelRule::Second(&[0x0DCA, 0x0DD9, 0x0DDA, 0x0DDC, 0x0DDD, 0x0DDE])),
        ],
    ),
    (
        HB_SCRIPT_BRAHMI,
        &[
            (0x11005, VowelRule::Second(&[0x11038])),
            (0x1100B, VowelRule::Second(&[0x1103E])),
            (0x1100F, VowelRule::Second(&[0x11042])),
        ],
    ),
    (
        HB_SCRIPT_KHOJKI,
        &[
            (0x11200, VowelRule::Second(&[0x1122C, 0x11231, 0x11233])),
            (0x11206, VowelRule::Second(&[0x1122C])),
            (0x1122C, VowelRule::Second(&[0x11230, 0x11231])),
            (0x11240, VowelRule::Second(&[0x1122E])),
        ],
    ),
    (
        HB_SCRIPT_KHUDAWADI,
        &[
            (0x112B0, VowelRule::Second(&[0x112E0, 0x112E5, 0x112E6, 0x112E7, 0x112E8])),
        ],
    ),
    (
        HB_SCRIPT_TIRHUTA,
        &[
            (0x11481, VowelRule::Second(&[0x114B0])),
            (0x1148B, VowelRule::Second(&[0x114BA])),
            (0x1148D, VowelRule::Second(&[0x114BA])),
            (0x114AA, VowelRule::Second(&[0x114B5, 0x114B6])),
        ],
    ),
    (
        HB_SCRIPT_MODI,
        &[
            (0x11600, VowelRule::Second(&[0x11639, 0x1163A])),
            (0x11601, VowelRule::Second(&[0x11639, 0x1163A])),
        ],
    ),
    (
        HB_SCRIPT_TAKRI,
        &[
            (0x11680, VowelRule::Second(&[0x116AD, 0x116B4, 0x116B5])),
            (0x11686, VowelRule::Second(&[0x116B2])),
        ],
    ),
];
